---
permalink: windows/concept-what-cloning-is.html 
sidebar: sidebar 
keywords: clone, database, create, replica, original, full, backup 
summary: 데이터베이스를 복제하여 원본 데이터베이스의 정확한 복제본을 생성할 수 있습니다. 전체 백업이나 데이터베이스의 현재 상태에서 클론을 생성할 수 있습니다. 
---
= 복제란 무엇인가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터베이스를 복제하여 원본 데이터베이스의 정확한 복제본을 생성할 수 있습니다. 전체 백업이나 데이터베이스의 현재 상태에서 클론을 생성할 수 있습니다.

SnapManager를 사용하여 클론을 생성할 때의 이점은 다음과 같습니다.

|===
| 장점 | 세부 정보 


 a| 
속도
 a| 
SnapManager 클론 작업에서는 Data ONTAP에서 사용할 수 있는 FlexClone 기능을 사용합니다. 따라서 대용량 데이터 볼륨을 빠르게 클론 복제할 수 있습니다.



 a| 
공간 효율성
 a| 
SnapManager를 사용하여 클론을 생성할 때는 백업과 클론 간의 변경에만 공간이 필요합니다. SnapManager 클론은 원래 데이터베이스의 쓰기 가능한 스냅샷 복사본으로 필요에 따라 확장할 수 있습니다. 반면 데이터베이스의 물리적 클론에는 전체 데이터베이스를 복제할 수 있는 충분한 공간이 있어야 합니다.



 a| 
가상 복사본
 a| 
복제된 데이터베이스를 원래 데이터베이스처럼 사용할 수 있습니다. 예를 들어, 클론을 테스트, 플랫폼 및 업데이트 확인, 대규모 데이터 집합에 대한 여러 시뮬레이션, 원격 사무소 테스트 및 스테이징에 사용할 수 있습니다. 클론을 변경해도 원래 데이터베이스는 영향을 받지 않습니다. 데이터베이스가 복제되면 복제된 데이터베이스가 완전히 작동합니다.



 a| 
단순성
 a| 
SnapManager 명령을 사용하여 모든 호스트에 데이터베이스를 클론 복제할 수 있습니다.

|===
데이터베이스를 복제하려면 먼저 다음 필수 구성 요소가 충족되어야 합니다.

* '$ORACLE_HOME\database'에서 'spfile<SID>.ora' 파일을 삭제합니다.
* '$ORACLE_HOME\database'에서 'init<SID>.ora' 파일을 삭제합니다.
* 클론 사양 파일에 지정된 Oracle 덤프 대상을 삭제합니다.
* 클론 사양 파일에 지정된 Oracle 제어 파일을 삭제합니다.
* 클론 사양 파일에 지정된 Oracle redo 로그 파일을 삭제합니다.


새 시스템 식별자를 클론으로 지정해야 합니다. 동일한 호스트에서 동일한 시스템 식별자를 갖는 두 데이터베이스를 동시에 실행할 수 없습니다. 동일한 시스템 식별자를 사용하여 다른 호스트에 클론을 생성할 수 있습니다. 클론을 생성한 시간, 날짜 및 시스템 식별자를 사용하여 클론에 레이블을 지정하거나 SnapManager에서 레이블을 생성하도록 할 수 있습니다.

레이블을 입력할 때 공백이나 특수 문자를 포함해서는 안 됩니다.

클론 생성 프로세스의 일부로 SnapManager는 복제된 데이터베이스에 필요한 Oracle 파일 및 매개 변수를 생성합니다. 필요한 Oracle 파일의 예로는 "init<SID>.ora"가 있습니다.

데이터베이스를 복제할 때 SnapManager는 "$oracle_home\database" 디렉토리에 데이터베이스에 대한 새 초기화 <sid>.ora" 파일을 만듭니다.

데이터베이스 백업을 데이터베이스가 있는 호스트 또는 대체 호스트에 복제할 수 있습니다.

복제한 데이터베이스가 '파일'을 사용하는 경우 SnapManager는 해당 클론에 대한 '파일'을 생성합니다. 이 파일은 '$ORACLE_HOME\database' 디렉토리에 배치되고 진단 파일의 디렉토리 구조가 생성됩니다. 파일 이름은 'Spfile <SID>.ora'입니다.
