---
permalink: windows/concept-database-backup-management.html 
sidebar: sidebar 
keywords: snapmanager, enable, back up, data, local, storage, resource, post-process, script, database 
summary: SnapManager를 사용하면 사후 처리 스크립트를 사용하여 로컬 스토리지 리소스에 있는 데이터를 백업할 수 있습니다. 
---
= 데이터베이스 백업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용하면 사후 처리 스크립트를 사용하여 로컬 스토리지 리소스에 있는 데이터를 백업할 수 있습니다.

SnapManager에서는 데이터베이스의 데이터를 백업, 복원 및 복구하는 다음과 같은 옵션을 제공합니다.

* 전체 데이터베이스 또는 일부를 백업합니다.
+
일부를 백업하는 경우 테이블스페이스 그룹이나 데이터 파일 그룹을 지정합니다.

* 데이터 파일과 아카이브 로그 파일을 별도로 백업합니다.
* 데이터베이스를 기본 스토리지(로컬 스토리지라고도 함)에 백업하고 사후 처리 스크립트를 사용하여 보조 스토리지로 백업하여 보호합니다.
* 일상적인 백업을 예약합니다.


* SnapManager(3.2 이상)가 이전 SnapManager 버전과 다른 방식 *

SnapManager(3.1 이하)을 사용하면 데이터 파일, 제어 파일 및 아카이브 로그 파일을 포함하는 전체 데이터베이스 백업을 생성할 수 있습니다.

SnapManager(3.1 이하)는 데이터 파일만 관리합니다. 아카이브 로그 파일은 SnapManager 외부의 솔루션을 사용하여 관리합니다.

SnapManager(3.1 이하)은 데이터베이스 백업 관리에 다음과 같은 제약을 부과합니다.

* 성능 영향
+
데이터베이스가 백업 모드에 있을 때 전체 온라인 데이터베이스 백업을 수행하면 백업이 생성될 때까지 데이터베이스 성능이 저하됩니다. SnapManager(3.2 이상)에서는 제한된 데이터베이스 백업과 빈번한 아카이브 로그 백업을 수행할 수 있습니다. 아카이브 로그 백업을 자주 수행하면 데이터베이스가 백업 모드로 전환되지 않도록 할 수 있습니다.

* 수동 복원 및 복구
+
필요한 아카이브 로그 파일이 액티브 파일 시스템에 없으면 데이터베이스 관리자는 아카이브 로그 파일이 포함된 백업을 식별하고 데이터베이스 백업을 마운트하고 복원된 데이터베이스를 복구해야 합니다. 이 프로세스에는 시간이 많이 소요됩니다.

* 공간 제약
+
데이터베이스 백업이 생성되면 아카이브 로그 대상이 꽉 차서 스토리지에 충분한 공간이 생성될 때까지 데이터베이스가 응답하지 않습니다. SnapManager(3.2 이상)에서 아카이브 로그 파일을 액티브 파일 시스템에서 정리하여 주기적으로 공간을 확보할 수 있습니다.



* 아카이브 로그 백업이 중요한 이유 *

복구 작업을 수행한 후 데이터베이스를 롤포워드하려면 아카이브 로그 파일이 필요합니다. Oracle 데이터베이스의 모든 트랜잭션은 아카이브 로그 파일에 캡처됩니다(데이터베이스가 아카이브 로그 모드에 있는 경우). 데이터베이스 관리자는 아카이브 로그 파일을 사용하여 데이터베이스 백업을 복원할 수 있습니다.

* 아카이브 전용 백업의 이점 *

* 아카이브 전용 백업에 대해 별도의 보존 기간을 제공합니다
+
복구에 필요한 아카이브 전용 백업의 보존 기간을 줄일 수 있습니다.

* 사후 처리 스크립트를 사용하여 아카이브 전용 백업을 보호합니다
* 데이터베이스의 성능을 향상시킵니다
* 아카이브 로그 백업을 통합합니다
+
SnapManager는 중복 아카이브 로그 백업을 해제하여 백업을 수행할 때마다 아카이브 로그 백업을 통합합니다.


