---
permalink: windows/concept-snapshot-copy-naming.html 
sidebar: sidebar 
keywords: specify, convention, pattern, snapshot, copies, copy, create, update, custom, text, snapshot, name 
summary: 생성 또는 업데이트하는 프로필과 관련된 스냅샷 복사본을 설명하기 위해 명명 규칙 또는 패턴을 지정할 수 있습니다. 모든 스냅샷 복사본 이름에 사용자 지정 텍스트를 포함할 수도 있습니다. 
---
= 스냅샷 복사본 이름 지정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
생성 또는 업데이트하는 프로필과 관련된 스냅샷 복사본을 설명하기 위해 명명 규칙 또는 패턴을 지정할 수 있습니다. 모든 스냅샷 복사본 이름에 사용자 지정 텍스트를 포함할 수도 있습니다.

프로파일을 만들거나 프로파일을 만든 후에 스냅샷 복사본 명명 패턴을 변경할 수 있습니다. 업데이트된 패턴은 아직 발생하지 않은 스냅샷 복사본에만 적용되며, 존재하는 스냅샷 복사본에는 이전 snapname 패턴이 유지됩니다.

다음 예에서는 볼륨에 대해 생성한 2개의 스냅샷 복사본 이름을 보여줍니다. 나열된 두 번째 스냅샷 복사본의 이름은 _F_H_1_이며 그 중간에 위치합니다. "1"은 백업 세트에서 가져온 첫 번째 스냅샷 복사본임을 나타냅니다. 나열된 첫 번째 스냅샷 복사본은 가장 최근에 생성된 것으로, "2"입니다. 즉, 두 번째 스냅샷 복사본이 생성된 것입니다. "1" 스냅샷 복사본에는 데이터 파일이 포함되어 있으며, "2" 스냅샷 복사본에는 제어 파일이 포함되어 있습니다. 데이터 파일 Snapshot 복사본 후에 제어 파일 Snapshot 복사본을 만들어야 하므로 2개의 스냅샷 복사본이 필요합니다.

[listing]
----
smsap_profile_sid_f_h_2_8ae482831ad14311011ad14328b80001_0
smsap_profile_sid_f_h_1_8ae482831ad14311011ad14328b80001_0
----
기본 패턴은 다음과 같이 필요한 smid를 포함합니다.

* 기본 패턴: smsap_{profile}_{db-sid}_{scope}_{mode}_{smid}
* 예: sap_my_profile_rac51_f_h_2_8abc01e915a55ac50115a55acc8d0001_0


스냅샷 복사본 이름에 다음 변수를 사용할 수 있습니다.

|===
| 변수 이름 | 설명 | 예제 값 


 a| 
smid(필수)
 a| 
SnapManager 고유 ID는 스냅샷 복사본의 이름을 생성할 때 필요한 유일한 요소입니다. 이 ID를 사용하면 고유한 스냅샷 이름을 생성할 수 있습니다.
 a| 
8abc01e915a55ac50115a55acc8d0001_0



 a| 
클래스(선택 사항)
 a| 
프로필 백업과 연결되어 있고 시간별(h), 일별(d), 주별(w), 월별(m) 또는 무제한(u)으로 표시되는 보존 클래스입니다.
 a| 
D



 a| 
설명(선택 사항)
 a| 
프로파일 백업과 관련된 설명입니다. 이 필드의 공백은 스냅샷 복사본 이름이 완료되면 밑줄로 변환됩니다.
 a| 
SAMPLE_COMMENT_spaces_REPLACED.(샘플



 a| 
날짜(선택 사항)
 a| 
프로파일에 대한 백업이 발생한 날짜입니다. 필요한 경우 날짜 값은 0으로 채워집니다. (yyyymmdd)
 a| 
20070218



 a| 
DB-HOST(선택 사항)
 a| 
생성 또는 업데이트 중인 프로파일과 연결된 데이터베이스 호스트 이름입니다.
 a| 
my_host(내 호스트



 a| 
DB-NAME(선택 사항)
 a| 
생성한 스냅샷 복사본과 관련된 데이터베이스 이름입니다.
 a| 
경주5



 a| 
db-sid(선택 사항)
 a| 
생성한 스냅샷 복제본과 연결된 데이터베이스 sid입니다.
 a| 
rac51



 a| 
레이블(선택 사항)
 a| 
프로파일 백업과 관련된 레이블입니다.
 a| 
sample_label



 a| 
모드(옵션)
 a| 
백업이 온라인(h) 또는 오프라인(c)으로 완료되었는지 여부를 지정합니다.
 a| 
h



 a| 
프로필(선택 사항)
 a| 
생성한 백업과 연결된 프로파일 이름입니다.
 a| 
내 프로필



 a| 
범위(선택 사항)
 a| 
백업이 전체(f) 또는 부분(p)인지 여부를 지정합니다.
 a| 
F



 a| 
시간(선택 사항)
 a| 
프로파일에 대한 백업이 발생하는 시간입니다. 이 변수의 시간 값은 24시간 시계를 사용하며 필요한 경우 0으로 채워집니다. 예를 들어 5:32 및 8초가 053208(hhmmss)으로 나타납니다.
 a| 
170530)을 참조하십시오



 a| 
표준 시간대(옵션)
 a| 
타겟 데이터베이스 호스트에 대해 지정된 표준 시간대입니다.
 a| 
예상



 a| 
UserText (선택 사항)
 a| 
입력할 수 있는 사용자 지정 텍스트입니다.
 a| 
운영

|===
[NOTE]
====
SAP용 SnapManager는 스냅샷 복사본의 긴 이름 형태의 콜론(:) 기호를 지원하지 않습니다.

====