---
permalink: windows/concept-general-layout-and-configuration.html 
sidebar: sidebar 
keywords: information, recommend, general, database, layout, storage, configuration, issue, disk, group, file, type, tablespace 
summary: 디스크 그룹, 파일 유형 및 테이블스페이스와 관련된 문제를 방지하기 위해 권장되는 일반 데이터베이스 레이아웃 및 스토리지 구성에 대한 정보를 찾을 수 있습니다. 
---
= 일반 레이아웃 및 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
디스크 그룹, 파일 유형 및 테이블스페이스와 관련된 문제를 방지하기 위해 권장되는 일반 데이터베이스 레이아웃 및 스토리지 구성에 대한 정보를 찾을 수 있습니다.

* 데이터베이스에 둘 이상의 SAN 파일 시스템 유형의 파일을 포함하지 마십시오.
+
데이터베이스를 구성하는 모든 파일은 동일한 유형의 파일 시스템에 있어야 합니다.

* SnapManager에는 4K 블록 크기의 배수도 필요합니다.


다음은 볼륨 분리를 위한 몇 가지 지침입니다.

* 한 데이터베이스의 데이터 파일만 볼륨에 있어야 합니다.
* 데이터베이스 바이너리, 데이터 파일, 온라인 redo 로그 파일, 아카이빙된 redo 로그 파일, 제어 파일 등 각 파일 분류에 대해 별도의 볼륨을 사용해야 합니다.
* SnapManager는 임시 데이터베이스 파일을 백업하지 않으므로 임시 데이터베이스 파일을 위한 별도의 볼륨을 생성할 필요가 없습니다.


SAP는 Oracle 데이터베이스 설치에 표준 레이아웃을 사용합니다. 이 레이아웃에서 SAP는 Oracle 제어 파일의 복사본을 "E:\Oracle\SID\origlogA, E:\Oracle\SID\origlogB 및 E:\Oracle\SID\sapdata1 파일 시스템"에 배치합니다.


NOTE: BR * Tools 백업에는 Oracle 설치의 데이터베이스 하위 디렉토리에 있는 Oracle 및 SAP 프로파일이 포함되므로 Oracle 설치는 스토리지에 있어야 합니다.

새 설치의 경우 SAPINST를 사용하여 제어 파일의 위치를 수정하고 일반적으로 sapdata1 파일 시스템에 있는 제어 파일을 데이터 파일과 동일한 볼륨에 있지 않은 파일 시스템으로 이동할 수 있습니다. (SAPINST는 SAP 시스템 설치를 위해 SAP가 제공하는 도구입니다.)

자세한 내용은 _SnapManager for SAP Best Practices_를 참조하십시오.

* 관련 정보 *

http://media.netapp.com/documents/tr-3823.pdf["SAP를 위한 SnapManager 모범 사례: media.netapp.com/documents/tr-3823.pdf"^]
