---
permalink: windows/concept-what-snapmanager-for-oraclesnapmanager-for-sap-does.html 
sidebar: sidebar 
keywords: snapmanager, sap, simplify, simplifies, automate, database, backup, recovery, clone, leverage, snapshot, copies, copy, snaprestore, flexclone, technology, technologies 
summary: SAP용 SnapManager는 스냅샷 복사본, SnapRestore 및 FlexClone 기술을 활용하여 데이터베이스 백업, 복구 및 복제를 단순화하고 자동화합니다. 
---
= SAP용 SnapManager의 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP용 SnapManager는 스냅샷 복사본, SnapRestore 및 FlexClone 기술을 활용하여 데이터베이스 백업, 복구 및 복제를 단순화하고 자동화합니다.

SnapManager는 DBA(데이터베이스 관리자)에게 다음과 같은 이점을 제공합니다.

* 데이터베이스 프로파일 작업
+
** 프로파일에서 호스트 및 데이터베이스 정보를 구성하고 유지할 수 있습니다.
+
프로파일을 기반으로 백업을 시작할 때 모든 백업에 다시 입력하지 않고 정보를 다시 사용할 수 있습니다. SnapManager를 사용하면 프로파일을 사용하여 작업을 빠르게 모니터링할 수도 있습니다.

** 프로필에서 스냅샷 복사본의 명명 패턴을 정의하고 사용자 지정(접두사 또는 접미사) 텍스트를 입력하여 모든 스냅샷 복사본의 비즈니스 정책과 동일한 명명 규칙을 사용할 수 있습니다.
** 데이터베이스 파일이 연결된 스토리지에 자동으로 매핑되므로 스토리지 시스템 이름을 알 필요가 없습니다.
** 새 프로파일을 만들 때 아카이브 로그 백업을 데이터 파일 백업과 분리하는 옵션을 지정할 수 있습니다.
+
기존 프로파일을 업데이트하여 아카이브 로그 백업을 데이터 파일 백업과 분리할 수도 있습니다.



* 데이터베이스 백업 작업을 수행하는 중입니다
+
** 전체 및 부분 데이터베이스 백업
+
*** 공간 효율적인 방법으로 전체 또는 부분 백업을 신속하게 생성할 수 있으므로 백업을 더 자주 수행할 수 있습니다.
+
전체 데이터베이스 백업에는 모든 데이터 파일, 제어 파일 및 아카이브 로그 파일이 단일 백업에 포함됩니다.

+
부분 데이터베이스 백업에는 지정된 데이터 파일 또는 테이블스페이스, 모든 제어 파일 및 모든 아카이브 로그 파일이 포함됩니다.

*** 사후 처리 스크립트를 사용하여 보조 스토리지에 대한 백업을 보호할 수 있습니다.
*** 백업을 매시간, 주별, 일별, 월별 또는 무제한 단위로 예약할 수 있습니다.


** 데이터 파일 및 아카이브 로그 파일의 백업을 분리합니다
+
*** SnapManager(3.2 이상)를 사용하면 데이터 파일과 아카이브 로그 파일을 개별적으로 백업할 수 있습니다. 이 작업을 수행하려면 프로파일을 만들거나 업데이트하는 동안 아카이브 로그 파일을 분리하는 옵션을 지정해야 합니다.
*** 보존 정책에서 데이터 파일 백업을 유지할 개수와 기간을 지정할 수 있습니다.
*** 아카이브 로그 파일 백업이 아카이브 로그 보존 기간에 보존되도록 기간을 지정할 수 있습니다.
*** 또한 SnapManager(3.2 이상)는 아카이브 로그 백업을 중복 아카이브 로그 파일로 사용하지 않고 고유한 아카이브 로그 파일로 아카이브 로그 백업만 보존하여 아카이브 로그 백업을 최소 백업 수로 통합합니다. 그러나 이 통합은 선택적으로 해제할 수 있습니다.




* 아카이브 로그 파일 관리
+
** SnapManager(3.2 이상)를 사용하면 아카이브 로그 대상에서 아카이브 로그 파일을 정리할 수 있습니다.
+
정리된 아카이브 로그 파일이 차지하는 공간은 이러한 아카이브 로그 파일을 포함하는 아카이브 로그 백업이 제거될 때 확보됩니다.

** SnapManager를 사용하면 아카이브 로그 파일을 아카이브 로그 대상에서 제거하기 전에 해당 아카이브 로그 파일이 백업되도록 할 수 있습니다.
+
백업되지 않은 아카이브 로그 파일은 정리되지 않습니다.

** SnapManager를 사용하면 Data Guard 기본 데이터베이스에서 아카이브 로그 파일을 정리하는 동안 아카이브 로그 파일을 Data Guard 대기 데이터베이스로 전송할 수 있습니다.
** SnapManager는 보관 로그 파일이 Oracle의 스트림 캡처 프로세스(있는 경우)에 의해 캡처되도록 합니다.
** 권장 사항
+
*** 아카이브 로그 대상 공간을 효과적으로 관리하려면 아카이브 로그 백업을 생성하고 아카이브 로그 파일과 함께 제거해야 합니다.


** SnapManager는 아카이브 로그 백업을 통합하여 아카이브 로그 백업을 중복 아카이브 로그 파일과 함께 사용하고 아카이브 로그 백업만 고유 아카이브 로그 파일과 함께 유지하여 최소 백업 수를 포함합니다.
+
그러나 이 통합은 선택적으로 해제할 수 있습니다. 중복 아카이브 로그 파일이 포함된 아카이브 로그 백업이 해제되고 고유한 아카이브 로그가 있는 단일 백업이 보존됩니다.



* 데이터베이스 복원 작업을 수행하는 중입니다
+
** 파일 기반 복구 작업을 수행할 수 있습니다.
+
또한 작업을 수행하기 전에 복원 작업을 미리 보고 복원 작업에 대한 파일별 분석을 얻을 수 있습니다.

** SnapRestore를 사용하면 데이터베이스를 복원하는 평균 시간을 줄일 수 있습니다.
** SnapManager(3.2 이상)를 사용하면 아카이브 로그 파일을 아카이브 로그 대상에서 사용할 수 없는 경우에도 백업에서 아카이브 로그 파일을 사용하여 데이터베이스를 자동으로 복구할 수 있습니다.
+
또한 SnapManager(3.2 이상)는 외부 위치의 아카이브 로그 파일을 사용하여 데이터베이스를 특정 범위로 복구하는 방법을 제공합니다.



* 테스트 및 개발을 위한 데이터베이스 클로닝 수행
+
** 운영 환경 외부에서 데이터베이스를 설정할 수 있도록 데이터베이스의 클론을 생성할 수 있습니다.
+
예를 들어, 개발 및 테스트 환경에서 클론을 생성하여 중요한 시스템으로의 업그레이드를 테스트할 수 있습니다.

** 운영 스토리지 시스템에서 데이터베이스를 클론 복제할 수 있습니다.
** SnapManager(3.2 이상)를 사용하면 백업에서 사용 가능한 아카이브 로그 파일을 사용하여 데이터 파일 백업을 복제할 수 있습니다.
+
*** 아카이브 로그 백업을 함께 수행한 경우에만 데이터 파일 백업을 복제할 수 있습니다.
*** 아카이브 로그 파일이 특정 범위까지 별도로 생성된 아카이브 로그 백업에서 사용 가능한 경우 데이터 파일 백업을 복제할 수도 있습니다.
*** 또한 Oracle에서 액세스할 수 있는 모든 외부 위치의 아카이브 로그 파일을 사용하여 독립 실행형 데이터베이스의 데이터 파일 백업을 특정 범위로 복제할 수도 있습니다.
*** 외부 위치에서 백업을 사용할 수 있는 경우 클론 생성 중에 외부 위치를 지정하여 클론 생성된 데이터베이스를 정합성 보장 상태로 복구할 수 있습니다.


** 아카이브 로그 전용 백업의 클론 생성은 지원되지 않습니다.


* 일반
+
** SAP의 BR * Tools와 통합
+
BR * Tools 패키지는 brarchive, BRBACKUP, BRCONNECT, brrecover, brrestore 등의 SAP 도구를 제공합니다. BRSPACE 및 BRTools





SnapManager는 스토리지 관리자에게 다음과 같은 이점을 제공합니다.

* 다양한 SAN 프로토콜을 지원합니다.
* 운영 환경에 가장 적합한 백업 유형(전체 또는 부분)을 기반으로 백업을 최적화할 수 있습니다.
* 공간 효율적인 데이터베이스 백업 생성
* 공간 효율적인 클론 생성:


SnapManager는 다음과 같은 Oracle 기능과도 연동됩니다.

* SnapManager는 Oracle의 RMAN을 사용하여 백업을 카탈로그로 작성할 수 있습니다.
+
RMAN을 사용하는 경우 DBA는 SnapManager 백업을 사용하고 블록 레벨 복구와 같은 모든 RMAN 기능의 가치를 유지할 수 있습니다. SnapManager을 사용하면 RMAN이 복구 또는 복구를 수행할 때 스냅샷 복사본을 사용할 수 있습니다. 예를 들어 RMAN을 사용하여 테이블스페이스 내의 테이블을 복구하고 SnapManager에서 만든 Snapshot 복제본에서 전체 데이터베이스 및 테이블스페이스 복구 및 복구를 수행할 수 있습니다. RMAN 복구 카탈로그는 백업되는 데이터베이스에 있어서는 안 됩니다.


