---
permalink: windows/concept-collecting-additional-log-information-for-easier-debugging.html 
sidebar: sidebar 
keywords: additional, log, debug, fail, snapmanager, operation, external, environment, variable, server.log.level, file, collect 
summary: 실패한 SnapManager 작업을 디버깅하기 위해 추가 로그가 필요한 경우 외부 환경 변수 server.log.level을 설정해야 합니다. 이 변수는 기본 로그 레벨을 무시하고 로그 파일의 모든 로그 메시지를 덤프합니다. 예를 들어 로그 수준을 DEBUG로 변경하여 추가 메시지를 기록하고 문제를 디버깅할 수 있습니다. 
---
= 추가 로그 정보를 수집하여 디버깅을 용이하게 합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실패한 SnapManager 작업을 디버깅하기 위해 추가 로그가 필요한 경우 외부 환경 변수 'server.log.level'을 설정해야 합니다. 이 변수는 기본 로그 레벨을 무시하고 로그 파일의 모든 로그 메시지를 덤프합니다. 예를 들어 로그 수준을 DEBUG로 변경하여 추가 메시지를 기록하고 문제를 디버깅할 수 있습니다.

SnapManager 로그는 다음 위치에서 찾을 수 있습니다.

* 'sapManager_install_directory\log'입니다


기본 로그 수준을 재정의하려면 다음 단계를 수행해야 합니다.

. SnapManager 설치 디렉토리에 platform.override 텍스트 파일을 생성한다.
. platform.override 텍스트 파일에 server.log.level 매개 변수를 추가합니다.
. 값 지정(*_trace, debug, Info, warn, error, 'server.log.level' 매개 변수에 대해 Fatal 또는 PROGRESS_ *)를 입력합니다.
+
예를 들어, 로그 수준을 _ERROR_로 변경하려면 'server.log.level' 값을 _ERROR_로 설정합니다.

+
'server.log.level=error'입니다

. SnapManager 서버를 다시 시작합니다.



NOTE: 추가 로그 정보가 필요하지 않으면 platform.override 텍스트 파일에서 server.log.level 매개 변수를 삭제할 수 있습니다.

SnapManager는 'msap.config' 파일에서 다음 파라미터의 사용자 정의 값을 기준으로 서버 로그 파일의 볼륨을 관리합니다.

* 'log.max_log_files'
* 'log.max_log_file_size'입니다
* "log.max_rolling_operation_factory_logs"를 선택합니다

