---
permalink: windows/concept-what-snapmanager-operation-states-are.html 
sidebar: sidebar 
keywords: snapmanager, operation, backup, restore, clone, state, indicate, progress 
summary: 'SnapManager 작업(백업, 복원 및 클론)은 서로 다른 상태일 수 있으며 각 상태는 작업의 진행률을 나타냅니다.' 
---
= SnapManager 작업 상태는 무엇입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 작업(백업, 복원 및 클론)은 서로 다른 상태일 수 있으며 각 상태는 작업의 진행률을 나타냅니다.

|===
| 작업 상태입니다 | 설명 


 a| 
성공했습니다
 a| 
작업이 성공적으로 완료되었습니다.



 a| 
실행 중입니다
 a| 
작업이 시작되었지만 완료되지 않았습니다. 예를 들어 2분 정도 걸리는 백업은 오전 11시에 실행되도록 예약되어 있습니다. 오전 11:01에 * Schedule * 탭을 보는 경우 작업이 실행 중인 것으로 나타납니다.



 a| 
작업을 찾을 수 없습니다
 a| 
스케줄이 실행되지 않았거나 마지막 실행 백업이 삭제되었습니다.



 a| 
실패했습니다
 a| 
작업이 실패했습니다. SnapManager가 중단 프로세스를 자동으로 실행하고 작업을 정리했습니다.

|===


== 복구할 수 없는 이벤트입니다

복구 가능한 SnapManager 이벤트에는 다음과 같은 문제가 있습니다.

* 데이터베이스는 Data ONTAP을 실행하는 스토리지 시스템에 저장되지 않습니다.
* Windows용 SnapDrive가 설치되지 않았거나 스토리지 시스템을 액세스할 수 없습니다.
* 볼륨에 공간이 부족하거나, 스냅샷 복사본의 최대 수에 도달했거나, 예기치 않은 예외가 발생한 경우 SnapManager에서 스냅샷 복사본 또는 스토리지 프로비저닝을 생성하지 못합니다.


복구 가능한 이벤트가 발생하면 SnapManager는 중단 프로세스를 수행하고 호스트, 데이터베이스 및 스토리지 시스템을 시작 상태로 반환하려고 시도합니다. 중단 프로세스가 실패하면 SnapManager는 해당 인시던트를 복구할 수 없는 이벤트로 처리합니다.

복구할 수 없는(대역외) 이벤트는 다음 중 하나가 발생할 때 발생합니다.

* 호스트 장애 등의 시스템 문제가 발생합니다.
* SnapManager 프로세스가 중지됩니다.
* 스토리지 시스템에 장애가 발생하거나 LUN(Logical Unit Number) 또는 스토리지 볼륨이 오프라인 상태이거나 네트워크에 장애가 발생할 경우 대역내 중단 작업이 실패합니다.


복구할 수 없는 이벤트가 발생하면 SnapManager는 중단 프로세스를 즉시 수행합니다. 호스트, 데이터베이스 및 스토리지 시스템이 초기 상태로 돌아오지 않았을 수 있습니다. 이 경우 분리된 스냅샷 복사본을 삭제하고 SnapManager 잠금 파일을 제거하여 SnapManager 작업이 실패한 후에 정리 작업을 수행해야 합니다.

SnapManager Lock 파일을 삭제하려면 대상 시스템에서 "$oracle_home"으로 이동하여 'sm_lock_TargetDBName' 파일을 삭제합니다. 파일을 삭제한 후 SnapManager for SAP 서버를 다시 시작해야 합니다.
