---
permalink: windows/concept-advantages-of-using-snapmanager.html 
sidebar: sidebar 
keywords: snapmanager, sap, task, database, manage, data, advantage, use 
summary: SAP용 SnapManager를 사용하면 데이터베이스에서 여러 작업을 수행하고 데이터를 효율적으로 관리할 수 있습니다. 
---
= SnapManager 사용의 이점
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP용 SnapManager를 사용하면 데이터베이스에서 여러 작업을 수행하고 데이터를 효율적으로 관리할 수 있습니다.

SnapManager for SAP는 스토리지 시스템에서 작동하며 다음과 같은 작업을 수행할 수 있도록 지원합니다.

* 운영 또는 2차 스토리지에 대한 공간 효율적인 백업을 생성하고 백업 일정을 수립합니다.
+
전체 및 부분 데이터베이스 백업을 만들고 보존 기간 정책을 적용할 수 있습니다. SnapManager(3.2 이상)를 사용하면 데이터 파일과 아카이브 로그의 백업만 만들 수 있습니다.

+
** SnapManager(3.2 이상)을 사용하면 백업 및 복원 작업 전후에 사전 처리 또는 사후 처리를 수행할 수 있습니다.
** SnapManager(3.2 이상)를 사용하면 후처리 스크립트를 사용하여 백업을 보호할 수 있습니다.


* 파일 기반 복원 작업을 사용하여 전체 또는 부분 데이터베이스를 복원합니다.
* 데이터베이스 백업을 자동으로 복원 및 복구합니다.
+
SnapManager(3.2 이상)를 사용하면 데이터베이스 백업을 자동으로 복원 및 복구할 수 있습니다. SnapManager는 백업에서 아카이브 로그 파일을 검색, 마운트 및 적용하여 복구된 데이터베이스를 자동으로 복구합니다.

* 아카이브 로그에만 대한 백업을 생성할 때 아카이브 로그 대상에서 아카이브 로그 파일을 압축합니다.
* 고유한 아카이브 로그 파일이 있는 백업만 유지하여 아카이브 로그 백업의 최소 개수를 자동으로 보존합니다.
* 작업 세부 정보를 추적하고 호스트, 프로필, 백업 또는 클론별로 보고서를 생성합니다.
* 백업 상태를 확인합니다.
* 프로필과 관련된 SnapManager 작업 기록을 유지 관리합니다.
* 운영 스토리지에서 공간 효율적인 백업 클론을 생성합니다.

