---
permalink: windows/concept-configuring-e-mail-notification.html 
sidebar: sidebar 
keywords: snapmanager, enable, email, notification, completion, status, profile-executed, database, operation, profile, execute, generate, status, configure 
summary: SnapManager를 사용하면 프로파일로 실행된 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 받을 수 있습니다. SnapManager에서 이메일을 생성하고 데이터베이스 작업 완료 상태에 따라 적절한 조치를 취할 수 있도록 도와줍니다. 이메일 알림 구성은 선택 사항입니다. 
---
= 이메일 알림 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용하면 프로파일로 실행된 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 받을 수 있습니다. SnapManager에서 이메일을 생성하고 데이터베이스 작업 완료 상태에 따라 적절한 조치를 취할 수 있도록 도와줍니다. 이메일 알림 구성은 선택 사항입니다.

개별 프로파일에 대한 이메일 알림을 프로필 알림으로 구성하고 리포지토리 데이터베이스의 여러 프로필에 대한 이메일 알림을 요약 알림으로 구성할 수 있습니다.

* 프로필 알림 *

개별 프로파일의 경우 성공한 데이터베이스 작업과 실패한 데이터베이스 작업 중 하나 또는 둘 다에 대한 이메일을 받을 수 있습니다.


NOTE: 기본적으로 전자 메일 알림은 실패한 데이터베이스 작업에 대해 활성화됩니다.

* 요약 알림 *

요약 알림을 사용하면 여러 프로필을 사용하여 수행된 데이터베이스 작업에 대한 요약 이메일을 받을 수 있습니다. 시간별, 일별, 주별 또는 월별 알림을 설정할 수 있습니다.


NOTE: SnapManager 3.3에서는 알림을 보내야 하는 호스트 서버를 지정한 경우에만 요약 알림이 전송됩니다. 3.3 이전 버전에서 SnapManager를 업그레이드하는 경우 요약 알림 구성에서 호스트 서버를 지정하지 않은 경우 요약 알림이 전송되지 않을 수 있습니다.


NOTE: RAC(Real Application Clusters) 환경에 있는 데이터베이스의 한 노드에 리포지토리를 생성하고 요약 알림을 활성화한 경우 나중에 동일한 리포지토리를 데이터베이스의 다른 노드에 추가하면 요약 알림 이메일이 두 번 전송됩니다.

한 번에 프로필 수준 알림 또는 요약 알림을 사용할 수 있습니다.

SnapManager는 다음 프로파일 실행 데이터베이스 작업에 대해 이메일 알림을 활성화합니다.

* 운영 스토리지에 백업을 생성합니다
* 백업을 복원합니다
* 클론 생성
* 백업을 확인합니다


이메일 알림이 활성화된 상태에서 프로필을 만들거나 업데이트한 후에는 프로필을 사용하지 않도록 설정할 수 있습니다. e-메일 알림을 사용하지 않도록 설정하면 해당 프로필이 실행된 데이터베이스 작업에 대한 e-메일 알림을 더 이상 받지 않습니다.

받은 이메일에는 다음 세부 정보가 포함되어 있습니다.

* 데이터베이스 작업의 이름입니다(예: 백업, 복원 또는 클론)
* 데이터베이스 작업에 사용되는 프로파일 이름입니다
* 호스트 서버의 이름입니다
* 데이터베이스의 시스템 식별자입니다
* 데이터베이스 작업의 시작 및 종료 시간입니다
* 데이터베이스 작업의 상태입니다
* 오류 메시지(있는 경우
* 경고 메시지(있는 경우


다음을 구성할 수 있습니다.

* 리포지토리의 메일 서버입니다
* 새 프로필에 대한 이메일 알림입니다
* 기존 프로필에 대한 이메일 알림입니다
* 리포지토리 아래의 여러 프로필에 대한 요약 이메일 알림



NOTE: CLI(Command-Line Interface)와 GUI(그래픽 사용자 인터페이스)에서 이메일 알림을 구성할 수 있습니다.
