---
permalink: windows/concept-how-to-organize-repositories.html 
sidebar: sidebar 
keywords: organize, snapmanager, repository, repositories, business, application, type, usage 
summary: SnapManager 리포지토리를 비즈니스 요구에 맞게 구성할 수 있습니다. 응용 프로그램 유형 및 사용을 비롯한 여러 가지 방법으로 구성할 수 있습니다. 
---
= 리포지토리 구성 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 리포지토리를 비즈니스 요구에 맞게 구성할 수 있습니다. 응용 프로그램 유형 및 사용을 비롯한 여러 가지 방법으로 구성할 수 있습니다.

여러 가지 방법으로 리포지토리를 구성할 수 있습니다. 이러한 두 가지 방법은 다음과 같습니다.

|===
| 유형 | 특징 


 a| 
응용 프로그램별
 a| 
서로 다른 애플리케이션을 실행하는 여러 Oracle 데이터베이스가 있는 경우 모든 애플리케이션 유형에 대해 SnapManager 리포지토리를 생성할 수 있습니다. 각 SnapManager 리포지토리에는 특정 응용 프로그램 유형의 데이터베이스에 대한 프로필이 있습니다. 해당 애플리케이션 유형의 모든 운영, 개발 및 테스트 데이터베이스는 동일한 SnapManager 저장소에서 관리됩니다. 이 옵션은 유사한 데이터베이스를 그룹화하고 복제를 쉽게 하는 데 도움이 됩니다. 그러나 여러 응용 프로그램 유형이 있는 경우 여러 SnapManager 리포지토리를 관리해야 할 수 있으며 다른 응용 프로그램 유형을 구현하기로 선택한 경우 다른 SnapManager 리포지토리를 만들어야 합니다. 이러한 SnapManager 리포지토리가 프로덕션 데이터베이스를 관리하므로 각 리포지토리는 고가용성을 갖춘 서버에 있어야 합니다. 이 경우 비용이 많이 들 수 있습니다. 또한 동일한 SnapManager 리포지토리에서 동일한 유형의 개발 및 테스트 데이터베이스와 함께 운영 데이터베이스를 관리해야 하는 것은 보안 문제가 될 수 있습니다.



 a| 
사용량별
 a| 
데이터베이스를 사용(예: 프로덕션, 개발, 테스트 및 교육)에 따라 SnapManager 리포지토리 간에 배포할 수 있습니다. 이 옵션은 저장소 수를 보유한 여러 유형의 데이터베이스로 제한합니다. 모든 운영 데이터베이스는 단일 SnapManager 저장소에서 관리되기 때문에 운영 데이터베이스 관리자만 이 리포지토리에 액세스할 수 있습니다. 또한 새 응용 프로그램 유형에 대해 다른 데이터베이스를 배포하도록 선택한 경우에는 새 리포지토리를 만드는 대신 해당 SnapManager 리포지토리에 데이터베이스를 등록하기만 하면 됩니다. 모든 운영 데이터베이스의 프로필을 보관하는 SnapManager 리포지토리에만 고가용성을 제공할 수 있습니다.

|===
Oracle용 SnapManager와 SAP용 SnapManager는 동일한 리포지토리를 공유해서는 안 됩니다. SnapManager for Oracle 및 SnapManager for SAP의 경우 두 환경 모두에 있는 경우 각 제품에 대해 서로 다른 저장소(다른 Oracle 데이터베이스 사용자)를 사용해야 합니다. 동일하거나 다른 데이터베이스에서 다른 리포지토리를 사용하면 각 제품에 대해 독립적인 업그레이드 주기를 허용하여 보다 유연하게 사용할 수 있습니다.
