---
permalink: windows/concept-managing-profiles-for-efficient-backups.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, database, perform, operation, manage, efficient, backup 
summary: 작업을 수행할 데이터베이스에 대해 SnapManager에서 프로필을 만들어야 합니다. 프로파일을 선택한 다음 수행할 작업을 선택해야 합니다. 
---
= 효율적인 백업을 위한 프로필 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
작업을 수행할 데이터베이스에 대해 SnapManager에서 프로필을 만들어야 합니다. 프로파일을 선택한 다음 수행할 작업을 선택해야 합니다.



== 프로파일과 관련된 작업

다음 작업을 수행할 수 있습니다.

* 프로파일을 생성하여 기본 또는 보조 스토리지에 전체 또는 부분 백업 및 백업을 수행할 수 있습니다.
+
데이터 파일 백업에서 아카이브 로그 백업을 분리하는 프로파일을 생성할 수도 있습니다.

* 프로필을 확인합니다.
* 프로파일을 업데이트합니다.
* 프로파일 삭제.




== 프로파일 및 인증에 대해 설명합니다

프로파일을 만들 때 데이터베이스를 지정하고 다음 방법 중 하나를 선택하여 데이터베이스에 연결할 수 있습니다.

* 사용자 이름, 암호 및 포트를 사용한 Oracle 인증
* 사용자 이름, 암호 또는 포트가 없는 운영 체제(OS) 인증
+
OS 인증의 경우 OS 계정 사용자 및 그룹 정보를 입력해야 합니다.

* 'qlnet.authentication_services` * none * 으로 설정된 경우 데이터베이스 인증. 그런 다음 SnapManager는 대상 데이터베이스에 대한 모든 연결에 대해 데이터베이스 사용자 이름과 암호를 사용합니다. SnapManager는 'qlnet.authentication_services` * NTS * 로 설정된 경우에도 Windows 기본 인증을 사용할 수 있습니다.


다음 환경에서만 qlnet.authentication_services` 를 * none * 으로 설정할 수 있습니다.

|===
| 데이터베이스 레이아웃 | Oracle 버전 | 타겟 데이터베이스에 대해 데이터베이스 인증이 지원됩니다 


 a| 
모든 비 ASM 및 비 RAC 데이터베이스
 a| 
Oracle 10g 및 Oracle 11g(11.2.0.3 미만)
 a| 
예

|===
[NOTE]
====
'qlnet.authentication_services` 를 비활성화하고 인증 방법을 데이터베이스 인증으로 변경한 후 'qlnet.authentication_services` * none * 으로 설정해야 합니다.

====
처음으로 프로파일에 액세스하는 경우 프로파일 암호를 입력해야 합니다. 자격 증명을 입력한 후 프로필 내에서 데이터베이스 백업을 볼 수 있습니다.
