---
permalink: windows/concept-what-database-restore-is.html 
sidebar: sidebar 
keywords: snapmanager, enable, perform, file-based, backup, restore, operation, database 
summary: SnapManager를 사용하면 파일 기반 백업 및 복원 작업을 수행할 수 있습니다. 
---
= 데이터베이스 복원이란 무엇입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용하면 파일 기반 백업 및 복원 작업을 수행할 수 있습니다.

다음 표에는 복원 방법이 설명되어 있습니다.

|===
| 복원 프로세스 | 세부 정보 


 a| 
파일 기반 복원
 a| 
스토리지 측 전체 파일 시스템 복구(운영 또는 2차 복구): SnapManager는 전체 LUN(Logical Unit Number) 복구를 수행합니다.

|===


== 스토리지 측 전체 파일 시스템 복구

스토리지 측 전체 파일 시스템 복구는 볼륨 복구를 수행할 수 없지만 스토리지 시스템에서 전체 파일 시스템을 복구할 수 있는 경우에 수행됩니다.

스토리지 측 파일 시스템 복구를 수행하는 경우 다음이 발생합니다.

* SAN 환경에서는 파일 시스템(및 기본 볼륨 그룹(있는 경우)이 사용하는 모든 LUN이 스토리지 시스템에 복구됩니다.


스토리지 측 파일 시스템 복구를 수행하는 경우 스토리지 위치에 따라 다음이 수행됩니다.

* SnapManager가 운영 스토리지 시스템에서 복구되면 SFSR을 통해 LUN(SAN)이 제자리에 복구됩니다.
* SnapManager가 보조 스토리지 시스템에서 복구되면 LUN(SAN)이 보조 스토리지 시스템에서 네트워크를 통해 운영 스토리지 시스템으로 다시 복제됩니다.


파일 시스템이 완전히 복원되므로 백업에 포함되지 않은 파일도 되돌릴 수 있습니다. 복구 중인 파일 시스템에 복구 작업이 아닌 파일이 있는 경우 재정의가 필요합니다.



== 호스트 측 파일 복원

호스트 측 파일 복사 복구는 SAN 환경에서 스토리지측 파일 시스템 복구 및 스토리지 측 파일 복구를 수행할 수 없을 때 마지막 수단으로 사용됩니다.

호스트 측 파일 복사 복원에는 다음 작업이 포함됩니다.

* 스토리지를 클론 복제하십시오
* 복제된 스토리지를 호스트에 연결합니다
* 클론 파일 시스템에서 액티브 파일 시스템으로 파일을 다시 복제합니다
* 호스트에서 클론 스토리지 연결을 끊는 중입니다
* 클론 스토리지 삭제

