---
permalink: windows/concept-what-repositories-are.html 
sidebar: sidebar 
keywords: snapmanager, information, profile, repositories, repository 
summary: SnapManager는 정보를 프로파일로 구성한 후 리포지토리와 연관됩니다. 프로파일에는 관리 중인 데이터베이스에 대한 정보가 포함되어 있고, 리포지토리에는 프로파일에서 수행되는 작업에 대한 데이터가 포함되어 있습니다. 
---
= 리포지토리의 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager는 정보를 프로파일로 구성한 후 리포지토리와 연관됩니다. 프로파일에는 관리 중인 데이터베이스에 대한 정보가 포함되어 있고, 리포지토리에는 프로파일에서 수행되는 작업에 대한 데이터가 포함되어 있습니다.

리포지토리는 백업이 발생한 시간, 백업된 파일 및 백업에서 클론이 생성되었는지 여부를 기록합니다. 데이터베이스 관리자가 데이터베이스를 복원하거나 데이터베이스의 일부를 복구할 때 SnapManager는 리포지토리를 쿼리하여 백업된 항목을 확인합니다.

리포지터리는 백업 작업 중에 생성된 데이터베이스 Snapshot 복사본의 이름을 저장하므로 저장소 데이터베이스는 동일한 데이터베이스에 있을 수 없으며 SnapManager이 백업하는 것과 동일한 데이터베이스에 포함될 수도 없습니다. SnapManager 작업을 실행할 때 두 개 이상의 데이터베이스(SnapManager 리포지토리 데이터베이스와 SnapManager에서 관리하는 타겟 데이터베이스)가 실행 중이어야 합니다.

리포지터리 데이터베이스가 다운되었을 때 그래픽 사용자 인터페이스(GUI)를 열려고 하면 'sm_gui.log' 파일에 다음과 같은 오류 메시지가 기록됩니다. [WARN]:'MSAP-01106: 리포지터리를 쿼리하는 동안 오류가 발생했습니다. 소켓에서 읽을 데이터가 더 이상 없습니다.' 또한 저장소 데이터베이스가 다운되면 SnapManager 작업이 실패합니다. 다른 오류 메시지에 대한 자세한 내용은 _ 알려진 문제 해결 _ 을(를) 참조하십시오.

유효한 호스트 이름, 서비스 이름 또는 사용자 이름을 사용하여 작업을 수행할 수 있습니다. SnapManager 작업을 지원하는 리포지토리의 경우 리포지토리 사용자 이름 및 서비스 이름은 알파벳 문자(A-Z), 숫자(0-9), 빼기 기호(-), 밑줄(_) 및 마침표(.)로만 구성되어야 합니다.

리포지토리 포트는 유효한 포트 번호일 수 있으며 리포지토리 호스트 이름은 유효한 호스트 이름일 수 있습니다. 호스트 이름은 알파벳 문자(A-Z), 숫자(0-9), 빼기 기호(-) 및 마침표(.)로 구성되어야 하지만 밑줄(_)은 사용하면 안 됩니다.

리포지토리는 Oracle 데이터베이스에서 만들어야 합니다. SnapManager에서 사용하는 데이터베이스는 데이터베이스 구성에 대한 Oracle 절차에 따라 설정해야 합니다.

단일 리포지토리에는 여러 프로필에 대한 정보가 포함될 수 있지만 일반적으로 각 데이터베이스는 하나의 프로파일에만 연결됩니다. 여러 개의 리포지토리가 있고 각 리포지토리에는 여러 개의 프로파일이 포함될 수 있습니다.
