---
permalink: windows/concept-profile-usage-for-br-tools-backups.html 
sidebar: sidebar 
keywords: br, tools, command, backint, interface, interface, snapmanager, profile, repository, credential, user, run, backup 
summary: backint 인터페이스를 사용하는 BR * Tools 명령을 실행하면 SnapManager는 리포지토리의 프로파일을 사용합니다. 리포지토리는 BR * Tools 명령을 실행하는 사용자의 SnapManager 자격 증명에 의해 결정됩니다. 
---
= BR * Tools 백업에 대한 프로파일 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
backint 인터페이스를 사용하는 BR * Tools 명령을 실행하면 SnapManager는 리포지토리의 프로파일을 사용합니다. 리포지토리는 BR * Tools 명령을 실행하는 사용자의 SnapManager 자격 증명에 의해 결정됩니다.

기본적으로 SnapManager는 SAP 데이터베이스 시스템 식별자와 이름이 같은 프로필을 사용합니다.



== 리포지토리에 액세스하기 위한 자격 증명 생성 정보

'smsap 자격 증명 세트' 명령을 사용하여 BR * Tools 사용자에 대한 리포지토리 자격 증명을 설정할 수 있습니다.



== 다른 SnapManager 프로파일 이름 지정 정보

시스템 식별자가 지정된 리포지토리에 있는 SnapManager 프로파일이 있는 모든 호스트에 대해 고유하면 기본 프로파일 이름만으로도 충분합니다. 데이터베이스 시스템 식별자 값을 사용하여 SnapManager 프로필을 만들고 이름을 지정할 수 있습니다.

그러나 동일한 시스템 식별자가 다른 호스트에서 사용되는 경우 또는 지정된 SAP 인스턴스에서 BR* Tools에 사용할 SnapManager 프로파일을 두 개 이상 지정하려면 BR* Tools 명령에 대한 프로파일 이름을 정의해야 합니다.

SAP 애플리케이션 내에서 예약된 데이터베이스 작업이 사용자로 실행됩니다. BR * SAP 애플리케이션에서 예약된 Tools 작업은 'APServiceSID'로 실행됩니다. 이러한 사용자는 리포지토리와 프로파일에 대한 액세스 권한이 있어야 합니다.

SAP 서비스 사용자 SAPServiceSID는 사용자가 로컬로 로그인할 수 없습니다. 이를 변경하려면 다음 단계를 수행하여 로컬 보안 정책을 수정해야 합니다.

.단계
. 시작 * > * 프로그램 * > * 관리 도구 * > * 로컬 보안 정책 * 을 클릭합니다.
. 로컬 정책*을 확장하고 ** 사용자 권한 할당**을 선택합니다
. 로컬 로그온 거부 * 정책을 검색합니다.
. 오른쪽 클릭하고 * 속성 * 을 선택합니다.
. 이 목록에서 * SAP 서비스 사용자 * 를 삭제합니다.




== 백업 유틸리티 매개 변수 파일 생성 정보

BR * Tools 명령은 백업 유틸리티 매개 변수('.utl' 매개 변수) 파일을 backint 인터페이스에 선택적으로 전달할 수 있습니다. 기본적으로 이 파일의 이름은 initSID.utl이며 여기서 SID는 데이터베이스의 시스템 식별자입니다.

기본적으로 BR * Tools는 initSID.sap 파일의 'util_par_file' 매개 변수에 의해 지정된 매개 변수 파일을 사용합니다. 백업 유틸리티 매개변수 파일은 일반적으로 'initSID.sap' 파일과 동일한 디렉토리에 저장됩니다.

profile_name=<profile>'을 '.utl' 파일에 추가하고 저장합니다. 프로파일은 BR * Tools 명령에 사용할 SnapManager_PROFILE_의 이름입니다.

다음 표에는 백업 보존, 빠른 복원 및 데이터 보호와 같은 작업을 위한 '.utl' 파일에 포함된 추가 백업 유틸리티 매개 변수가 나와 있습니다.

|===
| 운영 | 백업 유틸리티 매개 변수 


 a| 
백업 보존
 a| 
* 키: 유지
* 값: 무제한




| 매시간 | 매일 


| 매주 | 매월 
|===
다음 표에는 이러한 작업에 대한 다양한 백업 유틸리티 매개 변수가 설명되어 있습니다.

|===
| 작동 | 키 | 값 


 a| 
백업 보존
 a| 
빠른 속도 =
 a| 
대체

|===


== BR * Tools 초기화 파일에 백업 유틸리티 매개 변수 추가

SAP는 각 SAP 데이터베이스 인스턴스에 대해 '$ORACLE_HOME\database\'에 initSID.sap이라는 백업 프로파일 파일을 생성합니다. 이 파일을 사용하여 BR * Tools 명령에 사용되는 기본 백업 유틸리티 매개변수('.utl') 파일을 지정할 수 있습니다.

.단계
. initSID.sap 파일을 편집하여 'util_par_file='로 시작하는 줄을 찾습니다.
. 이 줄의 주석을 해제하고 프로파일 이름이 포함된 백업 유틸리티 매개 변수 파일에 경로를 추가합니다(예: "util_par_file=initSA1.utl").
. 'util_par_file'에 대한 값을 지정할 경우 파일이 있는지 확인하십시오.
+
파일을 찾을 수 없는 경우 BRBACKUP 명령은 해당 파일을 백업에 포함하려고 하기 때문에 실패합니다.



다음 오류 조건 중 하나라도 발견되면 프로파일 이름으로 '-u' 옵션을 사용해야 합니다.

* 파라미터 파일이 존재하지 않습니다
* profile_name 항목 없음


"orasid"와 "stidadm"은 모두 BR * Tools로 생성된 백업을 생성하거나 관리하는 데 사용되는 프로파일에 대한 액세스 권한이 필요합니다.



== BR * Tools 명령에서 백업 유틸리티 매개변수 파일 이름 지정

필요에 따라 '-r' 옵션을 사용하여 BR * Tools 명령에 백업 유틸리티 매개변수(.utl 매개변수) 파일을 지정할 수 있습니다. 명령줄의 값은 SAP 초기화 파일에 지정된 값을 재정의합니다.

BR * Tools는 '$ORACLE_HOME\database\' 디렉토리에서 매개변수 파일을 검색합니다. 파일을 다른 위치에 저장하는 경우 '-r' 옵션을 사용하여 전체 경로를 제공해야 합니다. 예를 들면 다음과 같습니다.

'* brbackup -r C:\oracle\netapp_fcp_price_10g_enterprise_inst_vol1\database\initcer.utl... *'
