---
permalink: windows/concept-how-snapmanager-retains-backups-on-the-local-storage.html 
sidebar: sidebar 
keywords: snapmanager, enable, create, backup, retention, policies, policy, successful, local, storage, retain, database 
summary: SnapManager를 사용하면 보존 정책을 충족하는 백업을 생성할 수 있습니다. 이 경우 로컬 스토리지에 대해 보존할 성공적인 백업 수를 지정합니다. 지정된 데이터베이스에 대해 프로파일에 보존되어야 하는 성공적인 백업 수를 지정할 수 있습니다. 
---
= SnapManager가 로컬 스토리지에 백업을 유지하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용하면 보존 정책을 충족하는 백업을 생성할 수 있습니다. 이 경우 로컬 스토리지에 대해 보존할 성공적인 백업 수를 지정합니다. 지정된 데이터베이스에 대해 프로파일에 보존되어야 하는 성공적인 백업 수를 지정할 수 있습니다.

다음에 대한 백업을 생성할 수 있습니다.

* 기본 스토리지에서 매일 10일 백업
* 기본 스토리지에서 2개월 간의 월별 백업
* 7일 동안 보조 스토리지에 매일 백업
* 2차 스토리지에 대해 4주간의 주별 백업
* 2차 스토리지에 대한 6개월 간의 월별 백업


SnapManager의 각 프로필에 대해 다음과 같이 제한적이지 않은 보존 클래스의 값을 변경할 수 있습니다.

* 매시간
* 매일
* 매주
* 매월


SnapManager는 보존 수(예: 15개 백업)와 보존 기간(예: 매일 10일 백업)을 모두 고려하여 백업을 보존할지 여부를 결정합니다. 보존 클래스에 대해 설정된 보존 기간을 초과하거나 백업 수가 보존 수를 초과할 경우 백업이 만료됩니다. 예를 들어 백업 수가 15이고(SnapManager가 15개의 백업을 성공적으로 수행함) 기간 요구 사항이 매일 10일 동안 설정된 경우 가장 오래된 적격 백업 5개가 만료됩니다.

백업이 만료되면 SnapManager는 만료된 백업을 해제 또는 삭제합니다. SnapManager는 항상 마지막으로 수행된 백업을 유지합니다.

SnapManager는 보존 개수에 대해 성공한 백업 수만 계산하며 다음을 고려하지 않습니다.

|===
| 보존 개수에 포함되지 않은 백업입니다 | 추가 정보 


 a| 
실패한 백업
 a| 
SnapManager는 성공하거나 실패한 백업에 대한 정보를 보관합니다. 백업이 실패할 경우 리포지토리에서 최소 공간만 필요하기 때문에 이를 삭제할 수 있습니다. 실패한 백업은 삭제할 때까지 저장소에 남아 있습니다.



 a| 
무제한 백업이나 다른 보존 클래스에 대해 백업하도록 지정된 백업입니다
 a| 
SnapManager는 무제한 보존되도록 지정된 백업을 삭제하지 않습니다. 또한 SnapManager에서는 동일한 보존 클래스에 있는 백업만 고려합니다(예: SnapManager에서는 시간별 보존 개수에 대해서만 시간별 백업을 고려합니다).



 a| 
로컬 스토리지에서 마운트된 백업입니다
 a| 
스냅샷 복사본이 마운트되면 클론 복제도 되므로 데이터 보존이 적용되지 않습니다. SnapManager에서는 스냅샷 복사본이 클론 복제된 경우 이를 삭제할 수 없습니다.



 a| 
로컬 스토리지에 클론을 생성하는 데 사용되는 백업입니다
 a| 
SnapManager는 클론을 생성하는 데 사용되는 모든 백업을 유지하지만 백업 보존 개수에 대해서는 고려하지 않습니다.

|===
SnapManager는 각 보존 클래스에 대한 기본 보존 수 및 기간을 제공합니다. 예를 들어, hourly retention class count의 경우 기본적으로 SnapManager는 4개의 hourly 백업을 유지합니다. 이 기본값을 무시하고 프로파일을 만들거나 업데이트할 때 값을 설정하거나 'msap.config' 파일에서 보존 수 및 기간의 기본값을 변경할 수 있습니다.

보존 정책에 따라 로컬 백업이 만료되면 백업이 삭제됩니다.

아카이브 전용 백업 작업에서 SnapManager는 온라인 데이터베이스 백업 프로세스와는 달리 재실행 로그 파일을 보관하지 않습니다. 아카이브 전용 백업 작업을 수행하기 전에 사전 작업 스크립트를 추가하여 redo 로그 파일을 아카이브해야 합니다. 사전 작업 스크립트는 '시스템 스위치 로그 파일 변경' 명령을 실행해야 합니다.

다음 예에서는 3일 백업 보존 정책(보존 횟수가 3으로 설정됨)을 기준으로 SnapManager에서 다양한 유형의 백업을 수행하는 작업을 보여 줍니다.

|===
| 백업 날짜 | 상태 | 보존 정책 작업이 수행됩니다 | 설명 


 a| 
5월 10일
 a| 
성공했습니다
 a| 
유지
 a| 
이 백업이 가장 최근에 성공한 백업이므로 유지됩니다.



 a| 
5월 9일
 a| 
성공, 복제
 a| 
건너뛰기
 a| 
SnapManager에서는 보존 정책 카운트의 클론 생성에 사용되는 백업을 고려하지 않습니다. 이 백업은 성공한 백업 횟수로부터 생략됩니다.



 a| 
5월 8일
 a| 
성공, 탑재
 a| 
건너뛰기
 a| 
SnapManager에서는 마운트된 백업을 보존 정책 횟수로 고려하지 않습니다. 이 백업은 성공한 백업 횟수로부터 생략됩니다.



 a| 
5월 7일
 a| 
실패했습니다
 a| 
건너뛰기
 a| 
실패한 백업은 계산되지 않습니다.



 a| 
5월 5일
 a| 
성공했습니다
 a| 
유지
 a| 
SnapManager는 이 두 번째 성공적인 일일 백업을 유지합니다.



 a| 
5월 3일
 a| 
성공했습니다
 a| 
유지
 a| 
SnapManager는 이 세 번째 일일 백업을 성공시켜 줍니다.



 a| 
5월 2일
 a| 
성공했습니다
 a| 
삭제
 a| 
SnapManager는 이 성공적인 백업을 계산하지만 SnapManager가 세 번의 일일 백업에 도달하면 이 백업이 삭제됩니다.

|===
* 관련 정보 *

http://mysupport.netapp.com/["NetApp Support 사이트에 문서화"^]
