---
permalink: windows/concept-what-database-backup-scheduling-is.html 
sidebar: sidebar 
keywords: schedule, update, monitor, backup, database, graphical, user, interface 
summary: 그래픽 사용자 인터페이스의 Schedule 탭을 사용하여 데이터베이스의 백업을 예약, 업데이트 및 모니터링할 수 있습니다. 
---
= 데이터베이스 백업 스케줄이란 무엇입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그래픽 사용자 인터페이스의 Schedule 탭을 사용하여 데이터베이스의 백업을 예약, 업데이트 및 모니터링할 수 있습니다.

다음 표에서는 일반적인 일정 관련 질문에 대해 설명합니다.

|===
| 질문 | 답변 


 a| 
SnapManager 서버가 다시 시작될 때 예약된 백업은 어떻게 됩니까?
 a| 
SnapManager 서버가 다시 시작되면 모든 스케줄이 자동으로 다시 시작됩니다. 그러나 SnapManager는 놓친 경우 후속 조치를 수행하지 않습니다.



 a| 
두 개의 데이터베이스에 동시에 두 개의 백업이 수행되도록 예약된 경우 어떻게 됩니까?
 a| 
SnapManager는 한 번에 하나씩 백업 작업을 시작한 다음 백업을 병렬로 실행할 수 있습니다. 예를 들어 데이터베이스 관리자가 오전 1시에 6개의 서로 다른 데이터베이스 프로파일에 대해 6개의 일일 백업 스케줄을 생성할 경우 6개의 백업이 모두 병렬로 실행됩니다.

짧은 시간 내에 단일 데이터베이스 프로파일에서 여러 백업이 수행되도록 예약된 경우 SnapManager 서버는 보존 기간이 가장 긴 백업 작업만 실행합니다.

백업 작업을 시작하기 전에 SnapManager에서 먼저 다음 사항을 확인합니다.

* 지난 30분 이내에 동일한 프로필에 대해 더 많은 보존 기간을 지정하여 백업을 성공적으로 생성했습니까?
* 다음 30분 이내에 다른 스케줄에서 동일한 프로필에 대해 더 많은 보존 기간을 사용하여 백업을 생성하려고 합니까?


두 질문에 모두 예라고 대답하면 SnapManager는 백업을 건너뜁니다.

예를 들어 데이터베이스 관리자는 데이터베이스 프로필에 대한 일별, 주별 및 월별 스케줄을 생성할 수 있으며, 이러한 스케줄은 모두 오전 1시에 백업을 수행하도록 예약되어 있습니다 3개의 백업이 동시에 오전 1시에 수행되도록 예약된 월의 어느 날, SnapManager는 월별 스케줄에 따라 백업 작업만 실행합니다.

30분의 시간 창은 SnapManager 속성 파일에서 변경할 수 있습니다.



 a| 
어떤 사용자가 백업 작업을 실행합니까?
 a| 
이 작업은 스케줄을 생성한 사용자 아래에서 실행됩니다. 그러나 데이터베이스 프로파일과 호스트 모두에 대해 유효한 자격 증명이 있는 경우 사용자 ID로 변경할 수 있습니다. 예를 들어 Avida Davis가 만든 백업 스케줄에 대해 예약된 백업 속성을 시작하면 Stella Morrow는 예약된 백업을 실행할 사용자로 이 작업 수행에서 자신의 사용자 ID를 선택할 수 있습니다.



 a| 
SnapManager 스케줄러는 네이티브 운영 체제 스케줄러와 어떻게 상호 작용합니까?
 a| 
SnapManager 서버에서는 운영 체제의 기본 스케줄러를 통해 예약된 백업을 볼 수 없습니다. 예를 들어 예약된 백업을 생성한 후에는 예약된 작업 창에 새 항목이 표시되지 않습니다.



 a| 
그래픽 사용자 인터페이스와 서버의 시계가 동기화되지 않으면 어떻게 됩니까?
 a| 
클라이언트와 서버의 시계가 동기화되지 않았습니다. 따라서 클라이언트의 시작 시간이 미래이지만 서버의 이전 시간에 있는 백업을 예약할 수 있습니다.

반복 백업의 경우 서버는 요청을 계속 수행합니다. 예를 들어, 2008년 1월 30일 오후 3시에 시작되는 시간별 백업 수행 요청을 서버가 받는 경우 그러나 현재 시간은 오후 3시 30분이다 그 날, 서버는 오후 4시에 첫 번째 백업을 수행합니다 매시간마다 백업을 계속 수행합니다.

그러나 일회성 백업의 경우 서버는 다음과 같이 요청을 처리합니다.

* 시작 시간이 현재 서버 시간의 마지막 5분 내에 있으면 SnapManager에서 즉시 백업을 시작합니다.
* 시작 시간이 5분 이상이면 SnapManager에서 백업을 시작하지 않습니다.


예를 들어, 다음 시나리오를 고려해 보십시오.

* 그래픽 인터페이스 호스트의 클럭은 실제 시간보다 3분 뒤에 있습니다.
* 클라이언트의 현재 시간은 오전 8:58입니다
* 1회 백업을 오전 9시에 수행하도록 예약합니다
* 또 다른 1회 백업을 오전 8시 30분에 수행하도록 예약합니다


서버에서 첫 번째 요청을 받으면 서버의 시간은 오전 9시 01분이다 백업 시작 시간이 과거이지만 SnapManager는 즉시 백업을 수행합니다.

서버에서 두 번째 요청을 받으면 백업 시작 시간은 5분 이상입니다. 시작 시간이 과거이기 때문에 스케줄 요청이 실패했다는 메시지가 표시됩니다.

SnapManager 속성 파일에서 5분의 시간을 변경할 수 있습니다.



 a| 
프로필을 삭제할 때 프로필에 대해 예약된 백업은 어떻게 됩니까?
 a| 
데이터베이스 프로필이 삭제되면 SnapManager 서버는 해당 프로필에 정의된 예약된 백업을 삭제합니다.



 a| 
일광 절약 시간 또는 SnapManager 서버 시간을 변경할 때 예약된 백업이 어떻게 작동합니까?
 a| 
SnapManager 백업 스케줄은 일광 절약 시간 또는 SnapManager 서버 시간 변경으로 인해 영향을 받습니다.

SnapManager 서버 시간이 변경될 때 다음 사항을 고려하십시오.

* 백업 스케줄이 트리거된 후 SnapManager 서버 시간이 다시 돌아오면 백업 스케줄이 다시 시작되지 않습니다.
* 예약된 시작 시간 전에 일광 절약 시간이 시작되면 백업 스케줄이 자동으로 트리거됩니다.
* 예를 들어, 미국에 있는 경우 오전 4시에 시간별 백업을 예약합니다 이 작업은 4시간마다 수행해야 하며 3월과 11월에는 일광 절약 시간 조정 전/후 요일에 오전 4시, 오전 8시, 오전 12시, 오전 4시, 오후 8시 및 자정에 백업이 수행됩니다.
* 백업이 오전 2시 30분에 예약되어 있는 경우 다음 사항에 유의하십시오 매일 밤:
+
** 클록이 한 시간 뒤로 떨어지면 백업이 이미 트리거되어 백업이 다시 트리거되지 않습니다.
** 클록이 한 시간 앞으로 오면 백업이 즉시 트리거됩니다. 미국 내에 있는 경우 이 문제를 방지하려면 오전 2시 이외의 시간에 백업을 시작하도록 예약해야 합니다 오전 3:00까지 간격.




|===