---
permalink: windows/reference-snapmanager-configuration-parameters.html 
sidebar: sidebar 
keywords: snapmanager, provide, list, configuration, parameter, edit, requirement, smsap, config, file 
summary: SnapManager는 요구 사항에 따라 편집할 수 있는 구성 매개 변수 목록을 제공합니다. 구성 매개 변수는 sap.config 파일에 저장됩니다. 그러나 smsap.config 파일에는 지원되는 구성 매개 변수가 모두 포함되어 있지 않을 수 있습니다. 요구 사항에 따라 구성 매개 변수를 추가할 수 있습니다. 
---
= SnapManager 구성 매개 변수
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager는 요구 사항에 따라 편집할 수 있는 구성 매개 변수 목록을 제공합니다. 설정 파라미터는 'msap.config' 파일에 저장된다. 그러나 'msap.config' 파일에는 지원되는 구성 매개 변수가 모두 포함되어 있지 않을 수 있습니다. 요구 사항에 따라 구성 매개 변수를 추가할 수 있습니다.

다음 표에는 지원되는 모든 SnapManager 구성 매개 변수가 나열되어 있으며 이러한 매개 변수를 사용해야 하는 경우도 나와 있습니다.

|===
| 매개 변수 | 설명 


 a| 
* 매시간 카운트를 더하세요
* 시간제.시간.기간
* 월수 보수도
* 월간기간

 a| 
이러한 매개 변수는 프로파일을 생성할 때 보존 정책을 설정합니다. 예를 들어, 다음 값을 할당할 수 있습니다.

매시간, 매시간, 카운트=12

시간제 유지 기간=2

월별 유지 횟수=2

월, 기간=6



 a| 
'restore.temporaryVolumeName'을 선택합니다
 a| 
이 매개 변수는 임시 볼륨에 이름을 할당합니다. SnapManager가 보조 스토리지에서 데이터를 복원하는 간접 방법을 사용하는 경우, 데이터가 데이터베이스 파일에 복사되고 데이터베이스가 복구될 때까지 기본 스토리지의 스크래치 볼륨이 데이터의 임시 복사본을 보류해야 합니다. 기본값이 없습니다. 값을 지정하지 않으면 간접 방법을 사용하는 restore 명령에 이름을 입력해야 합니다. 예를 들어, 다음 값을 할당할 수 있습니다.

restore.temporaryVolumeName= * sap_temp_volume *



 a| 
host.credentials.persist를 선택합니다
 a| 
이 매개 변수를 사용하면 SnapManager에서 호스트 자격 증명을 저장할 수 있습니다. 기본적으로 호스트 자격 증명은 저장되지 않습니다. 그러나 원격 클론에서 실행되는 사용자 지정 스크립트가 있고 원격 서버에 액세스해야 하는 경우에는 호스트 자격 증명을 저장해야 합니다. 'host.credentials.persist'에 * true * 를 할당하여 호스트 자격 증명 저장을 활성화할 수 있습니다. SnapManager는 호스트 자격 증명을 암호화하고 저장합니다.



 a| 
RestorePlanMaxFilesDispl재생됨
 a| 
이 매개 변수를 사용하면 복원 미리 보기에 표시할 최대 파일 수를 정의할 수 있습니다. 기본적으로 SnapManager에서는 복원 미리 보기에 최대 20개의 파일을 표시합니다. 그러나 0보다 큰 값으로 변경할 수 있습니다. 예를 들어, 다음 값을 할당할 수 있습니다.

* RestorePlanMaxFilesDispl플레이 = 30



NOTE: 잘못된 값을 지정하면 기본 파일 수가 표시됩니다.



 a| 
snapshot.list.timeout.min
 a| 
이 매개 변수를 사용하면 SnapManager 작업을 수행할 때 SnapManager가 '스냅 목록' 명령을 실행할 때까지 대기해야 하는 시간(분)을 정의할 수 있습니다. 기본적으로 SnapManager는 30분 동안 대기합니다. 그러나 0보다 큰 값으로 변경할 수 있습니다. 예를 들어, 다음 값을 할당할 수 있습니다.

* '냅샷.목록.타임아웃.분=40'



NOTE: 잘못된 값을 지정하면 기본값이 사용됩니다.

SnapManager 동작 시 'Snap list' 명령어 수행 시간이 'shapshot.list.timeout.min'에 지정된 값을 초과할 경우 타임아웃 오류 메시지와 함께 작업이 실패합니다.



 a| 
CuteIfFileExistsInOtherDestination 을 참조하십시오
 a| 
이 잘라내기 매개 변수를 사용하면 보관 로그 파일의 대상을 정의할 수 있습니다. 아카이브 로그 파일은 여러 대상에 저장됩니다. 아카이브 로그 파일을 보관하는 동안 SnapManager는 아카이브 로그 파일의 대상을 알아야 합니다. 지정할 수 있는 값은 다음과 같습니다.

* 지정된 대상에서 아카이브 로그 파일을 정리하려면 "pruneIfFileExistsInOtherDestination"에 * false * 를 할당해야 합니다.
* 외부 대상에서 아카이브 로그 파일을 정리하려면 "pruneIfFileExistsInOtherDestination"에 * true * 를 할당해야 합니다.




 a| 
"prune.archivelogs.backedup.from.otherdestination`
 a| 
이 잘라내기 매개 변수를 사용하면 지정된 아카이브 로그 대상에서 백업되거나 외부 아카이브 로그 대상에서 백업된 아카이브 로그 파일을 정리할 수 있습니다. 지정할 수 있는 값은 다음과 같습니다.

* 지정된 대상에서 보관 로그 파일을 정리하려는 경우, 지정된 대상에서 '-prune-dest'를 사용하여 보관 로그 파일을 백업하면 prune.archivelogs.backedup.from.otherdestination` 에 * false * 를 할당해야 합니다.
* 지정된 대상에서 보관 로그 파일을 정리하려는 경우 보관 로그 파일이 다른 대상에서 한 번 이상 백업되는 경우 * true * 를 "prune.archivelogs.backedup.from.otherdestination` 에 할당해야 합니다.




 a| 
mixum.archivelog.files.toprune.atime'입니다
 a| 
이 잘라내기 매개 변수를 사용하면 지정된 시간에 정리할 수 있는 최대 아카이브 로그 파일 수를 정의할 수 있습니다. 예를 들어, value:maximum.archivelog.files.toprune.atATime"= * 998 * 를 할당할 수 있습니다


NOTE: mixum.archivelog.files.toprune.atATime에 할당할 수 있는 값은 1000보다 작아야 합니다.



 a| 
'archivelogs.Consolidate'
 a| 
이 매개 변수를 사용하면 "archivelogs.Consolidate"에 * true * 를 지정하면 SnapManager에서 중복 아카이브 로그 백업을 사용할 수 있습니다.



 a| 
"백업, 레이블, 로그 포함"
 a| 
이 매개 변수를 사용하면 데이터 백업 및 아카이브 로그 백업의 레이블 이름을 구별하기 위해 추가할 접미사를 지정할 수 있습니다. 예를 들어 로그를 'suffix.backup.label.with.logs'에 할당할 경우 아카이브 로그 백업 레이블에 '_logs'가 접미사로 추가됩니다. 그러면 아카이브 로그 백업 레이블이 arch_logs가 됩니다.



 a| 
"backup.archivelogs.beyond.missingfiles`
 a| 
이 매개 변수를 사용하면 SnapManager에서 누락된 아카이브 로그 파일을 백업에 포함할 수 있습니다. 활성 파일 시스템에 없는 아카이브 로그 파일은 백업에 포함되지 않습니다. 활성 파일 시스템에 없는 아카이브 로그 파일을 모두 포함하려면 backup.archivelogs.beyond.missingfiles` 에 * true * 를 할당해야 합니다.

누락된 아카이브 로그 파일을 무시하도록 false를 할당할 수 있습니다.



 a| 
'rvctl.timeout'을 선택합니다
 a| 
이 파라미터를 사용하면 'rvctl' 명령어에 대한 타임아웃 값을 정의할 수 있다.


NOTE: 서버 컨트롤(SRVCTL)은 RAC 인스턴스를 관리하는 유틸리티입니다.

SnapManager가 timeout 값보다 srvctl 명령을 실행하는 데 더 많은 시간이 소요되면 SnapManager 작업이 실패하고 'Error: Timeout occurred while execute command: srvctl status' 오류 메시지가 표시됩니다.



 a| 
스냅샷, 복원, storageNameCheck
 a| 
이 매개 변수를 사용하면 SnapManager에서 7-Mode의 Data ONTAP에서 clustered Data ONTAP으로 마이그레이션하기 전에 생성된 스냅샷 복사본을 사용하여 복원 작업을 수행할 수 있습니다. 매개 변수에 할당된 기본값은 false 입니다. 7-Mode에서 운영되는 Data ONTAP을 clustered Data ONTAP으로 마이그레이션했지만 마이그레이션 전에 생성된 스냅샷 복사본을 사용하려면 sapshot.restore.storageNameCheck" = * true * 를 설정합니다.



 a| 
ervices.common.disableAbort`
 a| 
이 매개 변수는 장기 실행 작업 실패 시 정리를 비활성화합니다. Oracle 오류로 인해 오래 실행된 후 실패한 클론 작업을 수행하는 경우 ervices.common.disableAbort`=*true*.For 예제를 설정하면 클론을 정리하지 않을 수 있습니다. ervices.common.disableAbort`=*true* 를 설정하면 클론이 삭제되지 않습니다. Oracle 문제를 해결하고 실패한 지점에서 클론 작업을 다시 시작할 수 있습니다.



 a| 
* backup.sleep.dnfs.layout을 선택합니다
* "backup.sleep.dnfs.secs`

 a| 
이러한 매개 변수는 dNFS(Direct NFS) 레이아웃에서 절전 메커니즘을 활성화합니다. dNFS 또는 NFS(Network File System)를 사용하여 제어 파일 백업을 생성한 후 SnapManager는 제어 파일을 읽으려고 시도하지만 파일을 찾을 수 없습니다. 슬립 메커니즘을 활성화하려면 'backup.sleep.dnfs.layout'= * true * 로 설정하십시오. 기본값은 * TRUE * 입니다.

취침 메커니즘을 활성화할 때 취침 시간을 'backup.sleep.dnfs.secs` 지정해야 합니다. 할당된 대기 시간은 초 단위로 되어 있으며 값은 환경에 따라 다릅니다. 기본값은 5초입니다.

예를 들면 다음과 같습니다.

* "backup.sleep.dnfs.layout" = * true *
* "backup.sleep.dnfs.secs`=*2*




 a| 
* "override.default.backup.pattern`
* "new.default.backup.pattern`

 a| 
백업 레이블을 지정하지 않으면 SnapManager에서 기본 백업 레이블을 만듭니다. 이러한 SnapManager 매개 변수를 사용하여 기본 백업 레이블을 사용자 지정할 수 있습니다. 백업 레이블을 사용자 지정하려면 "override.default.backup.pattern` 값이 * true * 로 설정되어 있는지 확인하십시오. 기본값은 * false * 입니다.

백업 레이블의 새 패턴을 할당하기 위해 데이터베이스 이름, 프로파일 이름, 범위, 모드, 호스트 이름 등의 키워드를 'new.default.backup.pattern` 할당할 수 있습니다. 키워드는 밑줄을 사용하여 구분해야 합니다. 예: 'new.default.backup.pattern`=*dbname_profile_hostname_scope_mode*.


NOTE: 타임스탬프는 생성된 레이블의 끝에 자동으로 포함됩니다.



 a| 
"allow.underscore.in.clone.sid`
 a| 
Oracle에서는 Oracle 11gR2의 클론 SID에서 언더스코어를 사용할 수 있습니다. 이 SnapManager 매개 변수를 사용하면 클론 SID 이름에 밑줄을 포함할 수 있습니다. 클론 SID 이름에 밑줄을 포함하려면 "allow.underscore.in.clone.sid` 값이 * true * 로 설정되어 있는지 확인하십시오. 기본값은 * TRUE * 입니다.

Oracle 11gR2 이전 버전의 Oracle 버전을 사용하거나 클론 SID 이름에 밑줄을 포함하지 않으려면 값을 * FALSE * 로 설정합니다.



 a| 
"oracle.parameters.with.comma`
 a| 
이 매개 변수를 사용하면 쉼표(,)가 있는 모든 Oracle 매개 변수를 값으로 지정할 수 있습니다. 모든 작업을 수행하는 동안 SnapManager는 oracle.parameters.with.comma` 를 사용하여 모든 Oracle 매개 변수를 확인하고 값 분할을 건너뜁니다.

예를 들어, '_nls_numeric_characters_'= 값이 인 경우 oracle.parameters.with.comma=_nls_numeric_characters_` 를 지정합니다. 값으로 쉼표가 있는 여러 개의 Oracle 매개 변수가 있는 경우 ' oracle.parameters.with.comma` ' 매개 변수를 모두 지정해야 합니다.



 a| 
* archivedLogs.exclude를 선택합니다
* archedLogs.exclude.fileslike
* "<db-unique-name>.archivedLogs.exclude.fileslike"

 a| 
이러한 매개 변수를 사용하면 데이터베이스가 스냅샷 복사본 지원 스토리지 시스템에 있지 않고 해당 스토리지 시스템에서 SnapManager 작업을 수행하려는 경우 SnapManager가 프로파일 및 백업에서 아카이브 로그 파일을 제외할 수 있습니다.


NOTE: 프로파일을 만들기 전에 구성 파일에 제외 매개 변수를 포함해야 합니다.

이러한 매개 변수에 할당된 값은 최상위 디렉토리이거나 아카이브 로그 파일이 있는 마운트 지점이거나 하위 디렉토리일 수 있습니다.

아카이브 로그 파일이 프로필에 포함되지 않고 백업되지 않도록 하려면 다음 매개 변수 중 하나를 포함해야 합니다.

* 모든 프로파일 또는 백업에서 아카이브 로그 파일을 제외하기 위한 정규식을 지정하려면 archivedLogs.exclude를 사용합니다.
+
정규식과 일치하는 아카이브 로그 파일은 모든 프로파일 및 백업에서 제외됩니다.

+
예를 들어, 'archivedLogs.exclude=J:\\arch\\. *'를 설정할 수 있습니다.

+

NOTE: 대상에 파일 구분 기호가 있으면 패턴에 슬래시 기호(\)를 추가해야 하며 패턴은 이중 슬래시 패턴(\\. *)으로 끝나야 합니다.

* 모든 프로파일 또는 백업에서 아카이브 로그 파일을 제외하기 위한 SQL 식을 지정하려면 archivedLogs.exclude.fileslike를 사용합니다.
+
SQL 표현식과 일치하는 아카이브 로그 파일은 모든 프로파일 및 백업에서 제외됩니다.

+
예를 들어, 'archivedLogs.exclude.fileslike=J:\\ARCH2\\%'를 설정할 수 있습니다.

+

NOTE: 대상에 파일 구분 기호가 있으면 패턴에 슬래시 기호(\)를 추가해야 하며 패턴은 이중 슬래시 패턴(\\%)으로 끝나야 합니다.





 a| 
 a| 
* "<db-unique-name>.archivedLogs.exclude.fileslike" - 지정된_db-unique-name_을 사용하여 데이터베이스에 대해 생성된 백업 또는 프로파일에서 보관 로그 파일을 제외하기 위한 SQL 식을 지정합니다.
+
SQL 표현식과 일치하는 아카이브 로그 파일은 프로파일 및 백업에서 제외됩니다.

+
예를 들어, mydb.archivedLogs.exclude.fileslike=J:\\ARCH2\\%'를 설정할 수 있습니다.

+

NOTE: 대상에 파일 구분 기호가 있으면 패턴에 슬래시 기호(\)를 추가해야 하며 패턴은 이중 슬래시 패턴(\\%)으로 끝나야 합니다.




NOTE: BR * Tools는 이러한 매개 변수가 아카이브 로그 파일을 제외하도록 구성된 경우에도 다음 매개 변수를 지원하지 않습니다.

* archedLogs.exclude.fileslike
* "<db-unique-name>.archivedLogs.exclude.fileslike"


|===