---
permalink: windows/reference-the-backint-register-sld-command.html 
sidebar: sidebar 
keywords: sap, br, tools, backint, register-sld, command, snapmanager, interface, landscape, system, directory, sld, vendor 
summary: 'SAP BR * Tools를 사용하려면 SAP용 SnapManager에서 backint register-SLD 명령을 실행하여 SLD(시스템 환경 디렉터리)에 backint 인터페이스를 등록할 수 있습니다. 스토리지 공급업체에서 backint 인터페이스를 제공하여 스토리지 시스템이 BR * Tools 명령을 사용할 수 있도록 합니다. SAP용 SnapManager는 C:\Program Files\NetApp\SnapManager for SAP\bin\에 backint 인터페이스 파일을 설치합니다.' 
---
= backint register-SLD 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP BR * Tools를 사용하려면 SnapManager for SAP와 함께 'backint register-SLD' 명령을 실행하여 SLD(System Landscape Directory)에서 backint 인터페이스를 등록할 수 있습니다. 스토리지 공급업체에서 backint 인터페이스를 제공하여 스토리지 시스템이 BR * Tools 명령을 사용할 수 있도록 합니다. SnapManager for SAP는 'C:\Program Files\NetApp\SnapManager for SAP\bin\'에 backint 인터페이스 파일을 설치합니다.



== 구문

[listing]
----

backint register-sld
-host  host_name
-port  port_id
-username username
-password password
-template template_ID
----


== 매개 변수

* '*'-host_host_name_'
+
SAP SLD가 실행 중인 호스트의 이름을 지정합니다.

* '*'- port_port_id_'
+
SAP SLD가 HTTP 요청을 받아들이는 포트의 ID를 지정합니다. ID는 9자리 이하의 숫자여야 합니다.

* ''-username_username_' *
+
유효하고 승인된 SAP SLD 사용자 이름을 지정합니다.

* * ``password_password_'
+
유효하고 인증된 SAP SLD 사용자 암호를 지정합니다. 이는 선택 사항입니다. '-password'를 사용하여 비밀번호를 설정하지 않으면 '+username@http://host:port+` 형식으로 비밀번호를 입력하라는 메시지가 표시됩니다

+
올바른 암호를 입력하지 않으면 세 번 시도해도 명령이 실패하고 종료됩니다.

* * ``template_template_id_' *
+
사용자 지정 파일의 기반으로 사용할 수 있는 마스터 템플릿 XML 파일의 이름을 지정합니다.





== 명령 예

다음 예제는 명령이 성공적으로 완료되었음을 보여 줍니다.

[listing]
----
backint register-sld -host jack12 -port 50100
-username j2ee_admin -password user123 -template E:\template.xml
Operation Id [N96f4142a1442b31ee4636841babbc1d7] succeeded.
----