---
permalink: windows/reference-the-smosmsap-repository-rollingupgrade.html 
sidebar: sidebar 
keywords: command, perform, roll, upgrade, host, multiple, target, database, associate, version, smsap, roll upgrade 
summary: 이 명령은 단일 호스트 또는 여러 호스트 및 관련 타겟 데이터베이스에서 SnapManager 하위 버전에서 상위 버전으로 롤링 업그레이드를 수행합니다. 업그레이드된 호스트는 상위 버전의 SnapManager에서만 관리됩니다. 
---
= smsap 리포지토리 Rollingupgrade 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 명령은 단일 호스트 또는 여러 호스트 및 관련 타겟 데이터베이스에서 SnapManager 하위 버전에서 상위 버전으로 롤링 업그레이드를 수행합니다. 업그레이드된 호스트는 상위 버전의 SnapManager에서만 관리됩니다.



== 구문

[listing]
----

smsap repository rollingupgrade
-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port
-upgradehost host_with_target_database
[-force] [-noprompt]
[-quiet | -verbose]
----


== 매개 변수

* * ``리포지토리’ *
+
리포지터리 다음에 나오는 옵션은 리포지터리의 데이터베이스 세부 사항을 지정합니다.

* * ``dbname_repo_service_name_'
+
리포지토리를 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.

* '*'-host_repo_host_'
+
리포지토리 데이터베이스가 실행되는 호스트 컴퓨터의 이름 또는 IP 주소를 지정합니다.

* * ``로그인’
+
리포지토리 로그인 세부 정보를 시작합니다.

* * ``username_repo_username_' *
+
리포지토리를 저장하는 데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.

* * ``upgrade_host_with_target_database_'
+
낮은 버전의 SnapManager에서 상위 버전으로 업그레이드할 호스트의 이름을 지정합니다.

* '*'-port_repo_port_'
+
리포지토리를 저장하는 데이터베이스에 액세스하는 데 사용되는 TCP 포트 번호를 지정합니다.

* * ``힘’ *
+
리포지토리 업데이트를 강제 적용합니다. SnapManager에서 업데이트하기 전에 현재 리포지토리를 백업하라는 메시지를 표시합니다.

* ``공시’’
+
는 리포지토리 데이터베이스를 업데이트하기 전에 프롬프트를 표시하지 않습니다. '-nop프롬프트' 옵션을 사용하면 프롬프트가 나타나지 않으므로 스크립트를 사용하여 리포지토리를 쉽게 업데이트할 수 있습니다.

* ``조용한’
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* * '-verbose' *
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.





== 명령 예

다음 예제에서는 SLESDB 데이터베이스의 저장소를 업데이트합니다.

[listing]
----
smsap repository rollingupgrade -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -upgradehost hostA
----