---
permalink: windows/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credential, user, access, secure, resource, host, repository, repositories, database, profile, password, snapmanager, option, smsap 
summary: 이 명령을 사용하면 사용자가 호스트, 저장소 및 데이터베이스 프로필과 같은 보안 리소스에 액세스할 수 있도록 자격 증명을 설정할 수 있습니다. 호스트 암호는 SnapManager가 실행 중인 호스트의 사용자 암호입니다. 리포지토리 암호는 SnapManager 리포지토리 스키마를 포함하는 Oracle 사용자의 암호입니다. 프로파일 암호는 프로파일을 만드는 사람이 만든 암호입니다. 호스트 및 리포지토리 옵션의 경우 선택적 암호 옵션이 포함되지 않은 경우 명령 인수에 지정된 유형의 암호를 입력하라는 메시지가 표시됩니다. 
---
= smsap 자격 증명 집합 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 명령을 사용하면 사용자가 호스트, 저장소 및 데이터베이스 프로필과 같은 보안 리소스에 액세스할 수 있도록 자격 증명을 설정할 수 있습니다. 호스트 암호는 SnapManager가 실행 중인 호스트의 사용자 암호입니다. 리포지토리 암호는 SnapManager 리포지토리 스키마를 포함하는 Oracle 사용자의 암호입니다. 프로파일 암호는 프로파일을 만드는 사람이 만든 암호입니다. 호스트 및 리포지토리 옵션의 경우 옵션 '-password' 옵션이 포함되어 있지 않으면 명령 인수에 지정된 유형의 암호를 입력하라는 메시지가 표시됩니다.



== 구문

[listing]
----

smsap credential set
[-host
-name host_name
-username username]
[-password password]] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username] [-password repo_password]]
-port repo_port |
[-profile
-name profile_name]
[-password password]]
[-quiet | -verbose]
----


== 매개 변수

* * ``host_hostname_'
+
SnapManager가 실행 중인 호스트 서버의 이름 또는 IP 주소를 지정합니다.

+
'-host' 매개변수는 다음과 같은 옵션을 포함합니다.

+
** '-name host_name': 암호를 설정할 호스트의 이름을 지정합니다.
** '-username user_name': 호스트의 사용자 이름을 지정합니다.
** '-password password': 호스트에 있는 사용자의 암호를 지정합니다.


* * ``repository-dbname' *
+
프로필을 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.

+
'-repository' 매개 변수에는 다음 옵션이 포함됩니다.

+
** '-dbnamerepo_service_name': 프로파일을 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.
** '-host repo_host': 리포지터리 데이터베이스가 실행되는 호스트 서버의 이름 또는 IP 주소를 지정합니다.
** '-login-username repo_username': 리포지토리를 저장하는 데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.
** '-password password': 리포지터리를 저장하는 데이터베이스에 액세스하는 데 필요한 암호를 지정합니다.
** '-port repo_port': 리포지토리를 저장하는 데이터베이스에 액세스하는 데 사용되는 TCP 포트 번호를 지정합니다.


* * ``profile-name_profile_name_' *
+
데이터베이스가 연결된 프로파일을 지정합니다.

+
'-profile' 파라미터는 다음과 같은 옵션을 포함한다.

+
** '-name profilename': 암호를 설정할 프로파일의 이름을 지정합니다.
** '-password password': 프로파일에 액세스하는 데 필요한 비밀번호를 지정합니다.


* ``조용한’
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* * '-verbose' *
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.





== 리포지토리 자격 증명 설정을 위한 명령 예

다음 예제에서는 리포지토리에 대한 자격 증명을 설정합니다.

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== 호스트 자격 증명을 설정하는 명령의 예

호스트 자격 증명은 실제 운영 체제 자격 증명을 나타내므로 암호 외에 사용자 이름을 포함해야 합니다.

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----