---
permalink: windows/reference-error-message-classifications.html 
sidebar: sidebar 
keywords: determine, cause, error, message, clarification 
summary: 메시지 분류를 알고 있는 경우 오류의 원인을 확인할 수 있습니다. 
---
= 오류 메시지 분류
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
메시지 분류를 알고 있는 경우 오류의 원인을 확인할 수 있습니다.

다음 표에서는 SnapManager에서 볼 수 있는 다양한 메시지 유형의 숫자 범위에 대한 정보를 제공합니다.

|===
| 그룹 | 범위 | 사용 


 a| 
방법입니다
 a| 
1000-1999
 a| 
SnapManager 운영 환경의 상태 또는 문제를 기록하는 데 사용됩니다. 이 그룹에는 SnapManager가 호스트, 스토리지 시스템, 데이터베이스 등과 상호 작용하는 시스템에 대한 메시지가 포함됩니다.



 a| 
백업
 a| 
2000-2999
 a| 
데이터베이스 백업 프로세스와 연결되어 있습니다.



 a| 
복원
 a| 
3000-3999
 a| 
데이터베이스 복원 프로세스와 연결되어 있습니다.



 a| 
복제
 a| 
4000-4999
 a| 
데이터베이스 클론 프로세스와 연결되어 있습니다.



 a| 
프로파일
 a| 
5000-5999
 a| 
프로파일 관리에 사용됩니다.



 a| 
관리
 a| 
6000-6999
 a| 
백업 관리에 사용됩니다.



 a| 
가상 데이터베이스 인터페이스
 a| 
7000-7999
 a| 
가상 데이터베이스 인터페이스와 연결됩니다.



 a| 
가상 스토리지 인터페이스
 a| 
8000-8999
 a| 
가상 스토리지 인터페이스와 연결됩니다.



 a| 
리포지토리
 a| 
9000-9999
 a| 
리포지토리 인터페이스와 연결됩니다.



 a| 
메트릭
 a| 
10000-10999
 a| 
데이터베이스 백업 크기, 백업을 수행하는 경과 시간, 데이터베이스 복원 시간, 데이터베이스 복제 횟수 등과 관련이 있습니다.



 a| 
가상 호스트 인터페이스
 a| 
11000-11999
 a| 
가상 호스트 인터페이스와 연결됩니다. 호스트 운영 체제에 대한 인터페이스입니다.



 a| 
실행
 a| 
12000-12999
 a| 
운영 체제 호출 시작 및 처리를 포함하여 실행 패키지와 연관됩니다.



 a| 
프로세스
 a| 
13000-13999
 a| 
SnapManager의 Process 구성 요소와 연관됩니다.



 a| 
유틸리티
 a| 
14000-14999
 a| 
SnapManager 유틸리티, 전역 컨텍스트 등과 연관됩니다.



 a| 
덤프/진단
 a| 
15000-15999
 a| 
덤프 또는 진단 작업과 연관됩니다.



 a| 
도움말
 a| 
16000-16999
 a| 
도움말과 연결되어 있습니다.



 a| 
서버
 a| 
17000-17999
 a| 
SnapManager 서버 관리에 사용됩니다.



 a| 
API를 참조하십시오
 a| 
18000-18999
 a| 
API와 연결되어 있습니다.



 a| 
역인쇄
 a| 
19000-19999
 a| 
backint와 연관됩니다.



 a| 
인증
 a| 
20000-20999
 a| 
자격 증명의 승인과 연결되어 있습니다.

|===