---
permalink: windows/reference-the-smosmsaprepository-delete-command.html 
sidebar: sidebar 
keywords: command, delete, repository, store, database, profile, associate, credential, smsap 
summary: 이 명령은 데이터베이스 프로파일 및 관련 자격 증명을 저장하는 데 사용되는 리포지토리를 삭제합니다. 리포지토리에 프로파일이 없는 경우에만 리포지토리를 삭제할 수 있습니다. 
---
= smbap 리포지토리 삭제 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 명령은 데이터베이스 프로파일 및 관련 자격 증명을 저장하는 데 사용되는 리포지토리를 삭제합니다. 리포지토리에 프로파일이 없는 경우에만 리포지토리를 삭제할 수 있습니다.



== 구문

[listing]
----

smsap repository delete
-repository
-port repo_port
-dbname repo_service_name
-host repo_host
-login -username repo_username
[-force] [-noprompt]
[-quiet | -verbose]
----


== 매개 변수

* * ``리포지토리’ *
+
리포지터리 다음에 나오는 옵션은 리포지터리의 데이터베이스 세부 사항을 지정합니다.

* '*'-port_repo_port_'
+
리포지토리를 저장하는 데이터베이스에 액세스하는 데 사용되는 TCP 포트 번호를 지정합니다.

* * ``dbname_repo_service_name_'
+
리포지토리를 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.

* '*'-host_repo_host_'
+
리포지토리 데이터베이스가 실행되는 호스트 컴퓨터의 이름 또는 IP 주소를 지정합니다.

* * ``로그인’
+
리포지토리 로그인 세부 정보를 시작합니다.

* * ``username_repo_username_' *
+
리포지토리를 저장하는 데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.

* * ``힘’ *
+
완료되지 않은 작업이 있더라도 리포지토리를 강제로 삭제하려고 합니다. SnapManager에서는 완료되지 않은 작업이 있는 경우 리포지토리를 삭제할 것인지 묻는 메시지를 표시합니다.

* ``공시’’
+
는 리포지토리를 삭제하기 전에 메시지를 표시하지 않습니다. '-nop프롬프트' 옵션을 사용하면 프롬프트가 나타나지 않으므로 스크립트를 사용하여 리포지토리를 더 쉽게 삭제할 수 있습니다.

* ``조용한’
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* * '-verbose' *
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.





== 명령 예

다음 예제에서는 SLESDB 데이터베이스의 저장소를 삭제합니다.

[listing]
----
smsap repository delete -repository -dbname SALESDB
-host server1 -login -username admin -port 1527 -force -verbose
----