---
permalink: windows/reference-error-messages.html 
sidebar: sidebar 
keywords: information, error, message, associate, snapmanager, operation 
summary: 다른 SnapManager 작업과 관련된 오류 메시지에 대한 정보를 찾을 수 있습니다. 
---
= 오류 메시지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다른 SnapManager 작업과 관련된 오류 메시지에 대한 정보를 찾을 수 있습니다.



== 가장 일반적인 오류 메시지입니다

다음 표에는 SAP용 SnapManager와 관련하여 가장 일반적이고 중요한 몇 가지 오류가 나열되어 있습니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
'SD-10038: 파일 시스템이 쓸 수 없습니다.'
 a| 
SnapManager 프로세스에 파일 시스템에 대한 쓰기 액세스 권한이 없습니다.
 a| 
SnapManager 프로세스에서 파일 시스템에 대한 쓰기 권한을 가지고 있는지 확인해야 합니다. 이 문제를 해결한 후 다른 스냅샷을 생성해야 할 수 있습니다.



 a| 
smSAP-05075: 프로필을 생성할 수 없습니다. DP/XDP 관계를 적절히 구성하거나 기본 관계에 따라 올바른 보호 정책을 선택해야 합니다.
 a| 
기본 볼륨이 SnapVault 또는 SnapMirror 관계에 있지 않습니다.
 a| 
소스 볼륨과 타겟 볼륨 간의 데이터 보호 관계를 구성하고 관계를 초기화해야 합니다.



 a| 
"[SMSAP-05503] 프로파일에 동일한 이름을 지정했습니다. 프로파일 이름을 바꿀 다른 이름을 지정하십시오.
 a| 
동일한 이름의 프로파일이 리포지토리에 존재할 수 없습니다.
 a| 
사용하지 않는 프로필 이름을 제공하십시오.



 a| 
'MSAP-05505: 데이터세트 메타데이터를 업데이트할 수 없습니다.'
 a| 
데이터 세트가 삭제되었거나 존재하지 않을 수 있습니다.
 a| 
데이터 세트 메타데이터를 업데이트하기 전에 NetApp Management Console을 사용하여 데이터 세트가 있는지 확인합니다.



 a| 
S MSAP-05506: 프로파일에서 실행 중인 작업이 있으므로 프로필을 업데이트할 수 없습니다. 작업이 완료될 때까지 기다린 다음 프로필을 업데이트해야 합니다
 a| 
백업, 복원 및 클론 생성 작업이 진행 중인 경우 프로필을 업데이트할 수 없습니다.
 a| 
현재 작업을 완료한 후 프로파일을 업데이트합니다.



 a| 
'MSSAP-05509: 보관 기본 보존 기간이 잘못되었습니다. 양의 정수 값을 지정하십시오.'
 a| 
아카이브 로그 백업의 보존 기간은 음수일 수 없습니다.
 a| 
아카이브 로그 백업의 보존 기간에 대해 양의 값을 지정합니다.



 a| 
'smSAP-07463: 이 백업 복원을 수행하려면 데이터베이스가 필요한 상태여야 합니다. 데이터베이스를 필수 상태로 가져오지 못했습니다.
 a| 
데이터베이스가 백업 작업에 필요한 상태가 아닙니다.
 a| 
백업 복제본을 생성하기 전에 데이터베이스가 관련 상태인지 확인합니다. 복원할 데이터베이스의 상태는 수행하려는 복원 프로세스의 유형과 포함될 파일 유형에 따라 달라집니다.



 a| 
'SSAP-09315: 리포지토리 업그레이드 또는 업데이트 작업을 수행한 후 알림 호스트 세부 정보로 요약 알림을 업데이트하지 않으면 이전 버전에서 설정한 알림에 대한 요약 알림을 받지 못할 수 있습니다.'
 a| 
롤링 업그레이드 후 리포지토리에 대한 알림 설정이 구성되지 않습니다.
 a| 
롤링 업그레이드 후 알림을 받도록 요약 알림 설정을 업데이트합니다.



 a| 
'MSSAP-02076: 라벨 이름에는 밑줄 이외의 특수 문자를 사용할 수 없습니다.'
 a| 
레이블 이름에 밑줄 이외의 특수 문자가 포함되어 있습니다.
 a| 
레이블 이름은 프로파일 내에서 고유해야 합니다. 이름에는 문자, 숫자, 밑줄(_) 및 하이픈(-)을 사용할 수 있지만 하이픈으로 시작할 수는 없습니다. 레이블에는 밑줄을 제외한 특수 문자가 포함되어 있지 않아야 합니다.



 a| 
S MSAP-06308: 스케줄을 시작하려고 할 때 예외 발생: java.lang.NullPointerException
 a| 
시스템 호스트 이름 대신 프로필 호스트의 FQDN(정규화된 도메인 이름)이 구성되어 있으며 프로필 호스트의 FQDN을 확인할 수 없습니다.
 a| 
FQDN이 아니라 시스템의 호스트 이름을 사용해야 합니다.



 a| 
"ExecuteRestoreStps:Oracle-10003:SQL "Drop DISKGROUP; control diskgroup name; including contents"를 Oracle database + ASM1:ORA-15039:diskgroup not drop ORA-15027: diskgroup 활성 사용;"control diskgroup name;"predismount
 a| 
제어 파일을 사용하여 백업을 복원하는 작업이 제어 디스크 그룹을 삭제하지 못합니다. 이 문제는 제어 디스크 그룹에 오래된 백업 제어 파일이 있는 경우에 발생합니다.
 a| 
오래된 백업 제어 파일을 식별하고 수동으로 삭제합니다.



 a| 
'RMAN-06004: 복구 카탈로그 데이터베이스에서 Oracle 오류: ORA-01424: 이스케이프 문자 다음에 없거나 잘못된 문자가 있습니다.
 a| 
SnapManager가 RMAN과 통합되었을 때 백업 생성 작업에서 카탈로그에서 백업 복제본을 제거하지 못했습니다.
 a| 
RMAN에서 백업을 제거하는 데 사용되는 외부 스크립트가 있는지 확인합니다. RMAN에서 'crosscheck backup' 명령을 실행하여 RMAN 리포지토리와 'resync catalog' 명령을 업데이트하여 타겟 데이터베이스의 제어 파일을 복구 카탈로그와 동기화합니다.



 a| 
([debug]: 백업을 정리하는 동안 예외가 발생했습니다. java.lang.IllegalStateException: [어설션 실패] - 이 상태 불변은 참이어야 합니다
 a| 
단일 작업 ID에 대해 여러 스냅샷 복사본이 생성됩니다.
 a| 
스냅샷 복사본을 수동으로 삭제하고 스크립트를 사용하여 리포지토리에서 항목을 삭제합니다.



 a| 
SnapManager가 로그 파일에 표시하는 시스템 시간과 시간이 일치하지 않거나 동기화되지 않습니다.
 a| 
표준 시간대 변경은 아직 Java 7에서 지원되지 않습니다.
 a| 
Oracle에서 제공하는 tzupdateer 패치를 적용하십시오.



 a| 
dISC-00001: 스토리지를 검색할 수 없습니다. 다음 식별자가 없거나 예상된 유형: ASM 파일'이 아닙니다
 a| 
데이터 또는 제어 파일 또는 redo 로그는 ASM 데이터베이스에서 멀티플렉싱됩니다.
 a| 
Oracle 멀티플렉싱을 제거합니다.



 a| 
'0001-SMSAP-02016: 이 백업 작업의 일부로 백업되지 않은 데이터베이스의 외부 테이블이 있을 수 있습니다(이 백업 중에 데이터베이스가 열려 있지 않기 때문에 ALL_EXTERNAL_LOAMS를 쿼리하여 외부 테이블이 있는지 여부를 확인할 수 없습니다).
 a| 
SnapManager는 외부 테이블(예: .dbf 파일에 저장되지 않은 테이블)을 백업하지 않습니다. 이 문제는 백업 중에 데이터베이스가 열리지 않아 발생합니다. SnapManager는 사용 중인 외부 테이블이 있는지 확인할 수 없습니다.
 a| 
이 작업의 일부로 백업되지 않은 외부 테이블이 데이터베이스에 있을 수 있습니다(백업 중에 데이터베이스가 열려 있지 않음).



 a| 
'0002-332 관리자 오류: SD.snapshot을 확인할 수 없습니다.\n\n\n\n\n\n"DFM_SERVER"의 사용자 이름에 대한 볼륨 "volume_name"의 클론 액세스를 확인하십시오. 이유: 잘못된 리소스가 지정되었습니다. Operations Manager 서버 "DFM_SERVER""에서 ID를 찾을 수 없습니다
 a| 
적절한 액세스 권한 및 역할이 설정되지 않았습니다.
 a| 
명령을 실행하고자 하는 사용자에 대한 액세스 권한 또는 역할을 설정합니다.



 a| 
([warn]flow-11011: Operation aborted [error] flow-11008: Operation failed: Java heap space.)
 a| 
데이터베이스에 허용된 최대 수보다 많은 아카이브 로그 파일이 있습니다.
 a| 
. SnapManager 설치 디렉토리로 이동합니다.
. launch-java 파일을 엽니다.
. Java-Xmx160m Java heap space 파라미터 값을 증가시키십시오. 예를 들어, 기본값인 160m에서 200m로 값을 Java-Xmx200m로 수정할 수 있습니다.




 a| 
'SMSAP-21019: 대상에 대한 보관 로그 기록 정리가 실패했습니다: "Oracle-00101: RMAN 명령 실행 중 오류: [DELETE NOPROMPT ARCHIVELOG'E:\dest']
 a| 
대상 중 하나에서 보관 로그 잘라내기 작업이 실패합니다. 이러한 경우 SnapManager는 계속해서 다른 대상의 아카이브 로그 파일을 정리합니다. 액티브 파일 시스템에서 수동으로 삭제된 파일이 있는 경우 RMAN이 해당 대상에서 아카이브 로그 파일을 삭제하지 못합니다.
 a| 
SnapManager 호스트에서 RMAN에 접속합니다. RMAN 'crosscheck ARCHIVELOG ALL' 명령어를 실행하여 보관 로그 파일에 대해 잘라내기 작업을 다시 수행한다.



 a| 
"MSAP-13032: 작업을 수행할 수 없음: 보관 로그 푸네. 근본 원인:RMAN 예외:ORACLE-00101:RMAN 명령 실행 오류'.
 a| 
보관 로그 파일은 보관 로그 대상에서 수동으로 삭제됩니다.
 a| 
SnapManager 호스트에서 RMAN에 접속합니다. RMAN 'crosscheck ARCHIVELOG ALL' 명령어를 실행하여 보관 로그 파일에 대해 잘라내기 작업을 다시 수행한다.



 a| 
"쉘 출력을 구문 분석할 수 없습니다: (java.util.regex.Matcher [pattern=Command complete. region=0,18 lastmatch=]) 이(가) 일치하지 않습니다(name:backup_script) 쉘 출력을 구문 분석할 수 없습니다: (java.util.regex.Matcher [pattern=Command Complete. region=0,25 lastmatch=])이(설명:백업 스크립트)'과(와) 일치하지 않습니다

"쉘 출력을 구문 분석할 수 없습니다: (java.util.regex.Matcher [pattern=Command complete. region=0,9 lastmatch=])가 일치하지 않습니다(timeout:0)
 a| 
환경 변수가 작업 전 스크립트 또는 작업 후 스크립트에서 올바르게 설정되지 않았습니다.
 a| 
사전 작업 또는 사후 작업 스크립트가 표준 SnapManager 플러그인 구조를 따르는지 확인합니다. 스크립트에 환경 변수를 사용하는 방법에 대한 자세한 내용은 을 참조하십시오 xref:concept-operations-in-task-scripts.adoc[작업 스크립트의 작업입니다].



 a| 
ORA-01450: 최대 키 길이(6398)를 초과했습니다.
 a| 
SAP용 SnapManager 3.2에서 SAP용 SnapManager 3.3으로 업그레이드하는 경우 이 오류 메시지와 함께 업그레이드 작업이 실패합니다. 이 문제는 다음 이유 중 하나로 인해 발생할 수 있습니다.

* 리포지토리가 있는 테이블스페이스의 블록 크기가 8k 미만입니다.
* nls_length_semantics 매개 변수는 char로 설정됩니다.

 a| 
다음 매개 변수에 값을 할당해야 합니다.

* 'block_size' = * 8192 *
* 'nls_length' = * byte *


매개 변수 값을 수정한 후 데이터베이스를 다시 시작해야 합니다.

자세한 내용은 기술 자료 문서 2017632를 참조하십시오.

|===


== 데이터베이스 백업 프로세스와 관련된 오류 메시지(2000 시리즈)

다음 표에는 데이터베이스 백업 프로세스와 관련된 일반적인 오류가 나열되어 있습니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
'smSAP-02066: 데이터 백업 '데이터 로그'와 관련된 백업이므로 아카이브 로그 백업 '데이터 로그'를 삭제하거나 해제할 수 없습니다.
 a| 
아카이브 로그 백업이 데이터 파일 백업과 함께 수행되어 아카이브 로그 백업을 삭제하려고 했습니다.
 a| 
'_-force_' 옵션을 사용하여 백업을 삭제하거나 비확보하십시오.



 a| 
'smSAP-02067: 데이터 백업 "데이터 로그"와 관련된 백업이 지정된 보존 기간 내에 있으므로 아카이브 로그 백업 "데이터 로그"를 삭제하거나 해제할 수 없습니다.
 a| 
아카이브 로그 백업은 데이터베이스 백업과 연결되어 있으며 보존 기간 내에 있으며 아카이브 로그 백업을 삭제하려고 했습니다.
 a| 
'-force' 옵션을 사용하여 백업을 삭제하거나 비운다.



 a| 
'S MSAP-07142: 제외 패턴'으로 인해 아카이브된 로그가 제외되었습니다.
 a| 
프로파일 생성 또는 백업 생성 작업 중에 일부 아카이브 로그 파일을 제외합니다.
 a| 
별도의 조치가 필요하지 않습니다.



 a| 
S MSAP-07155:<count>보관된 로그 파일이 활성 파일 시스템에 없습니다. 이러한 아카이빙된 로그 파일은 백업에 포함되지 않습니다.
 a| 
프로파일 생성 또는 백업 생성 작업 중에 아카이브 로그 파일이 활성 파일 시스템에 없습니다. 이러한 아카이빙된 로그 파일은 백업에 포함되지 않습니다.
 a| 
별도의 조치가 필요하지 않습니다.



 a| 
'MSAP-07148: 아카이빙된 로그 파일을 사용할 수 없습니다.'
 a| 
프로파일 생성 또는 백업 생성 작업 중에 현재 데이터베이스에 대한 아카이브 로그 파일이 생성되지 않습니다.
 a| 
별도의 조치가 필요하지 않습니다.



 a| 
'SMSAP-07150: 아카이빙된 로그 파일을 찾을 수 없습니다.'
 a| 
프로파일 생성 또는 백업 생성 작업 중에 모든 아카이브 로그 파일이 파일 시스템에서 누락되거나 제외됩니다.
 a| 
별도의 조치가 필요하지 않습니다.



 a| 
'SMSAP-13032: 백업 생성'을 수행할 수 없습니다. 근본 원인:Oracle-20001: 데이터베이스 인스턴스 dfcln1:oracle-20004:RESETLOGS 옵션 없이 데이터베이스를 열 수 있을 것으로 예상하지만, Oracle은 데이터베이스가 RESETLOGS 옵션으로 열렸다는 보고를 하고 있습니다. 로그를 예기치 않게 다시 설정하지 않기 위해 프로세스가 계속되지 않습니다. RESETLOGS 옵션 없이 데이터베이스를 열 수 있는지 확인하고 다시 시도하십시오.'
 a| 
"재설정 안 함" 옵션으로 생성된 복제된 데이터베이스를 백업하려고 합니다. 복제된 데이터베이스는 완전한 데이터베이스가 아니지만 클론 생성된 데이터베이스에서 프로필 및 백업 생성 등의 SnapManager 작업을 수행할 수 있지만 클론 복제된 데이터베이스가 완전한 데이터베이스로 구성되지 않아 SnapManager 작업이 실패합니다.
 a| 
복제된 데이터베이스를 복구하거나 데이터베이스를 Data Guard 대기 데이터베이스로 변환합니다.

|===


== 복원 프로세스와 관련된 오류 메시지(3000 시리즈)

다음 표에는 복원 프로세스와 관련된 일반적인 오류가 나와 있습니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
'SMSAP-03031: 백업에 필요한 스토리지 리소스가 이미 확보되었기 때문에 백업 <variable>을(를) 복구하려면 복구 사양이 필요합니다.'
 a| 
복구 사양을 지정하지 않고 스토리지 리소스가 확보된 백업을 복원하려고 했습니다.
 a| 
복구 사양을 지정합니다.



 a| 
'smSAP-03032: 백업에 필요한 스토리지 리소스가 이미 확보되었기 때문에 복구 사양에는 복구할 파일에 대한 매핑이 포함되어야 합니다. 매핑이 필요한 파일은 <variable>from Snapshots:<variable>'입니다
 a| 
복구할 모든 파일에 대한 매핑이 없는 복구 사양과 함께 스토리지 리소스가 해제된 백업을 복원하려고 했습니다.
 a| 
매핑이 복원할 파일과 일치하도록 복원 사양 파일을 수정하십시오.



 a| 
"oracle-30028: 로그 파일 <filename>을(를) 덤프할 수 없습니다. 파일이 없거나 액세스할 수 없거나 손상되었을 수 있습니다. 이 로그 파일은 복구에 사용되지 않습니다.
 a| 
온라인 redo 로그 파일 또는 아카이브 로그 파일을 복구에 사용할 수 없습니다. 이 오류는 다음과 같은 이유로 인해 발생합니다.

* 오류 메시지에 언급된 온라인 redo 로그 파일 또는 아카이빙된 로그 파일에 복구에 적용할 변경 번호가 충분하지 않습니다. 이 문제는 데이터베이스가 트랜잭션 없이 온라인 상태일 때 발생합니다. REDO 로그 또는 보관된 로그 파일에는 복구에 적용할 수 있는 유효한 변경 번호가 없습니다.
* 오류 메시지에 언급된 온라인 redo 로그 파일 또는 아카이빙된 로그 파일에 Oracle에 대한 충분한 액세스 권한이 없습니다.
* 오류 메시지에 언급된 온라인 redo 로그 파일 또는 아카이빙된 로그 파일이 손상되어 Oracle에서 읽을 수 없습니다.
* 오류 메시지에 언급된 온라인 REDO 로그 파일 또는 보관된 로그 파일을 언급된 경로에서 찾을 수 없습니다.

 a| 
오류 메시지에 언급된 파일이 보관된 로그 파일이고 수동으로 복구를 제공한 경우 파일에 Oracle에 대한 전체 액세스 권한이 있는지 확인합니다. 파일에 모든 권한이 있더라도 보관 로그 파일에 복구에 적용할 변경 번호가 없으므로 이 메시지를 무시할 수 있습니다.

|===


== 클론 프로세스와 관련된 오류 메시지(4000 시리즈)

다음 표에서는 클론 프로세스와 관련된 일반적인 오류를 보여 줍니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
'MSSAP-04133: 덤프 대상이 존재하지 않아야 한다'
 a| 
SnapManager를 사용하여 새 클론을 생성하지만 새 클론에 사용되는 덤프 대상이 이미 있습니다. 덤프 대상이 있는 경우 SnapManager에서 클론을 생성할 수 없습니다.
 a| 
클론을 생성하기 전에 이전 덤프 대상을 제거하거나 이름을 변경합니다.



 a| 
'SMSAP-13032: 작업을 수행할 수 없음: 클론 생성. 근본 원인:Oracle-00001:SQL 실행 오류: [ALTER DATABASE OPEN RESETLOGS;]. ORA-38856: instance nNAMED_instance_2(redo thread 2)를 enabled로 표시할 수 없습니다.
 a| 
다음 설정을 사용하여 대기 데이터베이스에서 클론을 생성하면 클론 생성이 실패합니다.

* 스탠바이는 RMAN을 사용하여 데이터 파일 백업을 수행하는 방식으로 생성됩니다.

 a| 
클론을 생성하기 전에 클론 지정 파일에 '_no_recovery_through_resetlogs=true' 매개 변수를 추가합니다. 자세한 내용은 Oracle 설명서(ID 334899.1)를 참조하십시오. Oracle Metalink 사용자 이름과 암호가 있는지 확인합니다.



 a| 
 a| 
클론 사양 파일에 매개 변수 값을 제공하지 않았습니다.
 a| 
클론 사양 파일에서 필요하지 않은 경우 매개 변수 값을 제공하거나 해당 매개 변수를 삭제해야 합니다.

|===


== 프로필 관리 프로세스와 관련된 오류 메시지(5000 시리즈)

다음 표에서는 클론 프로세스와 관련된 일반적인 오류를 보여 줍니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
S MSAP-20600: 프로파일 "profile1"을 리포지토리 "repo_name"에서 찾을 수 없습니다. "프로파일 동기화"를 실행하여 프로파일과 리포지토리 간 매핑을 업데이트하십시오.
 a| 
프로파일 생성에 실패하면 덤프 작업을 수행할 수 없습니다.
 a| 
'스맵 시스템 덤프'를 사용합니다.

|===


== 백업 리소스 확보와 관련된 오류 메시지(백업 6000 시리즈)

다음 표에는 백업 작업과 관련된 일반적인 오류가 나와 있습니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
'SMSAP-06030: 사용 중이므로 백업을 제거할 수 없습니다:<variable>'
 a| 
백업이 마운트되었거나 무제한으로 보존되도록 표시된 상태에서 명령을 사용하여 백업 가용 작업을 수행하려고 했습니다.
 a| 
백업을 마운트 해제하거나 무제한 보존 정책을 변경합니다. 클론이 있으면 삭제합니다.



 a| 
'MSSAP-06045: 백업에 필요한 스토리지 리소스가 이미 확보되어 있어 <variable>을(를) 사용할 수 없습니다.
 a| 
백업이 이미 확보된 상태에서 명령을 사용하여 백업 가용 작업을 수행하려고 했습니다.
 a| 
이미 확보된 백업은 해제할 수 없습니다.



 a| 
S MSAP-06047: 성공한 백업만 해제할 수 있다. 백업 <ID>의 상태는 <status>'입니다.
 a| 
백업 상태가 성공하지 못한 경우 명령을 사용하여 백업 가용 작업을 수행하려고 했습니다.
 a| 
백업이 성공한 후 다시 시도하십시오.



 a| 
'MSSAP-13082: 백업 스토리지 리소스가 확보되어 <ID> 백업 <variable>에서 작업을 수행할 수 없습니다.'
 a| 
명령을 사용하여 스토리지 리소스가 확보된 백업을 마운트하려고 했습니다.
 a| 
스토리지 리소스가 확보된 백업에서는 backint 복원을 마운트, 클론 복제, 검증 또는 수행할 수 없습니다.

|===


== 롤링 업그레이드 프로세스와 관련된 오류 메시지(9000 시리즈)

다음 표에서는 롤링 업그레이드 프로세스와 관련된 일반적인 오류를 보여 줍니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
S MSAP-09234: 이전 리포지토리에 없는 호스트는 다음과 같다. 호스트 이름>'.
 a| 
이전 리포지토리 버전에 없는 호스트의 롤링 업그레이드를 수행하려고 했습니다.
 a| 
이전 버전의 SnapManager CLI에서 'repos일시적인 show-repository' 명령을 사용하여 이전 저장소에 호스트가 있는지 확인합니다.



 a| 
S MSAP-09255: 다음 호스트가 새 리포지토리에 없습니다. 호스트 이름>'.
 a| 
새 리포지토리 버전에 없는 호스트의 롤백을 수행하려고 했습니다.
 a| 
최신 버전의 SnapManager CLI에서 'repos일시적인 show-repository' 명령을 사용하여 호스트가 새 저장소에 있는지 확인합니다.



 a| 
S MSAP-09256: 새 프로파일 <profilename> 이(가) 있으므로 롤백이 지원되지 않습니다. 지정된 호스트 <hostname> 에 대해.
 a| 
리포지토리에 존재하는 새 프로파일이 포함된 호스트를 롤백하려고 했습니다. 그러나 이러한 프로필은 이전 SnapManager 버전의 호스트에는 존재하지 않았습니다.
 a| 
롤백 전에 SnapManager의 최신 버전 또는 업그레이드된 버전에서 새 프로필을 삭제합니다.



 a| 
'sMSAP-09257: 백업 <backupid>이 새 호스트에 마운트되었기 때문에 롤백이 지원되지 않습니다.'
 a| 
백업이 마운트된 최신 버전의 SnapManager 호스트를 롤백하려고 했습니다. 이러한 백업은 이전 버전의 SnapManager 호스트에 마운트되지 않습니다.
 a| 
최신 버전의 SnapManager 호스트에서 백업을 마운트 해제하고 롤백을 수행합니다.



 a| 
'SMSAP-09258: 새 호스트에서 백업 <backupid>이 마운트 해제되었으므로 롤백이 지원되지 않습니다.'
 a| 
마운트 해제된 백업이 있는 SnapManager 호스트의 최신 버전을 롤백하려고 했습니다.
 a| 
최신 버전의 SnapManager 호스트에 백업을 마운트한 다음 롤백을 수행합니다.



 a| 
S MSAP-09298: 더 높은 버전의 다른 호스트가 이미 있으므로 이 리포지토리를 업데이트할 수 없습니다. 대신 모든 호스트에 대해 롤링업그레이드를 수행하십시오.
 a| 
단일 호스트에서 롤링 업그레이드를 수행한 다음 해당 호스트의 저장소를 업데이트했습니다.
 a| 
모든 호스트에서 롤링 업그레이드를 수행합니다.



 a| 
'SMSAP-09297: 제약 조건을 설정하는 동안 오류가 발생했습니다. 리포지토리가 일관되지 않은 상태일 수 있습니다. 현재 작업 이전에 수행한 리포지토리 백업을 복원하는 것이 좋습니다.
 a| 
저장소 데이터베이스가 일관되지 않은 상태로 남아 있는 경우 롤링 업그레이드 또는 롤백 작업을 수행하려고 했습니다.
 a| 
이전에 백업한 리포지토리를 복원합니다.

|===


== 작업 실행(12,000 시리즈)

다음 표에서는 작업과 관련된 일반적인 오류를 보여 줍니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
S MSAP-12347 [오류]: SnapManager 서버가 호스트 <호스트> 및 포트 <포트>에서 실행되고 있지 않습니다. SnapManager 서버를 실행하는 호스트에서 이 명령을 실행하십시오.
 a| 
프로파일을 설정하는 동안 호스트 및 포트에 대한 정보를 입력했습니다. 그러나 SnapManager 서버가 지정된 호스트 및 포트에서 실행되고 있지 않으므로 SnapManager에서 이러한 작업을 수행할 수 없습니다.
 a| 
SnapManager 서버를 실행하는 호스트에서 명령을 입력합니다. 'lsnrctl status' 명령으로 포트를 확인하여 데이터베이스가 실행 중인 포트를 확인할 수 있습니다. 필요한 경우 백업 명령에서 포트를 변경합니다.

|===


== 프로세스 구성 요소 실행(13,000 시리즈)

다음 표에서는 SnapManager의 프로세스 구성 요소와 관련된 일반적인 오류를 보여 줍니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
'sMSAP-13083: x' 값을 가진 스냅이름 패턴에는 문자, 숫자, 밑줄, 대시, 중괄호 이외의 문자가 포함됩니다.
 a| 
프로파일을 만들 때 Snapname 패턴을 사용자 지정했지만 허용되지 않는 특수 문자를 포함했습니다.
 a| 
문자, 숫자, 밑줄, 대시 및 중괄호 이외의 특수 문자를 제거합니다.



 a| 
'SMSAP-13084: x'값을 가진 스냅이름 패턴에 왼쪽과 오른쪽 중괄호 수가 일치하지 않습니다.'
 a| 
프로파일을 만들 때 Snapname 패턴을 사용자 지정했지만 왼쪽 및 오른쪽 중괄호는 일치하지 않습니다.
 a| 
Snapname 패턴에 일치하는 여는 대괄호 및 닫는 대괄호를 입력합니다.



 a| 
'sMSAP-13085: x' 값을 가진 Snapname 패턴에 잘못된 변수 이름 "y"가 포함되어 있습니다.
 a| 
프로파일을 만들 때 Snapname 패턴을 사용자 지정했지만 허용되지 않는 변수를 포함했습니다.
 a| 
문제가 되는 변수를 제거합니다. 허용 가능한 변수 목록을 보려면 를 참조하십시오 xref:concept-snapshot-copy-naming.adoc[스냅샷 복사본 이름 지정].



 a| 
값이 "x"인 'sMSAP-13086 Snapname pattern에는 변수 "smid"가 포함되어야 합니다.
 a| 
프로파일을 만들 때 Snapname 패턴을 사용자 지정했지만 필요한 'mid' 변수를 생략했습니다.
 a| 
필요한 'MID' 변수를 삽입합니다.

|===


== SnapManager 유틸리티와 관련된 오류 메시지(14,000 시리즈)

다음 표에는 SnapManager 유틸리티와 관련된 일반적인 오류가 나와 있습니다.

|===
| 오류 메시지 | 설명 | 해상도 


 a| 
'MSAP-14501: 메일 ID는 비워둘 수 없습니다.'
 a| 
이메일 주소를 입력하지 않았습니다.
 a| 
유효한 이메일 주소를 입력하십시오.



 a| 
'MSSAP-14502: 메일 제목은 비워 둘 수 없습니다.'
 a| 
이메일 제목을 입력하지 않았습니다.
 a| 
적절한 이메일 제목을 입력합니다.



 a| 
'MSSAP-14506: 메일 서버 필드는 비워 둘 수 없습니다.'
 a| 
이메일 서버 호스트 이름 또는 IP 주소를 입력하지 않았습니다.
 a| 
유효한 메일 서버 호스트 이름 또는 IP 주소를 입력합니다.



 a| 
'MSSAP-14507: Mail Port 필드는 비워 둘 수 없습니다.'
 a| 
이메일 포트 번호를 입력하지 않았습니다.
 a| 
이메일 서버 포트 번호를 입력합니다.



 a| 
'MSSAP-14508: 보낸 메일 ID는 비워둘 수 없습니다.'
 a| 
보낸 사람의 전자 메일 주소를 입력하지 않았습니다.
 a| 
유효한 발신자의 이메일 주소를 입력하십시오.



 a| 
'MSAP-14509: 사용자 이름은 비워둘 수 없습니다.'
 a| 
인증을 활성화했으며 사용자 이름을 제공하지 않았습니다.
 a| 
이메일 인증 사용자 이름을 입력합니다.



 a| 
"MSAP-14510: 암호는 비워둘 수 없습니다. 암호를 입력하십시오.
 a| 
인증을 활성화했으며 암호를 제공하지 않았습니다.
 a| 
이메일 인증 암호를 입력합니다.



 a| 
'sMSAP-14550: 이메일 상태 <SUCCESS/FAILURE>'.
 a| 
포트 번호, 메일 서버 또는 수신기의 이메일 주소가 잘못되었습니다.
 a| 
이메일 구성 중에 적절한 값을 제공하십시오.



 a| 
'SMSAP-14559: 이메일 알림 전송 실패: <error>'.
 a| 
잘못된 포트 번호, 잘못된 메일 서버 또는 잘못된 수신인의 메일 주소 때문일 수 있습니다.
 a| 
이메일 구성 중에 적절한 값을 제공하십시오.



 a| 
'SMSAP-14560: Notification failed: Notification configuration is not available'(알림 실패: 알림 구성을 사용할 수 없습니다).
 a| 
알림 구성을 사용할 수 없으므로 알림 전송에 실패했습니다.
 a| 
알림 구성을 추가합니다.



 a| 
SMSAP-14565: 시간 형식이 잘못되었습니다. 시간 형식을 HH:MM 형식으로 입력하십시오.
 a| 
잘못된 형식으로 시간을 입력했습니다.
 a| 
hh:mm 형식으로 시간을 입력합니다.



 a| 
SMSAP-14566: 날짜 값이 잘못되었습니다. 유효한 날짜 범위는 1-31입니다.
 a| 
구성된 날짜가 올바르지 않습니다.
 a| 
날짜는 1에서 31 사이의 범위에 있어야 합니다.



 a| 
SMSAP-14567: 일 값이 잘못되었습니다. 유효한 일 범위는 1 - 7'입니다.
 a| 
구성된 요일이 올바르지 않습니다.
 a| 
1에서 7 사이의 날짜 범위를 입력합니다.



 a| 
'SMSAP-14569: 서버가 요약 알림 스케줄을 시작하지 못했습니다.'
 a| 
알 수 없는 이유로 SnapManager 서버가 종료되었습니다.
 a| 
SnapManager 서버를 시작합니다.



 a| 
'SMSAP-14570: Summary Notification Not Available'(요약 알림을 사용할 수 없음).
 a| 
요약 알림을 구성하지 않았습니다.
 a| 
요약 알림을 구성합니다.



 a| 
'SMSAP-14571: profile과 summary notification 모두 enable 불가'
 a| 
프로필 및 요약 알림 옵션을 모두 선택했습니다.
 a| 
프로필 알림 또는 요약 알림을 활성화합니다.



 a| 
'SMSAP-14572: 성공 또는 실패 알림 옵션 제공'
 a| 
성공 또는 실패 옵션을 활성화하지 않았습니다.
 a| 
성공 또는 실패 옵션 중 하나 또는 둘 모두를 선택해야 합니다.

|===