---
permalink: windows/reference-troubleshooting-snapmanager.html 
sidebar: sidebar 
keywords: information, common, issue, resolve, troubleshoot, snapmanager 
summary: 발생할 수 있는 가장 일반적인 문제 및 해결 방법에 대한 정보를 찾을 수 있습니다. 
---
= SnapManager 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
발생할 수 있는 가장 일반적인 문제 및 해결 방법에 대한 정보를 찾을 수 있습니다.

다음 표에서는 일반적인 문제와 가능한 해결 방법을 설명합니다.

[cols="2*"]
|===
| 문제 중심 질문입니다 | 가능한 해결 방법 


 a| 
대상 데이터베이스와 수신기가 실행되고 있습니까?
 a| 
lsnrctl status 명령을 실행합니다. 데이터베이스 인스턴스가 수신기에 등록되어 있는지 확인합니다.



 a| 
스토리지가 표시됩니까?
 a| 
다음 단계를 수행하십시오.

. 내 컴퓨터를 마우스 오른쪽 단추로 클릭한 다음 * 관리 * 를 선택합니다.
. 스토리지 * > * SnapDrive * > * 호스트 이름 * > * 디스크 * 를 클릭합니다.




 a| 
SnapManager 서버가 실행 중입니까?
 a| 
상태를 확인한 다음 서비스 구성을 사용하여 서버를 시작합니다.

그래픽 사용자 인터페이스(GUI) 또는 명령줄 인터페이스(CLI)를 사용하여 프로파일과 관련된 SnapManager 명령을 시작하려면 먼저 서버가 실행 중이어야 합니다. 서버를 시작하지 않고 리포지토리를 만들거나 업데이트할 수 있지만 다른 모든 SnapManager 작업을 실행하려면 서버가 실행 중이어야 합니다.

SnapManager 서버를 시작하려면 다음 명령을 입력합니다.

'msap_server start'를 선택합니다



 a| 
SnapManager 설정을 올바르게 실행하는 데 필요한 모든 구성 요소가 있습니까?
 a| 
'smsap system verify' 명령어를 실행하여 SnapDrive가 올바르게 설정되어 있는지 확인한다.



 a| 
올바른 버전의 SnapManager가 있습니까?
 a| 
SnapManager 버전을 확인하려면 'msap version' 명령어를 사용한다.



 a| 
SnapManager 로그 파일을 검토하여 오류 메시지가 문제를 격리하는 데 도움이 되는지 확인했습니까?
 a| 
SnapManager는 모든 로그 항목을 하나의 순환 로그 파일 세트에 기록합니다. 로그 파일은 'C:\program_files\NetApp\SnapManager for SAP\logs'에 있습니다.

Windows 2008을 사용하는 경우 로그는 다음 위치에 있습니다.

* 작업 로그:
+
** 'C:\Program Files\NetApp\SnapManager for SAP\var\log\smssap'


* 클라이언트 로그:
+
** 'C:\Users\Administrator\AppData\Roaming\NetApp\sap\3.3.0\'




또한 'C:\Documents and Settings\hostname\Application Data\NetApp\smsap\3.3.0\log' 위치에서 로그를 보는 것이 도움이 될 수 있습니다

각 작업 로그는 'msap_of_date_time.log' 형식의 자체 로그 파일에 기록됩니다.



 a| 
Data ONTAP를 실행하지 않는 스토리지 시스템에 아카이브 로그가 저장된 경우 SnapManager를 사용한 백업에서 아카이브 로그를 제외했습니까?
 a| 
'msap.config' 파일을 사용하면 특정 아카이브 로그 파일을 제외할 수 있습니다. Windows의 경우 파일은 'C:\program_files\netapp\smsap\properties\smsap.config'에 있습니다

파일에 언급된 형식을 사용하여 로컬 아카이브 로그를 제외합니다. 자세한 내용은 "설정 속성 설정" 항목을 참조하십시오.

SnapManager CLI에서 백업을 생성하는 동안 아카이브 로그 대상을 제외할 수도 있습니다. 자세한 내용은 ""데이터베이스 백업 작성" 항목을 참조하십시오.

SnapManager GUI에서 백업을 생성하는 동안 아카이브 로그 대상을 제외할 수도 있습니다.



 a| 
Windows에서 SnapManager를 설치 또는 업그레이드하려는 디렉토리에 MS-DOS 창이 열려 있습니까?
 a| 
다음과 유사한 오류 메시지가 표시됩니다.

[listing]
----
Directory
C:\Program Files\NetApp\SnapManager for SAP\bin
is currently in use by another program.
Any window, opened by you or
another user, that is currently
referencing this directory must be
closed before installation can proceed.
----
창을 닫고 설치 또는 업그레이드를 다시 시도하십시오.



 a| 
리포지토리에 연결할 수 없습니까?
 a| 
리포지터리에 연결할 수 없는 경우 리포지터리 데이터베이스에서 'lsnrctl status' 명령을 실행하고 활성 서비스 이름을 확인합니다. SnapManager가 저장소 데이터베이스에 연결되면 데이터베이스의 서비스 이름을 사용합니다. Listener 설정 방법에 따라 짧은 서비스 이름 또는 정규화된 서비스 이름이 될 수 있습니다. SnapManager가 백업, 복구 또는 기타 작업을 위해 데이터베이스에 연결할 때 호스트 이름과 SID를 사용합니다. 현재 연결할 수 없어 리포지토리가 올바르게 초기화되지 않으면 리포지토리를 제거할 것인지 묻는 오류 메시지가 표시됩니다. 현재 보기에서 리포지토리를 제거하여 다른 리포지토리에서 작업을 수행할 수 있습니다.

또한 해당 서비스가 실행 중인지 확인합니다.



 a| 
시스템에서 호스트 이름을 확인할 수 있습니까?
 a| 
지정된 호스트 이름이 다른 서브넷에 있는지 확인합니다. SnapManager에서 호스트 이름을 확인할 수 없다는 오류 메시지가 나타나면 호스트 파일에 호스트 이름을 추가합니다. 'C:\WINDOWS\system32\drivers\etc\hosts':'xxx.xxx.xxx.xxx.xxx 호스트 이름 IP 주소'에 있는 파일에 호스트 이름을 추가합니다



 a| 
SnapDrive가 실행 중입니까?
 a| 
SnapDrive 상태를 보려면 서비스로 이동한 다음 SnapDrive 서비스를 선택합니다.



 a| 
SnapDrive를 사용하여 액세스할 수 있도록 구성된 스토리지 시스템은 무엇입니까?
 a| 
SnapDrive에 대해 구성된 스토리지 시스템을 찾으려면 다음 단계를 수행하십시오.

. 내 컴퓨터 * 를 마우스 오른쪽 단추로 클릭한 다음 * 관리 * 를 선택합니다.
. 스토리지 * > * SnapDrive * 를 클릭합니다.
. 호스트 이름을 마우스 오른쪽 단추로 클릭한 다음 * 전송 프로토콜 설정 * 을 선택합니다.




 a| 
SnapManager GUI 성능을 어떻게 개선할 수 있습니까?
 a| 
* 리포지토리, 프로필 호스트 및 프로필에 대한 유효한 사용자 자격 증명이 있는지 확인합니다.
+
자격 증명이 유효하지 않으면 리포지토리, 프로필 호스트 및 프로필에 대한 사용자 자격 증명을 지웁니다. 리포지토리, 프로필 호스트 및 프로필에 대해 이전에 설정한 것과 동일한 사용자 자격 증명을 재설정합니다. 사용자 자격 증명 다시 설정에 대한 자세한 내용은 "'자격 증명 캐시 지우기 후 자격 증명 설정'을 참조하십시오.

* 사용하지 않는 프로파일을 닫습니다.
+
열려 있는 프로필 수가 더 많은 경우 SnapManager GUI 성능이 느려집니다.

* SnapManager GUI의 * 관리자 * 메뉴 아래의 사용자 기본 설정 창에서 * 시작 시 * 열기를 활성화했는지 확인합니다.
+
이 기능이 활성화되면 'C:\Documents and Settings\Administrator\Application Data\NetApp\smsap\3.3.0\GUI\state'에서 사용할 수 있는 사용자 구성('user.config') 파일이 'openOnStartup=profile'으로 표시됩니다.

+
시작 시 * 열기 * 가 활성화되어 있기 때문에 사용자 구성 파일('user.config')의 'lastOpenProfiles'(lastOpenProfiles=Profile1, Profile2, profile3,...)에서 최근 열린 프로파일을 SnapManager GUI에서 확인해야 합니다

+
나열된 프로파일 이름을 삭제하고 항상 최소 개수의 프로파일을 열린 상태로 유지할 수 있습니다.

* Windows 기반 환경에 새 버전의 SnapManager를 설치하기 전에 다음 위치에서 사용할 수 있는 SnapManager 클라이언트 측 항목을 삭제하십시오.
+
C:\Documents and Settings\Administrator\Application Data\NetApp





 a| 
SnapManager GUI는 여러 SnapManager 작업이 백그라운드로 동시에 시작되고 실행될 때 새로 고침에 더 많은 시간이 걸립니다. 이미 삭제되었지만 SnapManager GUI에 여전히 표시되는 백업을 마우스 오른쪽 버튼으로 클릭하면 해당 백업에 대한 백업 옵션이 백업 또는 클론 창에서 활성화되지 않습니다.
 a| 
SnapManager GUI가 새로 고쳐질 때까지 기다린 다음 백업 상태를 확인해야 합니다.



 a| 
Oracle 데이터베이스가 영어로 설정되지 않은 경우 어떻게 해야 합니까?
 a| 
Oracle 데이터베이스의 언어가 영어로 설정되어 있지 않으면 SnapManager 작업이 실패할 수 있습니다. Oracle 데이터베이스의 언어를 영어로 설정합니다.

. NLS_LANG 환경 변수가 설정되지 않았는지 확인합니다: echo %NLS_LANG%
. 다음 줄을 'C:\SnapManager_install_directory\service'에 있는 'wrapper.conf' 파일에 추가합니다.
+
셋트넬랑=아메리칸_아메리카.WE8MSWIN1252

. SnapManager 서버를 다시 시작합니다.
+
'msap_server restart'를 선택합니다




NOTE: 시스템 환경 변수가 NLS_LANG로 설정된 경우 NLS_LANG를 덮어쓰지 않도록 스크립트를 편집해야 합니다.



 a| 
리포지토리 데이터베이스가 둘 이상의 IP를 가리키며 각 IP에 다른 호스트 이름이 있는 경우 백업 예약 작업이 실패하면 어떻게 하시겠습니까?
 a| 
. SnapManager 서버를 중지합니다.
. 백업 스케줄을 트리거할 호스트에서 리포지토리 디렉토리의 스케줄 파일을 삭제합니다.
+
스케줄 파일 이름은 다음과 같은 형식으로 지정할 수 있습니다.

+
** repo_username#repository_database_name#repository_host#repo_port입니다
** repository-repo_usernamerepos일시적_database_name -repository_host -repo_port입니다





NOTE: 리포지토리 세부 정보와 일치하는 형식으로 스케줄 파일을 삭제해야 합니다.

. SnapManager 서버를 다시 시작합니다.
. SnapManager GUI에서 동일한 리포지토리 아래에 있는 다른 프로필을 열어 해당 프로필의 일정 정보를 놓치지 않도록 합니다.




 a| 
자격 증명 파일 잠금 오류와 함께 SnapManager 작업이 실패하면 어떻게 해야 합니까?
 a| 
SnapManager는 업데이트하기 전에 자격 증명 파일을 잠그고 업데이트 후 잠금을 해제합니다. 여러 작업이 동시에 실행될 경우 자격 증명 파일이 잠기게 되어 업데이트할 수 있습니다. 다른 작업에서 잠긴 자격 증명 파일에 동시에 액세스하려고 하면 파일 잠금 오류가 발생하여 작업이 실패합니다.

동시 작업의 빈도에 따라 smsap.config 파일에서 다음 매개 변수를 구성합니다.

* FileLock.retryInterval = 100밀리초입니다
* fileLock.timeout = 5000밀리초입니다



NOTE: 매개 변수에 할당된 값은 밀리초 단위여야 합니다.



 a| 
백업 검증 작업이 여전히 실행 중인데도 모니터 탭에서 백업 검증 작업의 중간 상태가 실패로 표시되면 어떻게 해야 합니까?
 a| 
오류 메시지가 sm_gui.log 파일에 기록됩니다. 이 문제를 해결할 'operation.heartbeatInterval' 및 'operation.heartbeatThreshold' 매개 변수의 새 값을 확인하려면 로그 파일을 확인해야 합니다.

. 'msap.config' 파일에 다음 매개 변수를 추가합니다.
+
** 동작 하트비트 간격=5000
** operation.heartbeatThreshold=5000 SnapManager에서 할당한 기본값은 5000입니다.


. 이러한 매개변수에 새 값을 할당합니다.
+

NOTE: 매개 변수에 할당된 값은 밀리초 단위여야 합니다.

. SnapManager 서버를 다시 시작하고 작업을 다시 수행합니다.




 a| 
힙 공간 문제가 발생하면 어떻게 해야 합니까?
 a| 
SnapManager for SAP 작업 중에 힙 공간 문제가 발생하면 다음 단계를 수행해야 합니다.

. SnapManager for SAP 설치 디렉토리로 이동합니다.
. installationDirectory\bin\launchjava 경로에서 "launchjava" 파일을 엽니다.
. Java-Xmx160m Java 힙 공간 매개 변수의 값을 늘립니다.
+
예를 들어, 기본값인 160m를 200m로 늘릴 수 있습니다.

+

NOTE: 이전 버전의 SAP용 SnapManager에서 Java 힙 공간 매개 변수의 값을 증가했다면 해당 값을 유지해야 합니다.





 a| 
SnapManager 서비스가 Windows 환경에서 시작되지 않고 다음 오류 메시지가 표시될 때 수행할 작업: Windows가 로컬 컴퓨터에서 스냅 관리자를 시작할 수 없습니다. 자세한 내용은 시스템 이벤트 로그를 참조하십시오. Microsoft 서비스가 아닌 경우 서비스 공급업체에 문의하고 서비스별 오류 코드 1을 참조하십시오.
 a| 
'Installation_directory\service'에 있는 wrapper.conf 파일에서 다음 매개 변수를 설정한다.

* 래퍼 시작 시간 제한 매개변수는 JVM(Java Virtual Machine)을 시작하는 래퍼와 응용 프로그램이 시작된 JVM의 응답 사이의 최대 허용 시간을 정의합니다.
+
기본값은 90초로 설정됩니다. 그러나 0보다 큰 값을 변경할 수 있습니다. 잘못된 값을 지정하면 기본값이 대신 사용됩니다.

* 래퍼.ping.timeout 매개 변수는 JVM에 대한 래퍼 ping과 JVM의 응답 사이의 최대 허용 시간을 정의합니다. 기본값은 90초로 설정됩니다.
+
그러나 0보다 큰 값으로 변경할 수 있습니다. 잘못된 값을 지정하면 기본값이 대신 사용됩니다.



|===