---
permalink: windows/task-perform-backup-restore-and-clone-operations-using-prescript-and-post-scripts.html 
sidebar: sidebar 
keywords: script, initiate, backup, restore, clone, operation, snapmanager, task-enable, page, create, wizard, restore, recover, create, parameter, prescript, post-script 
summary: 백업, 복원 또는 클론 작업을 시작하는 동안 자체 스크립트를 사용할 수 있습니다. SnapManager에서는 백업 생성 마법사, 복구 또는 복구 마법사 또는 클론 생성 마법사에 작업 설정 페이지를 표시합니다. 이 페이지에서 스크립트를 선택하고 스크립트에 필요한 매개 변수에 대한 값을 제공할 수 있습니다. 
---
= 처방과 사후 스크립트를 사용하여 백업, 복원 및 클론 작업을 수행합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업, 복원 또는 클론 작업을 시작하는 동안 자체 스크립트를 사용할 수 있습니다. SnapManager에서는 백업 생성 마법사, 복구 또는 복구 마법사 또는 클론 생성 마법사에 작업 설정 페이지를 표시합니다. 이 페이지에서 스크립트를 선택하고 스크립트에 필요한 매개 변수에 대한 값을 제공할 수 있습니다.



== 필요한 것

* 올바른 SnapManager 설치 위치에 플러그인 스크립트를 설치합니다.
* 'smsap plugin check' 명령어를 실행하여 플러그인이 올바르게 설치되었는지 확인한다.
* Bash 셸을 사용하고 있는지 확인합니다.




== 이 작업에 대해

명령줄 인터페이스(CLI)에서 스크립트 이름을 나열하고 매개 변수를 선택한 다음 값을 설정합니다.

.단계
. Bash 셸을 사용 중인지 확인하려면 명령 프롬프트에 다음 명령을 입력합니다.
+
``bash *’

+
또는 프롬프트에 "어느-bash" 명령을 입력하고 명령 출력을 스크립트의 시작 매개 변수로 사용할 수 있습니다.

+
오류가 표시되지 않으면 Bash 셸이 제대로 작동하고 있는 것입니다.

. 백업 작업의 경우 '-taskspec' 옵션을 입력하고 백업 작업 전후에 전처리 또는 사후 처리 작업을 수행하기 위한 작업 사양 XML 파일의 절대 경로를 제공합니다.
+
``smssap backup create-profile_profile_name_{[-full{-online|-offline|-auto}[-retain {-hourly|[-daily|-weekly|-monthly|-limited}][-verify]|[-data[[- files_files_[files]]|[-tablespaces_[_- tablespaces_]] autonline-weekly-offline_offline_offline}]]{auto-line-date-latel-weekly-line]]{auto-latel-line] [-archivelogs [-label_label_] [-comment_comment_] [-backup-dest_path1_[,[_path2_]]] [-exclude-dest_path1_[,_path2_]]] [-prelogs{-all|-unes scn_yyyy_yyyy-monthunm_casknm_casknm-days] 이전{HH_cunm_casknmm_cunm-days] [-days]일 [cunm-days]일 [casknunm-days]{HH_yyyy-days]{HH_yyyy-days](_cunm_caskunm-days].days_casknunm-days_casknunm_

+
백업 플러그인 작업이 실패한 경우 플러그인 이름과 반환 코드만 표시됩니다. 플러그인 스크립트에는 로그 메시지를 포함하고 메시지를 사용자 정의 로그 파일로 리디렉션해야 합니다.

. 백업 복구 작업의 경우 '-taskspec' 옵션을 입력하고 복원 작업 전후에 사전 처리 또는 사후 처리 작업을 수행하기 위한 작업 사양 XML 파일의 절대 경로를 제공합니다.
+
"* smssap backup restore -profile_profile_name_{-label_<label>_|- id_<id>_} {-files_<files>_|--tablespaces__|- complete|- controlfiles} [-recover {_-alllogs_|_- nologs_|- until_<refallback] vasspec_spec_spec_spec_refallback] vasspec_spec_spec_spec_spec_spec_spec

+
복구 플러그인 작업이 실패한 경우 플러그인 이름과 반환 코드만 표시됩니다. 플러그인 스크립트에는 로그 메시지를 포함하고 메시지를 사용자 정의 로그 파일로 리디렉션해야 합니다.

. 클론 생성 작업의 경우 '-taskspec' 옵션을 입력하고 클론 작업 전후에 사전 처리 또는 사후 처리 작업을 수행하기 위한 작업 사양 XML 파일의 절대 경로를 제공합니다.
+
'* smssap clone create -profile_profile_name_{-backup-label_backup_name_|-backup-id_<backup-id>_|-current}-newsid_new_sid-_clonespec_full_path_to_clonespecfile_[-reserve_<yes,no,inherit>_] vaskup_comment_comment_spec_spec_spec] <spec_comment><spec_spec_comment><spec_spec_comment><spec_comment><spec_spec_comment><spec_comment>

+
클론 플러그인 작업이 실패한 경우 플러그인 이름과 반환 코드만 표시됩니다. 플러그인 스크립트에는 로그 메시지를 포함하고 메시지를 사용자 정의 로그 파일로 리디렉션해야 합니다.





== 작업 사양 XML 파일을 사용하여 백업을 생성하는 예

[listing]
----
smsap backup create -profile SALES1 -full -online -taskspec sales1_taskspec.xml -force -verify
----