---
permalink: windows/task-download-and-start-the-graphical-user-interface-using-java-web-start-windows.html 
sidebar: sidebar 
keywords: java, web, start, snapmanager, install, host, download, graphical, user, interface, gui, jre 
summary: 'SnapManager가 호스트에 설치되어 있지 않은 경우 Java Web Start를 사용할 수 있습니다. Java Web Start는 SnapManager 구성 요소를 다운로드하고 그래픽 사용자 인터페이스(GUI)를 시작합니다. 지원되는 JRE 버전은 1.5, 1.6 및 1.7입니다.' 
---
= Java Web Start를 사용하여 그래픽 사용자 인터페이스를 다운로드하고 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager가 호스트에 설치되어 있지 않은 경우 Java Web Start를 사용할 수 있습니다. Java Web Start는 SnapManager 구성 요소를 다운로드하고 그래픽 사용자 인터페이스(GUI)를 시작합니다. 지원되는 JRE 버전은 1.5, 1.6 및 1.7입니다.



== 필요한 것

다음 조건이 충족되는지 확인해야 합니다.

* SnapManager 서버가 실행 중입니다.
* 웹 브라우저 창이 열려 있습니다.


.단계
. Microsoft Internet Explorer 웹 브라우저 창에서 '+https://smsap-server.domain.com:port+` 를 입력합니다.
+
'msap-server.domain.com'은 SnapManager를 설치한 정규화된 호스트 이름 및 도메인이고 'port'는 SnapManager 서버의 수신 포트입니다(기본적으로 27314).

+

NOTE: 브라우저 창에 https를 입력해야 합니다.

+
다음과 같은 메시지가 있는 대화 상자가 표시됩니다.




IMPORTANT: "사이트 보안 인증서에 문제가 있습니다...계속 진행하시겠습니까?"라는 메시지가 포함된 대화 상자가 표시됩니다

. 예 * 또는 * 계속 * 을 클릭합니다.
. JRE 6.0 및 응용 프로그램*을 다운로드하고 설치하려면 여기를 클릭하십시오.
+
다음 메시지와 함께 Java Web Start 다운로드 링크가 표시됩니다.




IMPORTANT: "이 사이트에는 다음 ActiveX 컨트롤이 필요할 수 있습니다: Java Plug-in 1.6"... "설치하려면 여기를 클릭하십시오.

. 설치 * 창에서 다음 단계를 수행하십시오.
+
.. 설치하려면 여기를 클릭하십시오... 라는 메시지를 클릭합니다
+
ActiveX 컨트롤 설치 * 메뉴가 표시됩니다.

.. ActiveX 컨트롤 설치... * 를 선택합니다.
+
다음 메시지가 표시됩니다.






IMPORTANT: "이 소프트웨어를 설치하시겠습니까?"라는 텍스트가 포함된 "Internet Explorer - 보안 경고" 이름: Java Plug-in 1.6

. 설치 * 를 클릭합니다.
+
J2SE Runtime Environment 1.6용 설치 프로그램의 "Java Plug-in 1.6." 창이 표시됩니다.

. 설치 * 를 클릭합니다.
+
J2SE Runtime Environment 1.6 설치를 요청하는 창이 표시됩니다. . 설치 창에서 다음 단계를 수행하십시오.

. 사용권 계약 * 페이지에서 * 사용권 계약 조건에 동의함 * 을 선택하고 * 다음 * 을 클릭합니다.
. 설치 유형 * 페이지에서 * 일반 * 을 선택하고 * 다음 * 을 클릭합니다.
. 설치 완료 * 창에서 * 마침 * 을 클릭합니다.
+
SnapManager가 다운로드를 시작합니다.

+
"이 파일을 저장하시겠습니까?"라는 메시지가 포함된 파일 다운로드 대화 상자가 나타납니다. application.jnlp'가 표시됩니다. . 파일 다운로드 * 창에서 다음 단계를 수행하십시오.

. Windows 클라이언트에 최신 버전의 JRE 1.6을 설치합니다.
. 'java-version' 명령을 실행하여 Java가 설치되었는지 확인합니다
+
출력은 Java 버전 1.6.0_24(Java 1.6) 이상을 나타내야 합니다.

. Java Web Start Launcher 프로그램을 사용하여 확장명이 jnlp인 파일을 항상 열도록 Windows 구성 설정을 변경합니다.
+
Windows 구성 설정을 변경하는 단계는 사용 중인 Windows 버전에 따라 다릅니다.

. 1단계에서 지정한 SnapManager URL을 입력합니다.
+
Windows 클라이언트에서 SnapManager 다운로드가 시작되고 다음 경고가 표시됩니다




WARNING: '보안' 대화 상자가 표시됩니다

. 다음 단계를 수행하십시오.
+
메시지 내용과 단추 레이블은 플랫폼에 따라 다릅니다.

+
.. 경고 - 보안 * 대화 상자에서 * 예 * 를 클릭합니다.
+
대화 상자가 표시됩니다.

.. 호스트 이름 불일치 대화 상자에서 * 실행 * 을 클릭합니다.
+
SnapManager 응용 프로그램의 서명에 대한 메시지가 있는 경고 - 보안 대화 상자가 표시됩니다.

.. Run * 을 클릭합니다.
+
Java Installer - Security Warning 이라는 제목의 대화 상자와 다음 메시지가 표시됩니다.






WARNING: 경고 보안 - 응용 프로그램의 디지털 서명에 오류가 있습니다. Do you want the application'(응용 프로그램을 실행하시겠습니까?)

. Run * 을 클릭합니다.
+
브라우저가 SnapManager for SAP GUI를 다운로드하고 시작합니다.


