---
permalink: windows/task-create-profiles.html 
sidebar: sidebar 
keywords: create, profile, assign, oracle, database, policy, set, retention, count, class 
summary: 프로필을 생성할 때 프로필에 특정 Oracle 데이터베이스 사용자 계정을 할당할 수 있습니다. 프로파일에 대한 보존 정책을 설정하고 각 보존 클래스에 대한 보존 수와 기간을 설정할 수 있습니다. 
---
= 프로파일 작성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
프로필을 생성할 때 프로필에 특정 Oracle 데이터베이스 사용자 계정을 할당할 수 있습니다. 프로파일에 대한 보존 정책을 설정하고 각 보존 클래스에 대한 보존 수와 기간을 설정할 수 있습니다.



== 이 작업에 대해

데이터베이스의 '-login', -password', '-port' 매개 변수의 값을 제공하지 않으면 운영 체제(OS) 인증 모드는 기본 자격 증명을 사용합니다.

프로파일을 만드는 동안 SnapManager는 복원 적격성 검사를 수행하여 데이터베이스를 복원하는 데 사용할 수 있는 복원 메커니즘을 결정합니다.

SnapManager(3.2 이상)를 사용하면 새 프로파일을 만들거나 기존 프로파일을 업데이트하는 동안 데이터 파일에서 아카이브 로그 파일을 분리할 수 있습니다. 프로파일을 사용하여 백업을 분리한 후 데이터 파일만 백업하거나 데이터베이스의 아카이브 로그 전용 백업만 생성할 수 있습니다. 새 프로파일 또는 업데이트된 프로파일을 사용하여 데이터 파일과 아카이브 로그 파일을 모두 포함하는 백업을 만들 수 있습니다. 그러나 프로파일을 사용하여 전체 백업을 생성하거나 설정을 되돌릴 수는 없습니다.

* 전체 및 부분 백업을 생성하기 위한 프로파일 *

데이터 파일, 제어 파일, 아카이브 로그 파일 및 지정된 데이터 파일 또는 테이블스페이스, 모든 제어 파일 및 모든 아카이브 로그 파일이 포함된 부분 데이터베이스 백업을 포함하는 전체 데이터베이스 백업을 생성하기 위해 프로파일을 생성할 수 있습니다. SnapManager에서는 전체 및 부분 백업에 대해 생성된 프로파일을 사용하여 별도의 아카이브 로그 백업을 생성할 수 없습니다.

* 데이터 파일 전용 백업 및 아카이브 전용 백업을 만들기 위한 프로파일 *

새 프로파일을 생성할 때 데이터 파일 백업에서 아카이브 로그 백업을 분리하기 위해 '-separate-archivelog-backups'를 포함시킬 수 있습니다. 기존 프로파일을 업데이트하여 아카이브 로그 백업을 데이터 파일 백업과 분리할 수도 있습니다.

새 프로파일 옵션을 사용하여 아카이브 로그 백업을 분리하여 다음 SnapManager 작업을 수행할 수 있습니다.

* 아카이브 로그 백업을 생성합니다
* 아카이브 로그 백업을 삭제합니다
* 아카이브 로그 백업을 마운트합니다
* 아카이브 로그 백업을 비울 수 있습니다


데이터 파일 백업에서 아카이브 로그 백업을 분리하기 위해 프로파일을 생성하는 동안 아카이브 로그 파일이 프로파일이 생성되는 데이터베이스에 없으면 경고 메시지가 표시됩니다.


WARNING: 보관 로그 파일이 활성 파일 시스템에 없습니다. archive log thread version> 로그 파일보다 이전 버전의 아카이브된 로그 파일은 백업에 포함되지 않습니다

이 데이터베이스에 대한 백업을 생성하는 경우에도 데이터베이스 백업에서 아카이브 로그 파일을 사용할 수 없습니다.


NOTE: 프로파일을 만드는 동안 오류가 발생하면 'smsap system dump' 명령을 사용합니다. 프로파일을 만든 후 오류가 발생하면 'msap operation dump'와 'msap profile dump' 명령을 사용합니다.

.단계
. 사용자 이름, 암호 및 포트(Oracle 인증)를 사용하여 프로파일을 만들려면 다음 명령을 입력합니다.
+
``smssap profile create-profileprofile[-profile-passwordprofile_password] -repository-dbnameterepo_dbname -hetreaddresspo_host -portreportpo_port -login -database -dbnamedb_dbename]{usernednemnederman_commentname][-login_subportname]{login_substentname]{login_subtentname]{login_subtentname]{login_subtentname]{userndurename]{recentname=subtnepidnemnemnemeta_subtentname]{recentname]{userndurnemeta_subportname]{recentname]{recentname]{recentname=emeta-subtentname]{recentname=emeta_subportname=subportname=emeta-subtentname=emeta_substationname]{recentname]{recentname]{recentname=substation

+
이 명령의 다른 옵션은 다음과 같습니다.

+
['-force'] ['-nop프롬프트']

+
['quiet'|'rbose']

+
데이터베이스에 액세스하는 방법에 따라 프로파일을 만들 때 다른 옵션을 포함할 수도 있습니다.

+
|===
| 만약... | 그러면... 


 a| 
* 데이터베이스 인증을 사용하여 프로파일을 생성하려고 합니다 *
 a| 
데이터베이스 로그인 정보를 지정합니다.



 a| 
* 백업에 대한 백업 보존 정책을 지정하려는 경우 *
 a| 
보존 클래스에 대한 보존 수 또는 기간을 지정하거나 둘 모두를 지정합니다. 기간은 클래스의 단위(예: 시간별 시간, 일별 일)입니다.

** hourly는 hourly retention class로, ['-count n']['-duration m']은 retention count와 retention duration을 각각 나타낸다.
** daily는 일별 보존 클래스이며, 이 클래스는 각각 ['-count n']['-duration m']이 보존 횟수와 보존 기간입니다.
** 주별 보존 클래스는 ['-count n']['-duration m']이 각각 보존 횟수와 보존 기간인 주별 보존 클래스입니다.
** 월 단위 보유는 월 단위 보유등급으로 ['-count n']['-duration m']은 각각 보존 횟수와 보존 기간입니다.




 a| 
* 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 활성화하고자 합니다 *
 a| 
다음 옵션 및 변수를 지정합니다.

** '-summary-notification'을 사용하면 저장소 데이터베이스 아래에 있는 여러 프로필에 대한 요약 전자 메일 알림을 구성할 수 있습니다.
** '-notification'을 사용하면 프로필에 대한 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 받을 수 있습니다.
** '-SUCCESS-EMAIL_address2'를 사용하면 새 프로파일 또는 기존 프로파일을 사용하여 수행된 데이터베이스 작업에 대한 이메일 알림을 받을 수 있습니다.
** '-failure-emailemail_address2'를 사용하면 새 프로파일 또는 기존 프로파일을 사용하여 실패한 데이터베이스 작업에 대한 이메일 알림을 받을 수 있습니다.
** '-subjectsubject_text'는 새 프로필이나 기존 프로필을 만드는 동안 이메일 알림의 제목 텍스트를 지정합니다. 리포지토리에 대한 알림 설정이 구성되어 있지 않은 상태에서 CLI를 사용하여 프로필 또는 요약 알림을 구성하려고 하면 콘솔 로그에 'SMSAP-14577: 알림 설정이 구성되지 않음'이라는 메시지가 기록됩니다.
+
알림 설정을 구성한 후 리포지토리에 대한 요약 알림을 설정하지 않고 CLI를 사용하여 요약 알림을 구성하려고 하면 콘솔 로그에 'SMSAP-14575: Summary notification configuration not available for this repository'라는 메시지가 표시됩니다





 a| 
* 데이터 파일과 별도로 아카이브 로그 파일을 백업하려고 합니다 *
 a| 
다음 옵션 및 변수를 지정합니다.

** '-separate-archivelog-backups'를 사용하면 데이터 파일 백업에서 아카이브 로그 백업을 분리할 수 있습니다.
** '-retain-archivelog-backups'는 아카이브 로그 백업의 보존 기간을 설정합니다. 양의 보존 기간을 지정해야 합니다.
+
아카이브 로그 백업은 아카이브 로그 보존 기간을 기준으로 유지됩니다. 데이터 파일 백업은 기존 보존 정책에 따라 보존됩니다.

** '-include-with-online-backups'에는 온라인 데이터베이스 백업과 함께 아카이브 로그 백업이 포함됩니다.
+
이 옵션을 사용하면 클론 생성을 위해 온라인 데이터 파일 백업 및 아카이브 로그 백업을 함께 생성할 수 있습니다. 이 옵션을 설정하면 온라인 데이터 파일 백업을 만들 때마다 데이터 파일과 함께 아카이브 로그 백업이 즉시 생성됩니다.

** '-no-include-with-online-backups'에는 데이터베이스 백업과 함께 아카이브 로그 백업이 포함되지 않습니다.




 a| 
* 성공적인 프로파일 생성 작업 * 후에 덤프 파일을 수집할 수 있습니다
 a| 
profile create 명령의 끝에 있는 dump 옵션을 지정합니다.

|===

