---
permalink: windows/task-upgrading-snapmanager-for-oraclesnapmanager-for-sap-hosts.html 
sidebar: sidebar 
keywords: upgrade, exist, snapmanager, host, version, simultaneous, result, downtime, schedule, operation, time, upgrading 
summary: 모든 기존 SnapManager 호스트를 업그레이드하여 최신 버전의 SnapManager를 사용할 수 있습니다. 모든 호스트가 동시에 업그레이드됩니다. 그러나 이 경우 해당 시간 동안 모든 SnapManager 호스트와 예약된 작업의 다운타임이 발생할 수 있습니다. 
---
= SnapManager 호스트 업그레이드 중
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 기존 SnapManager 호스트를 업그레이드하여 최신 버전의 SnapManager를 사용할 수 있습니다. 모든 호스트가 동시에 업그레이드됩니다. 그러나 이 경우 해당 시간 동안 모든 SnapManager 호스트와 예약된 작업의 다운타임이 발생할 수 있습니다.

. 다음 단계를 수행하여 SnapManager 서버를 중지합니다.
+
.. Windows 서비스 창에서 * SAP용 NetApp SnapManager * 를 선택합니다.
.. 왼쪽 패널에서 * Stop * (중지 *)을 클릭합니다.


. SnapManager 설치 파일을 두 번 클릭합니다.
+
|===
| 운영 체제가... | 그 다음에... 


 a| 
Windows x86
 a| 
netapp.smsap.windows-x86-version_number.exe



 a| 
Windows x64
 a| 
netapp.smsap.windows-x64-version_number.exe

|===
+
다음 메시지가 표시됩니다. 게시자를 확인할 수 없습니다. 이 소프트웨어를 실행하시겠습니까?

. 확인 * 을 클릭합니다.
+
소개 창이 표시됩니다.

. 다음 * 을 클릭합니다.
+
설치 폴더 선택 창이 표시됩니다.

. 기본 설치 위치를 그대로 사용하거나 새 위치를 선택하려면 * 다음 * 을 클릭합니다.
+
기본 위치는 C:\Program Files\NetApp\SnapManager for SAP입니다.

. 메뉴 사용 가능 여부 창에서 * 다음 * 을 클릭합니다.
. 서비스 속성 지정 창에서 Windows 서비스의 계정 및 암호 정보를 입력합니다.
+
지정된 계정은 다음 그룹의 구성원이어야 합니다.

+
** 스토리지 시스템의 로컬 관리 그룹입니다
** 로컬 관리자의 그룹입니다
** 재부팅 후 서비스를 자동으로 시작해야 하는지 또는 서비스를 수동으로 시작해야 하는지 여부를 지정할 수 있는 ORA_DBA 그룹입니다.


. 사전 설치 요약 창에서 * 설치 * 를 클릭합니다.
. 설치 완료 창에서 * 다음 * 을 클릭합니다.
. 중요 정보 창에서 * 완료 * 를 클릭하여 설치 프로그램을 종료합니다.


* 관련 정보 *

xref:concept-preparing-to-install-snapmanager-for-oraclesnapmanager-for-sap.adoc[SAP용 SnapManager 설치 준비 중]

xref:concept-preinstallation-tasks.adoc[사전 설치 작업]

xref:task-downloading-snapmanager-for-oraclesnapmanager-for-sap-installation-package.adoc[SnapManager for SAP 설치 패키지를 다운로드합니다]
