---
permalink: windows/task-configure-summary-e-mail-notification-for-multiple-profiles.html 
sidebar: sidebar 
keywords: snapmanager, enable, configure, summary, email, notification, multiple, profile, repository, database 
summary: SnapManager를 사용하면 저장소 데이터베이스 아래에 있는 여러 프로필에 대한 요약 전자 메일 알림을 구성할 수 있습니다. 
---
= 여러 프로필에 대한 요약 이메일 알림을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용하면 저장소 데이터베이스 아래에 있는 여러 프로필에 대한 요약 전자 메일 알림을 구성할 수 있습니다.



== 이 작업에 대해

SnapManager 서버 호스트를 알림 호스트로 설정하여 요약 알림 e-메일을 수신자에게 보낼 수 있습니다. SnapManager 서버 호스트 이름 또는 IP 주소가 변경되면 알림 호스트도 업데이트할 수 있습니다.

e-메일 알림이 필요한 일정 시간 중 하나를 선택할 수 있습니다.

* HOURLY(매시간): 매시간마다 이메일 알림을 수신합니다
* 매일: 매일 이메일 알림을 수신합니다
* Weekly(매주): 매주 이메일 알림을 수신합니다
* 매월: 매월 이메일 알림을 수신합니다


이러한 프로파일을 사용하여 수행한 작업에 대한 알림을 받으려면 단일 이메일 주소 또는 쉼표로 구분된 이메일 주소 목록을 입력해야 합니다. 여러 이메일 주소를 입력할 때 쉼표와 다음 이메일 주소 사이에 공백이 없어야 합니다.


NOTE: 큰따옴표 안에 여러 전자 메일 주소 집합을 입력해야 합니다.

SnapManager에서는 다음 변수를 사용하여 사용자 지정된 이메일 제목을 추가할 수 있습니다.

* 데이터베이스 작업에 사용되는 프로파일 이름입니다.
* 데이터베이스 이름
* 데이터베이스의 SID입니다
* 호스트 서버의 이름입니다
* yyyymmdd:hh:ss 형식으로 데이터베이스 작업의 시작 시간입니다
* yyyymmdd:hh:ss 형식으로 데이터베이스 작업의 종료 시간입니다
* 데이터베이스 작업 상태입니다


사용자 지정 제목을 추가하지 않도록 선택하면 SnapManager에서 '값 제목 표시' 오류 메시지를 표시합니다.

.단계
. 다음 명령을 입력합니다.
+
``smssap notification update-summary-notification-repository-port_-dbname_repo_service_name_-host_repo_host_-login-username_username_-email_address_1_, _email_address_2_-subject_subject_pattern_-frequency {-daily-time-time_time_port_port_port_port_port_port_port_port_port_-dbname_-port_port_name_-port_name_-host_name_-host_name_-host_name__name_-host_name_-host_name_-host_name__name__name__name__name__name__name_name__name__name_name__name__name_

+
이 명령의 다른 옵션은 다음과 같습니다.

+
['-force'] ['-nop프롬프트']

+
['quiet'|'-verbose']



[listing]
----

smsap notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email-address admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1 -notification-host wales
----