---
permalink: windows/task-adding-new-profile-to-summary-notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, profile, command, add 
summary: 저장소 데이터베이스에 대한 요약 전자 메일 알림을 구성한 후 요약 알림 명령을 사용하여 요약 알림에 새 프로필을 추가할 수 있습니다. 
---
= 요약 e-메일 알림에 새 프로필 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
저장소 데이터베이스에 대한 요약 전자 메일 알림을 구성한 후 요약 알림 명령을 사용하여 요약 알림에 새 프로필을 추가할 수 있습니다.

. smsap profile create -profileprofile_name [-profile-passwordprofile_password] -repository -dbnamerepo_service_name -hotrepo_host -login -usernamerepo_username -database -dbnamedb_hostname] versnednednednersamdb -versname [usernamportname]{username]{usernedname -durename]{usernednportname]{uservidename]{uservidename=videname]{usernportname -viderm -videname]{usernportname=videname]{usernportname=videname=versename]{usernednednednednednportname]{usernationvidationversename=videname]{usernportname=vidationversename]{userdate-dnportname=vidationversename]{userdate_recationvidationname]{userdate_recationname]{usernportname]{user
+
이 명령의 다른 옵션은 다음과 같습니다.

+
[-force]


