---
permalink: windows/task-updating-profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, backup, database, operating, system, authentication, information, host, oracle, updating 
summary: '프로파일을 업데이트하여 프로파일 암호, 보존할 백업 수, 데이터베이스에 대한 액세스, 데이터베이스 인증에 대한 운영 체제\(OS\) 인증 및 이에 대한 호스트 정보를 수정할 수 있습니다. Oracle 데이터베이스 암호 정보가 변경되면 프로필에서 해당 정보도 변경해야 합니다.' 
---
= 프로파일을 업데이트하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
프로파일을 업데이트하여 프로파일 암호, 보존할 백업 수, 데이터베이스에 대한 액세스, 데이터베이스 인증에 대한 운영 체제(OS) 인증 및 호스트 정보를 수정할 수 있습니다. Oracle 데이터베이스 암호 정보가 변경되면 프로필에서 해당 정보도 변경해야 합니다.

SnapManager(3.2 이상)를 사용하면 -separate-archivelog-backups 옵션을 사용하여 데이터 파일 백업에서 아카이브 로그 백업을 분리하도록 프로파일을 업데이트할 수 있습니다. 아카이브 로그 백업에 대해 별도의 보존 기간을 지정할 수 있습니다. SnapManager를 사용하면 아카이브 로그 백업을 온라인 데이터베이스 백업과 함께 포함할 수 있습니다. 클로닝을 위해 온라인 데이터 파일 백업 및 아카이브 로그 백업을 함께 생성할 수도 있습니다. 온라인 데이터 파일 백업을 생성하면 데이터 파일과 함께 아카이브 로그 백업이 즉시 생성됩니다.

.단계
. 다음 명령을 입력합니다.
+
ssmap profile update -profilenew_profile [-new-profilenew_profile_name] [-profile-passwordprofile_password] [-profile-profile-passwordprofile] [-profile -subscopenb_dbname -host db_host [-siddb_sid_port][-login -username1.subscendurnemetm_subscopenetm_subscopenetm_subscenetm_subscenetyptename][] subscendurename] subscontentname] subscontentname] subscendurnemetm -subscidenetm -subscopena_subscontentname] subscopena_subscopenetm -subscidenb_subscopenb_subscopenb_subscenetm -subscenb_subscopenb_subscopenb_subscenb_subscenetm_subscenb_subscenb_subscenb_subscenb_subscen

+
이 명령의 다른 옵션은 다음과 같습니다.

+
[-force] [-nop프롬프트]

+
|===
| 원하는 작업 | 그러면... 


 a| 
* 프로필에서 데이터베이스 백업에 대한 백업 보존 정책을 변경합니다. *
 a| 
보존 정책을 변경하려면 보존 클래스의 보존 수 또는 보존 기간을 지정하거나 둘 다 지정합니다. 기간은 클래스의 단위(예: 시간별 시간, 일별 일)입니다.

** hourly 는 매시간 보존 클래스이며 [-countn][-durationm]]은 각각 보존 수와 보존 기간입니다.
** daily 는 [-countn][-durationm]]가 각각 보존 횟수와 보존 기간으로 사용되는 일별 보존 클래스입니다.
** -weekly 는 주별 보존 클래스로서 [-countn] [-durationm]]은 각각 보존 수와 보존 기간입니다.
** monthly 는 월 단위 보존 클래스이며 [-countn][-durationm]]은 각각 보존 횟수와 보존 기간입니다.




 a| 
* 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 활성화합니다. *
 a| 
다음 옵션 및 변수를 지정합니다.

** -summary-notification 리포지토리 데이터베이스에서 여러 프로필에 대한 요약 전자 메일 알림을 구성할 수 있습니다.
** 알림을 통해 프로필에 대한 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 받을 수 있습니다.
** -success-emailemail_address2 새 프로파일 또는 기존 프로파일을 사용하여 데이터베이스 작업이 성공적으로 완료된 후 이메일 알림을 받을 수 있습니다.
** 실패-emailemail_address2 새 프로파일 또는 기존 프로파일을 사용하여 실패한 데이터베이스 작업에 대한 이메일 알림을 받을 수 있습니다.
** -subjectsubject_text 새 프로필이나 기존 프로필을 만드는 동안 이메일 알림의 제목 텍스트를 지정합니다. 리포지토리에 대한 알림 설정이 구성되지 않은 상태에서 CLI(명령줄 인터페이스)를 사용하여 프로필 또는 요약 알림을 구성하려고 하면 콘솔 로그에 SMSAP-14577: 알림 설정이 구성되지 않음 이라는 메시지가 기록됩니다.
+
알림 설정을 구성한 후 리포지토리에 대한 요약 알림을 설정하지 않고 CLI를 사용하여 요약 알림을 구성하려고 하면 콘솔 로그에 다음 메시지가 기록됩니다. __**_SMSAP-14575: 이 리포지토리에 대한 요약 알림 구성을 사용할 수 없습니다





 a| 
* 프로파일을 업데이트하여 아카이브 로그 파일의 백업을 별도로 만듭니다 *
 a| 
다음 옵션 및 변수를 지정합니다.

** 개별 아카이브 - 백업을 사용하면 아카이브 로그 파일을 데이터베이스 파일과 별도로 백업할 수 있습니다.
+
이 옵션을 지정한 후 데이터 파일 전용 백업이나 아카이브 전용 백업을 만들 수 있습니다. 전체 백업을 생성할 수 없습니다. 또한 백업을 분리하여 프로파일 설정을 되돌릴 수 없습니다. SnapManager는 archivelogs 전용 백업을 수행하기 전에 생성된 백업의 보존 정책을 기반으로 백업을 유지합니다.

** -retain-archivelog-backups는 아카이브 로그 백업의 보존 기간을 설정합니다.
+

NOTE: 처음으로 프로파일을 업데이트하는 경우 -separate-archivelog-backups 옵션을 사용하여 아카이브 로그 백업을 데이터 파일 백업에서 분리할 수 있습니다. -retain-archivelog-backups 옵션을 사용하여 아카이브 로그 백업의 보존 기간을 제공해야 합니다. 나중에 프로파일을 업데이트할 때 보존 기간을 설정하는 것은 선택 사항입니다.

** include-with-online-backups는 아카이브 로그 백업이 데이터베이스 백업과 함께 포함되도록 지정합니다.
** -no-include-with-online-backups는 아카이브 로그 파일 백업이 데이터베이스 백업과 함께 포함되지 않도록 지정합니다.




 a| 
* 대상 데이터베이스의 호스트 이름을 변경합니다. *
 a| 
프로파일의 호스트 이름을 변경하려면 -hostnew_db_host 를 지정합니다.



 a| 
* 프로필 업데이트 작업 후 덤프 파일을 수집합니다 *
 a| 
dump 옵션을 지정합니다.

|===
. 업데이트된 프로파일을 보려면 smsap profile show 명령을 입력합니다


* 관련 정보 *

xref:concept-how-to-collect-dump-files.adoc[덤프 파일을 수집하는 방법]
