---
permalink: windows/task-customizing-e-mail-subject-for-a-new-profile.html 
sidebar: sidebar 
keywords: customize, email, subject, profile, create, cusomtizing 
summary: 새 프로필을 만들 때 이메일 제목을 사용자 지정할 수 있습니다. 
---
= 새 프로필에 대한 이메일 제목 사용자 지정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 프로필을 만들 때 이메일 제목을 사용자 지정할 수 있습니다.

{profile}_\{operation-name}_\{db-sid}_\{db-host}_\{start-date}_\{end-date}_\{status} 패턴을 사용하거나 원하는 텍스트를 입력하여 이메일 제목을 사용자 지정할 수 있습니다.

|===
| 변수 이름 | 설명 | 예제 값 


 a| 
프로파일
 a| 
데이터베이스 작업에 사용되는 프로파일 이름입니다
 a| 
PROF1



 a| 
Operation - 이름입니다
 a| 
데이터베이스 작업 이름입니다
 a| 
백업, 데이터 백업, 데이터 및 아카이브 로그 백업



 a| 
db -sid
 a| 
데이터베이스의 SID입니다
 a| 
DB1



 a| 
DB-호스트
 a| 
호스트 서버의 이름입니다
 a| 
호스트 A



 a| 
시작 날짜
 a| 
mmdd:hh:ss yyyy 형식의 데이터베이스 작업 시작 시간입니다
 a| 
2012년 4월 27일 21:00:45 PST



 a| 
종료 날짜
 a| 
mmdd:hh:ss yyyy 형식의 데이터베이스 작업 종료 시간입니다
 a| 
2012년 4월 27일 21:10:45 PST



 a| 
상태
 a| 
데이터베이스 작업 상태입니다
 a| 
성공

|===
변수에 값을 제공하지 않으면 SnapManager에 누락된 값 - 제목 오류 메시지가 표시됩니다.

. 다음 명령을 입력합니다.
+
smsap profile create -profileprofile[-profile-passwordprofile_password] -repository -dbnamersepo_service_name -hotrestpo_host -portrepo_port -login -dbnamedb_dbname]{usernednemnedername]{usernersamentname=substationuser_username][-login.user_substentname=substentname]{usernemeterm_subtnemeterm_substentname]{usernemetername]{username]{username]{usernepidname=substentname=substentname=substentname]{username=substationname=substationname=subscalm_substationname]{recentname=substationname=subscentname]{recentname]{recentname=substentname]{username=substentname=subscentname=substitename]{recentname=emetitename=substationname=emet


