---
permalink: windows/task-set-credentials-after-clearing-credential-cache.html 
sidebar: sidebar 
keywords: clear, cache, remove, store, user, credential, host, repository, repositories, profile, set 
summary: 캐시를 지워 저장된 사용자 자격 증명을 제거한 후 호스트, 저장소 및 프로필에 대한 자격 증명을 설정할 수 있습니다. 
---
= 자격 증명 캐시를 지운 후 자격 증명을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
캐시를 지워 저장된 사용자 자격 증명을 제거한 후 호스트, 저장소 및 프로필에 대한 자격 증명을 설정할 수 있습니다.



== 이 작업에 대해

이전에 제공한 리포지토리, 프로필 호스트 및 프로필에 대해 동일한 사용자 자격 증명을 설정해야 합니다. 사용자 자격 증명을 설정하는 동안 암호화된 자격 증명 파일이 생성됩니다.

자격 증명 파일은 'C:\Documents and Settings\Administrator\Application Data\NetApp\smsap\3.3.0'에 있습니다.

SnapManager 그래픽 사용자 인터페이스(GUI)에서 리포지터리에 리포지토리가 없는 경우 다음 단계를 수행합니다.

.단계
. 기존 리포지토리를 추가하려면 * 작업 * > * 기존 리포지토리 추가 * 를 클릭합니다.
. 리포지토리에 대한 자격 증명을 설정하려면 다음 단계를 수행하십시오.
+
.. 리포지토리를 마우스 오른쪽 단추로 클릭하고 * 열기 * 를 선택합니다.
.. 리포지터리 자격 증명 인증 창에 사용자 자격 증명을 입력합니다.


. 호스트에 대한 자격 증명을 설정하려면 다음 단계를 수행하십시오.
+
.. 리포지토리 아래에서 호스트를 마우스 오른쪽 버튼으로 클릭하고 * Open * 을 선택합니다.
.. Host Credentials Authentication 창에 사용자 자격 증명을 입력합니다.


. 프로파일에 대한 자격 증명을 설정하려면 다음 단계를 수행하십시오.
+
.. 호스트 아래에서 프로파일을 마우스 오른쪽 단추로 클릭하고 * 열기 * 를 선택합니다.
.. Profile Credentials Authentication 창에서 사용자 자격 증명을 입력합니다.



