---
permalink: windows/task-create-repositories.html 
sidebar: sidebar 
keywords: snapmanager, require, repository, host, data, operation, perform, create 
summary: SnapManager를 사용하려면 호스트에 있는 리포지토리가 수행하는 작업에 대한 데이터를 보류해야 합니다. 
---
= 리포지토리를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용하려면 호스트에 있는 리포지토리가 수행하는 작업에 대한 데이터를 보류해야 합니다.



== 필요한 것

다음 작업이 완료되었는지 확인합니다.

.단계
. 리포지토리 데이터베이스에서 Oracle 사용자 및 암호를 생성합니다.
. 리포지토리에 대한 사용자 액세스 권한을 부여합니다.


저장소의 경우 SnapManager for SAP는 설치된 테이블스페이스에 대해 최소 4K 블록 크기가 필요합니다. 다음 SQL 명령을 사용하여 블록 크기를 확인할 수 있습니다.

[listing]
----
select a.username, a.default_tablespace, b.block_size
from dba_users a, dba_tablespaces b
a.username = repo_user
----
위치

* ' a.default_tablespace = b.tablespace_name'
* "a.username` = 리포지토리의 사용자 이름입니다




== 이 작업에 대해

리포지토리를 업그레이드하는 경우 SnapManager 서버를 다시 부팅하여 연결된 일정을 다시 시작해야 합니다.

.단계
. 리포지토리를 만들려면 리포지토리 생성 명령을 다음 일반 형식으로 입력합니다.
+
"* smsap repository create-repository-dbname_repo_service_name_-host_repo_host_-login-username_repo_username_-port_port_[-force] [-nopmp프롬프트] [-quiet|-verbose] *

+
여기서,

+
** 리포지토리 데이터베이스의 이름은 -repository-dbname입니다.
** '-host'는 리포지토리의 호스트 이름입니다.
** '-username'은 리포지토리에 액세스할 수 있는 데이터베이스 사용자의 이름입니다.
** '-port'는 호스트의 포트입니다. 이 명령의 다른 옵션은 다음과 같습니다.
+
['-force'] ['-nop프롬프트']

+
['quiet'|'-verbose']






NOTE: 같은 이름의 기존 리포지토리가 있고 '-force' 옵션을 사용하는 경우 기존 리포지토리 스키마 내의 모든 데이터를 덮어씁니다.



== 리포지토리를 생성하는 중입니다

다음 명령줄은 리포지토리를 만듭니다.

[listing]
----
smsap repository create -repository -dbname HR1
-host server1 -login -username admin -port 1521
----