---
permalink: windows/task-configure-mail-server-for-a-repository.html 
sidebar: sidebar 
keywords: snapmanager, enable, mail, server, detail, email, alert, configure, repository 
summary: SnapManager를 사용하면 이메일 경고가 전송되는 메일 서버 세부 정보를 지정할 수 있습니다. 
---
= 리포지토리에 대한 메일 서버를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용하면 이메일 경고가 전송되는 메일 서버 세부 정보를 지정할 수 있습니다.



== 이 작업에 대해

SnapManager를 사용하면 보낸 사람의 전자 메일 서버 호스트 이름 또는 IP 주소와 전자 메일 알림이 필요한 저장소 데이터베이스 이름의 전자 메일 서버 포트 번호를 지정할 수 있습니다. 메일 서버 포트 번호는 0에서 65535 사이의 범위로 구성할 수 있습니다. 기본값은 25입니다. 전자 메일 주소에 대한 인증이 필요한 경우 사용자 이름과 암호를 지정할 수 있습니다.

e-메일 알림을 처리하는 호스트 서버의 이름 또는 IP 주소를 지정해야 합니다.

.단계
. 이메일 경고를 보내도록 메일 서버를 구성하려면 다음 명령을 입력합니다.
+
"* smssap notification set-sender-email_email_address_-mailhost_mailport_mailport_[-authentication-username_-password_password_] -repository-port_repo_port_-dbname_repo_service_name_-host_repo_host_-login-username_repo_username_username_username_*

+
이 명령의 다른 옵션은 다음과 같습니다.

+
['-force']

+
['quiet'|'-verbose']

+
|===
| 다음을 수행하려면... | 그러면... 


 a| 
* 을 눌러 발신자의 이메일 주소를 지정합니다. *
 a| 
sender-email 옵션을 지정합니다. SAP용 SnapManager 3.2에서는 전자 메일 주소의 도메인 이름을 지정하는 동안 하이픈(-)을 포함할 수 있습니다. 예를 들어 보낸 사람의 전자 메일 주소를 '+sender-emailuser@org-corp.com+'로 지정할 수 있습니다.



 a| 
발신자의 이메일 서버 호스트 이름 또는 IP 주소를 지정합니다
 a| 
'-mailhost' 옵션을 지정합니다.



 a| 
e-메일 알림을 필요로 하는 리포지토리 데이터베이스 이름의 e-메일 서버 포트 번호를 지정합니다. 메일 서버 포트 번호는 0에서 65535 사이의 범위로 구성할 수 있습니다. 기본값은 25입니다.*
 a| 
'-mailport' 옵션을 지정합니다.



 a| 
* 전자 메일 주소에 대한 인증이 필요한 경우 사용자 이름과 암호를 지정합니다. *
 a| 
사용자 이름 및 암호 뒤에 '-authentication' 옵션을 지정합니다.

|===


다음 예에서는 메일 서버를 구성합니다.

[listing]
----
smsap notification set -sender-email admin1@org.com -mailhost hostname.org.com -mailport 25 authentication -username admin1 -password admin1 -repository -port 1521 -dbname SMSAPREPO -host hotspur -login -username grabal21 -verbose
----