---
permalink: windows/task-prune-archive-log-files.html 
sidebar: sidebar 
keywords: prune, archive, log, file, location, create 
summary: 백업을 생성하는 동안 아카이브 로그 위치에서 아카이브 로그 파일을 정리할 수 있습니다. 
---
= 아카이브 로그 파일을 압축합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업을 생성하는 동안 아카이브 로그 위치에서 아카이브 로그 파일을 정리할 수 있습니다.



== 필요한 것

* 아카이브 로그 파일은 현재 백업 작업에 의해 백업되어야 합니다.
+
보관 로그 파일을 포함하지 않는 다른 백업과 함께 가지치기를 지정하면 보관 로그 파일이 정리되지 않습니다.

* 데이터베이스가 마운트된 상태여야 합니다.
+
데이터베이스가 마운트되지 않은 경우 백업 명령과 함께 '-force' 옵션을 입력합니다.





== 이 작업에 대해

백업 작업을 수행하는 동안 다음을 지정할 수 있습니다.

* 잘라내기 범위:
+
** 모든 아카이브 로그 파일을 삭제합니다.
** 지정된 SCN(시스템 변경 번호)이 될 때까지 아카이브 로그 파일을 삭제합니다.
** 지정된 시간까지 아카이브 로그 파일을 삭제합니다.
** 지정된 기간 전에 아카이브 로그 파일을 삭제합니다.


* 보관 로그 파일을 정리해야 하는 대상.
+

NOTE: 아카이브 로그 파일 잘라내기 작업이 한 대상에서 실패한 경우에도 SnapManager는 계속해서 다른 대상에서 아카이브 로그 파일을 정리합니다.



아카이브 로그 파일을 삭제하기 전에 SnapManager에서 다음 사항을 확인합니다.

* 아카이브 로그 파일은 한 번 이상 백업됩니다.
* 아카이브 로그 파일이 있는 경우 Oracle Dataguard Standby 데이터베이스로 전송됩니다.
* 아카이브 로그 파일은 Oracle Streams 캡처 프로세스(있는 경우)에 의해 캡처됩니다.


아카이브 로그 파일이 백업되고 대기 상태로 배송되며 캡처 프로세스에서 캡처된 경우 SnapManager는 단일 실행 시 모든 아카이브 로그 파일을 삭제합니다. 그러나 백업되지 않았거나 대기 상태로 배송되지 않았거나 캡처 프로세스에서 캡처되지 않은 아카이브 로그 파일이 있는 경우 SnapManager는 아카이브 로그 파일을 하나씩 삭제합니다. 단일 실행 시 아카이브 로그 파일을 삭제하는 것이 아카이브 로그를 하나씩 삭제하는 것보다 빠릅니다.

SnapManager는 아카이브 로그 파일을 그룹화하고 일괄 처리별로 삭제할 수도 있습니다. 각 배치에는 최대 998개의 파일이 있습니다. 이 값은 'msap.config' 파일의 구성 매개 변수 mixum.archivelog.files.toprune.atATime을 사용하여 998 미만으로 구성할 수 있습니다.

SnapManager는 Oracle RMAN(Recovery Manager) 명령을 사용하여 아카이브 로그 파일을 삭제합니다. 그러나 SnapManager는 RMAN 보존 정책 및 삭제 정책과 통합되지 않습니다.


NOTE: 보관 로그 대상에서 보관 로그 파일을 삭제하면 보관 로그 파일을 가지치기는 실패합니다.

SnapManager는 다음 시나리오에서 아카이브 로그 파일 정리를 지원하지 않습니다.

* 아카이브 로그 파일은 플래시 복구 영역에 있습니다.
* 아카이브 로그 파일은 대기 데이터베이스에 있습니다.
* 아카이브 로그 파일은 SnapManager 및 RMAN에서 모두 관리합니다.


.단계
. 다음 명령을 입력합니다.
+
``smssap backup create-profile_name_{[-full{-online|-offline|-auto}[-retain {-hourly|[-daily|-weekly|-monthly|-limited}][-verify]|[-data[[- files_files_[_files_]]]|[-tablespaces_[_- tablespaces_- weekly_databel_auto_calletablespaces]-{auto-weekly_databel_callel_date-offline]-{auto-online]-{data-date-date-online]{data-date- [-archivelogs [-label_label_] [-comment_comment_] [-backup-dest_path1_[,[_path2_]]] [-exclude-dest_path1_[,_path2_]]] [-prelogs{-all|-undest_unes_yyyy_vunnune] v.. days [caskvune_yyyy_hunm_hunm_hunm_days] _ v.

+
|===
| 원하는 작업 | 그러면... 


 a| 
* 아카이브 로그 파일 정리 *
 a| 
다음 옵션을 지정합니다.

** '-prunelogs'는 백업을 생성하는 동안 아카이브 로그 파일을 삭제하도록 지정합니다.
+
*** '-ALL'은 모든 보관 로그 파일을 삭제하도록 지정합니다.
*** '-untilscn'은 지정된 SCN이 될 때까지 보관 로그 파일 삭제를 지정합니다.
*** '-until-date'는 지정된 날짜 및 시간을 포함하여 아카이브 로그를 삭제하도록 지정합니다.
*** '-before'{-months-days-weeks-hours}는 지정된 기간 전에 아카이브 로그 파일을 삭제하도록 지정합니다.






 a| 
* 보관 로그 파일을 정리할 대상을 포함합니다 *
 a| 
'-prune-dest' 옵션을 지정합니다.

|===

