---
permalink: unix-administration/concept-creating-task-specification-file-and-scripts-for-snapmanager-operations.html 
sidebar: sidebar 
keywords: snapmanager, sap, task, specification, extensible, markup, language, xml, pretask, backup, restore, clone, operation, creating, create, file, script, operation 
summary: 'SnapManager for SAP는 백업, 복원 및 클론 작업의 사전 작업 및 사후 작업을 나타내는 작업 사양 XML(Extensible Markup Language) 파일을 사용합니다. 백업, 복원 및 클론 작업 전후에 수행할 작업에 대한 사전 작업 및 사후 작업 스크립트 이름을 XML 파일에 추가할 수 있습니다.' 
---
= SnapManager 작업에 대한 작업 사양 파일 및 스크립트를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for SAP는 백업, 복원 및 클론 작업의 사전 작업 및 사후 작업을 나타내는 작업 사양 XML(Extensible Markup Language) 파일을 사용합니다. 백업, 복원 및 클론 작업 전후에 수행할 작업에 대한 사전 작업 및 사후 작업 스크립트 이름을 XML 파일에 추가할 수 있습니다.

SnapManager(3.1 이하)에서는 클론 작업에 대해서만 사전 작업 및 사후 작업 스크립트를 실행할 수 있습니다. SAP용 SnapManager(3.2 이상)에서는 백업, 복원 및 클론 작업을 위한 사전 작업 스크립트와 사후 작업 스크립트를 실행할 수 있습니다.

SnapManager(3.1 이하)에서 작업 사양 섹션은 클론 사양 XML 파일의 일부입니다. SAP용 SnapManager 3.2에서 작업 사양 섹션은 별도의 XML 파일입니다.


NOTE: SnapManager 3.3 이상은 SnapManager 3.2 이전 릴리즈에서 생성한 클론 사양 XML 파일의 사용을 지원하지 않습니다.

SAP용 SnapManager(3.2 이상)에서는 성공적인 SnapManager 작업을 위해 다음 조건이 충족되는지 확인해야 합니다.

* 백업 및 복원 작업의 경우 작업 사양 XML 파일을 사용합니다.
* 클론 작업의 경우 클론 사양 XML 파일과 작업 사양 XML 파일의 두 가지 사양 파일을 제공합니다.
+
사전 작업 또는 사후 작업 활동을 활성화하려면 작업 사양 XML 파일을 선택적으로 추가할 수 있습니다.



SnapManager 그래픽 사용자 인터페이스(GUI), 명령줄 인터페이스(CLI) 또는 텍스트 편집기를 사용하여 작업 사양 파일을 생성할 수 있습니다. 적절한 편집 기능을 사용하려면 파일에 .xml 확장명을 사용해야 합니다. 나중에 백업, 복원 및 클론 작업에 사용할 수 있도록 이 파일을 저장할 수 있습니다.

작업 사양 XML 파일에는 다음 두 섹션이 포함되어 있습니다.

* 사전 작업 섹션에는 백업, 복원 및 클론 작업 전에 실행할 수 있는 스크립트가 포함되어 있습니다.
* 사후 작업 섹션에는 백업, 복원 및 클론 작업 이후에 실행할 수 있는 스크립트가 포함되어 있습니다.


사전 작업 및 사후 작업 섹션에 포함된 값은 다음 지침을 준수해야 합니다.

* 태스크 이름: 태스크의 이름은 스크립트 이름과 일치해야 하며, 이 스크립트는 'plugin.sh-t설명해' 명령을 실행할 때 표시됩니다.
+

NOTE: 일치하지 않는 경우 '파일을 찾을 수 없습니다'라는 오류 메시지가 나타날 수 있습니다.

* 매개 변수 이름: 매개 변수의 이름은 환경 변수 설정으로 사용할 수 있는 문자열이어야 합니다.
+
문자열은 사용자 정의 스크립트의 매개 변수 이름과 일치해야 하며, 이 이름은 'plugin.sh -기술식' 명령을 실행할 때 표시됩니다.



다음 샘플 작업 사양 파일의 구조를 기반으로 사양 파일을 만들 수 있습니다.

[listing]
----

<task-specification>
  <pre-tasks>
<task>
      <name>name</name>
      <parameter>
          <name>name</name>
          <value>value</value>
       </parameter>
    </task>
  </pre-tasks>
  <post-tasks>
    <task>
      <name>name</name>
      <parameter>
          <name>name</name>
          <value>value</value>
       </parameter>
    </task>
  </post-tasks>
</task-specification>
----

NOTE: 작업 사양 XML 파일에는 정책이 포함되어 있지 않아야 합니다.

SnapManager GUI에서 매개 변수 값을 설정하고 XML 파일을 저장할 수 있습니다. 백업 생성 마법사, 복구 또는 복구 마법사 및 클론 생성 마법사의 작업 설정 페이지를 사용하여 기존 작업 사양 XML 파일을 로드하고 사전 작업 또는 사후 작업 작업에 선택한 파일을 사용할 수 있습니다.

작업은 동일하거나 다른 매개 변수 및 값 조합으로 여러 번 실행할 수 있습니다. 예를 들어 저장 작업을 사용하여 여러 파일을 저장할 수 있습니다.


NOTE: SnapManager는 작업 사양 파일의 파일 확장자에 관계없이 백업, 복원 및 클론 작업에 대한 전처리 또는 사후 처리 작업에 대해 작업 사양 파일에 제공된 XML 태그를 사용합니다.
