---
permalink: unix-administration/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, role-base, access, control, rbac, credential, management 
summary: '사용자 인증 및 RBAC(역할 기반 액세스 제어)를 적용하여 SnapManager에서 보안을 관리할 수 있습니다. 사용자 인증 방법을 사용하면 저장소, 호스트 및 프로필과 같은 리소스에 액세스할 수 있습니다. RBAC에서는 SnapManager가 데이터베이스의 데이터 파일이 포함된 볼륨 및 LUN에 대해 수행할 수 있는 작업을 제한할 수 있습니다.' 
---
= 보안 및 자격 증명 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 인증 및 역할 기반 액세스 제어(RBAC)를 적용하여 SnapManager에서 보안을 관리할 수 있습니다. 사용자 인증 방법을 사용하면 저장소, 호스트 및 프로필과 같은 리소스에 액세스할 수 있습니다. RBAC에서는 SnapManager가 데이터베이스의 데이터 파일이 포함된 볼륨 및 LUN에 대해 수행할 수 있는 작업을 제한할 수 있습니다.

CLI(Command-Line Interface) 또는 GUI(그래픽 사용자 인터페이스)를 사용하여 작업을 수행할 때 SnapManager는 리포지토리 및 프로파일에 대해 설정된 자격 증명을 검색합니다. SnapManager는 이전 설치의 자격 증명을 저장합니다.

리포지토리와 프로필은 암호로 보호할 수 있습니다. 자격 증명은 개체에 대해 사용자에 대해 구성된 암호이며 암호는 개체 자체에 구성되어 있지 않습니다.

다음 작업을 수행하여 인증 및 자격 증명을 관리할 수 있습니다.

* 운용에 대한 비밀번호 프롬프트나 'msap credentential set' 명령어를 이용하여 사용자 인증을 관리한다.
+
리포지토리, 호스트 또는 프로파일에 대한 자격 증명을 설정합니다.

* 액세스 권한이 있는 리소스를 제어하는 자격 증명을 봅니다.
* 모든 리소스(호스트, 리포지토리 및 프로필)에 대한 사용자 자격 증명을 지웁니다.
* 개별 리소스(호스트, 리포지토리 및 프로필)에 대한 사용자의 자격 증명을 삭제합니다.


다음 작업을 수행하여 역할 기반 액세스를 관리할 수 있습니다.

* SnapDrive를 사용하여 SnapManager에 대해 RBAC를 사용하도록 설정합니다.
* Operations Manager 콘솔을 사용하여 사용자를 역할에 할당하고 역할 기능을 설정합니다.
* 필요에 따라 SnapManager에서 'msap.config 파일'을 편집하여 암호화된 암호를 저장할 수 있습니다.


Protection Manager를 설치한 경우 다음과 같은 방법으로 기능에 액세스할 수 있습니다.

* Protection Manager가 설치되어 있는 경우 데이터베이스 프로필을 생성할 때 SnapManager는 데이터 세트를 생성하고 데이터베이스 파일이 포함된 볼륨으로 데이터 세트를 채웁니다.
+
백업 작업 후 SnapManager는 데이터 세트 컨텐츠를 데이터베이스 파일과 동기화된 상태로 유지합니다.

* Protection Manager가 설치되어 있지 않으면 SnapManager에서 데이터 세트를 생성할 수 없으며 프로파일에 대한 보호를 설정할 수 없습니다.

