---
permalink: unix-administration/concept-workflow-summary-for-local-and-secondary-database-backup.html 
sidebar: sidebar 
keywords: dba, snapmanager, storage, administrator, netapp, management, console, data, protection, capability, local, backup, protect, database, target, workflow, summary, local, secondary, backup 
summary: '이 예에서 DBA(SnapManager 사용) 및 스토리지 관리자(NetApp 관리 콘솔 데이터 보호 기능 사용)는 타겟 데이터베이스의 로컬 백업 및 보조 백업(보호 백업이라고도 함)을 구성하기 위한 작업을 조정합니다.' 
---
= 로컬 및 보조 데이터베이스 백업에 대한 워크플로우 요약
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 예에서 DBA(SnapManager 사용) 및 스토리지 관리자(NetApp 관리 콘솔 데이터 보호 기능 사용)는 타겟 데이터베이스의 로컬 백업 및 보조 백업(보호 백업이라고도 함)을 구성하기 위한 작업을 조정합니다.

수행된 작업의 순서는 다음과 같이 요약됩니다.

* * 보조 리소스 풀 구성 *
+
스토리지 관리자는 NetApp Management Console 데이터 보호 기능을 사용하여 급여 데이터베이스 백업을 저장하는 데 사용할 수 있는 보조 사이트에서 스토리지 시스템의 리소스 풀을 구성합니다.

* * 보조 백업 스케줄링 *
+
스토리지 관리자는 NetApp Management Console 데이터 보호 기능을 사용하여 보조 백업 일정을 구성합니다.

* * 보호 정책 구성 *
+
스토리지 관리자는 NetApp Management Console 데이터 보호 기능을 사용하여 타겟 데이터베이스에 대한 보조 백업 보호 정책을 구성합니다. 보호 정책에는 스케줄이 포함되며, 백업 보호 기능을 구현할 기본 보호 유형(백업, 미러 또는 둘 다 조합)을 지정하고 운영 데이터, 2차 스토리지 및 때로는 3차 스토리지 노드에 대한 보존 정책의 이름을 지정합니다.

* * 데이터베이스 프로파일 구성 및 보호 정책 할당 *
+
DBA는 SnapManager를 사용하여 보조 백업을 지원하는 타겟 데이터베이스의 프로필을 만들거나 편집합니다. 프로파일을 구성하는 동안 DBA는 다음을 수행합니다.

+
** 보조 스토리지에 대한 백업 보호를 활성화합니다.
** NetApp Management Console 데이터 보호 기능에서 생성 및 검색된 새 보호 정책을 이 프로필에 할당합니다.
+
보호 정책을 할당하면 타겟 데이터베이스가 부분적으로 프로비저닝되었지만 NetApp Management Console 데이터 보호 기능 데이터 세트를 준수하지 않는 경우 자동으로 포함됩니다. 완전히 프로비저닝되면 데이터 세트 구성을 통해 타겟 데이터베이스를 보조 스토리지에 백업할 수 있습니다.

+
데이터 세트 이름은 '_smsap_hostname_databasename_' 구문을 사용합니다. 이 구문은 "smsap_prod01.sample.com_p01" 으로 변환됩니다.



* * 2차 및 3차 스토리지 프로비저닝 *
+
스토리지 관리자는 NetApp Management Console 데이터 보호 기능을 사용하여 리소스 풀을 할당하여 2차 및 때로는 3차 스토리지 노드를 프로비저닝합니다(할당된 보호 정책에서 3차 스토리지 노드를 지정하는 경우).

* * 로컬 스토리지에 백업 *
+
DBA는 SnapManager에서 보호 기능이 설정된 프로파일을 열고 로컬 스토리지에 대한 전체 백업을 생성합니다. 새 백업이 SnapManager에 보호 스케줄로 표시되지만 아직 보호되지 않은 것으로 표시됩니다.

* * 보조 백업 확인 *
+
백업이 보호 설정 프로파일을 기반으로 하기 때문에 보호 정책의 스케줄에 따라 보조 백업으로 전송됩니다. DBA는 SnapManager를 사용하여 보조 스토리지에 대한 백업 전송 지연을 확인합니다. 백업이 보조 스토리지에 복제된 후 SnapManager는 백업 보호 상태를 "보호되지 않음"에서 "보호됨"으로 변경합니다.


