---
permalink: unix-administration/concept-full-online-backups.html 
sidebar: sidebar 
keywords: full, online, backup, snapmanager, database, create, snapshot, copies, copy, volume, level, tablespace 
summary: 전체 온라인 백업 중에 SnapManager는 전체 데이터베이스를 백업하고 테이블스페이스 레벨이 아닌 볼륨 레벨에서 스냅샷 복사본을 생성합니다. 
---
= 전체 온라인 백업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전체 온라인 백업 중에 SnapManager는 전체 데이터베이스를 백업하고 테이블스페이스 레벨이 아닌 볼륨 레벨에서 스냅샷 복사본을 생성합니다.

SnapManager은 각 백업에 대해 2개의 스냅샷 복사본을 생성합니다. 데이터베이스에 필요한 모든 파일이 단일 볼륨에 있으면 두 스냅샷 복사본이 해당 볼륨에 나타납니다.

전체 백업을 지정할 때 SnapManager는 다음 작업을 수행합니다.

. 전체 데이터베이스를 온라인 백업 모드로 설정합니다
. 데이터베이스 파일이 포함된 모든 볼륨의 스냅샷 복사본을 생성합니다
. 데이터베이스를 온라인 백업 모드에서 해제합니다
. 로그 스위치를 강제 실행한 다음 로그 파일을 보관합니다
+
또한 REDO 정보를 디스크로 플러시합니다.

. 백업 제어 파일을 생성합니다
. 로그 파일 및 백업 제어 파일의 스냅샷 복사본을 생성합니다


전체 백업을 수행할 때 SnapManager는 전체 데이터베이스를 온라인 백업 모드로 전환합니다. 개별 테이블스페이스(예: '/oracle/cer/sapdata1/system_1/system.data1')는 지정된 특정 테이블스페이스 또는 데이터 파일보다 긴 온라인 백업 모드에 있습니다.

데이터베이스가 백업 모드로 전환될 때 Oracle은 전체 블록을 로그에 기록하고 백업 사이에 델타를 쓰는 역할만 하지 않습니다. 데이터베이스는 온라인 백업 모드에서 더 많은 작업을 수행하므로 전체 백업을 선택하면 호스트에 더 많은 로드가 수행됩니다.

전체 백업을 수행할 경우 호스트에 로드가 더 많이 있지만 전체 백업을 수행할 경우 Snapshot 복사본이 더 적게 필요하므로 스토리지 요구사항이 감소합니다.
