---
permalink: unix-administration/concept-fast-restore-eligibility-checks.html 
sidebar: sidebar 
keywords: perform, restore, backup, snapmanager, eligibility, check, fast 
summary: 신속한 백업 복원을 수행하도록 선택하면 SnapManager에서는 먼저 자격 검사를 수행하여 빠른 복원 프로세스를 사용할 수 있는지 여부를 확인합니다. 
---
= 빠른 복구 적격성 검사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
신속한 백업 복원을 수행하도록 선택하면 SnapManager에서는 먼저 자격 검사를 수행하여 빠른 복원 프로세스를 사용할 수 있는지 여부를 확인합니다.

SnapManager에서는 다음과 같은 검사 유형을 제공합니다.

* 필수 검사: SnapManager는 이 확인 하의 모든 조건이 통과한 경우에만 빠른 복원 프로세스를 수행할 수 있습니다.
* Overridable check: 이 검사 조건이 실패할 경우 관리자는 검사를 재정의하여 빠른 복원 프로세스를 강제로 수행할 수 있습니다. 그러나 이러한 점검은 신중하게 재정의해야 합니다.


다음 표에는 발생할 수 있는 문제와 빠른 복구 적격성 검사를 재정의할 수 있는지 여부가 나와 있습니다.

|===
| 문제 | Pass 필수 요소입니다 | 세부 정보 


 a| 
ACFS, 보팅 디스크 또는 OCR은 11gR2의 ASM 디스크 그룹에 있습니다
 a| 
예
 a| 
빠른 복원을 수행할 수 없습니다. 해상도: 없음

재정의할 수 없습니다.



 a| 
SnapManager 3.0 이상에서 생성된 백업만 빠르게 복원할 수 있습니다
 a| 
예
 a| 
재정의할 수 없습니다.



 a| 
UNIX용 SnapDrive 4.0 이상에서 생성된 스냅샷 복사본만 빠르게 복원할 수 있습니다
 a| 
예
 a| 
재정의할 수 없습니다.



 a| 
볼륨은 루트 볼륨입니다
 a| 
예
 a| 
복구 중인 볼륨은 스토리지 시스템의 루트 볼륨입니다. 해결 방법: 스토리지 시스템에서 루트 볼륨을 사용하지 마십시오.

재정의할 수 없습니다.



 a| 
Windows에서는 볼륨 복원을 사용할 수 없습니다
 a| 
예
 a| 
복구 중인 볼륨은 스토리지 시스템의 루트 볼륨입니다. 해상도: 없음

재정의할 수 없습니다.



 a| 
볼륨 복원이 비활성화되어 있습니다
 a| 
예
 a| 
볼륨 복원이 비활성화되었습니다. 해상도: 복원을 시작할 때 다른 옵션을 선택하여 볼륨 복원을 활성화합니다. 명령줄 인터페이스에서는 -fast-off를 사용하지 마십시오.

재정의할 수 없습니다.



 a| 
동일한 볼륨에 있는 파일 및 데이터 파일을 제어합니다
 a| 
예
 a| 
온라인 백업의 경우, SnapManager는 볼륨의 스냅샷 복사본 2개를 가져가기 때문에 제어 파일과 데이터 파일이 같은 볼륨에 있을 수 없습니다. 하나는 핫 백업 모드에서 데이터 파일이 정합성이 보장되는 복사본입니다. 그리고 핫 백업 모드가 완료된 후 백업 제어 파일의 정합성이 유지되는 파일). 볼륨 복원은 첫 번째 스냅샷 복사본으로 복원되며, 이 복사본은 백업 제어 파일이 포함된 두 번째 스냅샷 복사본을 삭제합니다. 데이터 파일 전용 복원이 발생하면 제어 파일은 일관성 없는 상태로 되돌려지고 SnapManager는 백업 제어 파일을 복원한 다음 원하는 동작이 아닌 resetlogs 옵션을 사용하여 데이터베이스를 엽니다.

해결 방법: 동일한 기본 볼륨을 공유하지 않는 별도의 파일 시스템으로 제어 파일 및 데이터 파일을 마이그레이션합니다. 이렇게 하면 검사에 실패한 복원이 도움이 되지 않지만 이후의 백업 복원 작업에 도움이 됩니다.

재정의할 수 없습니다.



 a| 
아카이브 로그 및 데이터 파일이 동일한 볼륨에 없어야 합니다
 a| 
예
 a| 
데이터베이스 아카이브 로그 및 데이터 파일은 동일한 스토리지 시스템 볼륨이 지원하는 파일 시스템에 상주합니다. 볼륨 복원이 수행된 경우 데이터베이스가 핫 백업 모드에서 벗어난 후에 기록된 아카이브 로그 파일을 사용할 수 없기 때문에 SnapManager는 온라인 백업 복원 후 데이터베이스를 열 수 없습니다. 또한 아카이브 로그 파일에 있을 수 있는 이후의 트랜잭션을 롤포워드할 수 없습니다.

해결 방법: 동일한 기본 스토리지 시스템 볼륨을 공유하지 않는 별도의 파일 시스템으로 아카이브 로그 및 데이터 파일을 마이그레이션합니다. 이렇게 하면 검사에 실패한 복원이 도움이 되지 않지만 이후의 백업 복원 작업에 도움이 됩니다.

재정의할 수 없습니다.



 a| 
온라인 로그 및 데이터 파일이 동일한 볼륨에 없어야 합니다
 a| 
예
 a| 
데이터베이스 온라인 redo 로그 및 데이터 파일은 동일한 스토리지 시스템 볼륨이 지원하는 파일 시스템에 상주합니다. 볼륨 복원이 수행된 경우 복구에서는 되돌려질 수 있으므로 온라인 redo 로그를 사용할 수 없습니다.

해결 방법: 온라인 redo 로그 및 데이터 파일을 동일한 기본 스토리지 시스템 볼륨을 공유하지 않는 별도의 파일 시스템으로 마이그레이션합니다. 이렇게 하면 검사에 실패한 복원이 도움이 되지 않지만 이후의 백업 복원 작업에 도움이 됩니다.

재정의할 수 없습니다.



 a| 
복구 범위에 포함되지 않은 파일 시스템의 파일은 되돌려집니다
 a| 
예
 a| 
복구 중인 파일 이외의 호스트에 표시되는 파일은 볼륨의 파일 시스템에 있습니다. 빠른 복구나 스토리지 측 파일 시스템 복원이 수행된 경우 스냅샷 복사본이 생성될 때 호스트에 표시되는 파일이 원래 콘텐츠로 되돌아갑니다. SnapManager에서 20개 이하의 파일을 검색할 경우 해당 파일이 적격성 검사 목록에 표시됩니다. 그렇지 않으면 SnapManager에서 파일 시스템을 조사해야 한다는 메시지를 표시합니다.

해결 방법: 데이터베이스에서 사용하지 않는 파일을 다른 볼륨을 사용하는 다른 파일 시스템으로 마이그레이션합니다. 또는 파일을 삭제합니다.

SnapManager에서 파일 용도를 확인할 수 없는 경우 검사 실패를 재정의할 수 있습니다. 검사를 재정의하면 복원 범위에 없는 파일이 되돌려집니다. 파일을 되돌려도 어떤 것도 영향을 받지 않는다는 확신이 있는 경우에만 이 검사를 무시합니다.



 a| 
복구 범위에 포함되지 않은 지정된 볼륨 그룹의 파일 시스템이 되돌려집니다
 a| 
아니요
 a| 
여러 파일 시스템이 동일한 볼륨 그룹에 있지만 모든 파일 시스템을 복구해야 하는 것은 아닙니다. 볼륨 그룹에서 사용하는 LUN에는 모든 파일 시스템의 데이터가 포함되어 있으므로 스토리지 측 파일 시스템 복구 및 빠른 복구를 사용하여 볼륨 그룹 내의 개별 파일 시스템을 복구할 수 없습니다. 빠른 복구 또는 스토리지 측 파일 시스템 복구를 사용하려면 볼륨 그룹 내의 모든 파일 시스템을 동시에 복구해야 합니다. SnapManager에서 20개 이하의 파일을 검색할 경우 SnapManager에서 해당 파일을 적격성 검사 목록에 표시합니다. 그렇지 않으면 SnapManager에서 파일 시스템을 조사해야 한다는 메시지를 표시합니다.

해결 방법: 데이터베이스에서 사용하지 않는 파일을 다른 볼륨 그룹으로 마이그레이션합니다. 또는 볼륨 그룹에서 파일 시스템을 삭제합니다.

재정의할 수 있습니다.



 a| 
복구 범위에 포함되지 않은 지정된 볼륨 그룹의 호스트 볼륨은 되돌려집니다
 a| 
아니요
 a| 
여러 호스트 볼륨(논리 볼륨)이 동일한 볼륨 그룹에 있지만 모든 호스트 볼륨을 복구해야 하는 것은 아닙니다. 이 검사는 볼륨 그룹의 다른 호스트 볼륨이 호스트의 파일 시스템으로 마운트되지 않은 경우를 제외하고 복원 범위에 포함되지 않은 볼륨 그룹의 파일 시스템과 유사합니다. 해결 방법: 데이터베이스에서 사용하는 호스트 볼륨을 다른 볼륨 그룹으로 마이그레이션합니다. 또는 볼륨 그룹의 다른 호스트 볼륨을 삭제합니다.

검사를 재정의하면 볼륨 그룹의 모든 호스트 볼륨이 복원됩니다. 다른 호스트 볼륨을 되돌리더라도 부정적인 영향을 주지 않는다는 확신이 있을 경우에만 이 검사를 재정의합니다.



 a| 
마지막 백업 이후 파일 익스텐트가 변경되었습니다
 a| 
예
 a| 
재정의할 수 없습니다.



 a| 
복원 범위에 포함되지 않은 볼륨의 매핑된 LUN은 되돌려집니다
 a| 
예
 a| 
볼륨에서 복구하도록 요청된 LUN 이외의 LUN은 현재 호스트에 매핑되어 있습니다. 이러한 LUN을 사용하는 다른 호스트 또는 애플리케이션이 불안정해지기 때문에 볼륨 복구를 수행할 수 없습니다. LUN 이름이 밑줄과 정수 인덱스(예: _0 또는 _1)로 끝나는 경우 이러한 LUN은 일반적으로 동일한 볼륨 내의 다른 LUN의 클론입니다. 데이터베이스의 다른 백업이 마운트되었거나 다른 백업의 클론이 있을 수 있습니다.

해결 방법: 데이터베이스에서 사용하지 않는 LUN을 다른 볼륨으로 마이그레이션합니다. 매핑된 LUN이 클론인 경우 데이터베이스의 동일한 데이터베이스 또는 클론의 마운트된 백업을 찾고 백업을 마운트 해제하거나 클론을 제거합니다.

재정의할 수 없습니다.



 a| 
복구 범위에 포함되지 않은 볼륨의 매핑되지 않은 LUN을 되돌렸습니다
 a| 
아니요
 a| 
볼륨에서 복구하도록 요청된 LUN 이외의 LUN이 있습니다. 이러한 LUN은 현재 어떤 호스트에도 매핑되지 않으므로 복원해도 활성 프로세스는 중단되지 않습니다. 그러나 LUN은 일시적으로 매핑 해제될 수 있습니다. 해결 방법: 데이터베이스에서 사용하지 않는 LUN을 다른 볼륨으로 마이그레이션하거나 LUN을 삭제합니다.

이 확인을 재정의하는 경우 볼륨 복원에서 해당 LUN을 스냅샷 복사본이 생성된 상태로 되돌립니다. 스냅샷 복사본을 생성할 때 LUN이 없으면 볼륨 복원 후 LUN이 존재하지 않습니다. LUN을 되돌리더라도 부정적인 영향을 미치지 않는다는 것이 확실한 경우에만 이 확인을 재정의합니다.



 a| 
볼륨의 스냅샷 복사본에 있는 LUN은 되돌릴 때 일관되지 않을 수 있습니다
 a| 
아니요
 a| 
스냅샷 복사본을 생성하는 동안 스냅샷 복사본이 요청된 LUN 이외의 LUN이 볼륨에 존재했습니다. 이러한 다른 LUN은 정합성 보장 상태가 아닐 수 있습니다. 해결 방법: 데이터베이스에서 사용하지 않는 LUN을 다른 볼륨으로 마이그레이션하거나 LUN을 삭제합니다. 이 방법은 검사가 실패한 복구 프로세스에 도움이 되지 않지만 LUN이 이동 또는 삭제된 후에 수행된 향후 백업을 복원하는 데 도움이 됩니다.

이 확인을 재정의하는 경우 LUN은 스냅샷 복사본이 생성된 비일관성 있는 상태로 돌아갑니다. LUN을 되돌리더라도 부정적인 영향을 미치지 않는다는 것이 확실한 경우에만 이 확인을 재정의합니다.



 a| 
새 스냅샷 복사본에는 볼륨 클론이 있습니다
 a| 
예
 a| 
스냅샷 복사본의 복원이 요청된 후 생성된 스냅샷 복사본의 클론을 생성했습니다. 볼륨 복원으로 이후 스냅샷 복사본이 삭제되며 해당 스냅샷 복사본이 클론인 경우 해당 복사본을 삭제할 수 없으므로 볼륨 복원을 수행할 수 없습니다. 해결 방법: 이후 스냅샷 복사본의 클론을 삭제합니다.

재정의할 수 없습니다.



 a| 
새 백업이 마운트되었습니다
 a| 
예
 a| 
백업이 복구된 후 생성된 백업이 마운트됩니다. 볼륨 복원으로 인해 이후 스냅샷 복사본이 삭제되므로, 클론을 가지고 있는 스냅샷 복사본은 삭제할 수 없고, 백업 마운트 작업에서 클론 복제된 스토리지가 생성되고, 볼륨 복원을 수행할 수 없습니다. 해결 방법: 이후 백업을 마운트 해제 또는 마운트된 백업 이후에 수행된 백업에서 복구

재정의할 수 없습니다.



 a| 
최신 백업의 클론이 존재합니다
 a| 
예
 a| 
백업이 복구된 후 생성된 백업의 클론이 생성됩니다. 볼륨 복원으로 인해 이후 스냅샷 복사본이 삭제되고 해당 스냅샷 복사본이 클론으로 포함되어 있는 경우에는 삭제할 수 없으므로 볼륨 복원을 수행할 수 없습니다. 해결 방법: 최신 백업의 클론을 삭제하거나 클론이 있는 백업 이후에 수행된 백업에서 복원합니다.

재정의할 수 없습니다.



 a| 
볼륨의 새 스냅샷 복사본이 손실됩니다
 a| 
아니요
 a| 
볼륨 복구를 수행하면 볼륨이 복원되는 스냅샷 복사본 이후에 생성된 모든 스냅샷 복사본이 삭제됩니다. SnapManager에서 나중에 스냅샷 복사본을 동일한 프로필의 SnapManager 백업에 다시 매핑할 수 있는 경우 "새 백업이 확보되거나 삭제됨" 메시지가 나타납니다. SnapManager에서 나중에 동일한 프로필의 SnapManager 백업에 스냅샷 복사본을 다시 매핑할 수 없는 경우 이 메시지가 나타나지 않습니다. 해결 방법: 이후 백업에서 복원하거나 이후 스냅샷 복사본을 삭제합니다.

재정의할 수 있습니다.



 a| 
새 백업이 해제되거나 삭제됩니다
 a| 
아니요
 a| 
볼륨 복원을 수행하면 볼륨이 복원되고 있는 스냅샷 복사본 이후에 생성된 모든 스냅샷 복사본이 삭제됩니다. 따라서 복구 중인 백업 이후에 생성된 모든 백업은 삭제되거나 해제됩니다. 이후 백업은 다음 시나리오에서 삭제됩니다.

* 백업 상태가 보호되지 않습니다
* Stain.al방식 FreeExpiredBackups는 smsap.config의 * false * 입니다


이후의 백업은 다음 시나리오에서 확보됩니다.

* 백업 상태가 보호되어 있습니다
* Stain.al방식 FreeExpiredBackups는 smsap.config에서 true인 * false * 입니다


해결 방법: 이후 백업에서 복원하거나 이후 백업을 사용 가능 또는 삭제합니다.

이 검사를 재정의하면 복구 중인 백업 이후에 생성된 백업이 삭제되거나 해제됩니다.



 a| 
볼륨의 SnapMirror 관계가 손실됩니다
 a| 
예(RBAC가 비활성화되어 있거나 RBAC 권한이 없는 경우)
 a| 
SnapMirror 관계의 기본 스냅샷 복사본 이전으로 볼륨을 스냅샷 복사본으로 복원하면 관계가 소멸됩니다. 해결 방법: 관계의 기본 스냅샷 복사본 후에 생성된 백업에서 복원합니다. 또는 스토리지 관계를 수동으로 분리한 다음 복원이 완료된 후 관계를 다시 생성하여 기준을 다시 설정합니다.

RBAC가 활성화되어 있고 RBAC 권한이 있는 경우 를 재정의할 수 있습니다.



 a| 
빠른 복원 프로세스가 발생하면 볼륨에 대한 SnapVault 관계가 손실됩니다
 a| 
예(RBAC가 비활성화되어 있거나 RBAC 권한이 없는 경우)
 a| 
SnapVault 관계의 기본 스냅샷 복사본 이전으로 볼륨을 스냅샷 복사본으로 복원하면 관계가 소멸됩니다. 해결 방법: 관계의 기본 스냅샷 복사본 후에 생성된 백업에서 복원합니다. 또는 스토리지 관계를 수동으로 분리한 다음 복원이 완료된 후 관계를 다시 생성하여 기준을 다시 설정합니다.

RBAC가 활성화되어 있고 RBAC 권한이 있는 경우 재정의할 수 없습니다.



 a| 
복원 범위에 포함되지 않은 볼륨의 NFS 파일은 되돌려집니다
 a| 
아니요
 a| 
스토리지 시스템 볼륨에 있는 파일은 호스트에 표시되지 않으며 볼륨 복구를 수행하면 되돌려집니다. 해결 방법: 데이터베이스에서 사용하지 않는 파일을 다른 볼륨으로 마이그레이션하거나 파일을 삭제합니다.

재정의할 수 있습니다. 이 검사 실패를 덮어쓰면 LUN이 삭제됩니다.



 a| 
볼륨에 대한 CIFS 공유가 있습니다
 a| 
아니요
 a| 
복구 중인 볼륨에 CIFS 공유가 있습니다. 다른 호스트가 볼륨 복원 중에 볼륨의 파일에 액세스하고 있을 수 있습니다. 해결 방법: 불필요한 CIFS 공유를 제거합니다.

재정의할 수 있습니다.



 a| 
대체 위치에서 복원 중입니다
 a| 
예
 a| 
대체 위치에서 파일을 복구하도록 지정하는 복원 작업에 대한 복구 사양이 제공되었습니다. 호스트 측 복사 유틸리티만 대체 위치에서 복원할 수 있습니다.

해상도: 없음.

재정의할 수 없습니다.



 a| 
RAC 데이터베이스에서는 스토리지 측 파일 시스템 복원이 지원되지 않습니다
 a| 
예
 a| 
재정의할 수 없습니다.

|===