---
permalink: unix-administration/concept-understanding-enabling-or-disabling-of-data-protection-in-profile.html 
sidebar: sidebar 
keywords: enable, disable, data, protection, creating, create, update, updating, database, profile, understand, enabling, disabling 
summary: 데이터베이스 프로파일을 만들거나 업데이트하는 동안 데이터 보호를 설정하거나 해제할 수 있습니다. 
---
= 프로파일에서 데이터 보호 활성화 또는 비활성화 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터베이스 프로파일을 만들거나 업데이트하는 동안 데이터 보호를 설정하거나 해제할 수 있습니다.

보조 스토리지 리소스에서 데이터베이스의 보호된 백업을 생성하려면 데이터베이스 관리자와 스토리지 관리자가 다음 작업을 수행합니다.

[cols="1a,2a"]
|===
| 원하는 작업 | 그러면... 


 a| 
프로파일을 만들거나 편집합니다
 a| 
프로파일을 만들거나 편집하려면 다음을 수행합니다.

* 보조 스토리지에 대한 백업 보호를 설정합니다.
* 7-Mode에서 작동하는 Data ONTAP를 사용 중이며 Protection Manager를 설치한 경우 Protection Manager에서 스토리지 또는 백업 관리자가 생성한 정책을 선택할 수 있습니다.
+
7-Mode에서 운영되는 Data ONTAP을 사용 중이고 보호가 설정되어 있는 경우 SnapManager에서 데이터베이스에 대한 데이터 세트를 생성합니다. 데이터 세트는 데이터와 관련된 구성 정보와 함께 스토리지 세트 모음으로 구성됩니다. 데이터 세트와 연결된 스토리지 세트에는 데이터를 클라이언트로 내보내는 데 사용되는 운영 스토리지 세트와 다른 스토리지 세트에 있는 복제본 및 아카이브 세트가 포함됩니다. 데이터 세트는 내보내기 가능한 사용자 데이터를 나타냅니다. 관리자가 데이터베이스 보호를 해제하면 SnapManager에서 데이터 세트를 삭제합니다.

* ONTAP를 사용하는 경우 생성된 SnapMirror 또는 SnapVault 관계에 따라 _SnapManager_cDOT_Mirror_또는 _SnapManager_cDOT_Vault_정책을 선택해야 합니다.


백업 보호를 비활성화하면 데이터 세트가 삭제되며 이 프로파일에 대한 백업 복원 또는 클론 생성이 불가능하다는 경고 메시지가 표시됩니다.



 a| 
프로필을 봅니다
 a| 
스토리지 관리자가 보호 정책을 구현할 스토리지 리소스를 아직 할당하지 않았기 때문에 SnapManager 그래픽 사용자 인터페이스와 'profile show' 명령 출력에 맞지 않는 것으로 표시됩니다.



 a| 
Protection Manager Management Console에서 스토리지 리소스를 할당합니다
 a| 
Protection Manager Management Console에서 스토리지 관리자는 보호되지 않은 데이터 세트를 확인하고 프로파일과 연결된 데이터 세트의 각 노드에 대한 리소스 풀을 할당합니다. 그런 다음 스토리지 관리자는 보조 볼륨이 프로비저닝되고 보호 관계가 초기화되었는지 확인합니다.



 a| 
SnapManager에서 규정을 준수하는 프로필을 봅니다
 a| 
SnapManager에서 데이터베이스 관리자는 그래픽 사용자 인터페이스 및 'profile show' 명령 출력에서 프로필이 순응 상태로 변경되어 리소스가 할당되었음을 나타냅니다.



 a| 
백업을 생성합니다
 a| 
* 전체 백업을 선택합니다.
* 또한 백업을 보호할지 여부를 선택하고 기본 보존 클래스(예: 시간별 또는 일별)를 선택합니다.
* 7-Mode에서 작동하는 Data ONTAP를 사용 중이고 보호 관리자 보호 스케줄을 재정의하는 보조 스토리지에 대한 백업을 즉시 보호하려면 '-protectnow' 옵션을 지정합니다.
* ONTAP를 사용 중이고 보조 스토리지에 대한 백업을 즉시 보호하려면 "보호" 옵션을 지정합니다.
+

NOTE: Clustered Data ONTAP에는 '보호주' 옵션이 적용되지 않습니다.





 a| 
백업을 봅니다
 a| 
새 백업은 보호 스케줄로 표시되지만 아직 보호되지 않은 것으로 표시됩니다(SnapManager 인터페이스 및 'backup show' 명령 출력에서). 보호 상태는 ""보호되지 않음""으로 표시됩니다.



 a| 
백업 목록을 봅니다
 a| 
스토리지 관리자가 백업이 보조 스토리지에 복사되었는지 확인한 후 SnapManager는 백업 보호 상태를 ""보호되지 않음""에서 ""보호됨""으로 변경합니다.

|===