---
permalink: unix-administration/concept-restoring-database-backup.html 
sidebar: sidebar 
keywords: snapmanager, sap, enable, restore, database, state, snapshot, copy, addition, file-base, restoring, backup, mean-time-to-recoverr, mttr 
summary: 'SAP용 SnapManager를 사용하면 스냅샷 복사본이 생성된 시점의 상태로 데이터베이스를 복원할 수 있습니다. SnapManager는 파일 기반 복원 프로세스 외에도 볼륨 기반의 빠른 복원 기술을 지원하므로 다른 복구 방법에 비해 복원 시간이 크게 단축됩니다. 백업이 더 자주 생성되므로 적용해야 하는 로그 수가 감소하므로 데이터베이스의 MTTR(Mean-Time-to-Recovery)이 줄어듭니다.' 
---
= 데이터베이스 백업 복원 중
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP용 SnapManager를 사용하면 스냅샷 복사본이 생성된 시점의 상태로 데이터베이스를 복원할 수 있습니다. SnapManager는 파일 기반 복원 프로세스 외에도 볼륨 기반의 빠른 복원 기술을 지원하므로 다른 복구 방법에 비해 복원 시간이 크게 단축됩니다. 백업이 더 자주 생성되므로 적용해야 하는 로그 수가 감소하므로 데이터베이스의 MTTR(Mean-Time-to-Recovery)이 줄어듭니다.

다음은 데이터베이스의 데이터 복원 및 복구와 관련하여 수행할 수 있는 몇 가지 작업입니다.

* 데이터베이스 백업을 복원하는 가장 빠른 방법이며 SnapManager에서 사용하는 기본인 파일 기반 복구나 볼륨 기반 복원을 수행합니다.
* 전체 백업 또는 백업 일부를 복원합니다.
+
일부를 복원하는 경우 테이블스페이스의 그룹이나 데이터 파일 그룹을 지정합니다. 데이터와 함께 컨트롤 파일을 복원하거나 컨트롤 파일 자체만 복원할 수도 있습니다.

* 데이터베이스에 커밋된 마지막 트랜잭션을 저장하는 사용 가능한 모든 로그 또는 특정 시점을 기준으로 데이터를 복구합니다.
+
Oracle SCN(시스템 변경 번호) 또는 날짜 및 시간(yyyy-mm-dd:hh:mm:ss)을 지정할 수 있습니다. SnapManager는 24시간 시계를 사용합니다.

* 기본 스토리지의 백업에서 복구(로컬 백업)
* SnapManager를 사용하여 백업을 복원 및 복구하거나 SnapManager를 사용하여 백업을 복원하고 RMAN(복구 관리자)과 같은 다른 툴을 사용하여 데이터를 복구합니다.
* 대체 위치에서 백업을 복원합니다.
* 복구 사양 파일을 사용하여 보조 스토리지(원격 백업) 및 대체 위치에서 보호된 백업을 복원합니다.


SnapManager 3.0 이상 버전을 사용하여 이전 버전의 SnapManager에서 만든 백업을 복원할 수 있습니다.

관리자는 SnapManager GUI(그래픽 사용자 인터페이스)를 사용하거나 CLI(명령줄 인터페이스)를 사용하여 복원 또는 복구 작업을 수행할 수 있습니다.
