---
permalink: unix-administration/concept-partial-online-backups.html 
sidebar: sidebar 
keywords: full, backup, perform, partial, backup, tablespace, database, snapmanager, online 
summary: 전체 백업 대신 데이터베이스에서 테이블스페이스의 부분 백업을 수행하도록 선택할 수 있습니다. SnapManager가 전체 백업을 위해 볼륨의 스냅샷 복사본을 사용하는 동안 SnapManager는 부분 백업을 위해 지정된 각 테이블스페이스의 스냅샷 복사본을 사용합니다. 
---
= 부분 온라인 백업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전체 백업 대신 데이터베이스에서 테이블스페이스의 부분 백업을 수행하도록 선택할 수 있습니다. SnapManager는 _full_backups를 위해 볼륨의 스냅샷 복사본을 사용하는 동안 SnapManager는 _partial_backups를 위해 지정된 각 테이블스페이스의 스냅샷 복사본을 만듭니다.

테이블스페이스 레벨은 Oracle이 백업 모드로 허용하는 가장 낮은 레벨이므로 SnapManager는 테이블스페이스에 데이터 파일을 지정하더라도 테이블스페이스 레벨에서 백업을 처리합니다.

부분 백업의 경우 각 테이블스페이스는 전체 백업에 비해 짧은 시간 동안 백업 모드에 있습니다. 온라인 백업 중에는 데이터베이스를 항상 사용할 수 있지만, 데이터베이스는 더 많은 작업을 수행해야 하며 호스트는 더 많은 물리적 I/O를 수행해야 합니다 또한 지정된 각 테이블스페이스의 스냅샷 복사본 또는 전체 볼륨 대신 지정된 데이터 파일이 포함된 각 테이블스페이스를 생성하기 때문에 SnapManager에서는 더 많은 스냅샷 복사본을 사용합니다.

SnapManager는 특정 테이블스페이스 또는 데이터 파일의 스냅샷 복사본을 생성합니다. 부분 백업 알고리즘은 SnapManager가 지정된 각 테이블스페이스 또는 데이터 파일의 스냅샷 복사본을 가져올 때까지 반복되는 루프입니다.


NOTE: 부분 백업을 수행할 수는 있지만 항상 전체 데이터베이스의 전체 백업을 수행하는 것이 좋습니다.

부분 백업 중에 SnapManager는 다음 작업을 수행합니다.

. 데이터 파일이 포함된 테이블스페이스를 백업 모드로 설정합니다.
. 테이블스페이스에서 사용하는 모든 볼륨의 스냅샷 복사본을 만듭니다.
. 테이블스페이스를 백업 모드에서 해제합니다.
. 모든 테이블스페이스 또는 파일의 스냅샷 복사본을 가져올 때까지 이 프로세스를 계속합니다.
. 로그 스위치를 강제 실행한 다음 로그 파일을 보관합니다.
. 백업 제어 파일을 생성합니다.
. 로그 파일 및 백업 제어 파일의 스냅샷 복사본을 만듭니다.

