---
permalink: unix-administration/concept-about-control-file-and-archive-log-file-handling.html 
sidebar: sidebar 
keywords: snapmanager, control, file, log, backup, archive, recovery, operation, handling 
summary: SnapManager에는 제어 파일이 포함되어 있으며 필요에 따라 각 백업과 함께 아카이브 로그 파일을 포함합니다. 아카이브 로그 파일은 복구 작업에 사용됩니다. 
---
= 제어 파일 및 아카이브 로그 파일 처리에 대해 설명합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager에는 제어 파일이 포함되어 있으며 필요에 따라 각 백업과 함께 아카이브 로그 파일을 포함합니다. 아카이브 로그 파일은 복구 작업에 사용됩니다.

데이터베이스는 컨트롤 파일을 사용하여 데이터베이스 파일의 이름, 위치 및 크기를 식별합니다. SnapManager는 복원 프로세스에서 제어 파일이 사용되므로 각 백업에 제어 파일을 포함합니다.

데이터베이스의 변경 사항은 온라인 redo 로그를 사용하여 추적되며, 이 로그는 최종적으로 아카이빙되고 아카이빙된 redo 로그(또는 아카이브 로그)라고 합니다. SnapManager(3.2 이상)를 사용하면 다른 보존 및 빈도로 데이터 파일과 아카이브 로그 파일을 개별적으로 백업할 수 있습니다. SnapManager는 아카이브 로그만 백업하거나 데이터 파일 및 아카이브 로그의 통합 백업을 수행할 수 있습니다. SnapManager는 아카이브 로그의 완벽한 자동 관리 기능을 제공하며 데이터베이스 복구를 위해 수동 작업이 필요하지 않으며, 백업을 수행한 후 하나 이상의 아카이브 로그 대상에서 아카이브 로그를 정리할 수도 있습니다.


NOTE: 백업에 포함된 테이블스페이스와 데이터 파일을 확인하려면 backup show 명령이나 Backup Properties 창을 사용합니다.

다음 표에서는 SnapManager가 각 작업 중에 제어 및 아카이브 로그 파일을 처리하는 방법을 보여 줍니다.

[cols="1a,2a,2a"]
|===
| 작업 유형입니다 | 제어 파일 | 로그 파일을 보관합니다 


 a| 
백업
 a| 
각 백업에 포함됩니다
 a| 
각 백업에 포함될 수 있습니다



 a| 
복원
 a| 
단독으로 또는 테이블스페이스 또는 데이터 파일과 함께 복원할 수 있습니다
 a| 
복구 프로세스에 사용할 수 있습니다

|===