---
permalink: unix-administration/concept-managing-profiles-for-efficient-backups.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, database, operation, manage, managing, efficient 
summary: 작업을 수행할 데이터베이스에 대해 SnapManager에서 프로필을 만들어야 합니다. 프로파일을 선택한 다음 수행할 작업을 선택해야 합니다. 
---
= 효율적인 백업을 위한 프로필 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
작업을 수행할 데이터베이스에 대해 SnapManager에서 프로필을 만들어야 합니다. 프로파일을 선택한 다음 수행할 작업을 선택해야 합니다.



== 프로파일과 관련된 작업

다음 작업을 수행할 수 있습니다.

* 프로필을 생성하여 운영, 2차 또는 3차 스토리지로 전체 또는 부분 백업과 백업을 수행할 수 있습니다.
+
데이터 파일 백업에서 아카이브 로그 백업을 분리하는 프로파일을 생성할 수도 있습니다.

* 프로필을 확인합니다.
* 프로파일을 업데이트합니다.
* 프로파일 삭제.




== 프로파일 및 인증에 대해 설명합니다

프로파일을 만들 때 데이터베이스를 지정하고 다음 방법 중 하나를 선택하여 데이터베이스에 연결할 수 있습니다.

* 사용자 이름, 암호 및 포트를 사용한 Oracle 인증
* 사용자 이름, 암호 또는 포트가 없는 운영 체제(OS) 인증
+
OS 인증의 경우 OS 계정 사용자 및 그룹 정보를 입력해야 합니다.

+

NOTE: RAC(Real Application Cluster) 데이터베이스에 대해 OS 인증을 사용하려면 SnapManager 서버가 RAC 환경의 각 노드에서 실행되고 있어야 하며 데이터베이스 암호는 RAC 환경의 모든 Oracle 인스턴스에 대해 동일해야 합니다. SnapManager는 데이터베이스 사용자 이름 및 암호를 사용하여 프로파일의 모든 RAC 인스턴스에 연결합니다.

* qlnet.authentication_services` 가 ' * none * '으로 설정된 경우 데이터베이스 인증. 그런 다음 SnapManager는 대상 데이터베이스에 대한 모든 연결에 대해 데이터베이스 사용자 이름과 암호를 사용합니다.
+

NOTE: ASM(Automatic Storage Management) 인스턴스에 대해 데이터베이스 인증을 사용하려면 ASM 인스턴스에 로그인하는 데 사용하는 사용자 이름과 암호를 입력해야 합니다.



다음 환경에서만 qlnet.authentication_services` 를 ' * none * '으로 설정할 수 있습니다.

[cols="1a,1a,1a,1a"]
|===
| 데이터베이스 레이아웃 | Oracle 버전 | 타겟 데이터베이스에 대해 데이터베이스 인증이 지원됩니다 | ASM 인스턴스에 대해 데이터베이스 인증이 지원됩니다 


 a| 
모든 비 ASM 및 비 RAC 데이터베이스
 a| 
Oracle 10g 및 Oracle 11g(11.2.0.3 미만)
 a| 
예
 a| 
아니요



 a| 
UNIX의 독립 실행형 ASM 데이터베이스
 a| 
Oracle 11.2.0.3 이상
 a| 
예
 a| 
예



 a| 
UNIX의 RAC 데이터베이스에 있는 ASM 인스턴스입니다
 a| 
Oracle 11.2.0.3
 a| 
아니요
 a| 
아니요



 a| 
NFS 기반 RAC 데이터베이스
 a| 
Oracle 11.2.0.3
 a| 
예
 a| 
아니요

|===

NOTE: 'qlnet.authentication_services` disable을 설정하고 인증방식을 DB authentication으로 변경한 후, 'qlnet.authentication_services`'를 ' * none * '으로 설정해야 한다.

처음으로 프로파일에 액세스하는 경우 프로파일 암호를 입력해야 합니다. 자격 증명을 입력한 후 프로필 내에서 데이터베이스 백업을 볼 수 있습니다.
