---
permalink: unix-administration/concept-what-database-restore-is.html 
sidebar: sidebar 
keywords: snapmanager, enable, volume-based, file-based, backup, restore, operation, database, restore 
summary: SnapManager를 사용하면 볼륨 기반 또는 파일 기반 백업 및 복원 작업을 수행할 수 있습니다. 
---
= 데이터베이스 복원이란 무엇입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용하면 볼륨 기반 또는 파일 기반 백업 및 복원 작업을 수행할 수 있습니다.

다음 표에는 복원 방법이 설명되어 있습니다.

[cols="1a,3a"]
|===
| 복원 프로세스 | 세부 정보 


 a| 
볼륨 기반의 신속한 복원(운영 스토리지에서)
 a| 
SnapManager는 전체 볼륨을 복원하여 데이터베이스의 데이터 파일을 복원합니다. 이 기본 프로세스는 데이터베이스를 복원하는 가장 빠른 방법입니다.



 a| 
파일 기반 복원
 a| 
스토리지 측 전체 파일 시스템 복구(운영 또는 2차 복구): SnapManager는 전체 LUN(Logical Unit Number) 복구를 수행합니다.



 a| 
스토리지 측 파일 복구: SnapManager는 NAS 환경에서 단일 파일 스냅 복구(SFSR)를 수행합니다. SFSR에서 보호된 객체를 나타내는 각 파일 또는 LUN이 복구됩니다.



 a| 
호스트 측 파일 복사본 복원(운영 또는 2차 사이트에서): SnapManager은 LUN 또는 FlexClone을 사용하여 로컬 백업을 복제합니다. 클론이 마운트된 다음 SnapManager가 클론에서 액티브 파일 시스템으로 호스트 파일을 복제합니다.

|===

NOTE: 백업이 운영 스토리지에도 있는 경우 보조 스토리지에서 백업을 복원할 수 없습니다.

빠른 복원 작업이 완료되면 SnapManager는 다음 작업을 수행합니다.

* Snapshot 복사본이 더 이상 운영 스토리지에 존재하지 않기 때문에 동일한 프로필에서 더 최근의 백업(백업 복원 후 작성됨)을 해제합니다.
* 빠른 복원 프로세스에 따라 스냅샷 복사본이 자동으로 삭제된 것과 동일한 프로필의 백업을 위한 모든 스냅샷 복사본을 삭제합니다.
+
이렇게 하면 백업이 부분적으로 확보되는 것을 방지할 수 있습니다. 예를 들어, Backup_A가 먼저 생성된 다음 Backup_B가 생성되었습니다. 각 데이터 파일에는 스냅샷 복사본과 아카이브 로그용 스냅샷 복사본이 하나씩 있습니다. SnapManager에서 빠른 복원 프로세스를 사용하여 Backup_A를 복원하면 SnapManager는 Backup_B에서 데이터 파일 스냅샷 복사본을 자동으로 삭제합니다 아카이브 로그가 빠른 복원 프로세스에서 복원되지 않으므로 빠른 복원 프로세스가 완료된 후 SnapManager는 아카이브 로그의 Backup_B의 스냅샷 복사본을 삭제해야 합니다.





== 빠른 복원

빠른 복원 또는 볼륨 기반 복원은 가능한 가장 빠른 복원 방법이므로 이름이 지정됩니다. 전체 스토리지 시스템 볼륨은 스냅샷 복사본으로 되돌려집니다. 스토리지 수준에서 이 복원은 거의 즉각적으로 수행됩니다. 그러나 볼륨 복원을 수행하면 다음과 같은 부정적인 결과가 발생할 수 있으므로 주의해서 사용해야 합니다.

* 다음을 포함하여 전체 스토리지 측 볼륨을 되돌릴 수 있습니다.
+
** 백업의 일부로 고려되지 않은 파일입니다
** 볼륨에 있는 다른 파일, 파일 시스템 또는 LUN


* 볼륨을 되돌릴 스냅샷 복사본 이후에 생성된 모든 스냅샷 복사본이 삭제됩니다.
+
예를 들어, 볼륨이 월요일 백업을 복원한 경우 화요일 백업을 더 이상 복원할 수 없습니다.

* 복원된 스냅샷 복사본이 관계의 기본 스냅샷 복사본보다 오래되었으면 보조 스토리지 시스템과의 관계가 끊어집니다.




== 스토리지 측 전체 파일 시스템 복구

스토리지 측 전체 파일 시스템 복구는 볼륨 복구를 수행할 수 없지만 스토리지 시스템에서 전체 파일 시스템을 복구할 수 있는 경우에 수행됩니다.

스토리지 측 파일 시스템 복구를 수행하는 경우 다음이 발생합니다.

* SAN 환경에서는 파일 시스템(및 기본 볼륨 그룹(있는 경우)이 사용하는 모든 LUN이 스토리지 시스템에 복구됩니다.
* NAS 환경에서는 파일 시스템의 모든 파일이 스토리지 시스템에 복구됩니다.
+
NAS 환경의 경우 이 복원 메커니즘은 스토리지측 파일 복원보다 더 큰 이점을 제공하지 않습니다.



스토리지 측 파일 시스템 복구를 수행하는 경우 스토리지 위치에 따라 다음이 수행됩니다.

* SnapManager가 운영 스토리지 시스템에서 복구되면 SFSR을 통해 LUN(SAN) 또는 파일(NAS)이 제자리에 복구됩니다.
* SnapManager가 보조 스토리지 시스템에서 복구되면 LUN(SAN) 또는 파일(NAS)이 보조 스토리지 시스템에서 네트워크를 통해 운영 스토리지 시스템으로 다시 복제됩니다.


파일 시스템이 완전히 복원되므로 백업에 포함되지 않은 파일도 되돌릴 수 있습니다. 복구 중인 파일 시스템에 복구 작업이 아닌 파일이 있는 경우 재정의가 필요합니다.



== 스토리지 측 파일 복원

스토리지 측 파일 시스템 복구를 수행할 수 없는 경우 스토리지 측 파일 복구가 수행되는 경우가 있습니다. 스토리지 측 파일 복구에서는 파일 시스템 내의 개별 파일이 스토리지 시스템에서 직접 복구됩니다.

이 유형의 복원은 NFS 환경이나 ASM 환경에서 특정 경우에만 수행할 수 있습니다.

스토리지측 파일 복원이 수행되는 경우 다음과 같은 현상이 발생합니다.

* SnapManager가 운영 스토리지 시스템에서 NFS 파일을 복구하면 SFSR을 사용하여 개별 파일이 해당 위치에 복구됩니다.
* SnapManager가 보조 스토리지 시스템에서 NFS 파일을 복구하면 스토리지 네트워크를 통해 개별 파일이 운영 스토리지 시스템으로 다시 복제됩니다.




== 호스트 측 파일 복원

빠른 복구, 스토리지 측 파일 시스템 복구 및 스토리지 측 파일 복원을 수행할 수 없는 경우 SAN 환경에서 호스트 측 파일 복사 복원이 마지막 수단으로 사용됩니다.

호스트 측 파일 복사 복원에는 다음 작업이 포함됩니다.

* 스토리지를 클론 복제하십시오
* 복제된 스토리지를 호스트에 연결합니다
* 클론 파일 시스템에서 액티브 파일 시스템으로 파일을 다시 복제합니다
* 호스트에서 클론 스토리지 연결을 끊는 중입니다
* 클론 스토리지 삭제


보조 스토리지에서 복구할 때 SnapManager은 먼저 보조 스토리지 시스템에서 운영 스토리지 시스템으로 직접 데이터 복구를 시도합니다(호스트 개입 없음). SnapManager에서 이 유형의 복구를 수행할 수 없는 경우(예: 파일 시스템에 복구에 포함되지 않은 파일이 있는 경우) SnapManager는 호스트 측 파일 복사 복구를 수행합니다. SnapManager에는 보조 스토리지에서 호스트 측 파일 복사 복구를 수행하는 두 가지 방법이 있습니다. SnapManager Selects 방식은 'msap.config' 파일에 설정된다.

* 직접: SnapManager는 보조 스토리지의 데이터를 클론 복제하고, 보조 스토리지 시스템에서 호스트로 클론 복제된 데이터를 마운트한 다음 클론 데이터를 활성 환경에 복사합니다. 기본 보조 액세스 정책입니다.
* 간접: SnapManager는 먼저 데이터를 운영 스토리지의 임시 볼륨에 복사한 다음 임시 볼륨에서 호스트로 데이터를 마운트한 다음 임시 볼륨의 데이터를 활성 환경에 복사합니다. 이 보조 액세스 정책은 호스트에서 보조 스토리지 시스템에 직접 액세스할 수 없는 경우에만 사용해야 합니다. 이 방법을 사용하여 복원하는 데에는 두 개의 데이터 복제본이 만들어지기 때문에 직접 보조 액세스 정책보다 두 배 정도 시간이 걸립니다.


직접 또는 간접 방법의 사용 여부는 'msap.config' 설정 파일의 restore.secondaryAccessPolicy` 매개 변수 값에 의해 결정된다. 기본값은 DIRECT 입니다.
