---
permalink: unix-administration/concept-restores-of-protected-backups-overview.html 
sidebar: sidebar 
keywords: restore, method, backup, data, secondary, primary, storage, protect, overview 
summary: 보조 스토리지에서 운영 스토리지로 백업 데이터를 복구하는 데 사용할 복원 방법을 선택할 수 있습니다. 
---
= 보호된 백업 복구 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보조 스토리지에서 운영 스토리지로 백업 데이터를 복구하는 데 사용할 복원 방법을 선택할 수 있습니다.

다음 표에서는 보조 스토리지에서 백업을 복원하는 데 사용할 수 있는 다양한 시나리오 및 방법에 대해 설명합니다.

[cols="1a,3a"]
|===
| 복원 대상 | 설명 


 a| 
운영 스토리지로 직접
 a| 
데이터를 보호하는 데 사용된 것과 동일한 네트워크를 통해 보조 스토리지 시스템의 데이터를 운영 스토리지 시스템의 원래 위치로 직접 반환합니다.

SnapManager는 가능한 경우 직접 저장 방법을 사용합니다. 데이터가 SAN(Storage Area Network)의 파일 시스템에 있고 다음 조건 중 하나가 적용되는 경우 이 방법은 사용할 수 없습니다.

* 다른 비 데이터베이스 파일은 동일한 파일 시스템에서 복구되지 않습니다.
* 복구 중인 파일 시스템에 있는 제어 파일 및 데이터 파일의 스냅샷 복사본이 다른 시간에 촬영되었습니다.
* LUN(Logical Unit Number)이 볼륨 그룹에 있지만 같은 볼륨 그룹의 다른 LUN은 복구되지 않습니다.




 a| 
호스트에 직접
 a| 
보조 스토리지 시스템의 데이터를 복제하고 클론된 데이터를 호스트에 마운트합니다. 데이터의 클론을 만들어 마운트한 후에는 SnapManager에서 데이터를 원래 위치에 복사합니다.



 a| 
스토리지 또는 호스트에 간접적으로
 a| 
데이터를 보호하고 호스트에 새 스토리지를 마운트하는 데 사용된 것과 동일한 네트워크를 통해 보조 스토리지 시스템의 데이터를 운영 시스템의 새 위치로 반환합니다. 데이터를 반환하여 마운트한 후 SnapManager가 데이터를 원래 위치에 복사합니다. 간접 저장 방법은 데이터를 반환하는 데 오랜 시간이 걸릴 수 있습니다.

SnapManager는 먼저 운영 호스트의 스크래치 볼륨에 데이터를 복사한 후 SnapManager에서 이를 사용하여 데이터베이스를 복원 및 복구합니다. 스크래치 데이터를 자동으로 삭제할지 여부는 사용된 프로토콜에 따라 다릅니다.

* SAN의 경우 SnapManager는 반환된 데이터를 삭제합니다.
* NAS(Network-Attached Storage)의 경우 SnapManager는 반환된 qtree의 콘텐츠를 삭제하지만 qtree 자체는 삭제하지 않습니다. qtree를 삭제하려면 관리자는 스크래치 볼륨을 마운트하고 UNIX rmdir 명령을 사용하여 qtree를 제거해야 합니다.


|===
데이터를 스토리지로 직접 반환할 수 없는 경우 SnapManager은 데이터를 호스트에 직접 반환하거나 간접적으로 스토리지 또는 호스트에 반환할 수 있습니다. 이 방법은 조직에서 보조 스토리지에 직접 연결할 수 있는지 또는 스토리지 네트워크를 통해 데이터를 복사해야 하는지 여부를 관리하는 정책에 따라 달라집니다. smsap.config 파일에서 구성 정보를 설정하여 이 정책을 관리할 수 있습니다.
