---
permalink: unix-administration/concept-limitations.html 
sidebar: sidebar 
keywords: scenario, limitation, environment, snapmanager 
summary: 환경에 영향을 줄 수 있는 시나리오 및 제한 사항을 알고 있어야 합니다. 
---
= SnapManager 작업 시 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
환경에 영향을 줄 수 있는 시나리오 및 제한 사항을 알고 있어야 합니다.

* 데이터베이스 레이아웃 및 플랫폼과 관련된 제한 사항 *

* SnapManager는 파일 시스템의 제어 파일을 지원하며 원시 디바이스의 제어 파일은 지원하지 않습니다.
* SnapManager는 MSCS(Microsoft 클러스터링) 환경에서 작동하지만 MSCS 구성(활성 또는 수동)의 상태를 인식하지 못하고 MSCS 클러스터의 대기 서버로 리포지토리의 활성 관리를 전송하지 않습니다.
* RHEL(Red Hat Enterprise Linux) 및 Oracle Enterprise Linux 4.7, 5.0, 5.1, 5.2 및 5.3에서는 다중 경로 네트워크 I/O(MPIO) 환경에서 동적 다중 경로(DMP)를 사용하여 원시 장치에 Oracle을 배포할 때 ext3 파일 시스템이 지원되지 않습니다.
+
이 문제는 SnapDrive에서 UNIX 또는 이전 버전의 SnapManager 4.1을 사용하는 경우에만 나타납니다.

* RHEL의 SnapManager는 * parted * 유틸리티를 사용하여 디스크 분할을 지원하지 않습니다.
+
이것은 RHEL * parted * 유틸리티에 대한 문제입니다.

* RAC 구성에서 RAC 노드 A에서 프로필 이름을 업데이트하면 해당 프로필의 스케줄 파일이 RAC 노드 A에 대해서만 업데이트됩니다
+
RAC 노드 B의 동일한 프로파일에 대한 스케줄 파일이 업데이트되지 않으며 이전 스케줄 정보가 포함됩니다. 노드 B에서 예약된 백업이 트리거되면 노드 B에 이전 스케줄 파일이 포함되어 있기 때문에 예약된 백업 작업이 실패합니다. 그러나 예약된 백업 작업은 프로파일 이름이 변경된 노드 A에서 성공적으로 수행됩니다. SnapManager 서버를 다시 시작하여 노드 B의 프로파일에 대한 최신 스케줄 파일을 받을 수 있습니다

* 리포지토리 데이터베이스는 둘 이상의 IP 주소를 사용하여 액세스할 수 있는 호스트에 있을 수 있습니다.
+
둘 이상의 IP 주소를 사용하여 리포지토리에 액세스하는 경우 각 IP 주소에 대해 스케줄 파일이 생성됩니다. IP 주소 중 하나(예: IP1) 아래에 프로필(예: 프로필 A)에 대한 일정 백업이 생성된 경우 해당 IP 주소에 대한 일정 파일만 업데이트됩니다. 다른 IP 주소(예: IP2)에서 프로파일 A에 액세스할 경우 IP2의 스케줄 파일에 IP1에서 생성된 스케줄에 대한 항목이 없기 때문에 예약된 백업이 나열되지 않습니다.

+
해당 IP 주소 및 스케줄 파일에서 스케줄이 트리거될 때까지 기다리거나 서버를 다시 시작할 수 있습니다.



* SnapManager 구성과 관련된 제한 사항 *

* UNIX용 SnapDrive는 특정 플랫폼에서 둘 이상의 파일 시스템 및 볼륨 관리자를 지원합니다.
+
데이터베이스 파일에 사용되는 파일 시스템 및 볼륨 관리자는 SnapDrive 구성 파일에 기본 파일 시스템 및 볼륨 관리자로 지정해야 합니다.

* SnapManager는 다음과 같은 요구 사항이 있는 MultiStore 스토리지 시스템의 데이터베이스를 지원합니다.
+
** MultiStore 스토리지 시스템에 대한 암호를 설정하려면 SnapDrive를 구성해야 합니다.
** 기본 볼륨이 동일한 MultiStore 스토리지 시스템에 없는 경우 SnapDrive는 MultiStore 스토리지 시스템의 qtree에 있는 LUN 또는 파일의 스냅샷 복사본을 생성할 수 없습니다.


* SnapManager는 단일 클라이언트(둘 다 CLI 또는 GUI)의 서로 다른 포트에서 실행되는 두 SnapManager 서버에 대한 액세스를 지원하지 않습니다.
+
포트 번호는 타겟 호스트와 원격 호스트에서 동일해야 합니다.

* 볼륨 내의 모든 LUN은 볼륨 레벨이나 Qtree 내에 상주해야 하며 둘 다 있어서는 안 됩니다.
+
데이터가 qtree에 있고 볼륨을 마운트하는 경우 Qtree 내의 데이터는 보호되지 않기 때문입니다.

* SnapManager 작업이 실패하고 리포지토리 데이터베이스가 다운된 경우 GUI에 액세스할 수 없습니다.
+
SnapManager 작업을 수행할 때 저장소 데이터베이스가 실행 중인지 확인해야 합니다.

* SnapManager는 LPM(Live Partition Mobility) 및 LAM(Live Application Mobility)을 지원하지 않습니다.
* SnapManager는 Oracle Wallet Manager 및 TDE(Transparent Data Encryption)를 지원하지 않습니다.
* MetroCluster는 RDM(Raw Device Mapping) 환경에서 MetroCluster 구성을 지원하지 않습니다. SnapManager 구성은 아직 VSC(가상 스토리지 콘솔)에서 지원되지 않기 때문입니다.


* 프로파일 관리와 관련된 제한 사항 *

* 아카이브 로그 백업을 분리하기 위해 프로파일을 업데이트하는 경우 호스트에서 롤백 작업을 수행할 수 없습니다.
* GUI에서 프로파일을 활성화하여 아카이브 로그 백업을 만들고 나중에 다중 프로파일 업데이트 창 또는 프로파일 업데이트 창을 사용하여 프로파일을 업데이트하려고 하면 해당 프로파일을 수정하여 전체 백업을 만들 수 없습니다.
* 다중 프로필 업데이트 창에서 여러 프로필을 업데이트하고 일부 프로필에 * Backup Archivelogs Seively * 옵션이 활성화되어 있고 다른 프로필에 옵션이 비활성화되어 있는 경우 * Backup Archivelogs Seively * 옵션이 비활성화됩니다.
* 여러 프로필을 업데이트하고 일부 프로필에 * Backup Archivelogs Seively * 옵션이 활성화되어 있고 다른 프로필에 옵션이 비활성화되어 있는 경우, 다중 프로필 업데이트 창의 * Backup Archivelogs Seively * 옵션이 비활성화됩니다.
* 프로파일의 이름을 바꾸면 호스트를 롤백할 수 없습니다.


* 롤링 업그레이드 또는 롤백 작업과 관련된 제한 사항 *

* 리포지토리의 호스트에서 롤백 작업을 수행하지 않고 호스트에 대한 이전 버전의 SnapManager를 설치하려고 하면 다음을 수행할 수 없을 수 있습니다.
+
** 호스트에 대한 이전 또는 이후 버전의 SnapManager에서 만든 프로파일을 봅니다.
** 이전 또는 이후 버전의 SnapManager에서 생성한 백업이나 클론에 액세스합니다.
** 호스트에서 롤링 업그레이드 또는 롤백 작업을 수행합니다.


* 아카이브 로그 백업을 생성하기 위해 프로파일을 분리한 후에는 관련 호스트 리포지토리에서 롤백 작업을 수행할 수 없습니다.


* 백업 작업과 관련된 제한 사항 *

* 복구 중에 백업이 이미 마운트되어 있는 경우 SnapManager는 백업을 다시 마운트하지 않고 이미 마운트된 백업을 사용합니다.
+
다른 사용자가 백업을 마운트하고 이전에 마운트된 백업에 액세스할 수 없는 경우 다른 사용자가 권한을 제공해야 합니다.

+
모든 아카이브 로그 파일에는 그룹에 할당된 사용자에 대한 읽기 권한이 있습니다. 백업이 다른 사용자 그룹에 의해 마운트되는 경우 아카이브 로그 파일에 대한 액세스 권한이 없을 수 있습니다. 사용자는 마운트된 아카이브 로그 파일에 대한 권한을 수동으로 지정한 다음 복구 또는 복구 작업을 다시 시도할 수 있습니다.

* SnapManager는 데이터베이스 백업의 스냅샷 복사본 중 하나가 보조 스토리지 시스템으로 전송되더라도 백업 상태를 "보호"로 설정합니다.
* 예약된 백업에 대해서는 SnapManager 3.2 이상에서만 작업 사양 파일을 사용할 수 있습니다.
* Protection Manager와 통합된 SnapManager는 SnapVault 및 Qtree SnapMirror에 기본 스토리지의 여러 볼륨을 보조 스토리지의 단일 볼륨으로 백업할 수 있도록 지원합니다.
+
동적 2차 볼륨 사이징은 지원되지 않습니다. 자세한 내용은 DataFabric Manager Server 3.8과 함께 사용되는 Provisioning Manager 및 Protection Manager 관리 가이드 를 참조하십시오.

* SnapManager는 사후 처리 스크립트를 사용한 백업 보관을 지원하지 않습니다.
* 리포지토리 데이터베이스가 둘 이상의 IP 주소를 가리키고 있고 각 IP 주소의 호스트 이름이 다른 경우 한 IP 주소에 대해 백업 예약 작업이 성공하지만 다른 IP 주소에 대해서는 실패합니다.
* SnapManager 3.4 이상으로 업그레이드한 후에는 SnapManager 3.3.1을 사용하여 사후 처리 스크립트로 예약된 백업을 업데이트할 수 없습니다.
+
기존 일정을 삭제하고 새 일정을 만들어야 합니다.



* 복원 작업과 관련된 제한 사항 *

* 복구 작업을 수행하는 간접 방법을 사용하고 복구에 필요한 아카이브 로그 파일을 보조 스토리지 시스템의 백업에서만 사용할 수 있는 경우 SnapManager에서 데이터베이스를 복구하지 못합니다.
+
이는 SnapManager가 보조 스토리지 시스템에서 아카이브 로그 파일의 백업을 마운트할 수 없기 때문입니다.

* SnapManager가 볼륨 복원 작업을 수행할 때 해당 백업이 복구된 후 생성된 아카이브 로그 백업 복사본은 삭제되지 않습니다.
+
데이터 파일 및 아카이브 로그 파일 대상이 동일한 볼륨에 있으면 아카이브 로그 파일 대상에 사용 가능한 아카이브 로그 파일이 없는 경우 볼륨 복원 작업을 통해 데이터 파일을 복원할 수 있습니다. 이 시나리오에서는 데이터 파일의 백업 이후에 생성되는 아카이브 로그 스냅샷 복사본이 손실됩니다.

+
아카이브 로그 대상에서 모든 아카이브 로그 파일을 삭제해서는 안 됩니다.



* 클론 작업과 관련된 제한 사항 *

* 유연한 볼륨을 포함하는 스토리지 시스템에서 inode를 검색 및 처리하는 속도 때문에 클론 분할 작업의 진행 상황에 대해 0에서 100 사이의 숫자 값을 볼 수 없습니다.
* SnapManager는 클론 분할 작업이 성공적으로 완료된 경우에만 이메일 수신을 지원하지 않습니다.
* SnapManager에서는 FlexClone 분할만 지원합니다.
* 복구 실패 때문에 외부 아카이브 로그 파일 위치를 사용하는 RAC 데이터베이스의 온라인 데이터베이스 백업 클론 생성이 실패합니다.
+
Oracle이 외부 아카이브 로그 위치에서 복구를 위해 아카이브 로그 파일을 찾아 적용하지 못하여 클론을 생성하지 못합니다. 이는 Oracle의 제한 사항입니다. 자세한 내용은 Oracle 버그 ID: 13528007을 참조하십시오. Oracle은 의 기본 위치가 아닌 위치에서 아카이브 로그를 적용하지 않습니다 http://metalink.oracle.com/["Oracle Support 사이트"^]. 유효한 Oracle Metalink 사용자 이름과 암호가 있어야 합니다.

* SnapManager 3.3 이상은 SnapManager 3.2 이전 릴리즈에서 생성한 클론 사양 XML 파일 사용을 지원하지 않습니다.
* 임시 테이블스페이스가 데이터 파일 위치와 다른 위치에 있는 경우 클론 작업은 데이터 파일 위치에 테이블스페이스를 생성합니다.
+
그러나 임시 테이블스페이스가 데이터 파일 위치와 다른 위치에 있는 OVF(Oracle Managed Files)인 경우 클론 작업은 데이터 파일 위치에 테이블스페이스를 생성하지 않습니다. OMF는 SnapManager에서 관리하지 않습니다.

* '-resetlogs' 옵션을 선택하면 SnapManager에서 RAC 데이터베이스를 복제하지 못합니다.


* 아카이브 로그 파일 및 백업과 관련된 제한 사항 *

* SnapManager는 플래시 복구 영역 대상에서 아카이브 로그 파일 정리를 지원하지 않습니다.
* SnapManager는 대기 대상에서 아카이브 로그 파일 정리를 지원하지 않습니다.
* 아카이브 로그 백업은 보존 기간 및 기본 시간별 보존 클래스에 따라 보존됩니다.
+
SnapManager CLI 또는 GUI를 사용하여 아카이브 로그 백업 보존 클래스를 수정할 경우 아카이브 로그 백업은 보존 기간을 기준으로 보존되므로 수정된 보존 클래스는 백업에 고려되지 않습니다.

* 아카이브 로그 대상에서 아카이브 로그 파일을 삭제하는 경우 아카이브 로그 백업에는 누락된 아카이브 로그 파일보다 오래된 아카이브 로그 파일이 포함되지 않습니다.
+
최신 아카이브 로그 파일이 누락된 경우 아카이브 로그 백업 작업이 실패합니다.

* 보관 로그 대상에서 보관 로그 파일을 삭제하면 보관 로그 파일을 가지치기는 실패합니다.
* SnapManager는 아카이브 로그 대상에서 아카이브 로그 파일을 삭제하거나 아카이브 로그 파일이 손상된 경우에도 아카이브 로그 백업을 통합합니다.


* 대상 데이터베이스 호스트 이름 변경과 관련된 제한 사항 *

타겟 데이터베이스 호스트 이름을 변경할 때는 다음 SnapManager 작업이 지원되지 않습니다.

* SnapManager GUI에서 타겟 데이터베이스 호스트 이름 변경
* 프로파일의 타겟 데이터베이스 호스트 이름을 업데이트한 후 리포지토리 데이터베이스의 롤백.
* 새 타겟 데이터베이스 호스트 이름에 대해 여러 프로파일을 동시에 업데이트합니다.
* SnapManager 작업이 실행 중일 때 타겟 데이터베이스 호스트 이름을 변경합니다.


* SnapManager CLI 또는 GUI * 와 관련된 제한 사항

* SnapManager GUI에서 생성된 profile create 작업에 대한 SnapManager CLI 명령에는 history 설정 옵션이 없다.
+
SnapManager CLI에서는 'profile create' 명령을 사용하여 기록 보존 설정을 구성할 수 없습니다.

* SnapManager는 UNIX 클라이언트에서 사용할 수 있는 JRE(Java Runtime Environment)가 없는 경우 Mozilla Firefox에서 GUI를 표시하지 않습니다.
* SnapManager CLI를 사용하여 타겟 데이터베이스 호스트 이름을 업데이트하는 동안 열려 있는 SnapManager GUI 세션이 하나 이상 있으면 열려 있는 모든 SnapManager GUI 세션이 응답하지 않습니다.


* SnapMirror 및 SnapVault * 과 관련된 제한 사항

* 7-Mode에서 작동하는 Data ONTAP를 사용하는 경우 SnapVault 후처리 스크립트는 지원되지 않습니다.
* ONTAP를 사용하는 경우 SnapMirror 관계가 설정된 볼륨에서 생성된 백업에 VBSR(볼륨 기반 SnapRestore)을 수행할 수 없습니다.
+
이는 ONTAP 제한 사항 때문이며, VBSR을 수행할 때 관계를 중단할 수 없습니다. 하지만 볼륨에 SnapVault 관계가 설정된 경우에만 최근 또는 가장 최근에 생성된 백업에 VBSR을 수행할 수 있습니다.

* 7-Mode에서 작동하는 Data ONTAP를 사용하고 있으며 SnapMirror 관계가 설정된 볼륨에서 생성된 백업에 VBSR을 수행하려는 경우 SnapDrive for UNIX에서 "override-vbsr-snapmirror-check" 옵션을 ' * on * '으로 설정할 수 있습니다.
+
이에 대한 자세한 내용은 SnapDrive 설명서를 참조하십시오.

* 일부 시나리오에서는 볼륨에 SnapVault 관계가 설정된 경우 첫 번째 스냅샷 복사본과 연결된 마지막 백업을 삭제할 수 없습니다.
+
관계를 끊은 경우에만 백업을 삭제할 수 있습니다. 이 문제는 기본 스냅샷 복사본에 대한 ONTAP 제한 사항 때문입니다. SnapMirror 관계에서 기본 스냅샷 복사본은 SnapMirror 엔진에 의해 생성되고 SnapVault 관계에서 기본 스냅샷 복사본은 SnapManager를 사용하여 생성되는 백업입니다. 각 업데이트에 대해 기본 스냅샷 복사본이 SnapManager를 사용하여 생성한 최신 백업을 가리킵니다.



* Data Guard 대기 데이터베이스와 관련된 제한 사항 *

* SnapManager는 논리적 Data Guard 대기 데이터베이스를 지원하지 않습니다.
* SnapManager는 Active Data Guard 대기 데이터베이스를 지원하지 않습니다.
* SnapManager에서는 Data Guard 대기 데이터베이스의 온라인 백업을 허용하지 않습니다.
* SnapManager에서는 Data Guard 대기 데이터베이스의 부분 백업을 허용하지 않습니다.
* SnapManager에서는 Data Guard 대기 데이터베이스 복원을 허용하지 않습니다.
* SnapManager에서는 Data Guard 대기 데이터베이스에 대한 아카이브 로그 파일을 정리할 수 없습니다.
* SnapManager는 Data Guard Broker를 지원하지 않습니다.


* 관련 정보 *

http://mysupport.netapp.com/["NetApp Support 사이트에 문서화"^]
