---
permalink: unix-administration/concept-what-full-and-partial-backups-are.html 
sidebar: sidebar 
keywords: entire, database, portion, tablespace, data, file, full, partial, backup 
summary: 전체 데이터베이스를 백업하거나 일부 데이터베이스를 백업하도록 선택할 수 있습니다. 데이터베이스의 일부를 백업하도록 선택한 경우 테이블스페이스 또는 데이터 파일 그룹을 백업하도록 선택할 수 있습니다. 테이블스페이스와 데이터 파일 모두에 대해 별도의 백업을 선택할 수 있습니다. 
---
= 전체 및 부분 백업이란
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전체 데이터베이스를 백업하거나 일부 데이터베이스를 백업하도록 선택할 수 있습니다. 데이터베이스의 일부를 백업하도록 선택한 경우 테이블스페이스 또는 데이터 파일 그룹을 백업하도록 선택할 수 있습니다. 테이블스페이스와 데이터 파일 모두에 대해 별도의 백업을 선택할 수 있습니다.

다음 표에는 각 백업 유형의 이점과 결과가 나와 있습니다.

[cols="1a,2a,2a"]
|===
| 백업 유형 | 장점 | 단점 


 a| 
가득 참
 a| 
Snapshot 복사본 수를 최소화합니다. 온라인 백업의 경우 각 테이블스페이스는 백업 작업의 전체 시간 동안 백업 모드에 있습니다. SnapManager는 데이터베이스가 사용하는 각 볼륨에 대해 하나의 스냅샷 복사본을 생성하고 로그 파일이 차지하는 각 볼륨에 대해 하나의 스냅샷 복사본을 만듭니다.
 a| 
온라인 백업의 경우 각 테이블스페이스는 백업 작업의 전체 시간 동안 백업 모드에 있습니다.



 a| 
부분
 a| 
각 테이블스페이스가 백업 모드에서 사용하는 시간을 최소화합니다. SnapManager는 테이블스페이스로 생성한 스냅샷 복사본을 그룹화합니다. 각 테이블스페이스는 스냅샷 복사본을 생성할 수 있을 정도로 백업 모드에 있습니다. 이러한 스냅샷 복사본 그룹화 방법은 온라인 백업 중에 로그 파일의 물리적 블록 쓰기를 최소화합니다.
 a| 
백업에는 동일한 볼륨에 있는 여러 테이블스페이스의 Snapshot 복제본을 생성해야 할 수 있습니다. 이 방법을 사용하면 백업 작업 중에 SnapManager에서 단일 볼륨의 여러 스냅샷 복사본을 생성할 수 있습니다.

|===

NOTE: 부분 백업을 수행할 수는 있지만 항상 전체 데이터베이스의 전체 백업을 수행해야 합니다.
