---
permalink: unix-administration/concept-licenses-required-for-data-protection.html 
sidebar: sidebar 
keywords: ensure, license, require, data, protection, install, enable, primary, secondary, storage, system 
summary: 운영 및 2차 스토리지 시스템에서 데이터 보호에 필요한 라이센스가 설치 및 설정되어 있는지 확인해야 합니다. 
---
= SnapManager의 데이터 보호에 필요한 라이센스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
운영 및 2차 스토리지 시스템에서 데이터 보호에 필요한 라이센스가 설치 및 설정되어 있는지 확인해야 합니다.

운영 스토리지 시스템은 Oracle 데이터베이스에 대한 최신 트랜잭션 업데이트를 수신하고, 데이터를 저장하고, 데이터베이스의 로컬 백업 보호를 제공합니다. 또한 운영 스토리지 시스템은 데이터베이스 데이터 파일, 로그 파일 및 제어 파일을 유지 관리합니다. 보조 스토리지 시스템은 보호 백업을 위한 원격 스토리지 역할을 합니다.

데이터 보호를 위해 운영 스토리지 시스템에 다음 라이센스가 설치 및 설정되어 있어야 합니다.


NOTE: 2차 스토리지 시스템에서 데이터 보호를 설정하려면 2차 스토리지 시스템에도 이러한 라이센스를 설치 및 활성화해야 합니다.

* 7-Mode에서 작동하는 Data ONTAP(7.3.1 이상) 또는 clustered Data ONTAP(8.2 이상)
* SnapVault(보호 정책에 따라 다름)
* SnapRestore
* SnapMirror(보호 정책에 따라 다름)
* NFS(Network File System) 및클로닝에 FlexClone이 필요합니다.
+
또한 SnapDrive가 SAN 환경에서 FlexClone을 사용하도록 구성된 경우에만 SAN(Storage Area Network)에 FlexClone이 필요합니다.

* 적절한 프로토콜(예: NFS, iSCSI(Internet Small Computer System Interface) 또는 FC(Fibre Channel))


SnapVault 또는 SnapMirror는 사용된 보호 정책에 따라 운영 및 2차 스토리지 시스템에 있어야 합니다. 기본 백업 보호 정책에는 지원 시스템에 SnapVault만 설치되어 있어야 합니다. 미러 보호가 포함된 정책에는 지원 시스템에 SnapMirror가 설치되어 있어야 합니다. 백업 및 미러링 재해 복구 정책을 사용하려면 지원 시스템에 SnapMirror가 설치되어 있어야 합니다.
