---
permalink: unix-administration/concept-when-can-you-use-fast-restore.html 
sidebar: sidebar 
keywords: rule, apply, fast, restore, achieve, optimal, performance, guidelines 
summary: 최적의 복원 성능을 얻기 위해 빠른 복원을 사용하는 경우 특정 규칙이 적용됩니다. 경우에 따라 빠른 복원을 사용할 수 없습니다. 
---
= 빠른 복원을 사용할 수 있는 시기를 위한 지침입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
최적의 복원 성능을 얻기 위해 빠른 복원을 사용하는 경우 특정 규칙이 적용됩니다. 경우에 따라 빠른 복원을 사용할 수 없습니다.

최적의 복원 성능(볼륨 복원 또는 전체 디스크 그룹 복원)을 얻으려면 다음 규칙을 준수해야 합니다.

* 전체 백업의 전체 복원만 빠른 복원을 수행할 수 있습니다.
* 데이터 파일만 빠른 복원을 수행할 수 있습니다.
* 빠른 복원을 위해서는 데이터 파일이 볼륨의 유일한 파일이어야 합니다.
+
임시 데이터 파일이 볼륨에 있을 수 있지만 제어 파일, 로그, pfile 또는 기타 파일은 데이터 파일과 별도의 볼륨에 있어야 합니다. 제어 파일, 아카이브 로그 및 온라인 로그 파일과 별도의 볼륨에 데이터 파일이 있는 Oracle 데이터베이스를 설정해야 합니다.

* 볼륨에 데이터베이스 한 개에 대한 데이터 파일만 있어야 합니다.
* 여러 파일 시스템을 사용할 수 있지만 해당 파일 시스템의 파일은 하나의 데이터베이스에만 대한 데이터 파일이어야 합니다.
* SAP에는 약간 다른 파일 레이아웃이 필요합니다.
+
"일반 레이아웃 및 구성" 단원에 자세한 내용이 나와 있습니다.

* 데이터베이스를 복원하는 데 brrestore를 사용하면 백업 유틸리티 매개 변수 파일의 fast 매개 변수와 함께 빠른 복원이 사용됩니다.



NOTE: 빠른 복원을 사용하여 이전에 만든 백업을 복원할 수 있는지 여부를 확인하려면 'msap backup restore' 명령의 '-preview' 옵션을 사용합니다.

다음과 같은 경우에는 빠른 복원 프로세스를 사용할 수 없습니다.

* 부분 백업 시
* 백업이 운영 스토리지에도 있는 경우 보조 스토리지로부터의 백업 시
+
파일 기반 또는 볼륨 기반 복원을 사용하여 이러한 데이터를 복원할 수 없습니다.

* SnapVault로 보호되는 백업입니다
+
마지막 보호 백업보다 이전에 생성된 백업에는 빠른 복원 프로세스를 사용할 수 없습니다. 그러나 마지막으로 보호된 백업 이후에 생성된 백업에 대해서는 빠른 복원 프로세스를 사용할 수 있습니다. 예를 들어, 백업 A, B 및 C를 고려합니다 B는 SnapVault를 사용하여 보조 스토리지로 전송할 마지막 백업입니다. B와 C를 빠르게 복원할 수 있지만 마지막 보호 백업보다 이전에 생성되었기 때문에 A를 빠르게 복원할 수 없습니다. SnapVault는 시간 차이를 계산하고 다음에 백업을 보조 스토리지로 전송할 때 보조 스토리지에 전송하기 위해 기본 SnapVault가 필요합니다. 마지막 보호 백업은 기본 스냅샷 복사본으로 작동합니다. 따라서 빠른 복원 프로세스를 사용하면 SnapVault에서 기준을 인식하지 못합니다.

* 볼륨을 되돌릴 스냅샷 복사본 이후에 생성된 Snapshot 복사본을 사용하는 FlexClone 또는 LUN 클론
+
예를 들어, 클론은 SnapManager에 의해 마운트되거나 클론 복제되는 이후 백업의 결과일 수 있습니다.

* 활성 SnapDrive 스냅샷 복사본에 포함되지 않은 LUN입니다


동일한 백업에 대해 다른 유형의 복원과 함께 빠른 복원을 수행할 수 없습니다. 예를 들어, 한 데이터 볼륨을 빠른 복원 프로세스를 사용하여 복원할 수 있지만 다른 데이터 볼륨은 복원할 수 없는 경우 빠른 복원 프로세스를 사용하여 복원할 수 없습니다. 이 경우 파일 기반 복구를 선택할 수 있습니다.

또한 데이터베이스 복원과 관련하여 다음 사항을 고려해야 합니다.

* SnapManager는 아카이브 로그 또는 redo 로그를 복구하지 않지만 아카이브 로그 파일의 백업을 마운트하여 복구에 사용합니다.
* SnapManager에서는 볼륨 복원을 사용하여 제어 파일을 복원하지 않습니다.
* 제어 파일과 데이터 파일을 복원하려면 SnapManager에서 두 단계로 복원을 수행합니다.
+
SnapManager는 먼저 제어 파일을 복구한 다음 데이터 파일을 복구합니다.

* SnapManager가 표준 테이블스페이스 파일과 동일한 볼륨에서 임시 파일을 찾을 경우 볼륨 레벨 복구를 수행하기 위해 덮어쓰기를 실행할 필요가 없습니다.
+
볼륨 복원 후 TEMP 테이블스페이스가 다시 온라인 상태로 전환됩니다.



SAP용 SnapManager와 backint 인터페이스 모두 사용할 수 있는 복원 메커니즘을 결정할 때 동일한 논리를 사용합니다. SAP용 SnapManager 또는 backint 인터페이스에서 백업을 수행했는지 여부와 SAP용 SnapManager 또는 backint 인터페이스를 통해 복구를 수행했는지 여부에 관계없이 모든 복원 방법을 사용할 수 있습니다.

* 관련 정보 *

http://mysupport.netapp.com/["NetApp Support 사이트 관련 문서: mysupport.netapp.com"]
