---
permalink: unix-administration/concept-profile-usage-for-br-tools-backups.html 
sidebar: sidebar 
keywords: backint, snapmanager, profile, repository, backup 
summary: backint 인터페이스를 사용하는 BR * Tools 명령을 실행하면 SnapManager는 리포지토리의 프로파일을 사용합니다. 리포지토리는 BR * Tools 명령을 실행하는 사용자의 SnapManager 자격 증명에 의해 결정됩니다. 
---
= BR * Tools 백업에 대한 프로파일 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
backint 인터페이스를 사용하는 BR * Tools 명령을 실행하면 SnapManager는 리포지토리의 프로파일을 사용합니다. 리포지토리는 BR * Tools 명령을 실행하는 사용자의 SnapManager 자격 증명에 의해 결정됩니다.

기본적으로 SnapManager는 SAP 데이터베이스 시스템 식별자와 이름이 같은 프로필을 사용합니다.



== 리포지토리에 액세스하기 위한 자격 증명 생성 정보

'smsap 자격 증명 세트' 명령을 사용하여 BR * Tools 사용자에 대한 리포지토리 자격 증명을 설정할 수 있습니다.



== 다른 SnapManager 프로파일 이름 지정 정보

시스템 식별자가 지정된 리포지토리에 있는 SnapManager 프로파일이 있는 모든 호스트에 대해 고유하면 기본 프로파일 이름만으로도 충분합니다. 데이터베이스 시스템 식별자 값을 사용하여 SnapManager 프로필을 만들고 이름을 지정할 수 있습니다.

그러나 동일한 시스템 식별자가 다른 호스트에서 사용되는 경우 또는 지정된 SAP 인스턴스에서 BR* Tools에 사용할 SnapManager 프로파일을 두 개 이상 지정하려면 BR* Tools 명령에 대한 프로파일 이름을 정의해야 합니다.

SAP 애플리케이션 내에서 예약된 데이터베이스 작업이 사용자로 실행됩니다. BR * SAP 응용 프로그램 내에서 예약된 도구 작업은 'sidadm'으로 실행됩니다. 이러한 사용자는 리포지토리와 프로파일에 대한 액세스 권한이 있어야 합니다.

사용자의 자격 증명을 설정하려면 다음 단계를 수행하십시오.

. 'idadm'으로 로그인합니다.
. 다음 명령을 입력하여 저장소 자격 증명을 설정합니다.
+
'* smssap 자격 증명 세트 명령 *'

. 다음 명령을 입력하여 프로파일을 동기화합니다.
+
'* smssap 프로파일 동기화 * '

. 다음 명령을 입력하여 검색된 프로필의 암호를 설정합니다.
+
'* smsap 자격 증명 세트 * '





== 백업 유틸리티 매개 변수 파일 생성 정보

BR * Tools 명령은 백업 유틸리티 매개 변수(.utl 매개 변수) 파일을 backint 인터페이스에 선택적으로 전달할 수 있습니다. 기본적으로 이 파일의 이름은 initSID.utl이며 여기서 SID는 데이터베이스의 시스템 식별자입니다.

기본적으로 BR * Tools는 'initSID.sap 파일'의 '_util_par_file_' 파라미터로 지정된 파라미터 파일을 사용합니다. 백업 유틸리티 매개변수 파일은 일반적으로 'initSID.sap 파일'과 같은 디렉토리에 저장됩니다.

profile_name=<profile>'을 '.utl' 파일에 추가하고 저장합니다. '_profile_'은 BR * Tools 명령에 사용할 SnapManager 프로파일의 이름입니다.

다음 표에는 백업 보존, 빠른 복원 및 데이터 보호와 같은 작업을 위한 '.utl' 파일에 포함된 추가 백업 유틸리티 매개 변수가 나와 있습니다.

[cols="1a,3a"]
|===
| 운영 | 백업 유틸리티 매개 변수 


 a| 
백업 보존
 a| 
* 키: 유지
* 값: 무제한 | 시간별 | 일별 | 주별 | 월별




 a| 
빠른 복원
 a| 
* 키: 빠릅니다
* 값: |OVERRIDE|FALLBACK|OFF를 필요로 합니다




 a| 
데이터 보호
 a| 
* 키: 보호
* 값: 예 | 아니요 | 비워 둡니다



NOTE: value 매개 변수에 대해 언급한 여러 옵션은 명령줄 인터페이스에 사용되는 '-protect' 옵션과 비슷합니다.



 a| 
보조 스토리지에서 사용자 기본 설정에 따라 위치 세트로 데이터를 백업합니다
 a| 
* 키: preferred_backup_locations
* 값: 데이터 보호 노드 이름을 쉼표로 구분된 목록으로 표시합니다.
* 기본값: 설정된 값이 없습니다.



NOTE: 데이터 보호 정책 노드 이름을 추가하는 방법은 을 참조하십시오 xref:concept-about-different-protection-policies.adoc[보호 정책 설명 정보].



 a| 
보조 스토리지에서 원하는 위치로 데이터를 복원합니다
 a| 
* 키: restore_from_lest_backup_location
* 값: 예 | 아니오
* 기본값: 예


|===
다음 표에는 이러한 작업에 대한 다양한 백업 유틸리티 매개 변수가 설명되어 있습니다.

[cols="1a,1a,1a"]
|===
| 작동 | 키 | 값 


 a| 
백업 보존
 a| 
빠른 속도 =
 a| 
대체



 a| 
빠른 복원
 a| 
유지 =
 a| 
매시간



 a| 
데이터 보호
 a| 
보호 =
 a| 
아니요

|===


== BR * Tools 초기화 파일에 백업 유틸리티 매개 변수 추가

SAP는 각 SAP 데이터베이스 인스턴스에 대해 '$ORACLE_HOME/dbs/'에 initSID.sap'이라는 백업 프로파일 파일을 생성합니다. 이 파일을 사용하여 BR * Tools 명령에 사용되는 기본 백업 유틸리티 매개변수('.utl') 파일을 지정할 수 있습니다.

. initSID.sap 파일을 편집하여 util_par_file="로 시작하는 줄을 찾습니다.
. 이 줄의 주석을 해제하고 프로파일 이름이 포함된 백업 유틸리티 매개 변수 파일에 경로를 추가합니다(예: "util_par_file=initSA1.utl").
. 'util_par_file'에 대한 값을 지정할 경우 파일이 있는지 확인하십시오.
+
파일을 찾을 수 없는 경우 BRBACKUP 명령은 해당 파일을 백업에 포함하려고 하기 때문에 실패합니다.



다음 오류 조건 중 하나라도 발견되면 프로파일 이름으로 '-u' 옵션을 사용해야 합니다.

* 파라미터 파일이 존재하지 않습니다
* profile_name 항목 없음


orasid와 sidadm 모두 BR * Tools로 생성된 백업을 생성하거나 관리하는 데 사용되는 프로파일에 액세스해야 합니다.



== BR * Tools 명령에서 백업 유틸리티 매개변수 파일 이름 지정

필요에 따라 -r 옵션을 사용하여 BR * Tools 명령에 백업 유틸리티 매개 변수(.utl 매개 변수) 파일을 지정할 수 있습니다. 명령줄의 값은 SAP 초기화 파일에 지정된 값을 재정의합니다.

BR * Tools는 '$ORACLE_HOME/dbs/' 디렉토리에서 매개변수 파일을 검색합니다. 파일을 다른 위치에 저장하는 경우 -r 옵션을 사용하여 전체 경로를 제공해야 합니다. 예를 들면 다음과 같습니다.

'*+brbackup-r/opt/netapp_fcp_price_10g_enterprise_inst_vol1/dbs/initcer.utl...+ *'
