---
permalink: unix-administration/reference-the-smosmsapbackup-delete-command.html 
sidebar: sidebar 
keywords: run, backup, delete, command, remove, clone, fail, unlimited, basis, retention, class, smsap 
summary: 실패한 클론 또는 백업을 생성하는 데 사용된 백업과 같이 자동으로 제거되지 않은 백업을 제거하려면 backup delete 명령을 실행할 수 있습니다. 보존 클래스를 변경하지 않고 무제한 유지되는 백업을 삭제할 수 있습니다. 
---
= smsap 백업 삭제 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"backup delete" 명령을 실행하면 클론 생성에 사용된 백업이나 실패한 백업 등 자동으로 제거되지 않은 백업을 제거할 수 있습니다. 보존 클래스를 변경하지 않고 무제한 유지되는 백업을 삭제할 수 있습니다.



== 구문

[listing, subs="+macros"]
----
pass:quotes[smsap backup delete
-profile _profile_name_
[-label _label_ [-data | -archivelogs\] | [-id _guid_ | -all\]
-force
[-dump\]
[-quiet | -verbose\]]
----


== 매개 변수

* '*-profile_profile_name_*'
+
제거할 백업과 관련된 데이터베이스를 지정합니다. 프로파일에는 데이터베이스의 식별자와 기타 데이터베이스 정보가 들어 있습니다.

* '*-id_GUID_*'
+
지정된 GUID를 사용하여 백업을 지정합니다. GUID는 백업을 생성할 때 SnapManager에 의해 생성됩니다. 'smsap backup list' 명령을 사용하여 각 백업의 GUID를 표시할 수 있습니다.

* '*-label_label_ *'
+
지정된 레이블을 사용하여 백업을 지정합니다. 필요에 따라 백업 범위를 데이터 파일 또는 아카이브 로그로 지정합니다.

* '*-data*'
+
데이터 파일을 지정합니다.

* ``archivelogs*’
+
아카이브 로그 파일을 지정합니다.

* '*-모두 *'
+
모든 백업을 지정합니다. 지정된 백업만 삭제하려면 '-id' 또는 '-label' 옵션을 사용합니다.

* '*-dump*'
+
백업 삭제 작업에 성공하거나 실패한 후 덤프 파일을 수집합니다.

* '*-force * '
+
백업을 강제로 제거합니다. SnapManager는 백업과 관련된 리소스를 해제하는 데 문제가 있더라도 백업을 제거합니다. 예를 들어 백업이 Oracle RMAN(Recovery Manager)으로 카탈로그에 기록되었지만 RMAN 데이터베이스가 더 이상 존재하지 않는 경우, "-force"를 포함하여 RMAN에 연결할 수 없더라도 백업을 삭제합니다.

* ``조용한’’’
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* '*-verbose * '
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.



'''


== 예

다음 예제에서는 백업을 삭제합니다.

[listing]
----
smsap backup delete -profile SALES1 -label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
'''