---
permalink: unix-administration/reference-troubleshooting-graphical-user-interface-issues.html 
sidebar: sidebar 
keywords: information, common, graphical, user, interface, gui, issue, resolve, troubleshooting 
summary: '일반적인 그래픽 사용자 인터페이스(GUI) 문제 해결에 도움이 되는 몇 가지 일반적인 문제에 대한 정보를 찾을 수 있습니다.' 
---
= 그래픽 사용자 인터페이스 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일반적인 그래픽 사용자 인터페이스(GUI) 문제 해결에 도움이 되는 몇 가지 일반적인 문제에 대한 정보를 찾을 수 있습니다.

|===
| 문제 | 설명 | 해결 방법 


 a| 
작업을 수행하기 위해 SnapManager GUI에 액세스하는 동안 '호스트에서 사용자에 대한 인증에 실패했습니다.'라는 오류 메시지가 표시될 수 있습니다
 a| 
이 문제는 SnapManager 서버가 실행 중인 호스트에서 사용자의 암호가 변경된 경우 발생합니다. 암호가 변경된 후 GUI를 시작한 사용자에 대해 생성된 자격 증명 캐시가 무효화됩니다. SnapManager GUI는 여전히 캐시의 자격 증명을 사용하여 인증하므로 인증에 실패합니다.
 a| 
다음 작업 중 하나를 수행해야 합니다.

* 암호가 변경된 사용자의 자격 증명을 삭제한 후 다음 명령을 실행하여 캐시에 새 자격 증명을 추가합니다.
+
.. '스맵 인증정보 삭제
.. '맵 자격 증명 세트'


* 'msap 자격 증명 clear 명령'을 실행하여 전체 캐시를 지웁니다. 메시지가 나타나면 GUI를 다시 열고 자격 증명을 설정합니다.




 a| 
Java 웹 시작을 사용하여 SnapManager GUI에 액세스하는 동안 보안 경고가 표시됩니다.
 a| 
Java 웹 시작을 사용하여 SnapManager GUI에 액세스하는 동안 보안 경고가 표시됩니다. 이 문제는 JNLP jar가 자체 서명되고 SnapManager에서 사용하는 Java 버전이 높은 보안 수준에서 자체 서명된 jar를 허용하지 않기 때문에 발생합니다.
 a| 
Java 제어판에서 보안 설정을 보통 으로 변경하거나 SnapManager GUI URL을 예외 목록에 추가합니다.



 a| 
SnapManager 웹 시작 GUI에 잘못된 버전이 표시됩니다.
 a| 
웹 시작 GUI를 시작할 때 최신 버전에서 이전 버전으로 SnapManager를 다운그레이드한 후 최신 버전의 SnapManager 웹 시작 GUI가 시작됩니다.
 a| 
다음 단계를 수행하여 캐시를 지워야 합니다.

. 콘솔을 시작합니다.
. ' * javaws-viewer *'를 입력합니다
. Java 캐시 뷰어 화면에서 SnapManager 응용 프로그램을 마우스 오른쪽 단추로 클릭하고 * 삭제 * 를 선택합니다.




 a| 
GUI를 다시 시작하고 특정 프로파일의 백업을 확인하려고 하면 프로파일의 이름만 표시됩니다.
 a| 
SnapManager는 사용자가 프로파일을 열 때까지 프로파일에 대한 정보를 표시하지 않습니다.
 a| 
다음 단계를 수행하십시오.

. 프로파일을 마우스 오른쪽 단추로 클릭하고 메뉴에서 * 열기 * 를 선택합니다.
+
SnapManager 프로파일 인증 대화 상자가 표시됩니다.

. 호스트 사용자 이름과 암호를 입력합니다.
+
SnapManager 백업 목록이 표시됩니다.




NOTE: 자격 증명이 유효하고 캐시에 남아 있는 한 프로필을 한 번만 인증하면 됩니다.



 a| 
GUI에서 첫 번째 리포지토리를 열면 '프로파일 이름 XXXX가 이전에 로드된 리포지토리와 충돌합니다.'와 유사한 오류 메시지가 표시됩니다
 a| 
동일한 이름의 프로파일이 리포지토리에 존재할 수 없습니다. 또한 한 번에 하나의 리포지토리만 열 수 있습니다.
 a| 
서로 다른 두 운영 체제(OS) 사용자의 충돌하는 프로파일을 참조하거나 리포지토리에 대한 SQL 문을 실행하여 프로파일의 이름을 변경합니다. "* update SMSAP_33_profile set name='new_name' where name='old_name' * "



 a| 
SMSAP-01092:'Unable to initialize reRepository repo1@이(가) 없습니다. repo1SMSAP-11006: Cannot resolve host is not exist.' 오류 메시지가 표시됩니다
 a| 
리포지토리는 더 이상 존재하지 않기 때문에 액세스할 수 없습니다. GUI는 자격 증명 파일에서 리포지토리 목록을 초기화합니다.
 a| 
이 리포지토리를 제거할지 묻는 오류 메시지가 나타나서 나중에 로드하지 않도록 합니다. 이 리포지토리에 액세스할 필요가 없으면 * 삭제 * 를 클릭하여 GUI 보기에서 제거합니다. 이렇게 하면 자격 증명 파일의 리포지토리에 대한 참조가 제거되고 GUI는 리포지토리를 다시 로드하지 않습니다.



 a| 
SUSE Linux Enterprise Server 10 및 SUSE Linux Enterprise Server 11 플랫폼에서 호스트 자격 증명이 인증에 실패하여 프로필을 생성하지 못했습니다.
 a| 
SnapManager는 PAM(Pluggable Authentication Module)을 사용하여 사용자를 인증합니다. SUSE Linux Enterprise Server 버전 10 및 11 플랫폼에서는 필요한 인증 세부 정보를 제공하는 '/etc/pam.d' 디렉토리에 기본적으로 SnapManager 파일이 없습니다. 따라서 호스트 자격 증명이 실패합니다.
 a| 
SUSE Linux Enterprise Server 10 및 11 플랫폼에서 호스트에 로그인하려면 다음 단계를 수행하십시오.

. '/etc/pam.d/.'에 SnapManager 파일을 만듭니다
. 다음 내용을 ``etc/pam.d/sSnapManager:”에 있는 'SnapManager' 파일에 추가합니다
+
[listing]
----

#%PAM-1.0
auth     include   common-auth
account  include   common-account
password include   common-password
session  include   common-session
----
. 파일을 저장하고 프로파일 생성 작업을 다시 시도하십시오.




 a| 
SnapManager는 데이터베이스 트리 구조를 로드하는 데 시간이 더 오래 걸리고 SnapManager GUI에 시간 초과 오류 메시지가 표시됩니다.
 a| 
SnapManager GUI에서 부분 백업 작업을 수행하려고 하면 SnapManager는 모든 프로필에 대한 자격 증명을 로드하려고 시도합니다. 잘못된 항목이 있으면 SnapManager가 해당 항목의 유효성을 검사하려고 하면 시간 초과 오류 메시지가 표시됩니다.
 a| 
SnapManager CLI(Command-Line Interface)에서 'credentials delete' 명령을 사용하여 미사용 호스트, 리포지토리 및 프로파일의 자격 증명을 삭제합니다.



 a| 
클론 분할 작업 후 SnapManager에서 새 프로파일을 생성하지 못하고 새 프로파일이 생성되는지 여부를 알 수 없습니다.
 a| 
클론 분할 작업 후 새 프로파일이 생성되지 않으면 SnapManager에서 메시지를 표시하지 못합니다. 실패한 작업에 대해 메시지가 표시되지 않으므로 프로파일이 만들어진 것으로 가정할 수 있습니다.
 a| 
클론 분할 작업을 위해 새 프로파일이 생성되는지 확인하려면 다음 단계를 수행하십시오.

. 모니터 * 탭을 클릭하고 클론 분할 작업 항목을 마우스 오른쪽 버튼으로 클릭한 다음 * 속성 * 을 선택합니다.
. 프로파일 속성 창에서 * 로그 * 탭을 클릭하여 클론 분할 작업 및 프로파일 생성 로그를 확인합니다.




 a| 
백업, 복원 또는 클론 작업 전후에 발생하는 전처리 또는 후처리 작업에 대한 사용자 정의 스크립트는 SnapManager GUI에서 볼 수 없습니다.
 a| 
해당 마법사를 시작한 후 사용자 지정 백업, 복원 또는 클론 스크립트 위치에 사용자 지정 스크립트를 추가하면 사용 가능한 스크립트 목록에 사용자 지정 스크립트가 표시되지 않습니다.
 a| 
SnapManager 호스트 서버를 다시 시작한 다음 SnapManager GUI를 엽니다.



 a| 
클론 작업에 SnapManager(3.1 이하)에서 생성된 클론 사양 XML 파일을 사용할 수 없습니다.
 a| 
SAP용 SnapManager 3.2에서 작업 사양 섹션(작업 사양)은 별도의 작업 사양 XML 파일로 제공됩니다.
 a| 
SAP용 SnapManager 3.2를 사용하는 경우 클론 사양 XML에서 작업 사양 섹션을 제거하거나 새 클론 사양 XML 파일을 만들어야 합니다. SnapManager 3.3 이상은 SnapManager 3.2 이하 릴리스에서 생성된 클론 사양 XML 파일을 지원하지 않습니다.



 a| 
SnapManager CLI에서 'smsap 자격 증명 지우기' 명령을 사용하거나 SnapManager GUI에서 * 관리자 * > * 자격 증명 * > * 자격 증명 * > * 지우기 * > * 캐시 * 를 클릭하여 사용자 자격 증명을 지웠을 때 GUI에서 SnapManager 작업이 진행되지 않습니다.
 a| 
리포지토리, 호스트 및 프로파일에 대해 설정된 자격 증명이 지워집니다. SnapManager는 작업을 시작하기 전에 사용자 자격 증명을 확인합니다. 사용자 자격 증명이 유효하지 않으면 SnapManager에서 인증에 실패합니다. 호스트 또는 프로파일이 리포지토리에서 삭제되어도 캐시에서 사용자 자격 증명을 사용할 수 있습니다. 이러한 불필요한 자격 증명 항목은 GUI에서 SnapManager 작업을 느리게 합니다.
 a| 
캐시가 지워지는 방식에 따라 SnapManager GUI를 다시 시작합니다.

[NOTE]
====
* SnapManager GUI에서 자격 증명 캐시를 지운 경우에는 SnapManager GUI를 종료할 필요가 없습니다.
* SnapManager CLI에서 자격 증명 캐시를 지운 경우 SnapManager GUI를 다시 시작해야 합니다.
* 암호화된 자격 증명 파일을 수동으로 삭제한 경우 SnapManager GUI를 다시 시작해야 합니다.


====
리포지토리, 프로필 호스트 및 프로필에 대해 제공한 자격 증명을 설정합니다. SnapManager GUI에서 리포지토리 트리 아래에 매핑된 리포지토리가 없는 경우 다음 단계를 수행합니다.

. 작업 * > * 기존 리포지토리 추가 * 를 클릭합니다
. 리포지토리를 마우스 오른쪽 단추로 클릭하고 * 열기 * 를 클릭한 다음 * 리포지토리 자격 증명 인증 * 창에 사용자 자격 증명을 입력합니다.
. 리포지토리 아래에서 호스트를 마우스 오른쪽 단추로 클릭하고 * Open * 을 클릭한 다음 * Host Credentials Authentication * 에 사용자 자격 증명을 입력합니다.
. 호스트 아래에서 프로파일을 마우스 오른쪽 단추로 클릭하고 * 열기 * 를 클릭한 다음 * 프로파일 자격 증명 인증 * 에 사용자 자격 증명을 입력합니다.




 a| 
프로파일 속성 창의 * 보호 관리자 보호 정책 * 드롭다운 메뉴와 프로파일 생성 마법사의 정책 설정 페이지에서 * 없음 * 을 선택하면 "다음 이유로 보호 정책을 나열할 수 없습니다: 보호 관리자를 일시적으로 사용할 수 없습니다" 오류 메시지가 표시됩니다.
 a| 
Protection Manager가 SnapManager로 구성되지 않았거나 Protection Manager가 실행되고 있지 않습니다.
 a| 
별도의 조치가 필요하지 않습니다.



 a| 
브라우저의 취약한 SSL(Secure Sockets Layer) 암호화 강도로 인해 Java 웹 시작 GUI를 사용하여 SnapManager GUI를 열 수 없습니다.
 a| 
SnapManager는 128비트 미만의 SSL 암호를 지원하지 않습니다.
 a| 
브라우저 버전을 업그레이드하고 암호화 강도를 확인합니다.

|===