---
permalink: unix-administration/reference-troubleshooting-storage-system-renaming-issue.html 
sidebar: sidebar 
keywords: face, issue, renaming, rename, storage, system, successful, troubleshooting 
summary: 스토리지 시스템의 이름을 바꾸거나 스토리지 시스템의 이름을 성공적으로 바꾼 후에 문제가 발생할 수 있습니다. 
---
= 스토리지 시스템의 이름 바꾸기 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템의 이름을 바꾸거나 스토리지 시스템의 이름을 성공적으로 바꾼 후에 문제가 발생할 수 있습니다.

스토리지 시스템의 이름을 변경하려고 할 때 'MSSAP-05085 스토리지 컨트롤러 "FAS3020-rtp07New"가 프로파일과 연결된 것으로 검색되지 않습니다.'라는 오류 메시지가 나타나면서 작업이 실패할 수 있습니다

'smsap storage list' 명령을 실행할 때 나열되는 스토리지 시스템의 IP 주소 또는 이름을 입력해야 합니다.

스토리지 시스템의 이름을 변경한 후 SnapManager에서 스토리지 시스템을 인식하지 못하면 SnapManager 작업이 실패할 수 있습니다. 이 문제를 해결하려면 DataFabric Manager 서버 호스트 및 SnapManager 서버 호스트에서 몇 가지 추가 단계를 수행해야 합니다.

DataFabric Manager 서버 호스트에서 다음 단계를 수행합니다.

. DataFabric Manager 서버 호스트의 ''/etc/hosts'에 있는 호스트 파일에서 이전 스토리지 시스템의 IP 주소와 호스트를 삭제합니다.
. DataFabric Manager 서버 호스트의 ''/etc/hosts'에 있는 호스트 파일에 새 스토리지 시스템의 새 IP 주소와 호스트를 추가합니다.
. 다음 명령을 입력하여 스토리지 호스트 이름을 변경합니다.
+
'* DFM 호스트 이름 바꾸기 -a_old_host_namenew_host_name_ *

. 다음 명령을 입력하여 호스트에 새 IP 주소를 설정합니다.
+
'* DFM 호스트 set_old_host_name_or_objId_hostPrimaryAddress=_new_storage_controller_ip_address_ *'

+

NOTE: IP 주소를 새 스토리지 시스템 이름으로 지정한 경우에만 이 단계를 수행해야 합니다.

. 다음 명령을 입력하여 DataFabric Manager 서버 호스트에서 새 스토리지 시스템 이름을 업데이트합니다.
+
'* DFM 호스트 diag_old_storage_name_ *

+
다음 명령을 입력하여 이전 스토리지 컨트롤러 이름이 새 스토리지 컨트롤러 이름으로 교체되었는지 확인할 수 있습니다.

+
' * DFM host Discover new_storage_name * '



SnapManager 서버 호스트에서 루트 사용자로 다음 단계를 수행합니다.


NOTE: 새 스토리지 컨트롤러 이름을 입력할 때는 FQDN(정규화된 도메인 이름)이 아니라 시스템 별칭 이름을 사용해야 합니다.

. 다음 명령을 입력하여 이전 스토리지 시스템 이름을 삭제합니다.
+
'* SnapDrive config delete_old_storage_name_ * '

+

NOTE: 이전 스토리지 시스템 이름을 삭제하지 않으면 모든 SnapManager 작업이 실패합니다.

. 타겟 데이터베이스 호스트의 "etc/hosts"에 있는 호스트 파일에서 이전 스토리지 시스템의 IP 주소와 호스트를 삭제합니다.
. 타겟 데이터베이스 호스트의 ''/etc/hosts'에 있는 호스트 파일에 새 IP 주소와 새 스토리지 시스템의 호스트를 추가합니다.
. 다음 명령을 입력하여 새 스토리지 시스템 이름을 추가합니다.
+
'* SnapDrive config set root_new_storage_name_ * '

. 다음 명령을 입력하여 이전 및 이후 스토리지 시스템 이름을 매핑합니다.
+
'* SnapDrive config migrate set_old_storage_namenew_storage_name_ *

. 다음 명령을 입력하여 이전 스토리지 시스템의 관리 경로를 삭제합니다.
+
``SnapDrive config delete -mgmtpath_old_storage_name_*'

. 다음 명령을 입력하여 새 스토리지 시스템의 관리 경로를 추가합니다.
+
'* SnapDrive config set-mgmtpath_new_storage_name_ *'

. 다음 명령을 입력하여 데이터 파일과 아카이브 로그 파일 모두에 대한 데이터 세트를 새 스토리지 시스템 이름으로 업데이트합니다.
+
'* SnapDrive 데이터세트 변경 호스트 이름 - dn_dataset_name_-oldname_old_storage_name_-newname_new_storage_name_ *

. 다음 명령을 입력하여 새 스토리지 시스템 이름의 프로필을 업데이트합니다.
+
'* smssap 스토리지 이름 변경 -profile_profile_name_-oldname_old_storage_name_-newname_new_storage_name_ *

. 다음 명령을 입력하여 프로파일에 연결된 스토리지 시스템을 확인합니다.
+
'* smssap 저장 목록 - profile_profile_name_*'


