---
permalink: unix-administration/reference-the-smosmsapbackup-create-command.html 
sidebar: sidebar 
keywords: run, backup, create, command, database, storage, system, smsap 
summary: backup create 명령을 실행하여 하나 이상의 스토리지 시스템에서 데이터베이스 백업을 생성할 수 있습니다. 
---
= smsap 백업 create 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"backup create" 명령을 실행하여 하나 이상의 스토리지 시스템에 데이터베이스 백업을 생성할 수 있습니다.



== 구문


NOTE: 이 명령을 실행하기 전에 profile create 명령을 사용하여 데이터베이스 프로필을 만들어야 합니다.

[listing, subs="+macros"]
----
pass:quotes[smsap backup create
-profile profile_name
{[-full{-auto | -online | -offline} [-retain {_-hourly_ | _-daily_ | _-weekly_ | _-monthly_ | _-unlimited_} [-verify\]  |
[-data [[-files _files_ [_files_]] |
pass:quotes[[-tablespaces _tablespaces_ [_tablespaces_]] pass:quotes[[-label _label_]] {-auto | -online | -offline}
pass:quotes[[-retain {_-hourly_ | _-daily_ | _-weekly_ | _-monthly_ | _-unlimited_} [-verify] |
pass:quotes[[-archivelogs [-label _label_]] pass:quotes[[-comment _comment_\]}
[-protect | -noprotect | -protectnow\]
[-backup-dest _path1_ [ _, path2_\]\]
[-exclude-dest path1 [ _, path2_\]\]
[-prunelogs {-all | -until-scn _until-scn_ | -until-date _yyyy-MM-dd:HH:mm:ss_\] | -before {-months | -days | -weeks | -hours}}
-prune-dest _prune_dest1_,[_prune_dest2_\]\]
[-taskspec _taskspec_\]
[-dump]-force
[-quiet | -verbose]]
----


== 매개 변수

* '*-profile_profile_name_*'
+
백업할 데이터베이스와 관련된 프로파일의 이름을 지정합니다. 프로파일에는 데이터베이스의 식별자와 기타 데이터베이스 정보가 들어 있습니다.

* '*-auto*' * 옵션 *
+
데이터베이스가 마운트됨 또는 오프라인 상태인 경우 SnapManager는 오프라인 백업을 수행합니다. 데이터베이스가 열려 있거나 온라인 상태인 경우 SnapManager는 온라인 백업을 수행합니다. '-offline' 옵션과 함께 '-force' 옵션을 사용하면 데이터베이스가 현재 온라인 상태인 경우에도 SnapManager가 오프라인 백업을 강제 적용합니다.

* '*-online*' * 옵션 *
+
온라인 데이터베이스 백업을 지정합니다.

+
운영 데이터베이스가 열려 있거나 운영 데이터베이스가 마운트되어 있고 인스턴스가 열려 있는 경우 RAC(Real Application Clusters) 데이터베이스의 온라인 백업을 생성할 수 있습니다. 로컬 인스턴스가 종료 상태이거나 열려 있는 인스턴스가 없는 경우 온라인 백업에 '-force' 옵션을 사용할 수 있습니다. Oracle 버전은 10.2.0.5여야 합니다. 그렇지 않으면 RAC의 인스턴스가 마운트된 경우 데이터베이스가 중단됩니다.

+
** 로컬 인스턴스가 종료 상태에 있고 하나 이상의 인스턴스가 열린 상태인 경우 '-force' 옵션을 사용하여 로컬 인스턴스를 마운트된 상태로 변경할 수 있습니다.
** 열려 있는 인스턴스가 없으면 -force 옵션을 사용하여 로컬 인스턴스를 열린 상태로 변경할 수 있습니다.


* '*-offline*' * 옵션 *
+
데이터베이스가 종료 상태에 있는 동안 오프라인 백업을 지정합니다. 데이터베이스가 열림 또는 마운트됨 상태인 경우 백업이 실패합니다. '-force' 옵션을 사용하면 SnapManager에서 오프라인 백업을 위해 데이터베이스를 종료하기 위해 데이터베이스 상태를 변경하려고 시도합니다.

* '*-full*' * 옵션 *
+
전체 데이터베이스를 백업합니다. 여기에는 모든 데이터, 보관된 로그 및 제어 파일이 포함됩니다. 아카이빙된 redo 로그 및 제어 파일은 수행하는 백업 유형에 관계없이 백업됩니다. 데이터베이스의 일부만 백업하려면 '-files' 옵션 또는 '-tablespaces' 옵션을 사용합니다.

* '*-data*' * 옵션 *
+
데이터 파일을 지정합니다.

* '*-files_list_ *'
+
지정된 데이터 파일과 아카이브된 로그 및 제어 파일만 백업합니다. 파일 이름 목록을 공백으로 구분합니다. 데이터베이스가 열린 상태인 경우 SnapManager는 해당 테이블스페이스가 온라인 백업 모드에 있는지 확인합니다.

* ' * - 테이블스페이스_테이블스페이스_ * '
+
지정된 데이터베이스 테이블스페이스와 아카이브된 로그 및 제어 파일만 백업합니다. 테이블스페이스 이름을 공백으로 구분합니다. 데이터베이스가 열린 상태인 경우 SnapManager는 해당 테이블스페이스가 온라인 백업 모드에 있는지 확인합니다.

* '*-label_label_ *'
+
이 백업의 선택적 이름을 지정합니다. 이 이름은 프로파일 내에서 고유해야 합니다. 이름에는 문자, 숫자, 밑줄(_) 및 하이픈(-)이 포함될 수 있습니다. 하이픈으로 시작할 수 없습니다. 레이블을 지정하지 않으면 SnapManager는 SCOPE_TYPE_DATE 형식으로 기본 레이블을 만듭니다.

+
** 범위는 전체 백업을 나타내는 F 또는 부분 백업을 나타내는 P입니다.
** 오프라인(콜드) 백업을 나타내는 C, 온라인(핫) 백업을 나타내는 H 또는 자동 백업을 나타내는 A입니다(예: P_A_20081010060037IST).
** date는 백업의 년, 월, 일 및 시간입니다.
+
SnapManager는 24시간 시계를 사용합니다.



+
예를 들어 2007년 1월 16일 오후 5:45:16에 데이터베이스를 오프라인으로 사용하여 전체 백업을 수행한 경우 동부 표준 시간, SnapManager는 F_C_20070116174516EST 라벨을 작성합니다.

* '*-comment_string_ *'
+
이 백업을 설명하는 선택적 주석을 지정합니다. 문자열을 작은따옴표(')로 묶어야 합니다.

+

NOTE: 일부 셸은 따옴표를 해제합니다. 이 경우 백슬래시(\)로 따옴표(\)를 포함해야 합니다. 예를 들어, 다음과 같이 입력해야 할 수 있습니다: `\'이것은 코멘트\''.

* '*-verify*' * 옵션 *
+
Oracle dbv 유틸리티를 실행하여 백업의 파일이 손상되지 않았는지 확인합니다.

+

NOTE: '-verify' 옵션을 지정하면 검증 작업이 완료될 때까지 백업 작업이 완료되지 않습니다.

* '*-force * ' * 옵션 *
+
데이터베이스가 올바른 상태가 아닐 경우 상태를 변경합니다. 예를 들어 SnapManager는 사용자가 지정한 백업 유형과 데이터베이스가 있는 상태에 따라 데이터베이스의 상태를 온라인에서 오프라인으로 변경할 수 있습니다.

+
온라인 RAC 데이터베이스 백업의 경우 로컬 인스턴스가 종료 상태에 있거나 열려 있는 인스턴스가 없으면 '-force' 옵션을 사용합니다.

+

NOTE: Oracle 버전은 10.2.0.5여야 합니다. 그렇지 않으면 RAC의 인스턴스가 마운트된 경우 데이터베이스가 중단됩니다.

+
** 로컬 인스턴스가 종료 상태에 있고 하나 이상의 인스턴스가 열린 상태인 경우 '-force' 옵션을 사용하면 로컬 인스턴스가 마운트된 상태로 변경됩니다.
** 열려 있는 인스턴스가 없으면 '-force' 옵션을 사용하면 로컬 인스턴스가 열린 상태로 변경됩니다.


* ``조용한’’’
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* '*-verbose * '
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.

* ``보호|-노보호|-보호트노 *’
+
백업을 보조 스토리지로 보호해야 하는지 여부를 나타냅니다. noProtect 옵션은 백업을 보조 스토리지로 보호하지 않도록 지정합니다. 전체 백업만 보호됩니다. 두 옵션을 모두 지정하지 않으면 SnapManager는 백업이 전체 백업이고 프로파일이 보호 정책을 지정하는 경우 백업을 기본값으로 보호합니다. '-protectnow' 옵션은 7-Mode에서 작동하는 Data ONTAP에만 적용됩니다. 옵션은 백업이 보조 스토리지로 즉시 보호되도록 지정합니다.

* ``보존{-hourly|-daily|-weekly|-monthly|-limited} *’
+
백업을 매시간, 매일, 매주, 매월 또는 무제한 단위로 보존할지 여부를 지정합니다. retain 옵션을 지정하지 않으면 retention class는 기본적으로 `-hourly' 옵션을 사용합니다. 백업을 영구적으로 보존하려면 '-unlimited' 옵션을 사용하십시오. 무제한 옵션을 사용하면 보존 정책에 따라 백업을 삭제할 수 없습니다.

* '*-archivelogs*' * 옵션 *
+
아카이브 로그 백업을 생성합니다.

* "*-backup-dest_path1_, [,_[path2]_] *
+
아카이브 로그 백업을 위해 백업할 아카이브 로그 대상을 지정합니다.

* '*-exclude-dest_path1_, [,_[path2]_] *'
+
백업에서 제외할 아카이브 로그 대상을 지정합니다.

* '*-prunelogs{-all|-until-scnuntil-scn|-until-date_yyyy-mm-dd:HH:MM:ss_|-before{-months|-days|-weeks|-hours} *'
+
백업을 생성하는 동안 제공된 옵션을 기반으로 아카이브 로그 대상에서 아카이브 로그 파일을 삭제합니다. '-ALL' 옵션은 보관 로그 대상에서 모든 보관 로그 파일을 삭제합니다. '-until-scn' 옵션은 지정된 SCN(시스템 변경 번호)이 될 때까지 보관 로그 파일을 삭제합니다. '-date' 옵션은 지정된 시간까지 아카이브 로그 파일을 삭제합니다. '-before' 옵션은 지정된 기간(일, 월, 주, 시간) 이전에 아카이브 로그 파일을 삭제합니다.

* '*-prune-dest_prune_dest1, prune_dest2_ *'
+
백업을 생성하는 동안 아카이브 로그 대상에서 아카이브 로그 파일을 삭제합니다.

* ``taskspec_taskspec_*'
+
백업 작업의 사전 처리 작업 또는 사후 처리 작업에 사용할 수 있는 작업 사양 XML 파일을 지정합니다. taskspec 옵션을 제공하는 동안 XML 파일의 전체 경로를 제공해야 합니다.

* '*-dump*' * 옵션 *
+
데이터베이스 백업 작업이 성공하거나 실패한 후 덤프 파일을 수집합니다.



'''


== 명령 예

다음 명령을 실행하면 전체 온라인 백업이 생성되고 보조 스토리지에 백업이 생성되고 보존 정책이 매일 으로 설정됩니다.

[listing]
----
smsap backup create -profile SALES1 -full -online
-label full_backup_sales_May -profile SALESDB -force -retain -daily
Operation Id [8abc01ec0e79356d010e793581f70001] succeeded.
----
'''