---
permalink: unix-administration/reference-the-smosmsap-notification-set-command.html 
sidebar: sidebar 
keywords: notification, set, command, configure, mail, server, smsap 
summary: notification set 명령을 사용하여 메일 서버를 구성할 수 있습니다. 
---
= smsap notification set 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'notification set' 명령어를 이용하여 메일 서버를 설정할 수 있다.



== 구문

[listing, subs="+macros"]
----
pass:quotes[smsap notification set
-sender-email _email_address_
-mailhost _mailhost_
-mailport _mailport_
[-authentication
-username _username_
-password _password_]]
pass:quotes[-repository
-dbname _repo_service_name_
-port _repo_port_]]
pass:quotes[-host _repo_host_
-login -username _repo_username_
[-quiet | -verbose]]

----


== 매개 변수

* '*-sender-email_email_address_ *'
+
e-메일 알림을 보낼 보낸 사람의 e-메일 주소를 지정합니다. SAP용 SnapManager 3.2에서는 전자 메일 주소의 도메인 이름을 지정하는 동안 하이픈(-)을 포함할 수 있습니다. 예를 들어 보낸 사람 전자 메일 주소를 -sender-email07lbfmdatacenter@continental-corporation.com 으로 지정할 수 있습니다.

* '*-mailhost_mailhost_*'
+
e-메일 알림을 처리하는 호스트 서버의 이름 또는 IP 주소를 지정합니다.

* '*-mailport_mailport_*'
+
메일 서버 포트 번호를 지정합니다.

* '*-authentication-username_username_-password_password_ *'
+
전자 메일 주소에 대한 인증 세부 정보를 지정합니다. 사용자 이름과 암호를 지정해야 합니다.

* '*-repository*'
+
리포지토리 데이터베이스의 세부 정보를 지정합니다.

* '*-port_repo_port_ *'
+
리포지토리 데이터베이스에 액세스하는 데 사용되는 TCP(Transmission Control Protocol) 포트 번호를 지정합니다.

* '*-dbname_repo_service_name_ *'
+
리포지토리 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 시스템 식별자를 사용할 수 있습니다.

* '*-host_repo_host_ *'
+
저장소 데이터베이스가 있는 호스트의 이름 또는 IP 주소를 지정합니다.

* ' * - 로그인 * '
+
리포지토리 로그인 세부 정보를 지정합니다. 이는 선택 사항입니다. 지정되지 않은 경우 SnapManager는 기본적으로 OS 인증 연결 모드로 설정됩니다.

* '*-username_repo_username_ *'
+
리포지토리 데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.

* ``조용한’’’
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* '*-verbose * '
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.



'''


== 예

다음 예에서는 메일 서버를 구성합니다.

[listing]
----
smsap notification set -sender-email admin@org.com -mailhost hostname.org.com -mailport 25 authentication -username davis -password davis -repository -port 1521 -dbname SMSAPREPO -host hotspur
-login -username grabal21 -verbose
----
'''