---
permalink: unix-administration/reference-the-smosmsapprofile-create-command.html 
sidebar: sidebar 
keywords: run, profile, create, command, database, repository, mount, smsap 
summary: profile create 명령을 실행하여 리포지토리에 데이터베이스의 프로필을 만들 수 있습니다. 이 명령을 실행하기 전에 데이터베이스를 마운트해야 합니다. 
---
= smssap profile create 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"profile create" 명령을 실행하여 리포지터리에 데이터베이스의 프로필을 만들 수 있습니다. 이 명령을 실행하기 전에 데이터베이스를 마운트해야 합니다.



== 구문

[listing, subs="+macros"]
----
pass:quotes[smsap profile create
-profile _profile_ [-profile-password _profile_password_\]
-repository
-dbname _repo_service_name_
-host _repo_host_
-port _repo_port_
-login -username _repo_username_
-database
-dbname _db_dbname_
-host _db_host_
[-sid  _db_sid_\]
[-login
[-username _db_username_ -password _db_password_ -port _db_port_\]
[-asminstance -asmusername _asminstance_username_  -asmpassword _asminstance_password_\]]
[-rman {-controlfile | {-login
pass:quotes[-username  _rman_username_ -password  _rman_password_\}
-tnsname  _rman_tnsname_}}]]
pass:quotes[[-osaccount _osaccount_]] pass:quotes[[-osgroup _osgroup_]]
[-retain
pass:quotes[[-hourly [-count _n_]] pass:quotes[[-duration _m_]]]
pass:quotes[[-daily [-count _n_]] pass:quotes[[-duration _m_]]]
pass:quotes[[-weekly [-count _n_]] pass:quotes[[-duration _m_]]]
pass:quotes[[-monthly [-count _n_]] pass:quotes[[-duration _m_]]]]]
pass:quotes[-comment _comment_
-snapname-pattern _pattern_
[-protect \[-protection-policy _policy_]]
[-summary-notification]
[-notification
[-success
pass:quotes[-email _email_address1,email_address2_
-subject _subject_pattern_]]
[-failure
pass:quotes[-email _email_address1,email_address2_
-subject _subject_pattern_]]
[-separate-archivelog-backups -retain-archivelog-backups pass:quotes[-hours _hours_ |
-days _days_ |
-weeks _weeks_ |
-months _months_
[-protect [-protection-policy _policy_name_ | -noprotect]
[-include-with-online-backups | -no-include-with-online-backups]]
[-dump]
[-quiet | -verbose]
----


== 매개 변수

* ``프로파일_프로파일_*'
+
프로파일의 이름을 지정합니다. 이 이름은 최대 30자까지 지정할 수 있으며 호스트 내에서 고유해야 합니다.

* '' * -profile-password_profile_password_ *'
+
프로파일의 암호를 지정합니다.

* ``리포지터리 *’’
+
리포지터리 다음에 나오는 옵션은 프로파일을 저장하는 데이터베이스의 세부 사항을 지정합니다.

* ``dbname_repo_service_name_*'
+
프로필을 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.

* ``숙주_repo_host_*'
+
리포지토리 데이터베이스가 실행되는 호스트 컴퓨터의 이름 또는 IP 주소를 지정합니다.

* ``sid_db_sid_*'
+
프로파일이 설명하는 데이터베이스의 시스템 식별자를 지정합니다. 기본적으로 SnapManager에서는 데이터베이스 이름을 시스템 식별자로 사용합니다. 시스템 식별자가 데이터베이스 이름과 다른 경우 '-sid' 옵션을 사용하여 지정해야 합니다.

+
예를 들어 Oracle RAC(Real Application Clusters)를 사용하는 경우 SnapManager가 실행되는 RAC 노드에 있는 RAC 인스턴스의 시스템 식별자를 지정해야 합니다.

* ``로그인 *’’
+
리포지토리 로그인 세부 정보를 지정합니다.

* ``username_repo_username_*'
+
리포지토리 데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.

* ``port_repo_port_*’
+
리포지토리 데이터베이스에 액세스하는 데 사용되는 TCP 포트 번호를 지정합니다.

* ``데이터베이스’’’
+
프로필에 설명된 데이터베이스의 세부 정보를 지정합니다. 이 데이터베이스는 백업, 복원 또는 클론이 생성될 데이터베이스입니다.

* ``dbname_db_dbname_*'
+
프로파일이 설명하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 시스템 식별자를 사용할 수 있습니다.

* ``호스트 db_host_db_host_*'
+
데이터베이스가 실행되는 호스트 컴퓨터의 이름 또는 IP 주소를 지정합니다.

* ``아스미나스’’’
+
ASM(Automatic Storage Management) 인스턴스에 로그인하는 데 사용되는 자격 증명을 지정합니다.

* ``아소머네임_asminstance_username_*’’
+
ASM 인스턴스에 로그인하는 데 사용되는 사용자 이름을 지정합니다.

* ``asmpassword_asminstance_password_*'
+
ASM 인스턴스에 로그인하는 데 사용되는 암호를 지정합니다.

* ``로그인 *’’
+
데이터베이스 로그인 정보를 지정합니다.

* ``username_db_username_*'
+
프로파일이 설명하는 데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.

* '' * -password_db_password_ *'
+
프로필에 설명된 데이터베이스에 액세스하는 데 필요한 암호를 지정합니다.

* ``port_db_port_*'
+
프로파일이 설명하는 데이터베이스에 액세스하는 데 사용되는 TCP 포트 번호를 지정합니다.

* ``소산골_소산고 _ *’’
+
Oracle 데이터베이스 사용자 계정의 이름을 지정합니다. SnapManager는 이 계정을 사용하여 시작 및 종료와 같은 Oracle 작업을 수행합니다. 일반적으로 호스트에서 Oracle 소프트웨어를 소유하는 사용자입니다(예: orasid).

* ``오스그룹_오스그룹 _ *’
+
orasid 계정과 연결된 Oracle 데이터베이스 그룹 이름의 이름을 지정합니다.

* ``hourly[-hourly[-count_n_][-duration_m_][-daily[-count_n_][-duration_m_][-weekly[-count_n_][-duration_m_][-duration_m_] *] *
+
보존 클래스의 보존 기간(시간별, 일별, 주별, 월별)과 함께 보존 수의 두 가지 중 하나 또는 둘 모두를 사용하는 백업의 보존 정책을 지정합니다.

+
각 보존 클래스에 대해 보존 수 또는 보존 기간 중 하나 또는 둘 모두를 지정할 수 있습니다. 기간은 클래스의 단위(예: 시간별 시간, 일별 일)입니다. 예를 들어, 사용자가 일일 백업에 대해 보존 기간을 7로 지정하면 보존 수가 0이므로 SnapManager는 프로파일에 대한 일일 백업 수를 제한하지 않지만 SnapManager는 7일 전에 생성된 일일 백업을 자동으로 삭제합니다.

* ``소견_소견_*'
+
프로파일 도메인을 설명하는 프로파일에 대한 설명을 지정합니다.

* ``snapname-pattern_pattern_*'
+
스냅샷 복사본의 명명 패턴을 지정합니다. 또한 모든 스냅샷 복사본 이름에 고가용성 작업에 대한 HOPS와 같은 사용자 지정 텍스트를 포함할 수도 있습니다. 프로파일을 만들거나 프로파일을 만든 후에 스냅샷 복사본 명명 패턴을 변경할 수 있습니다. 업데이트된 패턴은 아직 생성되지 않은 스냅샷 복사본에만 적용됩니다. 존재하는 스냅샷 복사본에는 이전 Snapname 패턴이 유지됩니다. 패턴 텍스트에 여러 변수를 사용할 수 있습니다.

* ``보호-보호-정책_*’
+
백업을 보조 스토리지로 보호해야 하는지 여부를 나타냅니다.

+

NOTE: 보호 정책 없이 보호 정책을 지정하면 데이터 세트에 보호 정책이 적용되지 않습니다. 프로파일 생성 시 '-protect'를 지정하고 '-protection-policy'를 설정하지 않으면 나중에 'msap profile update' 명령으로 설정하거나 Protection Manager의 콘솔을 통해 스토리지 관리자가 설정할 수 있습니다.

* ``요약-알림 *’’
+
새 프로필에 대해 요약 e-메일 알림을 사용하도록 지정합니다.

* ``공시-성공-이메일_이메일_주소1,이메일 주소2-제목_패턴_*'
+
SnapManager 작업이 성공할 때 받는 사람이 전자 메일을 받을 수 있도록 새 프로필에 대해 전자 메일 알림을 사용하도록 지정합니다. 이메일 알림을 보낼 이메일 주소 또는 이메일 주소를 하나 이상 입력하고 새 프로필에 대한 이메일 제목 패턴을 입력해야 합니다.

+
새 프로필에 사용자 지정 제목 텍스트를 포함할 수도 있습니다. 프로필을 만들거나 프로필을 만든 후에 제목 텍스트를 변경할 수 있습니다. 업데이트된 제목은 전송되지 않은 이메일에만 적용됩니다. 이메일 제목에 여러 변수를 사용할 수 있습니다.

* ``공시-실패-이메일_이메일_주소1,이메일 주소2-제목_패턴_*'
+
SnapManager 작업이 실패할 때 수신자가 이메일을 수신할 수 있도록 새 프로필에 대해 이메일 알림 활성화 를 사용하도록 지정합니다. 이메일 알림을 보낼 이메일 주소 또는 이메일 주소를 하나 이상 입력하고 새 프로필에 대한 이메일 제목 패턴을 입력해야 합니다.

+
새 프로필에 사용자 지정 제목 텍스트를 포함할 수도 있습니다. 프로필을 만들거나 프로필을 만든 후에 제목 텍스트를 변경할 수 있습니다. 업데이트된 제목은 전송되지 않은 이메일에만 적용됩니다. 이메일 제목에 여러 변수를 사용할 수 있습니다.

* ``별개 아카이브 백업 *’’
+
아카이브 로그 백업이 데이터 파일 백업과 분리되도록 지정합니다. 프로파일을 만드는 동안 제공할 수 있는 선택적 매개 변수입니다. 이 옵션을 사용하여 백업을 분리한 후 데이터 파일만 백업 또는 아카이브 로그 전용 백업을 수행할 수 있습니다.

* ``보존-archivelog-backups-hours_hours_|-days_days_|-weeks_weeks_|-months_months_*'
+
아카이브 로그 백업이 아카이브 로그 보존 기간(시간별, 일별, 주별, 월별)을 기준으로 보존되도록 지정합니다.

* ``보호[-protection-policy_policy_name_|-nopprotect*’’
+
아카이브 로그 보호 정책을 기반으로 아카이브 로그 파일을 보호하도록 지정합니다.

+
noProtect 옵션은 아카이브 로그 파일을 보호하지 않도록 지정합니다.

* ``조용하다’’고 말했습니다
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* '' * - verbose * '
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.

* ``온라인 백업 포함’’’’이라고 말했습니다
+
아카이브 로그 백업이 온라인 데이터베이스 백업과 함께 포함되도록 지정합니다.

* ``온라인 백업 포함 없는 백업’’’이라고 말했습니다
+
아카이브 로그 백업이 온라인 데이터베이스 백업과 함께 포함되지 않도록 지정합니다.

* ``덤프’’’
+
성공적인 프로필 생성 작업 후에 덤프 파일이 수집되도록 지정합니다.



'''


== 예

다음 예에서는 시간별 보존 정책 및 e-메일 알림을 사용하여 프로필을 생성하는 방법을 보여 줍니다.

[listing]
----
smsap profile create -profile test_rbac -profile-password netapp -repository -dbname SMSAPREP -host hostname.org.com -port 1521 -login -username smsaprep -database -dbname RACB -host saal -sid racb1 -login -username sys -password netapp -port 1521 -rman -controlfile -retain -hourly -count 30 -verbose
Operation Id [8abc01ec0e78ebda010e78ebe6a40005] succeeded.
----
'''