---
permalink: unix-administration/reference-the-smosmsapcredential-delete-command.html 
sidebar: sidebar 
keywords: command, delete, user, credentials, secure, resource, smsap 
summary: 이 명령은 특정 보안 리소스에 대한 사용자 자격 증명을 삭제합니다. 
---
= smsap 자격 증명 삭제 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 명령은 특정 보안 리소스에 대한 사용자 자격 증명을 삭제합니다.



== 구문

[listing, subs="+macros"]
----
pass:quotes[smsap credential delete
[-host -name _host_name_
-username _username_\] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_\] |
[-profile
-name _profile_name_\]
[-quiet | -verbose]]
----


== 매개 변수

* '*-host_hostname_ *'
+
SnapManager가 실행 중인 호스트 서버의 이름을 지정합니다.

+
'-host' 매개변수는 다음과 같은 옵션을 포함합니다.

+
** '-name_host_name_': 암호를 삭제할 호스트의 이름을 지정합니다.
** '-username_user_name_': 호스트의 사용자 이름을 지정합니다.


* '*-repository-dbname*'
+
프로필을 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.

+
'-repository' 매개 변수에는 다음 옵션이 포함됩니다.

+
** '-dbname_repo_service_name_': 프로파일을 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.
** '-host_repo_host_': 리포지토리 데이터베이스가 실행되는 호스트 서버의 이름 또는 IP 주소를 지정합니다.
** '-login-username_repo_username_': 리포지토리를 저장하는 데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.
** '-port_repo_port_': 리포지토리를 저장하는 데이터베이스에 액세스하는 데 사용되는 TCP 포트 번호를 지정합니다.


* '*-profile-name_profile_name_*'
+
데이터베이스가 연결된 프로파일을 지정합니다.

+
'-profile' 파라미터는 다음과 같은 옵션을 포함한다.

+
** '-name_profilename_': 암호를 삭제할 프로필의 이름을 지정합니다.


* ``조용한’’’
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* '*-verbose * '
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.



'''


== 명령 예

이 예제에서는 프로파일의 자격 증명을 삭제합니다.

[listing]
----
smsap credential delete -profile -name user1 -verbose
----
[listing]
----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
이 예제에서는 리포지토리의 자격 증명을 삭제합니다.

[listing]
----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
이 예제에서는 호스트의 자격 증명을 삭제합니다.

[listing]
----
smsap credential delete -host -name Host2
----
[listing]
----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
'''