---
permalink: unix-administration/task-protect-archive-log-backups.html 
sidebar: sidebar 
keywords: create, creating, profile, enable, protection, archive, log, backup, policy, protect 
summary: 프로파일을 생성하는 동안 아카이브 로그 보호 정책을 기반으로 아카이브 로그 백업에 대한 보호를 설정할 수 있습니다. 
---
= 아카이브 로그 백업을 보호합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
프로파일을 생성하는 동안 아카이브 로그 보호 정책을 기반으로 아카이브 로그 백업에 대한 보호를 설정할 수 있습니다.

.단계
. 다음 명령을 입력합니다.
+
"* smssap profile create -profile_profile_[-profile-profile-password -password -password -password -dbname_repo_dbname_ -host_repo_host_-port_port_port_ -login -username_repo_username_ -database -dbname_db_db_db_host__username_ssid_username_username_username_name _m_] [-daily [-count_n_] [-duration_m_] [-weekly [-count_n_] [-duration_m_] [-monthly [-duration_m_] [-duration_m_]] [-comment_comment_comment_] [-snapname] subject 정책 [-protection_policy] email_address2_-subject_subject_pattern_] [-separate-archivelog-backups-retain-archivelog-backups-hours_|-days_days_|-weeks_weeks_|-months_months_[-protect[-protection-policy_policy_name_]|-nobinclude-online-backups-backups-no-no-backups-no-include-dump_no-dump_hours_hours

+
[cols="2a,5a"]
|===
| 만약... | 그러면... 


 a| 
* 아카이브 로그 백업을 별도로 백업하고 아카이브 로그 파일을 보호하려고 합니다 *
 a| 
다음 옵션을 지정합니다.

** '-separate-archivelog-backups'를 사용하면 아카이브 로그 파일을 데이터 파일에서 분리할 수 있습니다.
** '-Protect'는 아카이브 로그 아카이브 로그 백업에 대해 별도의 보호 정책을 할당합니다.
** '-protection-policy'는 아카이브 로그 백업에 대한 보호 정책을 지정합니다.


|===

