---
permalink: unix-administration/task-use-snapmanager-for-oraclesnapmanager-for-sap-to-create-the-database-profile-for-a-local-backup.html 
sidebar: sidebar 
keywords: database, administrator, snapmanager, database, initiate, local, storage, primary, system, creation, process, involve, manager 
summary: 데이터베이스 관리자는 SnapManager를 사용하여 운영 스토리지 시스템의 로컬 스토리지에 대한 백업을 시작하는 데 사용할 데이터베이스 프로필을 생성합니다. 전체 프로필 생성 및 백업 생성 프로세스는 전적으로 SnapManager에서 수행되지만 Protection Manager는 수행하지 않습니다. 
---
= SnapManager for SAP를 사용하여 로컬 백업에 대한 데이터베이스 프로필을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터베이스 관리자는 SnapManager를 사용하여 운영 스토리지 시스템의 로컬 스토리지에 대한 백업을 시작하는 데 사용할 데이터베이스 프로필을 생성합니다. 전체 프로필 생성 및 백업 생성 프로세스는 전적으로 SnapManager에서 수행되지만 Protection Manager는 수행하지 않습니다.

* 이 작업에 대한 정보 *

프로필에는 자격 증명, 백업 설정 및 백업에 대한 보호 설정을 비롯하여 관리 중인 데이터베이스에 대한 정보가 포함되어 있습니다. 프로파일을 만들면 해당 데이터베이스에서 작업을 수행할 때마다 데이터베이스 세부 정보를 지정할 필요 없이 프로필 이름만 제공하면 됩니다. 프로필은 하나의 데이터베이스만 참조할 수 있습니다. 동일한 데이터베이스를 둘 이상의 프로파일로 참조할 수 있습니다.

.단계
. SAP용 SnapManager 클라이언트로 이동합니다.
. SnapManager 리포지토리 트리에서 이 프로파일과 연결할 호스트를 마우스 오른쪽 버튼으로 클릭하고 * 프로파일 생성 * 을 선택합니다.
. 프로파일 구성 정보 페이지에서 다음 정보를 입력하고 * 다음 * 을 클릭합니다.
+
** 프로필 이름: payroll_prod
** 프로파일 암호: payroll123
** 설명: 생산 급여 데이터베이스


. 데이터베이스 구성 정보 페이지에서 다음 정보를 입력하고 * 다음 * 을 클릭합니다.
+
** 데이터베이스 이름: PAYDB
** 데이터베이스 SID: paolldb
** 데이터베이스 호스트: 기본값을 수락합니다
+
저장소 트리의 호스트에서 프로파일을 만들기 때문에 SnapManager는 호스트 이름을 표시합니다.



. 두 번째 데이터베이스 구성 정보 페이지에서 다음 데이터베이스 정보를 적용하고 * 다음 * 을 클릭합니다.
+
** Oracle 사용자 계정(ora<sid>의 경우): orapayrolldb를 나타내는 호스트 계정
** 호스트 그룹 - Oracle 그룹: DBA를 나타냅니다


. 데이터베이스 연결 정보 페이지에서 * 데이터베이스 인증 사용 * 을 선택하여 사용자가 데이터베이스 정보를 사용하여 인증할 수 있도록 합니다.
+
이 예에서는 다음 정보를 입력하고 * 다음 * 을 클릭합니다.

+
** SySDBA 관리자 권한이 있는 사용자 이름: sys. 관리 권한이 있는 시스템 데이터베이스 관리자를 나타냅니다
** 암호(SYSDBA 암호): Oracle
** 데이터베이스 호스트에 연결할 포트: 1527


. 스냅샷 명명 정보 페이지에서 변수를 선택하여 이 프로파일과 연결된 스냅샷의 명명 규칙을 지정합니다. 필요한 유일한 변수는 고유한 스냅샷 식별자를 생성하는 * smid * 변수입니다.
+
이 예제에서는 다음을 실행합니다.

+
.. 변수 토큰 목록에서 * {UserText} * 변수를 선택하고 * 추가 * 를 클릭합니다.
.. "prod01.sample.com_" 를 호스트 이름으로 입력하고 * OK * 를 클릭합니다.
.. Format(형식) 상자에서 "smssap" 바로 뒤에 호스트 이름이 나타날 때까지 * left * 를 클릭합니다.
.. 다음 * 을 클릭합니다.


+
"_smsap_hostname_smssapprofile_dbsid_scope_mode_smid_"의 스냅샷 명명 규칙은 "smsap_prpd01.sample.com_P01_BACKUP_P01_f_a_x" 가 됩니다. 여기서 "f"는 전체 백업을 나타내고 "a"는 자동 모드를 나타내며 "x"는 고유한 SMID를 나타냅니다.

. 작업 수행 페이지에서 정보를 확인하고 * 생성 * 을 클릭합니다.
. 프로파일 생성 작업 및 볼륨 기반 복원 자격 정보에 대한 정보를 보려면 * 작업 세부 정보 * 를 클릭합니다.

