---
permalink: unix-administration/task-perform-backup-restore-and-clone-operations-using-prescript-and-post-scripts.html 
sidebar: sidebar 
keywords: script, initiate, initiating, backup, restore, clone, operation, snapmanager, display, task-enabling, create, wizard, restore, recover, parameter, post-script 
summary: 백업, 복원 또는 클론 작업을 시작하는 동안 자체 스크립트를 사용할 수 있습니다. SnapManager에서는 백업 생성 마법사, 복구 또는 복구 마법사 또는 클론 생성 마법사에 작업 설정 페이지를 표시합니다. 이 페이지에서 스크립트를 선택하고 스크립트에 필요한 매개 변수에 대한 값을 제공할 수 있습니다. 
---
= 처방과 사후 스크립트를 사용하여 백업, 복원 및 클론 작업을 수행합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업, 복원 또는 클론 작업을 시작하는 동안 자체 스크립트를 사용할 수 있습니다. SnapManager에서는 백업 생성 마법사, 복구 또는 복구 마법사 또는 클론 생성 마법사에 작업 설정 페이지를 표시합니다. 이 페이지에서 스크립트를 선택하고 스크립트에 필요한 매개 변수에 대한 값을 제공할 수 있습니다.

* 필요한 것 *

* 올바른 SnapManager 설치 위치에 플러그인 스크립트를 설치합니다.
* 명령을 사용하여 플러그인이 올바르게 설치되었는지 확인합니다.
* Bash 셸을 사용하고 있는지 확인합니다.


* 이 작업에 대한 정보 *

명령줄 인터페이스(CLI)에서 스크립트 이름을 나열하고 매개 변수를 선택한 다음 값을 설정합니다.

.단계
. Bash 셸을 사용 중인지 확인하려면 명령 프롬프트에 다음 명령을 입력합니다.
+
``bash *’

+
또는 프롬프트에 "어느-bash" 명령을 입력하고 명령 출력을 스크립트의 시작 매개 변수로 사용할 수 있습니다.

+
오류가 표시되지 않으면 Bash 셸이 제대로 작동하고 있는 것입니다.

. 백업 작업의 경우 '-taskspec' 옵션을 입력하고 백업 작업 전후에 전처리 또는 사후 처리 작업을 수행하기 위한 작업 사양 XML 파일의 절대 경로를 제공합니다.
+
``smssap backup create-profile_name_{[-full{-online|-offline|-auto}[-retain {-hourly|[-daily|-weekly|-monthly|-limited}][-verify]|[-data[[- files_files_[_files_]]]|[-tablespaces_[_- tablespaces_- weekly_databel_auto_calletablespaces]-{auto-weekly_databel_callel_date-offline]-{auto-online]-{data-date-date-online]{data-date- [- archivelogs [-label_label_] [-comment_comment_] [-protect | -notprotect | -protectnow] [-backup -dest_path1_[, [_ path2_]] [-exclude -dest_path1_ vaskune_days [-prune_cunnames_cunune_days] [-yyyy_unnames_days] _ cvm_days [-days [-days] _ ckunnes_cunes_unn

+
백업 플러그인 작업이 실패한 경우 플러그인 이름과 반환 코드만 표시됩니다. 플러그인 스크립트에는 로그 메시지를 포함하고 메시지를 사용자 정의 로그 파일로 리디렉션해야 합니다.

. 백업 복구 작업의 경우 '-taskspec' 옵션을 입력하고 복원 작업 전후에 사전 처리 또는 사후 처리 작업을 수행하기 위한 작업 사양 XML 파일의 절대 경로를 제공합니다.
+
"* smssap backup restore -profile_profile_name_{-label_<label>_|- id_<id>_} {-files_<files>__|- 테이블스페이스___|- complete|- controlfiles} [-recover {_-alllogs_|_- nologs_|_- until_file] vasspec_secondary_refallback_spec_spec_spec_spec_spec_spec_spec_spec_spec_spec_spec_refallback] vetec_spec_spec_spec_spec_spec_spec_spec_revegid_refallback] vegid_rev_refallback <review_review_spec_spec_spec_spec_re

+
복구 플러그인 작업이 실패한 경우 플러그인 이름과 반환 코드만 표시됩니다. 플러그인 스크립트에는 로그 메시지를 포함하고 메시지를 사용자 정의 로그 파일로 리디렉션해야 합니다.

. 클론 생성 작업의 경우 -taskspec 옵션을 입력하고 클론 작업 전후에 사전 처리 또는 사후 처리 작업을 수행하기 위한 작업 사양 XML 파일의 절대 경로를 제공합니다.
+
"* smssap clone create -profile_profile_name_{-backup-label_backup_name_|- backup-id_<backup-id>_|- current} -newsid_new_sid_-clonespec_full_path_to_clonespecfile_[-reserve_<yes,no,inherit>_] vaskquid_comment_comment_vaskup_caskid><comment_comment] <comment_comment_comment_comment] <spec_comment><spec_comment><vaskup_comment_comment><comment><comment><comment><comment_comment><

+
클론 플러그인 작업이 실패한 경우 플러그인 이름과 반환 코드만 표시됩니다. 플러그인 스크립트에는 로그 메시지를 포함하고 메시지를 사용자 정의 로그 파일로 리디렉션해야 합니다.



'''


== 작업 사양 XML 파일을 사용하여 백업을 생성하는 예

[listing]
----
smsap backup create -profile SALES1 -full -online -taskspec sales1_taskspec.xml -force -verify
----
'''