---
permalink: unix-administration/task-update-profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, database, operating, system, os, authentication, updating, information, host, database, oracle, updating 
summary: '프로파일을 업데이트하여 프로파일 암호, 보존할 백업 수, 데이터베이스에 대한 액세스, 데이터베이스 인증에 대한 운영 체제(OS) 인증 및 호스트 정보를 수정할 수 있습니다. Oracle 데이터베이스 암호 정보가 변경되면 프로필에서 해당 정보도 변경해야 합니다.' 
---
= 프로파일을 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
프로파일을 업데이트하여 프로파일 암호, 보존할 백업 수, 데이터베이스에 대한 액세스, 데이터베이스 인증에 대한 운영 체제(OS) 인증 및 호스트 정보를 수정할 수 있습니다. Oracle 데이터베이스 암호 정보가 변경되면 프로필에서 해당 정보도 변경해야 합니다.

* 이 작업에 대한 정보 *

프로필에 보호 정책이 설정되어 있으면 SnapManager를 사용하여 정책을 변경할 수 없습니다. 스토리지 관리자는 Protection Manager의 콘솔을 사용하여 정책을 변경해야 합니다.

SnapManager(3.2 이상)를 사용하면 '-separate-archivelog-backups' 옵션을 사용하여 데이터 파일 백업에서 아카이브 로그 백업을 분리하도록 프로파일을 업데이트할 수 있습니다. 아카이브 로그 백업에 대해 별도의 보존 기간 및 보호 정책을 지정할 수 있습니다. SnapManager를 사용하면 아카이브 로그 백업을 온라인 데이터베이스 백업과 함께 포함할 수 있습니다. 클로닝을 위해 온라인 데이터 파일 백업 및 아카이브 로그 백업을 함께 생성할 수도 있습니다. 온라인 데이터 파일 백업을 생성하면 데이터 파일과 함께 아카이브 로그 백업이 즉시 생성됩니다.

.단계
. 다음 명령을 입력합니다.
+
{smssap profile update -profile_profile_[-new-profile_new_profile_name_] [-profile-password_profile_password_] [-profile-password_profile_password_] [-profile_password -database -dbname_db_dbname_ -host_db_host_[-sid_db_db_sid_] [-login_username_name -username_name_names] [-weekly-[-count_n_][-duration_m_]][-monthly[-count_n_][-duration_m_]]]][-comment_comment_comment_comment_comment_][-snapname-pattern_pattern_pattern_][- protect_archiving_subject_days]][-archiving_subject_subject_subject_subject_days]]]]][-protect_subject_protect_subject_subject_subject_subject_days_days]]]include_days_days_subject_subject_subject_days]]]]]][-subject_protect_protect_subject_subject_subject_subject_subject_subject_subject_subject_protect_subject_subject_days_subject_protect_days_days_days_days]]]]]][-days_days_

+
이 명령의 다른 옵션은 다음과 같습니다.

+
`[-force][-nop프롬프트]'

+
`[-quiet|verbose]'

+
[cols="2a,4a"]
|===
| 원하는 작업 | 그러면... 


 a| 
* 운영 체제 인증을 사용하도록 프로파일을 변경합니다 *
 a| 
사용자 이름, 암호 및 포트를 추가하는 대신 다음을 지정합니다.

** '-osaccount_account_name_'을(를) 운영 체제 계정 이름으로 지정합니다
** '-osgroup_osgroup_' 운영 체제 계정과 연관된 그룹으로, 일반적으로 Oracle 설치에 사용되는 계정입니다




 a| 
* ASM(Automatic Storage Management) 인스턴스 인증을 사용하여 프로파일을 생성합니다
 a| 
ASM 인스턴스 인증에 대한 자격 증명을 지정합니다.

** '-asmusername_asminstance_username_'은 ASM 인스턴스에 로그인하는 데 사용되는 사용자 이름입니다.
** '-asmpassword_asminstance_password_'는 ASM 인스턴스에 로그인하는 데 사용되는 암호입니다.




 a| 
* Oracle RMAN(Recovery Manager) 저장소로 카탈로그를 사용하거나 RMAN * 을 제거할 수 있습니다
 a| 
다음 옵션 및 변수를 지정합니다.

** tnsname.ora 파일에 정의된 tnsname _.
** '-login-username_username_'을 RMAN 카탈로그에 연결하는 데 필요한 사용자 이름으로 사용합니다.
+
지정되지 않은 경우 SnapManager는 운영 체제 인증 정보를 사용합니다. RAC(Real Application Clusters) 데이터베이스에는 운영 체제 인증을 사용할 수 없습니다.

** RMAN 카탈로그에 접속하기 위해 필요한 RMAN 비밀번호로서 '-PASSWORD_PASSWORD_'.
** 제어 파일을 RMAN 저장소로 사용하는 경우 '-controlfile'.
** RMAN을 제거하려면 -remove-rman을 사용합니다.




 a| 
* 프로필에서 데이터베이스 백업에 대한 백업 보존 정책을 변경합니다. *
 a| 
보존 정책을 변경하려면 보존 클래스의 보존 수 또는 보존 기간을 지정하거나 둘 다 지정합니다. 기간은 클래스의 단위(예: 시간별 시간, 일별 일)입니다.

** hourly는 hourly retention class로, [-count_n_][-duration_m_]]는 retention count와 retention duration을 각각 나타낸다.
** daily는 daily retention class로, [-count_n_][-duration_m_]]는 retention count와 retention duration을 각각 나타냅니다.
** 주별 보존 클래스는 [-count_n_] [-duration_m_]]이 각각 보존 횟수와 보존 기간을 나타내는 주단위 보존 클래스입니다.
** 월 단위 보존 클래스는 월 단위 보존 클래스로서 [-count_n_][-duration_m_]]은 각각 보존 횟수와 보존 기간입니다.




 a| 
* 프로파일에 대한 백업 보호 비활성화 *
 a| 
프로파일을 사용하여 만든 데이터베이스 백업을 보호하지 않으려면 -nobProtect를 지정합니다. '-protect'가 설정된 프로파일의 경우 보호를 사용하지 않으려면 이 작업으로 데이터 세트가 삭제되며 이 프로파일에 대한 백업을 복원하거나 복제할 수 없다는 경고 메시지가 표시됩니다.



 a| 
* 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 활성화합니다. *
 a| 
다음 옵션 및 변수를 지정합니다.

** '-summary-notification'을 사용하면 저장소 데이터베이스 아래에 있는 여러 프로필에 대한 요약 전자 메일 알림을 구성할 수 있습니다.
** '-notification'을 사용하면 프로필에 대한 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 받을 수 있습니다.
** '-SUCCESS-EMAIL_EMAIL_address2_'을 사용하면 새 프로파일 또는 기존 프로파일을 사용하여 데이터베이스 작업이 성공적으로 완료된 후 이메일 알림을 받을 수 있습니다.
** '-failure-email_email_address2_'을(를) 사용하면 새 프로파일 또는 기존 프로파일을 사용하여 실패한 데이터베이스 작업에 대한 이메일 알림을 받을 수 있습니다.
** '-subject_subject_text_'는 새 프로파일 또는 기존 프로파일을 만드는 동안 이메일 알림에 대한 제목 텍스트를 지정합니다. 리포지토리에 대한 알림 설정이 구성되어 있지 않고 CLI(명령줄 인터페이스)를 사용하여 프로필 또는 요약 알림을 구성하려고 하면 콘솔 로그에 'SMSAP-14577: 알림 설정이 구성되지 않음'이라는 메시지가 기록됩니다.
+
알림 설정을 구성한 후 리포지토리에 대한 요약 알림을 설정하지 않고 CLI를 사용하여 요약 알림을 구성하려고 하면 콘솔 로그에 'SMSAP-14575: Summary notification configuration not available for this repository'라는 메시지가 기록됩니다





 a| 
* 프로파일을 업데이트하여 아카이브 로그 파일의 백업을 별도로 만듭니다 *
 a| 
다음 옵션 및 변수를 지정합니다.

** '-separate-archivelog-backups'를 사용하면 아카이브 로그 파일을 데이터베이스 파일과 별도로 백업할 수 있습니다.
+
이 옵션을 지정한 후 데이터 파일 전용 백업이나 아카이브 전용 백업을 만들 수 있습니다. 전체 백업을 생성할 수 없습니다. 또한 백업을 분리하여 프로파일 설정을 되돌릴 수 없습니다. SnapManager는 archivelogs 전용 백업을 수행하기 전에 생성된 백업의 보존 정책을 기반으로 백업을 유지합니다.

** '-retain-archivelog-backups'는 아카이브 로그 백업의 보존 기간을 설정합니다.
+

NOTE: 처음으로 프로파일을 업데이트하는 경우 '-separate-archivelog-backups' 옵션을 사용하여 아카이브 로그 백업과 데이터 파일 백업을 분리할 수 있습니다. '-retain-archivelog-backups' 옵션을 사용하여 아카이브 로그 백업의 보존 기간을 제공해야 합니다. 나중에 프로파일을 업데이트할 때 보존 기간을 설정하는 것은 선택 사항입니다.

** '-protect'는 DFM(Data Fabric Manager) 서버에 애플리케이션 데이터 세트를 생성하고 데이터베이스, 데이터 파일, 제어 파일 및 아카이브 로그와 관련된 멤버를 추가합니다.
+
데이터 세트가 있으면 프로파일을 만들 때 다시 사용됩니다.

** '-protection-policy'는 보호 정책을 아카이브 로그 백업으로 설정합니다.
** '-include-with-online-backups'는 아카이브 로그 백업이 데이터베이스 백업과 함께 포함되도록 지정합니다.
** '-no-include-with-online-backups'는 아카이브 로그 파일 백업이 데이터베이스 백업과 함께 포함되지 않도록 지정합니다.




 a| 
* 대상 데이터베이스의 호스트 이름을 변경합니다. *
 a| 
프로파일의 호스트 이름을 변경하려면 '-host_new_db_host_'를 지정합니다.



 a| 
* 프로필 업데이트 작업 후 덤프 파일을 수집합니다 *
 a| 
'-dump' 옵션을 지정합니다.

|===
. 업데이트된 프로파일을 보려면 'smsap profile show' 명령을 입력합니다

