---
permalink: unix-administration/task-create-profiles.html 
sidebar: sidebar 
keywords: creating, create, profile, assign, oracle, database, account, retention, policy, protection, backup, duration, class 
summary: 프로필을 생성할 때 프로필에 특정 Oracle 데이터베이스 사용자 계정을 할당할 수 있습니다. 프로파일에 대한 보존 정책을 설정하고, 이 프로파일을 사용하여 모든 백업에 대해 보조 스토리지에 백업 보호를 설정하고, 각 보존 클래스에 대한 보존 수와 기간을 설정할 수 있습니다. 
---
= 프로파일 작성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
프로필을 생성할 때 프로필에 특정 Oracle 데이터베이스 사용자 계정을 할당할 수 있습니다. 프로파일에 대한 보존 정책을 설정하고, 이 프로파일을 사용하여 모든 백업에 대해 보조 스토리지에 백업 보호를 설정하고, 각 보존 클래스에 대한 보존 수와 기간을 설정할 수 있습니다.

* 이 작업에 대한 정보 *

데이터베이스의 '-login', -password', '-port' 매개 변수의 값을 제공하지 않으면 운영 체제(OS) 인증 모드는 기본 자격 증명을 사용합니다.

프로파일을 만드는 동안 SnapManager는 복원 적격성 검사를 수행하여 데이터베이스를 복원하는 데 사용할 수 있는 복원 메커니즘을 결정합니다. 데이터베이스가 qtree에 있고 상위 볼륨이 빠른 복원 또는 볼륨 기반 복원을 수행할 수 없는 경우 분석이 잘못될 수 있습니다.

SnapManager(3.2 이상)를 사용하면 새 프로파일을 만들거나 기존 프로파일을 업데이트하는 동안 데이터 파일에서 아카이브 로그 파일을 분리할 수 있습니다. 프로파일을 사용하여 백업을 분리한 후 데이터 파일만 백업하거나 데이터베이스의 아카이브 로그 전용 백업만 생성할 수 있습니다. 새 프로파일 또는 업데이트된 프로파일을 사용하여 데이터 파일과 아카이브 로그 파일을 모두 포함하는 백업을 만들 수 있습니다. 그러나 프로파일을 사용하여 전체 백업을 생성하거나 설정을 되돌릴 수는 없습니다.

* 전체 및 부분 백업을 생성하기 위한 프로파일 *

데이터 파일, 제어 파일, 아카이브 로그 파일 및 지정된 데이터 파일 또는 테이블스페이스, 모든 제어 파일 및 모든 아카이브 로그 파일이 포함된 부분 데이터베이스 백업을 포함하는 전체 데이터베이스 백업을 생성하기 위해 프로파일을 생성할 수 있습니다. SnapManager에서는 전체 및 부분 백업에 대해 생성된 프로파일을 사용하여 별도의 아카이브 로그 백업을 생성할 수 없습니다.

* 데이터 파일 전용 백업 및 아카이브 전용 백업을 만들기 위한 프로파일 *

새 프로파일을 생성할 때 데이터 파일 백업에서 아카이브 로그 백업을 분리하기 위해 '-separate-archivelog-backups'를 포함시킬 수 있습니다. 기존 프로파일을 업데이트하여 아카이브 로그 백업을 데이터 파일 백업과 분리할 수도 있습니다.

새 프로파일 옵션을 사용하여 아카이브 로그 백업을 분리하여 다음 SnapManager 작업을 수행할 수 있습니다.

* 아카이브 로그 백업을 생성합니다
* 아카이브 로그 백업을 삭제합니다
* 아카이브 로그 백업을 마운트합니다
* 아카이브 로그 백업을 비울 수 있습니다


데이터 파일 백업에서 아카이브 로그 백업을 분리하기 위해 프로파일을 생성하는 동안 아카이브 로그 파일이 프로파일이 생성되는 데이터베이스에 없으면 경고 메시지가 표시됩니다.


WARNING: 보관 로그 파일이 활성 파일 시스템에 없습니다. archive log thread version> 로그 파일보다 이전 버전의 아카이브된 로그 파일은 백업에 포함되지 않습니다

이 데이터베이스에 대한 백업을 생성하는 경우에도 데이터베이스 백업에서 아카이브 로그 파일을 사용할 수 없습니다.


NOTE: 프로파일을 만드는 동안 오류가 발생하면 'smsap system dump' 명령을 사용합니다. 프로파일을 만든 후 오류가 발생하면 'msap operation' dump와 'msap profile dump' 명령어를 사용한다.

. 사용자 이름, 암호 및 포트(Oracle 인증)를 사용하여 프로파일을 만들려면 다음 명령을 입력합니다.
+
"* smssap profile create -profileprofile[-profile-password_profile_password_] -repository -dbname_dbname_ -host_repo_host_-port_port_port_-login -username_repo_username_ -database -dbname_db_db_name_name_msnosdb_host__password [-ssame_username_name] -username_name_name_name_username_name_username_name_name_name_name_nsnosdbm_username_name_name] -name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name_name] -username_nosdbm_username_username_name_username_username_username_username_username_username_name_username_name_username_name_username_name_username_name_username_name_username_ _m_] [-daily [-count_n_] [-duration_m_] [-weekly [-count_n_] [-duration_m_] [-monthly [-duration_m_] [-duration_m_]] [-comment_comment_comment_] [-snapname] subject 정책 [-protection_policy] email_address2_-subject_subject_pattern_] [-separate-archivelog-backups-retain-archivelog-backups-hours_|-days_days_|-weeks_weeks_|-months_months_[-protect[-protection-policy_policy_name_]|-nobinclude-online-backups-backups-no-no-backups-no-include-dump_no-dump_hours_hours

+
이 명령의 다른 옵션은 다음과 같습니다.

+
`[-force][-nop프롬프트]'

+
`[-quiet|verbose]'

+

NOTE: RAC(Real Application Clusters) 환경의 경우 새 프로파일을 생성할 때 db_unique_name 매개 변수의 값을 '_db_dbname_'으로 제공해야 합니다.

+
데이터베이스에 액세스하는 방법에 따라 프로파일을 만들 때 다른 옵션을 포함할 수도 있습니다.

+
|===
| 만약... | 그러면... 


 a| 
* 운영 체제 인증을 사용하여 프로파일을 생성하려고 합니다 *
 a| 
DBA 그룹에서 운영 체제 계정에 대한 변수를 지정합니다(일반적으로 Oracle을 설치하는 데 사용되는 계정). 사용자 이름, 암호 및 포트를 추가하는 대신 다음을 지정합니다.

** '-osaccount_account_name_'을(를) 운영 체제 계정 이름으로 지정합니다
** '-osgroup_osgroup_'을 운영 체제 계정과 연관된 그룹으로 사용합니다




 a| 
* ASM(Automatic Storage Management) 인스턴스 인증을 사용하여 프로파일을 생성하려고 합니다 *
 a| 
ASM 인스턴스 인증에 대한 자격 증명을 지정합니다.

** '-asmusername_asminance_username_'은 ASM 인스턴스에 로그인하는 데 사용되는 사용자 이름입니다.
** '-asmpassword_asminstance_password_'는 ASM 인스턴스에 로그인하는 데 사용되는 암호입니다.




 a| 
* 데이터베이스 인증을 사용하여 프로파일을 생성하려고 합니다 *
 a| 
데이터베이스 로그인 정보를 지정합니다. 암호에 느낌표(!), 달러 기호($) 또는 억음 악센트 기호(')와 같은 특수 문자가 포함된 경우 SnapManager에서는 명령줄 인터페이스(CLI)에서 데이터베이스 인증 프로필을 만들 수 없습니다.



 a| 
* Oracle RMAN(Recovery Manager) 리포지토리 * 로 카탈로그를 사용하고 있습니다
 a| 
다음 옵션 및 변수를 지정합니다.

** tnsname.ora 파일에 정의된 tnsname _.
** '-login-username_username_'을 RMAN 카탈로그에 연결하는 데 필요한 사용자 이름으로 사용합니다.
+
지정되지 않은 경우 SnapManager는 운영 체제 인증 정보를 사용합니다. RAC 데이터베이스에서는 운영 체제 인증을 사용할 수 없습니다.

** RMAN 카탈로그에 접속하기 위해 필요한 RMAN 비밀번호로서 '-PASSWORD_PASSWORD_'.




 a| 
* 제어 파일을 RMAN 저장소로 사용하고 있습니다 *
 a| 
'-controlfile' 옵션을 지정합니다.



 a| 
* 백업에 대한 백업 보존 정책을 지정하려는 경우 *
 a| 
보존 클래스에 대한 보존 수 또는 기간을 지정하거나 둘 모두를 지정합니다. 기간은 클래스의 단위(예: 시간별 시간, 일별 일)입니다.

** hourly는 hourly retention class로 [-count_n_] `[-duration_m_]'는 각각 보존 개수와 보존 기간입니다.
** 일별 보존 클래스는 [-count_n_] `[-duration_m_]'이 각각 보존 횟수와 보존 기간으로 사용되는 일 단위 보존 클래스입니다.
** 주별 보존 클래스는 [-count_n_] `[-duration_m_]'이 각각 보존 횟수와 보존 기간을 나타내는 주단위 보존 클래스입니다.
** 월 단위 보존 클래스는 월 단위 보존 클래스이며, [-count_n_]"[-duration_m_]"는 각각 보존 횟수와 보존 기간입니다.




 a| 
* 프로파일에 대한 백업 보호를 활성화하고자 합니다 *
 a| 
다음 옵션 및 변수를 지정합니다.

** '-protect'는 백업 보호를 가능하게 합니다.
+
7-Mode에서 운영되는 Data ONTAP을 사용하는 경우 이 옵션은 DFM(Data Fabric Manager) 서버에 애플리케이션 데이터 세트를 생성하고 데이터베이스, 데이터 파일, 제어 파일, 아카이브 로그와 관련된 멤버를 추가합니다. 데이터 세트가 이미 있는 경우 프로파일을 만들 때 동일한 데이터 세트가 다시 사용됩니다.

** '-protection-policy_policy_'를 사용하면 보호 정책을 지정할 수 있습니다.
+
7-Mode에서 운영되는 Data ONTAP을 사용하고 SnapManager이 Protection Manager와 통합된 경우에는 Protection Manager 정책 중 하나를 지정해야 합니다.

+

NOTE: 가능한 보호 정책을 나열하려면 smsap "protection-policy list" 명령을 사용합니다.

+
Clustered Data ONTAP을 사용하는 경우, _SnapManager_cDOT_Mirror_또는 _SnapManager_cDOT_Vault_를 선택해야 합니다.

+

NOTE: 다음과 같은 경우 프로파일 만들기 작업이 실패합니다.

+
*** Clustered Data ONTAP을 사용하고 있지만 Protection Manager 정책을 선택한 경우
*** 7-Mode에서 작동하는 Data ONTAP를 사용하고 있지만 _SnapManager_cDOT_Mirror_또는 _SnapManager_cDOT_Vault_policy를 선택하십시오
*** SnapMirror 관계를 생성했지만 _SnapManager_cDOT_Vault_policy를 선택하거나 SnapVault 관계를 생성했지만 _SnapManager_cDOT_Mirror_policy를 선택한 경우
*** SnapMirror 또는 SnapVault 관계를 생성하지 않고 _SnapManager_cDOT_Vault_ 또는 _SnapManager_cDOT_Mirror_policy를 선택한 경우


** '-nobprotect'는 프로파일을 사용하여 생성된 데이터베이스 백업을 보호하지 않음을 나타냅니다.



NOTE: 보호 정책 없이 보호 정책을 지정하면 데이터 세트에 보호 정책이 적용되지 않습니다. 프로파일 생성 시 '-protect'가 지정되고 '-protection-policy'가 설정되지 않은 경우 나중에 'msap profile update' 명령으로 설정하거나 Protection Manager 콘솔을 사용하여 스토리지 관리자가 설정할 수 있습니다.



 a| 
* 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 활성화하고자 합니다 *
 a| 
다음 옵션 및 변수를 지정합니다.

** '-summary-notification'을 사용하면 저장소 데이터베이스 아래에 있는 여러 프로필에 대한 요약 전자 메일 알림을 구성할 수 있습니다.
** '-notification'을 사용하면 프로필에 대한 데이터베이스 작업의 완료 상태에 대한 이메일 알림을 받을 수 있습니다.
** `-SUCCESS-EMAIL_EMAIL_address2_'는 새 프로파일 또는 기존 프로파일을 사용하여 수행된 데이터베이스 작업에 대한 이메일 알림을 받을 수 있도록 합니다.
** '-FAILURE-EMAIL_EMAIL_address2_'를 사용하면 새 프로파일 또는 기존 프로파일을 사용하여 실패한 데이터베이스 작업에 대한 이메일 알림을 받을 수 있습니다.
** '-subject_subject_text_'는 새 프로파일 또는 기존 프로파일을 만드는 동안 이메일 알림의 제목 텍스트를 지정합니다. 리포지토리에 대한 알림 설정이 구성되어 있지 않은 상태에서 CLI를 사용하여 프로필 또는 요약 알림을 구성하려고 하면 콘솔 로그에 'SMSAP-14577: 알림 설정이 구성되지 않음'이라는 메시지가 기록됩니다
+
알림 설정을 구성한 후 리포지토리에 대한 요약 알림을 설정하지 않고 CLI를 사용하여 요약 알림을 구성하려고 하면 콘솔 로그에 'SMSAP-14575: Summary notification configuration not available for this repository'라는 메시지가 표시됩니다





 a| 
* 데이터 파일과 별도로 아카이브 로그 파일을 백업하려고 합니다 *
 a| 
다음 옵션 및 변수를 지정합니다.

** '-separate-archivelog-backups'를 사용하면 데이터 파일 백업에서 아카이브 로그 백업을 분리할 수 있습니다.
** '-retain-archivelog-backups'는 아카이브 로그 백업의 보존 기간을 설정합니다. 양의 보존 기간을 지정해야 합니다.
+
아카이브 로그 백업은 아카이브 로그 보존 기간을 기준으로 유지됩니다. 데이터 파일 백업은 기존 보존 정책에 따라 보존됩니다.

** '-Protect'는 아카이브 로그 백업을 보호합니다.
** '-protection-policy'는 보호 정책을 아카이브 로그 백업으로 설정합니다.
+
아카이브 로그 백업은 아카이브 로그 보호 정책에 따라 보호됩니다. 데이터 파일 백업은 기존 보호 정책에 따라 보호됩니다.

** '-include-with-online-backups'에는 온라인 데이터베이스 백업과 함께 아카이브 로그 백업이 포함됩니다.
+
이 옵션을 사용하면 클론 생성을 위해 온라인 데이터 파일 백업 및 아카이브 로그 백업을 함께 생성할 수 있습니다. 이 옵션을 설정하면 온라인 데이터 파일 백업을 만들 때마다 데이터 파일과 함께 아카이브 로그 백업이 즉시 생성됩니다.

** '-no-include-with-online-backups'에는 데이터베이스 백업과 함께 아카이브 로그 백업이 포함되지 않습니다.




 a| 
* 성공적인 프로파일 생성 작업 * 후에 덤프 파일을 수집할 수 있습니다
 a| 
profile create 명령의 끝에 -dump 옵션을 지정합니다.

|===
+
프로파일을 만들 때 SnapManager는 나중에 프로파일에 지정된 파일에 대해 볼륨 기반 복원 작업을 수행하려는 경우에 대비하여 파일을 분석합니다.


