---
permalink: unix-administration/task-protect-database-backups-on-secondary-storage.html 
sidebar: sidebar 
keywords: snapmanager, protect, backup, copies, copy, secondary, tertiary, storage, system 
summary: SnapManager를 사용하여 2차 또는 3차 스토리지 시스템의 백업 복사본을 보호할 수 있습니다. 
---
= 2차 또는 3차 스토리지에서 데이터베이스 백업 보호
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용하여 2차 또는 3차 스토리지 시스템의 백업 복사본을 보호할 수 있습니다.

* 이 작업에 대한 정보 *

운영 스토리지에서 백업을 성공적으로 수행한 후에는 BRBACKUP 명령을 사용하여 생성된 백업을 보조 스토리지에 즉시 보호할 수 없습니다.

.단계
. 다음 명령을 입력합니다.
+
``smssap backup create-profile_name_{[-full{-online|-offline|-auto}[-retain {-hourly|-daily|-weekly|-monthly|-limited}][-verify]|[-data[- files_[_files_[_files_]]]|[-tablespaces_[_- tablespaces_- weekly_offline_date-offline_date-offline}] autonline-date-date-date-date-date-date-online]] 자동 보존 [-archivelogs [-label_label_] [-comment_comment_comment_] [-snapvaultlabel_snapvault_label_label_] [-protect | -noprotect] [-backup -dest_path1_] [- exclude -dest_destivil_scunnames] vn _ v.. days [HH_cunnil_cn _ v.. days] _ vunes] _ vundays [HH_cn _ v. _ vunnil _ vunes] _ vunnames _ vunn

+
[cols="1a,3a"]
|===
| 원하는 작업 | 다음을 수행하십시오. 


 a| 
* SnapManager가 온라인 또는 오프라인 상태를 관리할 수 있도록 허용하는 대신 온라인 또는 오프라인 데이터베이스의 백업을 만듭니다
 a| 
오프라인 데이터베이스 또는 온라인 데이터베이스의 백업을 만들려면 '-offline' 또는 '-online' 옵션을 지정합니다. '-offline' 또는 '-online' 옵션을 사용할 경우 -auto 옵션을 사용할 수 없습니다.



 a| 
* 온라인 또는 오프라인 여부에 관계없이 SnapManager에서 데이터베이스 백업을 관리할 수 있습니다 *
 a| 
'-auto' 옵션을 지정합니다. auto 옵션을 사용하면 '-offline' 또는 '-online' 옵션을 사용할 수 없습니다.



 a| 
* 백업에 대한 설명을 추가합니다 *
 a| 
설명 문자열 뒤에 '-comment' 옵션을 지정합니다.



 a| 
* 데이터베이스가 현재 * 상태에 관계없이 데이터베이스를 백업하도록 지정한 상태로 강제 설정합니다
 a| 
'-force' 옵션을 지정합니다.



 a| 
* 생성 시 백업을 확인합니다 *
 a| 
'-verify' 옵션을 지정합니다.



 a| 
* 보조 스토리지에 백업 생성 *
 a| 
'-protect' 옵션을 지정합니다.

** ONTAP를 사용 중이고 보조 스토리지에 대한 백업을 즉시 보호하려면 '-protect' 옵션을 지정합니다.
+

NOTE: Clustered Data ONTAP에는 '-protectnow' 옵션이 적용되지 않습니다.

** 7-Mode에서 작동하는 Data ONTAP를 사용 중이고 보호 관리자 보호 스케줄을 재정의하는 보조 스토리지에 대한 백업을 즉시 보호하려면 '-protectnow' 옵션을 지정합니다.
** 보조 스토리지에 대한 백업을 방지하려면 '-nobProtect' 옵션을 지정합니다. ONTAP를 사용하고 프로파일을 만드는 동안 _SnapManager_cDOT_Vault_protection 정책을 선택한 경우, '-snapvaultlabel' 옵션을 지정해야 합니다. SnapVault 관계를 값으로 설정하는 동안 SnapMirror 정책 규칙에 지정된 SnapMirror 레이블을 제공해야 합니다.




 a| 
* 보존 클래스 값을 지정합니다 *
 a| 
'-retain' 옵션을 지정하고 다음 보존 클래스 중 하나에 따라 백업을 보존할지 여부를 지정합니다.

** ``매시간’’’
** ``매일’’
** ``매주’’’
** `-monthly'
** 무제한


보존 클래스를 지정하지 않으면 SnapManager에서는 기본적으로 -hourly 가 사용됩니다.

|===


'''


== 예

다음 명령을 실행하면 데이터베이스 백업이 보호됩니다.

[listing]
----
smsap backup create -profile PAYDB -protect -retain -daily -full auto -label full_bkup_sales
----
다음 명령을 실행하면 데이터베이스 백업이 즉시 보호됩니다.

[listing]
----
smsap backup create -profile PAYDB -protectnow -retain -daily -full auto -label full_bkup_sales
----
'''