---
permalink: unix-administration/task-free-backups.html 
sidebar: sidebar 
keywords: free, backup, delete, snapshot, copies, copy, deleting, metadata, function, smsap, command 
summary: 백업을 수행하여 백업 메타데이터를 삭제하지 않고 스냅샷 복사본을 삭제할 수 있습니다. 이 기능을 사용하면 백업이 차지하는 공간이 확보됩니다. smsap backup free 명령을 사용하여 백업을 확보할 수 있습니다. 
---
= 무료 백업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업을 수행하여 백업 메타데이터를 삭제하지 않고 스냅샷 복사본을 삭제할 수 있습니다. 이 기능을 사용하면 백업이 차지하는 공간이 확보됩니다. smsap backup free 명령을 사용하여 백업을 확보할 수 있습니다.

* 필요한 것 *

여유 공간을 확보하기 위해 백업을 사용하려면 다음 사항을 확인해야 합니다.

* 백업이 성공했습니다
* 백업을 마운트할 수 없습니다
* 백업에는 클론이 없습니다
* 무제한 보존 정책을 사용하여 백업을 보존하지 않습니다
* 백업이 아직 확보되지 않았습니다


* 이 작업에 대한 정보 *

프로필에 보호가 설정되어 있고 보호 정책에 미러 관계를 사용하는 운영 노드의 연결이 포함되어 있는 경우 백업이 확보되면 운영 노드에서 스냅샷 복사본이 삭제됩니다. 다음 번에 보조 스토리지로 전송되면 해당 스냅샷 복사본도 미러 노드에서 삭제됩니다.

보호 백업을 사용하지 않도록 설정할 경우 SnapManager는 Protection Manager에 백업용 로컬 Snapshot 복사본을 제거하도록 요청합니다. 보호된 백업에 대해 사용 가능한 백업 작업이 성공적이면 Protection Manager에서 비동기식 방식으로 스냅샷 복사본이 삭제됩니다.

[cols="2a,1a,3a,3a,4a"]
|===
| 보호 상태입니다 | 로컬 상태입니다 | 운영 스토리지의 작업입니다 | 2차 스토리지에 대한 작업 | 설명 


 a| 
요청되지 않음(보호되어야 함)
 a| 
있습니다
 a| 
백업을 해제합니다
 a| 
별도의 조치가 필요 없습니다
 a| 
SnapManager는 로컬 백업을 해제합니다.



 a| 
확보
 a| 
별도의 조치가 필요 없습니다
 a| 
별도의 조치가 필요 없습니다
 a| 
로컬 백업이 이미 확보되었습니다.



 a| 
보호되지 않음
 a| 
있습니다
 a| 
백업을 해제합니다
 a| 
별도의 조치가 필요 없습니다
 a| 
SnapManager는 보조 스토리지에 복제본이 없는 경우에도 로컬 백업을 해제합니다.



 a| 
확보
 a| 
별도의 조치가 필요 없습니다
 a| 
별도의 조치가 필요 없습니다
 a| 
로컬 백업이 이미 확보되었습니다.



 a| 
보호
 a| 
있습니다
 a| 
백업을 해제합니다
 a| 
별도의 조치가 필요하지 않습니다. 보조 백업 작업은 그대로 유지됩니다
 a| 
SnapManager는 로컬 백업을 해제합니다. 복사본은 보조 스토리지에 남아 있습니다.



 a| 
확보
 a| 
별도의 조치가 필요 없습니다
 a| 
별도의 조치가 필요 없습니다
 a| 
로컬 백업이 이미 확보되었습니다.

|===
덤프 옵션을 선택적 매개 변수로 지정하여 백업 가용 작업에 성공하거나 실패한 후 덤프 파일을 수집할 수 있습니다.

.단계
. 다음 명령을 입력합니다.
+
"* smssap backup free-profile_profile_name_{-label_label_[data|-archivelogs]|-id_id_|-all}-force [-dump] [-quiet] [-force] *


