---
permalink: unix-administration/task-use-protection-manager-to-configure-secondary-backup-schedules.html 
sidebar: sidebar 
keywords: support, backup, database, secondary, storage, administrator, protection, manager, configure, schedule 
summary: 보조 스토리지에 데이터베이스 백업을 지원하기 위해 스토리지 관리자는 Protection Manager를 사용하여 백업 스케줄을 구성합니다. 
---
= Protection Manager를 사용하여 보조 백업 스케줄을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보조 스토리지에 데이터베이스 백업을 지원하기 위해 스토리지 관리자는 Protection Manager를 사용하여 백업 스케줄을 구성합니다.

* 필요한 것 *

보조 백업에 대한 스케줄을 구성하기 전에 스토리지 관리자는 DBA 파트너에게 다음 정보를 제공합니다.

* DBA가 보조 백업을 따르기를 원하는 스케줄입니다.
+
이 경우 매일 오후 7시에 백업이 한 번 수행됩니다 매주 토요일 오전 1시에 백업이 한 번 수행됩니다



.단계
. Protection Manager의 NetApp 관리 콘솔로 이동합니다.
. 메뉴 표시줄에서 * 정책 * > * 보호 * > * 일정 * 을 클릭합니다.
+
Protection Policies 창의 Schedules 탭이 표시됩니다.

. 스케줄 목록에서 매일 오전 8시** 을 선택합니다.
. 복사 * 를 클릭합니다.
+
새 일일 스케줄 * 오후 8시 * 일 복사 가 목록에 표시됩니다. 이미 선택되어 있습니다.

. 편집 * 을 클릭합니다.
+
일일 일정 편집 속성 시트가 일정 탭으로 열립니다.

. 일정 이름을 7시 * 급여 일간으로 변경하고 * 설명을 업데이트한 다음 * 적용 * 을 클릭합니다.
+
변경 내용이 저장됩니다.

. Daily Events * 탭을 클릭합니다.
+
스케줄의 현재 일일 백업 시간은 오후 8시입니다 가 표시됩니다.

. 추가 * 를 클릭하고 새 시간 필드에 * 7:00 PM * 을 입력한 다음 * 적용 * 을 클릭합니다.
+
스케줄의 현재 일일 백업 시간은 현재 오후 7시입니다

. 확인 * 을 클릭하여 변경 사항을 저장하고 속성 시트를 종료합니다.
+
새 일별 일정인 * 7시 일일 급여 * 가 일정 목록에 표시됩니다.

. 스케줄 목록에서 Weekly schedule** Sunday at 8:00 PM + Daily** 를 선택합니다.
. 복사 * 를 클릭합니다.
+
새로운 주간 스케줄 * 일요일 오후 8시 + 일 * 이 목록에 표시됩니다. 이미 선택되어 있습니다.

. 편집 * 을 클릭합니다.
+
주간 일정 편집 속성 시트가 일정 탭에 열립니다.

. 일정 이름을 * 토요일 1 AM + 매일 7 PM * 으로 변경하고 설명을 업데이트합니다.
. Daily Schedule * (일일 일정 *) 드롭다운 목록에서 방금 만든 일일 일정, * 7 PM * 에 대한 급여 일일 일정을 선택합니다.
+
7시에 매일 급여 * 를 선택하면 * 오전 1시에 급여 토요일 + 오후 7시 * 일정이 정책에 적용될 때 이 일정이 일별 작업이 발생하는 시기를 정의합니다.

. 확인 * 을 클릭하여 변경 사항을 저장하고 속성 시트를 종료합니다.
+
새 주간 일정 * 급여 토요일(오전 1시 + 매일 오후 7시 *)이 일정 목록에 표시됩니다.


