---
permalink: unix-administration/task-delete-backups.html 
sidebar: sidebar 
keywords: delete, backup, free, space, remove, snapshot, copies, copy, volume, deleting 
summary: 백업을 더 이상 필요로 하지 않을 때 삭제해야 하므로 해당 백업이 차지하는 공간이 확보됩니다. 백업을 제거하면 볼륨당 255개의 스냅샷 복사본의 제한에 도달할 수 있는 가능성이 줄어듭니다. 
---
= 백업을 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업을 더 이상 필요로 하지 않을 때 삭제해야 하므로 해당 백업이 차지하는 공간이 확보됩니다. 백업을 제거하면 볼륨당 255개의 스냅샷 복사본의 제한에 도달할 수 있는 가능성이 줄어듭니다.

* 필요한 것 *

* 클론을 생성하는 데 백업이 사용되지 않았는지 확인해야 합니다.


* 이 작업에 대한 정보 *

보호된 백업을 삭제하면 SnapManager가 보조 스토리지 및 SnapManager 리포지토리에서 백업을 삭제합니다. 다음 표에는 로컬 백업을 삭제할 때 운영 스토리지와 보조 스토리지 모두에서 수행되는 작업이 나와 있습니다.

[cols="2a,1a,3a,3a,4a"]
|===
| 보호 상태입니다 | 로컬 상태입니다 | 운영 스토리지의 작업입니다 | 2차 스토리지에 대한 작업 | 설명 


 a| 
요청되지 않음(보호되어야 함)
 a| 
있습니다
 a| 
스냅샷 복사본을 삭제합니다
 a| 
별도의 조치가 필요 없습니다
 a| 
SnapManager 로컬 백업을 삭제합니다.



 a| 
확보
 a| 
별도의 조치가 필요 없습니다
 a| 
별도의 조치가 필요 없습니다
 a| 
로컬 백업이 이미 확보되었습니다. 해제된 백업을 삭제하면 백업 메타데이터가 리포지토리에서 제거됩니다.



 a| 
보호되지 않음
 a| 
있습니다
 a| 
스냅샷 복사본을 삭제합니다
 a| 
별도의 조치가 필요 없습니다
 a| 
SnapManager는 보호 여부에 관계없이 로컬 백업을 삭제합니다.



 a| 
확보
 a| 
별도의 조치가 필요 없습니다
 a| 
별도의 조치가 필요 없습니다
 a| 
로컬 백업이 이미 확보되었습니다. 해제된 백업을 삭제하면 백업 메타데이터가 리포지토리에서 제거됩니다.



 a| 
보호
 a| 
있습니다
 a| 
스냅샷 복사본을 삭제합니다
 a| 
SnapManager 보조 스토리지에서 백업을 삭제합니다
 a| 
SnapManager는 로컬 백업 및 보조 복사본을 삭제합니다.



 a| 
확보
 a| 
별도의 조치가 필요 없습니다
 a| 
SnapManager를 사용하면 보조 스토리지에서 백업을 사용할 수 있습니다
 a| 
SnapManager는 로컬 백업 및 보조 복사본을 삭제합니다.

|===
2차 스토리지로 보호되는 백업을 삭제하려고 하면 스냅샷 복사본이 삭제되도록 표시될 수 있으며 나중에 Protection Manager에서 삭제됩니다.

보존 클래스를 변경하지 않고 무제한 유지되는 백업을 삭제할 수 있습니다.

백업 삭제 작업이 성공하거나 실패한 후에 덤프 파일을 선택적으로 수집할 수 있습니다.

아카이브 로그 백업을 삭제하려면 아카이브 로그 백업에 대해 설정된 보존 기간을 확인해야 합니다. 아카이브 로그 백업이 보존 기간 내에 있고 복구된 데이터베이스 복구에 아카이브 로그 파일이 필요한 경우 아카이브 로그 백업을 삭제할 수 없습니다.

.단계
. 다음 명령을 입력하여 작업이 완료되었는지 확인합니다.
+
'* smssap 작업 목록 - profile_profile_name_-dump-quiet-verbose *

. 백업을 삭제하려면 다음 명령을 입력합니다.
+
``smssap 백업 삭제 - profile_profile_name_[-label_label_[data|-archivelogs]|-id_id_|-all][-force][-dump][-quiet|-verbose] *

+
강제 옵션을 사용하여 백업을 강제로 제거합니다. 불완전한 작업이 있는 백업을 강제로 제거하면 백업이 일관되지 않은 상태가 될 수 있습니다.


