---
permalink: unix-installation-cmode/concept-smsap-isg-defining-a-backup-strategy.html 
sidebar: sidebar 
keywords: define, backup, strategy, create, successful, restore, database, snapmanager, service, level, agreement, sla 
summary: '백업을 생성하기 전에 백업 전략을 정의하면 데이터베이스를 성공적으로 복원할 수 있는 백업이 있습니다. SnapManager는 서비스 수준 계약(SLA)을 충족할 수 있는 유연하고 세분화된 백업 일정을 제공합니다.' 
---
= 백업 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업을 생성하기 전에 백업 전략을 정의하면 데이터베이스를 성공적으로 복원할 수 있는 백업이 있습니다. SnapManager는 서비스 수준 계약(SLA)을 충족할 수 있는 유연하고 세분화된 백업 일정을 제공합니다.


NOTE: SnapManager 모범 사례는 _TR 3761_을 참조하십시오.



== 어떤 SnapManager 백업 모드가 필요합니까?

SnapManager는 두 가지 백업 모드를 지원합니다.

|===
| 백업 모드 | 설명 


 a| 
온라인 백업
 a| 
데이터베이스가 온라인 상태일 때 데이터베이스의 백업을 만듭니다. 이 백업 모드를 핫 백업이라고도 합니다.



 a| 
오프라인 백업
 a| 
데이터베이스가 마운트됨 또는 종료 상태일 때 데이터베이스의 백업을 생성합니다. 이 백업 모드를 콜드 백업이라고도 합니다.

|===


== 어떤 유형의 SnapManager 백업이 필요합니까?

SnapManager는 다음 세 가지 유형의 백업을 지원합니다.

|===
| 백업 유형 | 설명 


 a| 
전체 백업
 a| 
모든 데이터 파일, 제어 파일, 아카이브 로그 파일을 포함하는 전체 데이터베이스의 백업을 생성합니다.



 a| 
부분 백업
 a| 
선택한 데이터 파일, 제어 파일, 테이블스페이스 및 아카이브 로그 파일의 백업을 생성합니다



 a| 
아카이브 로그 전용 백업
 a| 
아카이브 로그 파일의 백업만 생성합니다. 프로파일을 만드는 동안 * Archivelogs를 별도로 백업 * 을 선택해야 합니다.

|===


== 어떤 유형의 데이터베이스 프로필이 필요합니까?

SnapManager는 데이터베이스 프로파일이 아카이브 로그 백업을 데이터 파일 백업과 분리하는지 여부에 따라 백업을 생성합니다.

|===
| 프로파일 유형 | 설명 


 a| 
데이터 파일 및 아카이브 로그의 통합 백업을 위한 단일 데이터베이스 프로파일
 a| 
다음을 생성할 수 있습니다.

* 모든 데이터 파일, 아카이브 로그 파일 및 제어 파일을 포함하는 전체 백업
* 선택한 데이터 파일, 테이블스페이스, 아카이브 로그 파일 및 제어 파일을 포함하는 부분 백업입니다




 a| 
아카이브 로그 백업 및 데이터 파일 백업을 위한 별도의 데이터베이스 프로파일
 a| 
다음을 생성할 수 있습니다.

* 데이터 파일 백업 및 아카이브 로그 백업을 위해 서로 다른 레이블이 있는 결합된 백업
* 데이터 파일 - 모든 데이터 파일의 백업 및 제어 파일
* 부분 데이터 - 선택한 데이터 파일 또는 테이블스페이스를 제어 파일과 함께 백업하는 파일 전용 백업입니다
* 아카이브 - 로그 전용 백업입니다


|===


== 스냅샷 복사본에 사용해야 하는 명명 규칙은 무엇입니까?

백업에서 생성된 스냅샷 복사본은 사용자 지정 명명 규칙을 따를 수 있습니다. 프로파일 이름, 데이터베이스 이름 및 SnapManager에서 제공하는 데이터베이스 SID와 같은 사용자 지정 텍스트 또는 기본 제공 변수를 사용하여 명명 규칙을 만들 수 있습니다. 정책을 생성하는 동안 명명 규칙을 생성할 수 있습니다.


NOTE: 명명 형식에 smid 변수를 포함해야 합니다. smid 변수는 고유한 스냅샷 식별자를 생성합니다.

스냅샷 복사본의 명명 규칙은 프로파일 생성 도중이나 이후에 변경할 수 있습니다. 업데이트된 패턴은 아직 생성되지 않은 스냅샷 복사본에만 적용되며, 기존 스냅샷 복사본에는 이전 패턴이 유지됩니다.



== 운영 스토리지 시스템 및 2차 스토리지 시스템에 백업 복사본을 얼마나 오래 보관하시겠습니까?

백업 보존 정책은 보존할 성공적인 백업 수를 지정합니다. 정책을 생성하는 동안 보존 정책을 지정할 수 있습니다.

보존 클래스로 시간별, 일별, 주별, 월별 또는 무제한을 선택할 수 있습니다. 각 보존 클래스에 대해 보존 수와 보존 기간을 함께 또는 개별적으로 지정할 수 있습니다.

* 보존 수는 보존되어야 하는 특정 보존 클래스의 최소 백업 수를 결정합니다.
+
예를 들어 백업 스케줄이 _DAILY_이고 보존 수가 _10_인 경우 10개의 일일 백업이 보존됩니다.

+

NOTE: Data ONTAP에서 허용하는 최대 스냅샷 복사본 수는 255개입니다. 최대 한도에 도달하면 기본적으로 새 스냅샷 복사본이 생성되지 않습니다. 그러나 Data ONTAP에서 이전 스냅샷 복사본을 삭제하도록 회전 정책을 구성할 수 있습니다.

* 보존 기간은 백업을 보존할 최소 일 수를 결정합니다.
+
예를 들어, 백업 스케줄이 _DAILY_이고 보존 기간이 _10_인 경우 일일 백업 10일이 보존됩니다.



SnapMirror 복제를 설정하면 보존 정책이 대상 볼륨에 미러링됩니다.


NOTE: 백업 복사본을 장기간 보존하려면 SnapVault를 사용해야 합니다.



== 소스 볼륨 또는 대상 볼륨을 사용하여 백업 복사본을 확인하시겠습니까?

SnapMirror 또는 SnapVault를 사용하는 경우 기본 스토리지 시스템의 스냅샷 복사본이 아닌 SnapMirror 또는 SnapVault 대상 볼륨의 스냅샷 복사본을 사용하여 백업 복사본을 확인할 수 있습니다. 검증을 위해 대상 볼륨을 사용하면 운영 스토리지 시스템의 로드가 감소합니다.

* 관련 정보 *

http://www.netapp.com/us/media/tr-3761.pdf["NetApp 기술 보고서 3761: SnapManager for Oracle: 모범 사례"^]
