---
permalink: unix-installation-cmode/task-smsap-isg-back-up-your-database.html 
sidebar: sidebar 
keywords: create, back up, database, schedule, initial, verification 
summary: 프로필을 만든 후에는 데이터베이스를 백업해야 합니다. 초기 백업 및 검증 후에 반복 백업을 예약할 수 있습니다. 
---
= 데이터베이스를 백업합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
프로필을 만든 후에는 데이터베이스를 백업해야 합니다. 초기 백업 및 검증 후에 반복 백업을 예약할 수 있습니다.



== 이 작업에 대해

다음 단계에서는 SnapManager 사용자 인터페이스를 사용하여 데이터베이스 백업을 만드는 방법을 보여 줍니다. 원하는 경우 CLI(Command-Line Interface)를 사용할 수도 있습니다.

CLI 또는 SAP BR * Tools를 사용하여 백업을 생성하는 방법에 대한 자세한 내용은 UNIX_용_SnapManager 관리 가이드를 참조하십시오.

.단계
. 리포지터리 트리에서 백업할 데이터베이스가 포함된 프로필을 마우스 오른쪽 단추로 클릭하고 * 백업 * 을 선택합니다.
. Label * 에 백업의 사용자 정의 이름을 입력합니다.
+
이름에 공백이나 특수 문자를 포함할 수 없습니다. 이름을 지정하지 않으면 SnapManager에서 자동으로 백업 레이블을 만듭니다.

+
SnapManager 3.4에서는 SnapManager에서 자동으로 생성된 백업 레이블을 수정할 수 있습니다. override.default.backup.pattern` 및 new.default.backup.pattern` 구성 변수를 편집하여 고유한 기본 백업 레이블 패턴을 만들 수 있습니다.

. 선택 사항: * SnapVault 레이블 * 에서 SnapVault 관계를 설정하는 동안 SnapMirror 정책 규칙에 지정한 SnapMirror 레이블을 입력해야 합니다.
+

NOTE: SnapVault 레이블 * 필드는 프로파일을 만드는 동안 _SnapManager_cDOT_Vault_를 보호 정책으로 선택한 경우에만 나타납니다.

. 필요한 경우 데이터베이스 시작 또는 종료 허용 * 을 선택하여 데이터베이스 상태를 수정합니다.
+
이 옵션을 사용하면 데이터베이스가 백업을 생성하는 데 필요한 상태가 아닐 경우 SnapManager가 자동으로 데이터베이스를 원하는 상태로 가져가 작업을 완료합니다.

. Database *, * Tablespaces * 또는 * datafes * 에서 "Backup" 페이지로 이동하려면 다음을 수행하십시오.
+
.. 전체 데이터베이스, 선택한 데이터 파일 또는 선택한 테이블스페이스를 백업하려면 * 백업 데이터 파일 * 을 선택합니다.
.. 아카이브 로그 파일을 개별적으로 백업하려면 * Backup Archivelogs * 를 선택합니다.
.. 이미 백업된 활성 파일 시스템에서 아카이브 로그 파일을 삭제하려면 * prune Archivelogs * 를 선택합니다.
+

NOTE: FRA(플래시 복구 영역)가 아카이브 로그 파일에 대해 활성화된 경우 SnapManager가 아카이브 로그 파일을 정리하지 못합니다.

.. 백업 보호를 활성화하려면 * 백업 보호 * 를 선택합니다.
+
이 옵션은 프로파일을 생성하는 동안 보호 정책이 선택된 경우에만 활성화됩니다.

.. Type * 드롭다운 목록에서 생성할 백업 유형(오프라인 또는 온라인)을 선택합니다.
+
Auto_를 선택하면 SnapManager는 데이터베이스의 현재 상태를 기반으로 백업을 생성합니다.

.. Retention Class * 드롭다운 목록에서 보존 클래스를 선택합니다.
.. 백업된 파일이 손상되지 않도록 하려면 Oracle DBVERIFY utility * 를 사용하여 백업 확인 확인란을 선택합니다.


. 작업 설정 * 페이지에서 백업 작업이 완료되기 전과 후에 작업을 수행할지 여부를 지정합니다.
. 백업 작업 수행 * 페이지에서 정보를 확인하고 * 백업 * 을 클릭합니다.
. 마침 * 을 클릭하여 마법사를 닫습니다.
+
작업이 실패하면 * Operation Details * 를 클릭하여 작업이 실패한 원인을 확인합니다.



* 관련 정보 *

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["UNIX용 SnapManager 3.4.1 SAP 관리 가이드"^]
