---
permalink: unix-installation-cmode/task-smsap-isg-integrate-with-sap-br-tools.html 
sidebar: sidebar 
keywords: sap, br, contain, tool, oracle, database, administration, brarchive, brbackup, brconnect, brrecover, brrestore, brspace, brtools, backint, file, integrate 
summary: 'Oracle 데이터베이스 관리를 위한 SAP 도구가 포함된 SAP BR * Tools(예: brarchive, BRBACKUP, BRCONNECT) brrecover, brrestore, BRSPACE 및 BRTools는 SnapManager for SAP에서 제공하는 backint 인터페이스를 사용합니다. SAP BR * Tools를 통합하려면 backint 파일이 설치된 /opt/netapp/smsap/bin/에 대한 BR * Tools 디렉토리에서 링크를 생성해야 합니다.' 
---
= SAP BR * Tools와 통합
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle 데이터베이스 관리를 위한 SAP 도구가 포함된 SAP BR * Tools(예: brarchive, BRBACKUP, BRCONNECT) brrecover, brrestore, BRSPACE 및 BRTools는 SnapManager for SAP에서 제공하는 backint 인터페이스를 사용합니다. SAP BR * Tools를 통합하려면 BR * Tools 디렉토리에서 backint 파일이 설치된 `/opt/netapp/smsap/bin/'으로 링크를 생성해야 합니다.



== 필요한 것

* SAP BR * Tools가 설치되어 있는지 확인해야 합니다.


.단계
. BR * Tools 디렉토리에서 각 SAP 인스턴스에 대한 '/opt/netapp/smsap/bin/backint' 파일에 대한 링크를 생성합니다.
+

NOTE: 새 버전의 SnapManager를 설치할 때 링크가 새 backint 인터페이스 버전을 가리키도록 파일을 복사하는 대신 링크를 사용해야 합니다.

. BR * Tools 명령을 실행하는 사용자의 자격 증명을 설정합니다.
+
운영 체제 사용자는 SAP 인스턴스의 백업 및 복원을 지원하기 위해 SnapManager for SAP 리포지토리, 프로필 및 서버의 자격 증명이 필요합니다.

. 다른 프로파일 이름을 지정하십시오.
+
기본적으로 SnapManager는 BR * Tools에서 명령을 처리할 때 SAP 시스템 식별자와 동일한 이름의 프로파일을 사용합니다. 사용자 환경에서 이 시스템 식별자가 고유하지 않으면 "initSID.utl" SAP 초기화 파일을 수정하고 매개 변수를 생성하여 올바른 프로필을 지정합니다. "initSID.utl" 파일은 "%ORACLE_HOME%\database"에 있습니다

+
* 예 *

+
샘플 "initSID.utl" 파일은 다음과 같습니다.

+
[listing]
----
# Backup Retention policy.
# Specifies the retention / lifecycle of backups on the filer.
#
----------------------------------------------------------------------
----------
# Default Value: daily
# Valid Values: unlimited/hourly/daily/weekly/monthly
# retain = daily
# Enabling Fast Restore.
#
----------------------------------------------------------------------
----------
# Default Value: fallback
# Valid Values: require/fallback/off
#
# fast = fallback
# Data Protection.
#
----------------------------------------------------------------------
----------
# Default Value: empty
# Valid Values: empty/yes/no
# protect =
# profile_name = SID_BRTOOLS
----
+

NOTE: 매개 변수 이름은 항상 소문자로 지정되며 주석에는 숫자 기호(#)가 있어야 합니다.

. 다음 단계를 수행하여 'initSID.sap' BR * Tools 구성 파일을 편집합니다.
+
.. initSID.sap 파일을 엽니다.
.. 백업 유틸리티 매개 변수 파일 정보가 포함된 섹션을 찾습니다.
+
* 예 *

+
[listing]
----
# backup utility parameter file
# default: no parameter file
# util_par_file =
----
.. 마지막 줄을 편집하여 'initSID.utl' 파일을 포함합니다.
+
* 예 *

+
[listing]
----
# backup utility parameter file
# default: no parameter file
# util_par_file = initSID.utl
----






== 작업을 마친 후

"backint register-SLD" 명령을 실행하여 SLD(System Landscape Directory)에 backint 인터페이스를 등록합니다.
