---
permalink: unix-installation-7mode/concept-prerequisites-for-performing-a-rollback.html 
sidebar: sidebar 
keywords: perform, rollback, ensure, environment, requirement, prerequisite 
summary: 롤백을 수행하기 전에 환경이 특정 요구 사항을 충족하는지 확인해야 합니다. 
---
= 롤백을 수행하기 위한 사전 요구 사항입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
롤백을 수행하기 전에 환경이 특정 요구 사항을 충족하는지 확인해야 합니다.

* SnapManager 3.3 이상을 사용하고 있고 SnapManager 3.1 이전 버전으로 롤백하려면 3.2로 롤백한 다음 원하는 버전으로 롤백해야 합니다.
* 외부 데이터 보호 또는 데이터 보존을 수행하는 데 사용되는 외부 스크립트를 백업해야 합니다.
* 롤백하려는 SnapManager 버전이 설치되어 있어야 합니다.
+

NOTE: SnapManager 3.3 이상에서 SnapManager 3.1 이전 버전으로 롤백을 수행하려면 먼저 SnapManager 3.2를 설치하고 롤백을 수행해야 합니다. 3.2로 롤백한 후 SnapManager 3.1 이하를 설치하고 해당 버전으로 롤백할 수 있습니다.

* 롤백하려는 SnapManager 버전에서 지원되는 UNIX용 SnapDrive 버전이 설치되어 있어야 합니다.
+
SnapDrive 설치에 대한 자세한 내용은 SnapDrive 설명서 세트를 참조하십시오.

* 리포지토리 데이터베이스를 백업해야 합니다.
* 롤백할 호스트가 리포지토리를 사용하는 경우 동일한 리포지토리를 사용하는 다른 호스트에서 SnapManager 작업을 수행하지 않아야 합니다.
+
다른 호스트에서 예약되거나 실행 중인 작업은 롤백이 완료될 때까지 기다립니다.

* 동일한 저장소 데이터베이스를 가리키는 프로필은 SnapManager 서버 호스트에서 다른 이름으로 만들어야 합니다.
+
같은 이름의 프로파일을 사용하는 경우 해당 리포지토리 데이터베이스와 관련된 롤백 작업이 경고 없이 실패합니다.

* 롤백하려는 호스트에서 SnapManager 작업을 수행하면 안 됩니다.
+
실행 중인 작업이 있는 경우 작업이 완료될 때까지 기다린 다음 롤백을 진행해야 합니다.




NOTE: 롤백 작업은 함께 롤백되는 호스트의 누적 백업 수가 증가함에 따라 더 오랜 시간 동안 실행됩니다. 롤백 기간은 지정된 호스트와 연결된 프로필 및 백업 수에 따라 달라질 수 있습니다.

* 관련 정보 *

http://mysupport.netapp.com/["NetApp Support 사이트에 문서화"^]
