---
permalink: unix-installation-7mode/reference-trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: 상표 정보 
---
= 상표 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Active IQ, AltaVault, 아키텍처 설계, ASUP, AutoSupport, Campaign Express, clustered Data ONTAP, 고객 피트니스, Data ONTAP, DataMotion, Element, Fitness, Flash Accel, Flash Cache, Flash Pool, FlexArray, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, Fueled by SolidFire, GetSuccessful, Helix Design, LockVault, ONTAP 관리, MetroCluster, MultiStore, NetApp, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANscreen, SANshare, SANtricity, SecureShare, 단순성, ONTAP 시뮬레이션, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore, Snapshot, SnapValidator, SnapVault, SolidFire, SolidFire Helix, StorageGRID, SyncMirror, Tech OnTap, Unbound Cloud 및 WAFL와 기타 이름은 미국, 대한민국 및/또는 기타 국가에서 사용되는 NetApp, Inc.의 상표 또는 등록 상표입니다. 다른 모든 브랜드 또는 제품은 해당 소유자의 상표 또는 등록 상표이며 이와 동등하게 취급되어야 합니다. NetApp 상표의 최신 목록은 웹 사이트에서 확인할 수 있습니다.

http://www.netapp.com/us/legal/netapptmlist.aspx[]
