---
permalink: unix-installation-7mode/task-update-the-existing-repository.html 
sidebar: sidebar 
keywords: update, exist, repository, upgrading, upgrade, updating, snapmanager, path 
summary: SnapManager 3.3.x에서 SnapManager 3.4 이상으로 업그레이드하는 경우 기존 리포지토리를 업데이트할 필요는 없지만 다른 모든 업그레이드 경로의 경우 업그레이드 후에 액세스할 수 있도록 기존 리포지토리를 업데이트해야 합니다. 
---
= 기존 리포지토리를 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 3.3.x에서 SnapManager 3.4 이상으로 업그레이드하는 경우 기존 리포지토리를 업데이트할 필요는 없지만 다른 모든 업그레이드 경로의 경우 업그레이드 후에 액세스할 수 있도록 기존 리포지토리를 업데이트해야 합니다.

* 필요한 것 *

* 업그레이드된 SnapManager 서버가 시작 및 확인되어야 합니다.
* 기존 리포지토리의 백업이 있어야 합니다.


* 이 작업에 대한 정보 *

* SnapManager 3.1 이전 버전에서 SnapManager 3.3 이상으로 업그레이드하는 경우 먼저 SnapManager 3.2로 업그레이드해야 합니다.
+
SnapManager 3.2로 업그레이드한 후 SnapManager 3.3 이상으로 업그레이드할 수 있습니다.

* 리포지토리를 업데이트한 후에는 이전 버전의 SnapManager에서 리포지토리를 사용할 수 없습니다.


.단계
. 기존 리포지토리 업데이트:
+
'* smsap repository update-repository-dbname repository_service_name-host repository_host_name-login-username repository_user_name-port repository_port * '

+
** 리포지토리 사용자 이름, 리포지토리 서비스 이름 및 리포지토리 호스트 이름은 영숫자, 빼기 기호, 밑줄 및 마침표로 구성될 수 있습니다.
** 리포지토리 포트는 유효한 포트 번호일 수 있습니다. 기존 리포지토리를 업데이트하는 동안 사용되는 다른 옵션은 다음과 같습니다.
** '힘' 옵션
** 'not프롬프트' 옵션
** 조용한 옵션
** 무당무제
+
* 예 *

+
[listing]
----
smsap repository update -repository -dbname HR1
-host server1 -login -username admin -port 1521
----




* 완료 후 *

SnapManager 서버를 다시 시작하여 연결된 일정을 모두 다시 시작합니다.
