---
permalink: unix-installation-7mode/task-prepare-storage-systems-for-snapvault-replication-7-mode.html 
sidebar: sidebar 
keywords: snapmanager, integrate, snapvault, technology, archive, snapshot, copies, copy, disk, configure, intialize, data-protection, relationship, source, volume, destination, volume, initialization, data, block, preparing, prepare, storage, system, replication 
summary: SnapManager의 통합 SnapVault 기술을 사용하여 스냅샷 복사본을 디스크에 아카이브하려면 먼저 소스 볼륨과 타겟 볼륨 간의 데이터 보호 관계를 구성하고 초기화해야 합니다. 초기화 시 SnapVault은 소스 볼륨의 스냅샷 복사본을 생성한 다음 복사본 및 해당 복사본이 대상 볼륨에 참조하는 모든 데이터 블록을 전송합니다. 
---
= SnapVault 복제를 위한 스토리지 시스템 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager의 통합 SnapVault 기술을 사용하여 스냅샷 복사본을 디스크에 아카이브하려면 먼저 소스 볼륨과 타겟 볼륨 간의 _data-protection relationship_을 구성하고 초기화해야 합니다. 초기화 시 SnapVault은 소스 볼륨의 스냅샷 복사본을 생성한 다음 복사본 및 해당 복사본이 대상 볼륨에 참조하는 모든 데이터 블록을 전송합니다.

* 필요한 것 *

* SnapManager 구성 마법사에서 운영 스토리지 위치에 대한 데이터 세트를 구성해야 합니다.
* 모든 LUN은 qtree에 있어야 하며 qtree당 하나의 LUN이 있어야 합니다.



IMPORTANT: 데이터베이스 파일과 트랜잭션 로그를 서로 다른 볼륨에 저장하는 경우 데이터베이스 파일의 소스 볼륨과 대상 볼륨 간의 관계, 트랜잭션 로그의 소스 볼륨과 대상 볼륨 간의 관계를 생성해야 합니다.

.단계
. 소스 및 대상 시스템 콘솔 모두에서 SnapVault:
+
* 예 *

+
[listing]
----
options snapvault.enable on
----
. 소스 시스템 콘솔에서 'options snapvault.access' 명령을 사용하여 소스 시스템에서 직접 데이터를 복사할 수 있는 시스템의 호스트 이름을 지정합니다.
+
* 예 *

+
다음 명령을 실행하면 destination_systemb에 복제할 수 있습니다.

+
[listing]
----
options snapvault.access host=destination_systemB
----
. 대상 시스템 콘솔에서 'options snapvault.access' 명령을 사용하여 복사된 데이터를 복원할 수 있는 시스템의 호스트 이름을 지정합니다.
+
* 예 *

+
다음 명령을 실행하면 복사된 데이터를 source_systema에 복원할 수 있습니다.

+
[listing]
----
options snapvault.access host=destination_systemA
----
. 소스 시스템 콘솔에서 'ndmpd on' 명령을 사용하여 NDMP를 설정합니다.
+
* 예 *

+
다음 명령을 실행하면 NDMP가 설정됩니다.

+
[listing]
----
ndmpd on
----
. 타겟 시스템 콘솔에서 'vol create' 명령을 사용하여 소스 볼륨보다 크거나 같은 SnapMirror 타겟 볼륨을 생성합니다.
+
* 예 *

+
다음 명령을 실행하면 애그리게이트 aggr1에 vol2라는 이름의 2GB 대상 볼륨이 생성됩니다.

+
[listing]
----
vol create vol2 aggr1 2g
----
. OnCommand UM(Unified Manager) NetApp 관리 콘솔에서 대상 볼륨의 리소스 풀을 추가합니다.
+
.. 데이터 * > * 리소스 풀 * 을 클릭하여 * 리소스 풀 * 페이지를 엽니다.
.. 리소스 풀 페이지에서 * 추가 * 를 클릭하여 * 리소스 풀 추가 * 마법사를 시작합니다.
.. 마법사의 안내에 따라 대상 볼륨의 애그리게이트를 지정합니다.
.. 마법사를 종료하려면 * 마침 * 을 클릭합니다.


. UM NetApp 관리 콘솔에서 SnapManager 구성 마법사에서 생성한 데이터 세트에 리소스 풀을 할당합니다.
+
.. Data * > * Datasets * 를 클릭하여 Datasets 페이지를 엽니다.
.. Datasets * 페이지에서 생성한 데이터 세트를 선택하고 * Edit * 를 클릭합니다.
.. 데이터 세트 편집 * 페이지에서 * 백업 * > * 프로비저닝/리소스 풀 * 을 클릭하여 * 데이터 세트 노드 구성 * 마법사를 엽니다.
.. 마법사의 안내에 따라 데이터 세트에 리소스 풀을 할당합니다.
+
리소스 풀 할당은 소스 볼륨과 대상 볼륨 간의 데이터 보호 관계를 지정합니다.

.. 마법사를 종료하고 데이터 보호 관계를 초기화하려면 * 마침 * 을 클릭합니다.
+
초기화 프로세스는 대상 볼륨에 대해 _baseline 전송_을 수행합니다. SnapVault은 소스 볼륨의 스냅샷 복사본을 생성한 다음 해당 복사본과 이 복사본이 타겟 볼륨에 참조하는 모든 데이터 블록을 전송합니다.




