---
permalink: unix-installation-7mode/task-smsap-isg-create-a-profile-for-your-database.html 
sidebar: sidebar 
keywords: create, profile, database, information, reference, multiple, creating 
summary: 해당 데이터베이스에서 작업을 수행하려면 데이터베이스에 대한 프로필을 만들어야 합니다. 프로파일에는 데이터베이스에 대한 정보가 들어 있으며 하나의 데이터베이스만 참조할 수 있습니다. 그러나 여러 프로파일에서 데이터베이스를 참조할 수 있습니다. 하나의 프로파일을 사용하여 생성된 백업은 두 프로파일이 동일한 데이터베이스에 연결되어 있더라도 다른 프로파일에서 액세스할 수 없습니다. 
---
= 데이터베이스에 대한 프로필을 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
해당 데이터베이스에서 작업을 수행하려면 데이터베이스에 대한 프로필을 만들어야 합니다. 프로파일에는 데이터베이스에 대한 정보가 들어 있으며 하나의 데이터베이스만 참조할 수 있습니다. 그러나 여러 프로파일에서 데이터베이스를 참조할 수 있습니다. 하나의 프로파일을 사용하여 생성된 백업은 두 프로파일이 동일한 데이터베이스에 연결되어 있더라도 다른 프로파일에서 액세스할 수 없습니다.

* 필요한 것 *

대상 데이터베이스 세부 정보가 '/etc/oratab' 파일에 포함되어 있는지 확인해야 합니다.

* 이 작업에 대한 정보 *

다음 단계에서는 SnapManager UI를 사용하여 데이터베이스에 대한 프로필을 만드는 방법을 보여 줍니다. 원하는 경우 CLI를 사용할 수도 있습니다.

CLI를 사용하여 프로파일을 만드는 방법에 대한 자세한 내용은 UNIX_용_SnapManager 관리 가이드를 참조하십시오.

.단계
. 리포지토리 트리에서 리포지토리 또는 호스트를 마우스 오른쪽 버튼으로 클릭하고 * 프로파일 생성 * 을 선택합니다.
. 프로파일 구성 정보 * 페이지에서 프로파일의 사용자 정의 이름과 암호를 입력합니다.
. 데이터베이스 구성 정보 * 페이지에서 다음 정보를 입력합니다.
+
|===
| 이 필드에서... | 수행할 작업... 


 a| 
* 데이터베이스 이름 *
 a| 
백업할 데이터베이스의 이름을 입력합니다.



 a| 
* 데이터베이스 SID *
 a| 
데이터베이스의 SID(보안 ID)를 입력합니다. 데이터베이스 이름과 데이터베이스 SID는 같을 수 있습니다.



 a| 
* 호스트 *
 a| 
타겟 데이터베이스가 있는 호스트의 IP 주소를 입력합니다. 호스트 이름이 DNS(Domain Name System)에 지정된 경우 호스트 이름을 지정할 수도 있습니다.



 a| 
* 호스트 계정 *
 a| 
대상 데이터베이스의 Oracle 사용자 이름을 입력합니다. 사용자의 기본값은 Oracle입니다.



 a| 
* 호스트 그룹 *
 a| 
Oracle 사용자 그룹 이름을 입력합니다. 기본값은 DBA입니다.

|===
. 데이터베이스 연결 정보 페이지에서 다음 중 하나를 선택합니다.
+
[cols="1a,3a"]
|===
| 선택... | 원하는 작업 


 a| 
* O/S 인증 사용 *
 a| 
운영 체제에서 유지 관리하는 자격 증명을 사용하여 데이터베이스에 액세스하는 사용자를 인증합니다.



 a| 
* 데이터베이스 인증 사용 *
 a| 
Oracle이 암호 파일 인증을 사용하여 관리 사용자를 인증하도록 허용합니다. 적절한 데이터베이스 연결 정보를 입력합니다.

** SYSDBA 특별 권한 사용자 이름 * 필드에 관리 권한이 있는 데이터베이스 관리자의 이름을 입력합니다.
** 암호 * 필드에 데이터베이스 관리자의 암호를 입력합니다.
** Port* 필드에 데이터베이스가 있는 호스트에 연결하는 데 사용되는 포트 번호를 입력합니다.
+
기본값은 1527입니다.





 a| 
* ASM 인스턴스 인증 사용 *
 a| 
ASM(Automatic Storage Management) 데이터베이스 인스턴스가 관리 사용자를 인증할 수 있도록 허용합니다. 적절한 ASM 인스턴스 인증 정보를 입력합니다.

** SYSDBA/SYSASM 특별 권한 사용자 이름 * 필드에 관리자 권한이 있는 ASM 인스턴스 관리자의 사용자 이름을 입력합니다.
** 암호 * 필드에 관리자의 암호를 입력합니다.


|===



NOTE: 데이터베이스 호스트에 ASM 인스턴스가 있는 경우에만 ASM 인증 모드를 선택할 수 있습니다.

. RMAN 구성 정보 페이지에서 다음 중 하나를 선택합니다.
+
|===
| 선택... | 만약... 


 a| 
*** RMAN은 사용하지 마십시오 ***
 a| 
RMAN을 사용하여 백업 및 복원 작업을 관리하고 있지 않습니다.



 a| 
*** 제어 파일을 통해 RMAN 사용 ***
 a| 
제어 파일을 사용하여 RMAN 저장소를 관리합니다.



 a| 
*** 복구 카탈로그를 통해 RMAN 사용 ***
 a| 
복구 카탈로그 데이터베이스를 사용하여 RMAN 저장소를 관리하고 있습니다. TNS(Transparent Network Substrate) 연결을 관리하는 데이터베이스의 복구 카탈로그 데이터베이스, 암호 및 Oracle net 서비스 이름에 액세스할 수 있는 사용자 이름을 입력합니다.

|===
. 스냅샷 명명 정보 * 페이지에서 변수를 선택하여 스냅샷 복사본의 명명 형식을 지정합니다.
+
이름 지정 형식에 '_smid_' 변수를 포함해야 합니다. '_smid_' 변수는 고유한 스냅샷 식별자를 만듭니다.

. 정책 설정 * 페이지에서 다음을 수행합니다.
+
.. 각 보존 클래스에 대한 보존 수와 기간을 입력합니다.
.. 보호 정책 * 드롭다운 목록에서 Protection Manager 정책을 선택합니다.
.. 아카이브 로그를 개별적으로 백업하려면 * Backup Archivelogs Seively * 확인란을 선택하고 보존을 지정하고 보호 정책을 선택합니다.
+
데이터 파일과 관련된 정책과 다른 정책을 선택할 수 있습니다. 예를 들어 데이터 파일에 대해 Protection Manager 정책 중 하나를 선택한 경우 아카이브 로그에 대해 다른 Protection Manager 정책을 선택할 수 있습니다.



. 알림 설정 구성 * 페이지에서 이메일 알림 설정을 지정합니다.
. 기록 구성 정보 * 페이지에서 SnapManager 작업 기록을 유지하는 옵션 중 하나를 선택합니다.
. 프로필 생성 작업 수행 * 페이지에서 정보를 확인하고 * 생성 * 을 클릭합니다.
. 마침 * 을 클릭하여 마법사를 닫습니다.
+
작업이 실패하면 * Operation Details * 를 클릭하여 작업이 실패한 원인을 확인합니다.



* 관련 정보 *

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["UNIX용 SnapManager 3.4.1 SAP 관리 가이드"^]
