---
permalink: unix-installation-7mode/task-prepare-storage-systems-for-snapmirror-replication-7-mode.html 
sidebar: sidebar 
keywords: snapmanager, snapmirror, technology, mirror, snapshot, copies, copy, configure, initialize, data-protection, relationship, destination, volume, prepare, preparing, storage, system, replication 
summary: SnapManager의 통합 SnapMirror 기술을 사용하여 스냅샷 복사본을 미러링하려면 먼저 소스 볼륨과 타겟 볼륨 간의 데이터 보호 관계를 구성하고 초기화해야 합니다. 초기화 시 SnapMirror는 소스 볼륨의 스냅샷 복사본을 생성한 다음 복사본 및 해당 복사본이 대상 볼륨에 참조하는 모든 데이터 블록을 전송합니다. 또한 소스 볼륨에 있는 비교적 최신 Snapshot 복사본 중 하나를 타겟 볼륨으로 전송합니다. 
---
= SnapMirror 복제를 위한 스토리지 시스템 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager의 통합 SnapMirror 기술을 사용하여 스냅샷 복사본을 미러링하려면 먼저 소스 볼륨과 타겟 볼륨 간의 _data-protection relationship_을 구성하고 초기화해야 합니다. 초기화 시 SnapMirror는 소스 볼륨의 스냅샷 복사본을 생성한 다음 복사본 및 해당 복사본이 대상 볼륨에 참조하는 모든 데이터 블록을 전송합니다. 또한 소스 볼륨에 있는 비교적 최신 Snapshot 복사본 중 하나를 타겟 볼륨으로 전송합니다.

* 이 작업에 대한 정보 *

ONTAP CLI 또는 OnCommand System Manager를 사용하여 이러한 작업을 수행할 수 있습니다. 아래 절차는 CLI를 사용하고 있다고 가정하고 작성되었습니다. 자세한 내용은 를 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMP1368826["7-Mode용 Data ONTAP 8.2 데이터 보호 온라인 백업 및 복구 가이드"^].


NOTE: SnapManager를 사용하여 qtree를 미러링할 수는 없습니다. SnapManager는 볼륨 미러링만 지원합니다.

동기식 미러링에는 SnapManager를 사용할 수 없습니다. SnapManager는 비동기식 미러링만 지원합니다.


IMPORTANT: 데이터베이스 파일과 트랜잭션 로그를 서로 다른 볼륨에 저장하는 경우 데이터베이스 파일의 소스 볼륨과 대상 볼륨 간의 관계, 트랜잭션 로그의 소스 볼륨과 대상 볼륨 간의 관계를 생성해야 합니다.

. 소스 시스템 콘솔에서 'options snapmirror.access' 명령을 사용하여 소스 시스템에서 직접 데이터를 복사할 수 있는 시스템의 호스트 이름을 지정합니다.
+
* 예 *

+
다음 항목을 통해 destination_systemb에 복제할 수 있습니다.

+
[listing]
----
options snapmirror.access host=destination_systemB
----
. 대상 시스템에서 '/etc/snapmirror.conf' 파일을 생성하거나 편집하여 복사할 볼륨을 지정합니다.
+
* 예 *

+
다음 항목은 source_systema의 vol0에서 destination_systemb의 vol2로의 복제를 지정합니다.

+
[listing]
----
source_systemA:vol0 destination_systemB:vol2
----
. 소스 및 대상 시스템 콘솔 모두에서 'napmirror on' 명령을 사용하여 SnapMirror를 활성화합니다.
+
* 예 *

+
다음 명령을 실행하면 SnapMirror가 설정됩니다.

+
[listing]
----
snapmirror on
----
. 타겟 시스템 콘솔에서 'vol create' 명령을 사용하여 소스 볼륨보다 크거나 같은 SnapMirror 타겟 볼륨을 생성합니다.
+
* 예 *

+
다음 명령을 실행하면 애그리게이트 aggr1에 vol2라는 이름의 2GB 대상 볼륨이 생성됩니다.

+
[listing]
----
vol create vol2 aggr1 2g
----
. 타겟 시스템 콘솔에서 vol restrict 명령을 사용하여 타겟 볼륨을 restricted로 표시합니다.
+
* 예 *

+
다음 명령을 실행하면 대상 볼륨 vol2가 제한된 것으로 표시됩니다.

+
[listing]
----
vol restrict vol2
----
. 소스 시스템 콘솔에서 'Snap sched' 명령을 사용하여 예약된 전송을 비활성화합니다.
+
* 예 *

+
예약된 전송이 SnapDrive와 충돌하지 않도록 하려면 예약된 전송을 비활성화해야 합니다.

+
다음 명령을 실행하면 예약된 전송이 해제됩니다.

+
[listing]
----
snap sched vol1 -----
----
. 대상 시스템 콘솔에서 'napmirror initialize' 명령을 사용하여 소스 볼륨과 대상 볼륨 간의 관계를 생성하고 관계를 초기화합니다.
+
초기화 프로세스는 대상 볼륨에 대해 _baseline 전송_을 수행합니다. SnapMirror는 소스 볼륨의 스냅샷 복사본을 만든 다음 복사본과 이 복사본이 대상 볼륨에 참조하는 모든 데이터 블록을 전송합니다. 소스 볼륨의 다른 스냅샷 복사본도 타겟 볼륨으로 전송합니다.

+
* 예 *

+
다음 명령을 실행하면 source_systema의 소스 볼륨 vol0과 destination_systemb의 대상 볼륨 vol2 간에 SnapMirror 관계가 생성되고 관계가 초기화됩니다.

+
[listing]
----
snapmirror initialize -S source_systemA:vol0 destination_systemB:vol2
----

