---
permalink: unix-installation-7mode/task-smsap-isg-schedule-recurring-backups.html 
sidebar: sidebar 
keywords: schedule, backup, operation, initiate, automatic, regular, interval, hourly, daily, weekly, monthly, one-time, basis, scheduling, recur 
summary: 백업이 정기적으로 자동으로 시작되도록 백업 작업을 예약할 수 있습니다. SnapManager를 사용하면 시간별, 일별, 주별, 월별 또는 일회성 단위로 백업을 예약할 수 있습니다. 
---
= 반복 백업을 예약합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업이 정기적으로 자동으로 시작되도록 백업 작업을 예약할 수 있습니다. SnapManager를 사용하면 시간별, 일별, 주별, 월별 또는 일회성 단위로 백업을 예약할 수 있습니다.

* 이 작업에 대한 정보 *

단일 데이터베이스에 여러 백업 일정을 할당할 수 있습니다. 그러나 동일한 데이터베이스에 대해 여러 백업을 예약할 때는 백업을 동시에 예약하지 않도록 해야 합니다.

다음 단계에서는 SnapManager UI(사용자 인터페이스)를 사용하여 데이터베이스에 대한 백업 일정을 만드는 방법을 보여 줍니다. 원하는 경우 CLI(Command-Line Interface)를 사용할 수도 있습니다. CLI를 사용하여 백업을 예약하는 방법에 대한 자세한 내용은 UNIX_용_SnapManager 관리 가이드를 참조하십시오.

. 리포지터리 트리에서 백업 일정을 만들 데이터베이스가 포함된 프로필을 마우스 오른쪽 단추로 클릭하고 * 백업 예약 * 을 선택합니다.
. Label * 에 백업의 사용자 정의 이름을 입력합니다.
+
이름에 공백이나 특수 문자를 포함할 수 없습니다. 이름을 지정하지 않으면 SnapManager에서 자동으로 백업 레이블을 만듭니다.

+
SnapManager 3.4에서는 SnapManager에서 자동으로 생성된 백업 레이블을 수정할 수 있습니다. override.default.backup.pattern` 및 new.default.backup.pattern` 구성 변수를 편집하여 고유한 기본 백업 레이블 패턴을 만들 수 있습니다.

. 필요한 경우 데이터베이스 시작 또는 종료 허용 * 을 선택하여 데이터베이스 상태를 수정합니다.
+
이 옵션을 사용하면 데이터베이스가 백업을 생성하는 데 필요한 상태가 아닐 경우 SnapManager가 자동으로 데이터베이스를 원하는 상태로 가져가 작업을 완료합니다.

. Database, Tablespaces 또는 Datafiles to Backup * 페이지에서 다음을 수행합니다.
+
.. 전체 데이터베이스, 선택한 데이터 파일 또는 선택한 테이블스페이스를 백업하려면 * 백업 데이터 파일 * 을 선택합니다.
.. 아카이브 로그 파일을 개별적으로 백업하려면 * Backup Archivelogs * 를 선택합니다.
.. 이미 백업된 활성 파일 시스템에서 아카이브 로그 파일을 삭제하려면 * prune Archivelogs * 를 선택합니다.
+

NOTE: FRA(플래시 복구 영역)가 아카이브 로그 파일에 대해 활성화된 경우 SnapManager가 아카이브 로그 파일을 정리하지 못합니다.

.. 백업 보호를 활성화하려면 * 백업 보호 * 를 선택합니다.
+
이 옵션은 프로파일을 생성하는 동안 보호 정책이 선택된 경우에만 활성화됩니다.

.. Protection Manager의 보호 스케줄을 무시하고 보조 스토리지에 대한 백업을 즉시 보호하려면 * Protect Now * 를 선택합니다.
.. Type * 드롭다운 목록에서 생성할 백업 유형(오프라인 또는 온라인)을 선택합니다.
+
Auto_를 선택하면 SnapManager는 데이터베이스의 현재 상태를 기반으로 백업을 생성합니다.

.. Retention Class * 드롭다운 목록에서 보존 클래스를 선택합니다.
.. 백업된 파일이 손상되지 않도록 하려면 Oracle DBVERIFY utility * 를 사용하여 백업 확인 확인란을 선택합니다.


. 스케줄 이름 * 필드에 스케줄의 사용자 정의 이름을 입력합니다.
+
이름에 공백을 포함할 수 없습니다.

. 백업 일정 구성 * 페이지에서 다음을 수행합니다.
+
.. Perform this operation * (이 작업 수행 *) 드롭다운 목록에서 백업 스케줄의 빈도를 선택합니다.
.. Start Date * (시작 날짜 *) 필드에서 백업 일정을 시작할 날짜를 지정합니다.
.. 시작 시간 * 필드에서 백업 일정을 시작할 시간을 지정합니다.
.. 백업을 생성할 간격을 지정합니다.
+
예를 들어 빈도를 매시간 단위로 선택하고 간격을 2로 지정하면 2시간마다 백업이 예약됩니다.



. 작업 설정 * 페이지에서 백업 작업이 완료되기 전과 후에 작업을 수행할지 여부를 지정합니다.
. 백업 일정 작업 수행 * 페이지에서 정보를 확인하고 별표 * 를 클릭합니다.
. 마침 * 을 클릭하여 마법사를 닫습니다.
+
작업이 실패하면 * Operation Details * 를 클릭하여 작업이 실패한 원인을 확인합니다.



* 관련 정보 *

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["UNIX용 SnapManager 3.4.1 SAP 관리 가이드"^]
