---
permalink: unix-installation-7mode/task-perform-rolling-upgrade-on-a-single-host-or-multiple-hosts.html 
sidebar: sidebar 
keywords: perform, roll, upgrade, single, multiple, snapmanager, server, host, command-line, interface, cli, version 
summary: 'CLI(Command-Line Interface)를 사용하여 단일 또는 여러 SnapManager 서버 호스트에서 롤링 업그레이드를 수행할 수 있습니다. 그런 다음 업그레이드된 SnapManager 서버 호스트는 최신 버전의 SnapManager에서만 관리됩니다.' 
---
= 단일 호스트 또는 여러 호스트에서 롤링 업그레이드를 수행합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CLI(Command-Line Interface)를 사용하여 단일 또는 여러 SnapManager 서버 호스트에서 롤링 업그레이드를 수행할 수 있습니다. 그런 다음 업그레이드된 SnapManager 서버 호스트는 최신 버전의 SnapManager에서만 관리됩니다.

* 필요한 것 *

롤링 업그레이드를 수행하기 위한 모든 사전 요구 사항이 완료되었는지 확인해야 합니다.

.단계
. 단일 호스트에서 롤링 업그레이드를 수행하려면 다음 명령을 입력합니다.
+
"* smsap 리포지토리 롤백 - repository -dbname_repo_service_name_-host_repo_host_-login-username_repo_username_-port_port_-upgrade_host_with_target_database_-force [-quiet|-verbose] *

+
다음 명령을 실행하면 hostA에 마운트된 모든 타겟 데이터베이스와 repo_host에 있는 repoA라는 저장소 데이터베이스의 롤링 업그레이드가 수행됩니다.

+
[listing]
----

smsap repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -upgradehost hostA
----
. 여러 호스트에서 롤링 업그레이드를 수행하려면 smsaprepository rollingupport -repository -dbnamerepo_service_name -hostrepo_host -login -usernamerepo_username -portrepo_port -upgrade_thostost_with_target_database1, host_with_target_datase2 -force [-quiet | -verbose] 명령을 입력합니다
+

NOTE: 여러 호스트의 경우 쉼표로 구분된 호스트 이름을 입력하고 쉼표와 다음 호스트 이름 사이에 공백이 없어야 합니다. RAC(Real Application Clusters) 구성을 사용하는 경우 모든 RAC 관련 호스트를 수동으로 업그레이드해야 합니다. allhosts를 사용하여 모든 호스트의 롤링 업그레이드를 수행할 수 있습니다.

+
다음 명령을 실행하면 호스트, hostA 및 hostB에 마운트된 모든 타겟 데이터베이스와 repo_host에 있는 repoA라는 저장소 데이터베이스의 롤링 업그레이드가 수행됩니다.

+
[listing]
----

smsap repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -upgradehost hostA,hostB
----
. 리포지터리 데이터베이스의 모든 호스트에서 롤링 업그레이드를 수행하려면 'smsaprepository rollingupport -repository -dbnamerepo_service_name -hstrepo_host -login -usernamerepo_username -portrepo_port -allhosts -force[-quiet | -verbose]' 명령을 입력합니다
+
저장소 데이터베이스를 성공적으로 업그레이드한 후 대상 데이터베이스에서 모든 SnapManager 작업을 수행할 수 있습니다.

+
다음 명령을 실행하면 repo_host에 있는 repoA라는 저장소 데이터베이스에서 사용할 수 있는 모든 대상 데이터베이스의 롤링 업그레이드가 수행됩니다.

+
[listing]
----

smsap repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
      -allhosts
----
+
** SnapManager 서버가 자동으로 시작되면 스케줄을 볼 수 있도록 서버를 다시 시작해야 합니다.
** 두 개의 관련 호스트 중 하나를 업그레이드하는 경우 첫 번째 호스트를 업그레이드한 후 두 번째 호스트를 업그레이드해야 합니다.
+
예를 들어, 호스트 A에서 호스트 B로 클론을 생성하거나 호스트 A에서 호스트 B로 백업을 마운트하면 호스트 A와 B는 서로 연결됩니다. 호스트 A를 업그레이드하면 호스트 A를 업그레이드한 후 바로 호스트 B를 업그레이드하라는 경고 메시지가 표시됩니다

+

NOTE: 호스트 A의 롤링 업그레이드 중에 클론이 삭제되거나 호스트 B에서 백업이 마운트 해제되더라도 경고 메시지가 표시됩니다 이는 원격 호스트에서 수행되는 작업에 대한 메타데이터가 리포지토리에 존재하기 때문입니다.




